### ISSUE TITLE
Date on portal displays wrong

### ISSUE THREAD

**Issue by MarsRomer2** [bcgov/CONN-CCBC-portal#1018]
**Describe the bug**
The date on the portal changes back one day after it has been saved

**To Reproduce**
When user chooses a date e.g. Oct 1 2023 in the Project Start Date and Project end date
Clicks Save and Continue
Comes back to the Project Planning page
Date displays as Sept 30, 2023

**Expected behaviour**
Date should remain as selected initially

**Screenshots**

**Logs/tracebacks**

**Additional context**

**Comment by VB-at-Bis** [comment]
Function that returns correct date in any browser timezone:
```
export const fixDate = (originalDate) => {
  const offset = 1000 * (new Date()).getTimezoneOffset() * 60;
  const adjusted = (new Date(originalDate)).getTime() + offset;
  const format = new Date(adjusted);
  return format;
}
```
