### ISSUE TITLE
Admin can change intake dates

### ISSUE THREAD

**Issue by MarsRomer2** [bcgov/CONN-CCBC-portal#1037]
As admin 
I want to be able to change the intake dates
so that it's simpler and more reliable than asking the development team to do it.

Description:
Admin can see the intake dates and times and change them.

Acceptance criteria:
- [ ] **Scenario: Administrator logs into admin dashboard**
Given that an administrator IDIR has been entered
when they successfully login
then they will be directed to the administrator dashboard
#
- [ ] **Scenario: manage intake dates button**
Given that an administrator has successfully logged in and is on their dashboard
when they click "Manage Intake Dates"
then they will be directed to the intake dates page
#
- [ ] **Scenario: visualize intakes**
Given that an administrator is on the intake management page
when an intake exists in the database
then the intake #, start date, end date, and description (in next AC) will be visible.
![image.png](https://images.zenhubusercontent.com/61e8875b1de5eff8f072cd04/e717c945-8715-4e68-92d4-a3c8283e8388)
#
- [ ] **Scenario: add intake**
Given that an administrator is on the intake management page
when they click on the button "add intake"
then a field will will appear stating "intake number [the next intake # based upon what exists in the database]
and a date picker input field will appear with the title "start date"
and a date picker input field will appear with the title "end date"
and a text input field will appear with the title "intake description"
and the "add intake" button will disappear
and a "save" & "cancel" button will appear
![image.png](https://images.zenhubusercontent.com/61e8875b1de5eff8f072cd04/f81dec08-e9c8-40e9-96d4-6863c575bd90)
![image.png](https://images.zenhubusercontent.com/61e8875b1de5eff8f072cd04/176af8e4-066a-4c2c-b8cf-a2091bf6f4e4)
#### Validations
- [ ] Start date must be after current date
- [ ] End date must be after start date
- [ ] All fields are required
- "Start date must be entered"
- "End date must be entered"
- "Please enter a description"
Validated on pressing save
Field outlined red
Red warning text appears below each field

- [ ] **Scenario: new intake saved**
Given an administrator has pressed add intake
when they press save
then any validations will be checked
when inputs pass the validations
then the inputs will be saved in the database
and the input fields will disappear
and the new intake will appear in the list of intakes
and, if applicable, changes will be visible within the applicant dashboard and other pages where dates and intake #s are.
#
- [ ] **Scenario: edit intake**
Given that the current date is before an intake end date
then that intake will have an "edit intake" link beside it
when an administrator clicks "edit intake"
then the input fields will appear
and the input fields will be pre-filled with the data currently saved in the database
- [ ] **Scenario: can't edit start date that's passed**
Given that the current date is after an intake start date
and before an intake end date
when an administrator clicks "edit intake"
then all fields except the start date will become inputs
- [ ] They cannot change a date that has already past, i.e. if the intake has already opened they can't change the open date, if the intake has already closed, they can't change the close date.
- [ ] The intake dates cannot overlap.  I.e. two intakes cannot be open at the same time.
- [ ] There are enough checks and balances to remove risk of mistakes by the admin

**Comment by elliottSlee** [comment]
@MarsRomer2 Would we like to re-open this for next sprint?

**Comment by MarsRomer2** [comment]
@elliottSlee from a quick look I think this is a duplicate of https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/gh/bcgov/conn-ccbc-portal/651
