### ISSUE TITLE
Error on deleting file on Assessment

### ISSUE THREAD

**Issue by eazeredo** [bcgov/CONN-CCBC-portal#1045]
**Describe the bug**

**To Reproduce**

**Expected behaviour**

**Screenshots**
![image.png](https://images.zenhubusercontent.com/606c9d37b7ff542cfdb25c53/4bd5f19f-7537-432d-9979-a3230ac6f686)

**Logs/tracebacks**

**Additional context**

**Comment by MarsRomer2** [comment]
work well now!
