### ISSUE TITLE
Order of status dropdown

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#1048]
### Describe the bug
The status dropdown is in alphabetical order but should be chronological order.

### To reproduce
On any application page, the status in the top right corner has a dropdown when clicked, it's currently in alphabetical order

### Expected behaviour
Can the dropdown menu be in the following order?

Received
Screening
Assessment
Recommendation
Conditionally approved
Approved
Complete
On hold
Cancelled
Closed

### Screenshots
**Current**
<img src="https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/34710b5a-dfb4-4194-8d33-2daccf42ef5d" width=60%>
**Desired**
<img src="https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/8f2763e7-db05-486d-b6cf-da90ccf1d5b1" width=60%>

**Comment by marcellmueller** [comment]
This shouldn't be tagged as a bug, it doesn't cause buggy behaviour. It is a feature that wasn't in the acceptance criteria.
