### ISSUE TITLE
Refactor Screening Assessments

### ISSUE THREAD

**Issue by eazeredo** [bcgov/CONN-CCBC-portal#1061]
- [x] DB: 
    - Create a query to list all `assessment` form data in the DB for a specific application
    - Move assessments from `form_data` table to it's own `assessment` table, which is in the best interest of both developers and analysts to query the data.
      - Separate table implementation: 
      - Very similar to the `form_data` table, will have jsonData, id, assessment_type,  archive/created_by additional columns
      - In the case where there is existing data, include a insert from to move data over.
      - RLS: ccbc_auth_user can't select/update/insert
    - Metabase
       - Update [this ](https://ccbc-metabase.apps.silver.devops.gov.bc.ca/question/74-screening-assessments)metabase query for new assessments table
  - [x] Will need to refactor the assessments page to reference new table
    - Assessments page will need to query new table
    - Mutation will need to be called on new table

**Comment by MarsRomer2** [comment]
Is there a way I can review this?  There are no acceptance criteria on this ticket and I don't remember the state of the screening assessments in test before this ticket was started so I can't tell if this ticket was implemented correctly to query the new data

**Comment by eazeredo** [comment]
The change happened on the database level to accommodate the other types of assessments, and it's transparent for the user.
