### ISSUE TITLE
Bug: If RFI files requested = null then do not show upload files button on applicant dashboard

### ISSUE THREAD

**Issue by MarsRomer2** [bcgov/CONN-CCBC-portal#1106]
**Describe the bug**
Applicants can still see the upload files button when there are no files being asked for (but there used to be).  
Applicant still has the ability to upload a file that was unselected (when at least one other file is being asked for)

**To Reproduce**
Part 1
1. Go to RFI screen on analyst portal
2. Find an existing RFI that asks for files to be uploaded and the due date hasn't passed
3. Uncheck all of the boxes for the files being requested
4. On applicant dashboard the upload files button still appears
Part 2:
1. Go to RFI screen on analyst portal
2. Find an existing RFI that asks for MORE THAN ONE file to be uploaded and the due date hasn't passed
3. Uncheck ONE of the boxes for the files being requested
4. On applicant dashboard click the upload files button
5. On the upload page it still allows the user to upload the file unselected in step 3.

**Expected behaviour**
Part 1: If no files are selected then applicant should not see the upload documents button
Part 2:  If analyst unselects one file to be uploaded but they are still asking for one or more files then applicant should not have the ability to upload the file that was unselected

**Comment by MarsRomer2** [comment]
Part 1 is not quite right yet.  
![image.png](https://images.zenhubusercontent.com/638e5e789d9295d36fe268e9/a467f2e8-c959-40ad-a95a-95dd928cd920)
Note above that I don't have any files selected for upload but in the below it still offers me an upload documents link on the applicant dashboard.
![image.png](https://images.zenhubusercontent.com/638e5e789d9295d36fe268e9/252192a3-09f4-459d-bade-9051d3a28535)

Part 2 works as expected! :)

**Comment by marcellmueller** [comment]
@MarsRomer2 Can you please give me more information on this? I have tested this some more and I cannot reproduce it. I have gone back and forth checking and unchecking files for the RFI and the Upload files button appears when it should for me. Thanks!
