### ISSUE TITLE
Bug: Upload and download of files is glitchy

### ISSUE THREAD

**Issue by MarsRomer2** [bcgov/CONN-CCBC-portal#1110]
**Describe the bug**
Upload of files (Applicant portal and analyst portal) is very slow or doesn't work at all at times.

**To Reproduce**
1. Go to Applicant portal
2. Click on Upload Files in dashboard
3. Upload a file
4. File takes a long time to upload

**Expected behaviour**
Files should upload instantaneously

** Related note:
Time out or error occurs on the first download more so than for subsequent uploads.
The download button of the RFI files was also a bit slow or non-responsive for the analyst as well

Dev Notes:
- As a way to get more feedback and tracing, we will need to add in Sentry's Performance metrics
- Investigation findings:
  - In the development environment, when a file of less than 5 megabytes is uploaded it consistently fails
  - The error is as follows below is on a 0-byte file, with the sensitive data removed
  - Interesting note is that the error does *not* occur in the test environment

```
{
  clientName: 'S3Client',
  commandName: 'PutObjectCommand',
  input: {
    Bucket: 'omitted',
    Key: '9978369e-1447-410b-a948-8a7b44b09685',
    Body: <Buffer >
  },
  metadata: {
    httpStatusCode: 200,
    requestId: '14EWW2H7R8TF14RV',
    extendedRequestId: 'DuT7+IXgb8W3asmSCSC9QOP4aE99dUquhVLk1OoshUxSEp9Zuyce4eJsleMHSKaw9MNuM9ayQqk=',
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}
Error {
  loaded: 0,
  total: 0,
  part: 1,
  Key: '9978369e-1447-410b-a948-8a7b44b09685',
  Bucket: 'omitted'
}
saveRemoteFile: 325.686ms
```

### To Do
- [x] #1173
- [ ] Follow up on #1173 and monitor data from Sentry custom upload spans
- [x] #1170
- [x] #1178

**Comment by AntBush** [comment]
@MarsRomer (or @MarsRomer2) Just want to confirm that this glitchy behaviour is also related to downloads being slow/working inconsistently or if it's solely the uploads (I see in the related note you mention the download button, but just wanting to double check)

**Comment by AntBush** [comment]
Possibly related to #987, as this may be due to slow network connection between openshift and AWS.

**Comment by VB-at-Bis** [comment]
Observation: 
- login as analyst, open application, open list of RFIs, click on `Email correspondence', choose file and observed never-ending loading indicator and error in console:
```
TypeError: i.readFileSync is not a function
    at O (main.js:432:19)
    at main.js:600:24
```
that points to 
```
function loadFile(path) {
  const segments = path.split('.')
  const extension = segments.length > 1 ? segments.pop() : ''
  const parse = parsers_registry[extension] || parsers_registry['*']

  // TODO Get rid of the sync call
  // eslint-disable-next-line no-sync
  return parse(fs.readFileSync(path, 'utf-8'))
}
```
in https://github.com/mozilla/node-convict/blob/master/packages/convict/src/main.js 

After page re-load, upload was successful and immediate.
Could it be indication that `convict` is mos-configured and tries to use `fs` in browser?

**Comment by VB-at-Bis** [comment]
Enabled S3 access logs (https://docs.aws.amazon.com/AmazonS3/latest/userguide/enable-server-access-logging.html) in test environment to collect metrics to determine the Turn-Around Time.
CloudWatch metrics (i.e. Average latency by S3 bucket and FirstByteLatency) are empty now. We will try again later as AWS docs suggest that after enabling access logs they will appear after several hours.
