### ISSUE TITLE
Change crunchy postgres image sources to use artifactory images

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/CONN-CCBC-portal#1117]
Images that are compatible with OpenShift's version of postgres operator have been removed from Crunchy's registry which will cause unplanned downtime if our pods restart. They have been hosted on bc gov Artifactory so we need to update our crunchy postgres image sources ASAP.

**Comment by MarsRomer2** [comment]
Is there anything I need to do here to test this ticket?  I've already confirmed I can access test metabase and the data in it

**Comment by marcellmueller** [comment]
No there isn't much to check on your end, I just moved this here so you knew it was completed.
