### ISSUE TITLE
Enable Download attachments for individual intakes

### ISSUE THREAD

**Issue by MarsRomer2** [bcgov/CONN-CCBC-portal#1120]
As an Admin
I want to be able to download attachments by intake
So that I can better organize and share the attachments after each intake

### Screen 

![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/4e0ed698-447b-40ad-8178-746e2c839d02)

### Fields and info

- [x] Add Title and Intake list dropdown field as per the design above
#
- **Intake Dropdown details:**
  - [x] **Domain:** Only "Closed" intakes are in the drop-down list (no empty/null option)
  - [x] **Options mask:**  as per designs below
  - [x] **Default:** Most recent intake is selected by default and appears in the box
  - [x] **Sort:** intakes are in descending chronological order (most recent at the top)
  - [x] **Width:** Dropdown box is wide enough to include full text

### Validations

- [x] Must have one intake option selected.

### Actions
<s>
- When click on "Download attachments" button 
  - [ ] Then only the files from the selected intake are downloaded 
  - [ ] And Disable the Download Attachments button 
  - [ ] And the download starts 
  - [ ] And show the "spinning wheel" that's used in the upload button
- [ ] After download successful or (errored out) - re-enable Download Attachment button
- [ ] Download Attachments button works as before</s>

## Not included:
- .
- .

## Technical Analysis: 
- Need to update the s3Archive route to take parameter for intake number
- Applications are already linked to an intake once submitted, so just need to update the query to filter by that.
- On the frontend: need to create a component to display intakes

**Comment by carreenu** [comment]
Functionality is appearing as described.
