### ISSUE TITLE
Edit Intake Dates

### ISSUE THREAD

**Issue by MarsRomer2** [bcgov/CONN-CCBC-portal#1123]
## User Story
As an admin, I want to edit intake dates that have not ended so that I can change any necessary dates.

# Acceptance Criteria:

## Page: View Intakes dates
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/0847b5fa-2dee-4fdd-bc88-88c53e7007be)

- [x] Show Edit pencil when Intake's End Date & Time <= Current Date & Time (before)

### Button Behaviour
- When clicking on "Add Intake" button
  - [x] Hide "Add Intake" button
  - [x] Hide the current row
  - [x] Show the "Edit" form with the fields filled
    - [x] **Transition:** slide down - similar to: https://codepen.io/mbxtr/pen/OJPOYg

## Page: Edit Intakes dates
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/6c8c8a72-7725-49e9-8a6b-40df134ba766)

- [x] If current date & time is > start date & time, then disable editing of start date & time
- [x] Clicking save or cancel in the form starts the transition animation slide the form div up

### Validations
- [ ] All validations happen when pressing Save
#
- **Required fields:**
- [x] Start date = null
Error message:  "Start date and time must be entered."
- [x] End date = null
Error message:  "End date and time must be entered."
#
- **Error state design:**
- [x] Field outlined red
- [x] Red warning text appears below each field
- [x] "Description (optional)" 
- [x] Description field - 150 characters
#
- The intake dates cannot overlap.  
  - [x] The Start Date cannot be between Start & End Date of other intakes.
  _I.e. two intakes cannot be open at the same time._
  Error message:  "Intake dates cannot overlap. Start date & time must be after end of any other intakes."
#
 [] -If a Future Intake exists, the intake End Date < Start Date of the Future Intake.
  Error message:  "The End date & time must be before the start date of the future intake."~~
#

### Action

- **Scenario: Save intake**
Given all fields have valid information
When I click on Save
- [x] Then the inputs will be saved in the database
- [x] And the input fields will be reseted
- [x] And the form will disappear (transition: slide up)
- [x] And the updated intake will appear in the list of intakes
- [x] And show the "Add Intake" button 
#
- **Scenario: Cancel Edit intake**
When I click on Cancel
- [x] Then the form will disappear (transition: slide up)
- [x] And the intake appears in the list of intakes
- [x] And show the "Add Intake" button 

[**Wireframe**](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=9536%3A51095&t=acXhe1X1yr6RG0cV-4)

**Comment by elliottSlee** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1123?planning-poker) with Zenhub @rafasdc

**Comment by MarsRomer** [comment]
Would it be a lot more effort to do live validations on this form?

**Comment by marcellmueller** [comment]
Leaving ` All validations happen when pressing Save` acceptance criteria unchecked since this has live validation.
