### ISSUE TITLE
Delete future Intake 

### ISSUE THREAD

**Issue by eazeredo** [bcgov/CONN-CCBC-portal#1124]
## User Story
As an administrator
I want to be able to delete the future intake
so that I can maintain an organized list of intakes

## Acceptance Criteria
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/16626302-b1f7-48dc-88b5-a9e486269a73)

- [x] Applicant can delete the intake that hasn't started yet.  (There should only be one intake in the future)

### Validations
- [x] **Show Delete action** for intakes if intake's start date & time > current date  & time
<s>- [ ] When click delete, a confirmation modal opens stating, "Are you sure you would like to delete Intake {# Start date & time - End date & time}. </s>

### Action
- [x] Soft delete the intake
<s>
- [ ] When "Delete" is clicked in the modal, the modal closes and an updated list of intakes are shown
- [ ] When "Cancel" is clicked in the modal, the modal closes and no changes are made
</s>
## Technical Details:
<s>- Will require a custom mutation to delete an intake and then update the remaining intakes</s>

**Comment by elliottSlee** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1124?planning-poker) with Zenhub @rafasdc
