### ISSUE TITLE
Record Conditional Approval Details

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1130]
As an analyst 
I want to record when applications get conditionally approved
so that I can keep track of applications progress

# Acceptance Criteria:
- [ ] Screen design matches below
- [x] Analyst can record the BC and ISED minister's decision
- [x] Analyst can record the announcement decision for each minister
- [x] Analyst can record when (date) an application has been conditionally approved
- [x] Analyst can record date that the applicant has been notified of conditional approval 
- [x] Analyst can record date that the applicant has accepted or withdrawn the conditional approval 
- [x] Analyst can record applicants approval, rejection, or no decision from the applicant.
- [x] Analyst can record the applicants response
- [x] Analyst can record the status that the applicant sees for their application
- [x] Analyst can upload ONE document for the letter of conditional approval - any file type.  Upload functions the same as the upload for assessment pages. 
- [x] Analyst can see the name of the document they uploaded
- [x] Analyst can remove the uploaded file to then be able to upload a new file
- [x] Breakpoints at vertical lines for narrow screens

**Screen**
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/ce513fb2-8d2a-4a9b-8c16-6d29a3b69e88)
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/f3d7054b-e1e0-4ce2-86f0-ddffbe21a598)
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/4f792e48-2047-49c0-85bd-b4a4ee41b8d9)
#### <1007px:
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/de1d618c-3fc0-428b-a3b2-df06551cb4e4)
#### <768px:
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/2e585f42-611d-414b-9c8b-29c9678bca75)

[**Wireframe**](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=10736%3A86709&t=ALWFPQalSdPLzmDR-4)

**Form fields**
| **Field**                            | **type** | **domain**                                             | **Required** |
|--------------------------------------|----------|--------------------------------------------------------|--------------|
| Minister's Decision                  | Radio    | "No Decision", "Approved", "Not approved", "Hold" |              |
| Minister's Decision Date             | Date     |                                                        |              |
| Announcement Recommendation | Dropdown | "No recommendation", "Announce immediately", "Hold announcement" |  |
| ISED's Decision                      | Radio    | "No Decision", "Approved", "Not approved", "Hold" |              |
| Minister's Decision Date             | Date     |                                                        |              |
| Announcement Recommendation | Dropdown | "No recommendation", "Announce immediately", "Hold announcement" |  |
| Letter of Cond Approv. sent Date     | Date     |                                                        |              |
| Upload Letter of Cond Approv.        | File     |                                                        |              |
| Applicant's Response                 | Radio    | "Not Received", "Accepted", "Rejected"                 |              |
| Applicant's Response Date            | Date     |                                                        |              |
| Change the status that Applicant see | boolean  | "Received", "Conditionally Approved"                                            |              |
|                                      |          |                                                        |              |

**Page Behaviours**

- [ ] `Change the status that Applicant sees` field is disabled unless BC `Minister's decision` == Approved and `Applicant's response` == Accepted
- [ ] Action: Show confirmation modal when the 'Status that Applicant sees' changes from "Received" to "Conditional Approval" and Save is pressed

**Icons**:
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/752155c5-58cf-4ba1-9239-4f34d8121495)
![feuillederable-mapleleaf.jpg](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/cbc93334-b2eb-4606-ae28-051917c9fba0)

**Validations**

- [ ] .
- [ ] .
- [ ] .

**Actions**

- [ ] .
- [ ] .
- [ ] .

### Not included:
- .
- .

## Implementation Details
- **DB:**
  - .
  - .
- **Middleware:**
  - .
  - .
- **Frontend:**
  - .
  - .
- **Tests:**
  - .
  - .
- **Documentation:**
  - .
  - .

**Comment by MarsRomer** [comment]
Looks great!!  
Just a couple of requests:
1. Can we please have the font in black for the drop downs so they don't look greyed out?
![image.png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/c0283229-d8d4-4184-9878-c04161396877)

2. Is there a way to clear the dates once entered?

3.  The upload button disappeared after I clicked it and selected a file  for upload.  I think the upload was taking a while and after successfully uploading the file it showed up again.  Can we have the same spinner behavior of the button as we do on the assessment pages? 
![image.png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/d353723c-d773-404e-91cf-085d53c1325e)

**Comment by marcellmueller** [comment]
@MarsRomer I can't reproduce #1 though I believe it's because I'm on Mac. Though I don't believe I can fix that unless we make the default option have the normal darker text. To make it have the lighter text for the initial option I had to basically change the text colour for all the dropdown options then change it once another one is selected. Styling dropdown menus is very limited and styling individual options can't be done (unless we create a custom one which can be a lot of work and isn't recommended for accessibility).

The rest I should be able to sort out, I will get on it today.

**Comment by MarsRomer** [comment]
@marcellmueller thanks, I am putting this ticket in the 'In progress' for now

**Comment by MarsRomer** [comment]
@marcellmueller  that works much better!  Just one thing I noticed about the dates, it's doing that thing where it changes the displayed date by one day.  I selected the 7th
![image.png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/5708d1c8-2d88-4b3b-b594-55ccbadad23b)
and after clicking save
it changed to 8th:
![image.png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/cfc166bf-d632-4b73-ab6f-38e56045b904)

**Comment by MarsRomer** [comment]
@marcellmueller I noticed that the date issue is happening elsewhere in the portal too - e.g. the list of assessments show a different date than what is entered.  Is this a fix in once place thing that will get addressed with this ticket or do you think it's better to create a new bug ticket for it?

**Comment by marcellmueller** [comment]
Oh that again, good catch. I can fix it!
