### ISSUE TITLE
Import  GIS Analysis Data Input

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1142]
As a member of the data team
I want to be able to upload the data analysis output
so that the analysts can use it for their assessments

**Description:**
This ticket is to build the front end for uploading the JSON file from the data team and then upload the data in the back end.  
Not included:  This ticket does not include the front end for the preview and confirmation/error pages. (#1382)

# Acceptance Criteria:
- [x] Use json input from data team to bulk import 
- [x] Json file will follow portal db schema
- [ ] Validate that the json being uploaded is the latest? possibly by asking data team to add timestamp to the name.  or by checking the analysis date in the json.
- [x] can see data in metabase to validate that it uploaded correctly
- [x] GIS Tab exists between dashboard and Admin tabs
- [x] Upload button on GIS tab
- [x] upload button only works with json
- [x] Uses growthbook feature flag

## Edit GIS Analysis

**Screen**
Upload page:
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/e99e1fae-ddbe-4c1b-a564-28eaaabe18d1)

**Page Behaviours**

- [x] GIS analysis data is easily accessible for the analyst doing the tech assessment
- [x] GIS analysis data exists in the database in a manner that it can be queried in metabase so that it can be included in the Selection Deck

**Validations**

- [x] **File type:** JSON 
- [x] The JSON file must match the expected format/structure

**Actions**

- [x] Save the data.
- [ ] Record the action in the history table (?).

**Comment by elliottSlee** [comment]
The data team has created a template with similar CCBC branding. Note, this is not a program document; this was created to be a record of the data team's output & outcomes for a project. Sample is available here: https://bcgov.sharepoint.com/:x:/r/teams/053702/Shared%20Documents/General/CCBC_Applications/GIS%20Assessments/CCBC-010011-GIS%20Assessment.xlsm?d=w50f8576f9edd45a4bc8cc03405a0f37d&csf=1&web=1&e=BDHnJe

**Comment by MarsRomer** [comment]
hey @VB-at-Bis  did you mean to close this ticket or put it into the PO review column?

**Comment by MarsRomer** [comment]
Could someone please email or attach a copy of the json file I could test this with?

**Comment by elliottSlee** [comment]
@MarsRomer https://bcgov.sharepoint.com/teams/04708/_layouts/15/download.aspx?UniqueId=66912c9c5e334d8f9456a05fb2ce8aa3&e=icslFb

**Comment by MarsRomer** [comment]
@VB-at-Bis which table(s) can I check in Metabase to see if the upload was successful?

**Comment by MarsRomer** [comment]
Hey Vlad, there are a few AC in this ticket that aren't checked off, do you want to look at them before I review?

**Comment by MarsRomer** [comment]
Hey Vlad, there are a few AC in this ticket that aren't checked off, do you want to look at them before I review?

**Comment by VB-at-Bis** [comment]
Metabase users can use `select *, ccbc_public.application_gis_data(app) from ccbc_public.application as app;` to get latest GIS data for the application

**Comment by VB-at-Bis** [comment]
Discussed with Elliot if we need to `Record the action in the history table.`  It seems GIS JSON uploads will contain all applications even if only some of them have updated estimates and thus, we need to avoid writing duplicate history records. We will create separate table for application GIS data and store only unique records there, and track history of that table, not the `gis_data` which stores batch JSONs.
