### ISSUE TITLE
Bug:  Submission Page shows 'Invalid DateTime'

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1146]
**Describe the bug**
When no intake is currently open, the submission page shows 'Invalid DateTime'

**To Reproduce**
1. Go to Applicant portal
2. Click on any project where you can go to the submission page
3. on Time Machine set date to Jan 13 2023
4. See error:  After submission, you can continue to edit this application until the intake closes on Invalid DateTime

**Expected behaviour**

- [x] If the application was submitted, and the intake has closed then the closing date of the intake in which this application was submitted shows.

 - [x] if the application was submitted and the intake is still open then the closing date of the current  shows.

- [x] If the application has not submitted, and no intake is currently open then the sentence reads: 
After submission, you can continue to edit this application until the intake closes.

- [x] If the application has not been submitted, and no intake is currently open then the sentence reads:
After submission, you can continue to edit this application until the intake closes.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/1e2ae52f-2de1-4464-a8ba-b368b21852fd)

**Logs/tracebacks**

**Additional context**

**Comment by carreenu** [comment]
Functionality demonstrated by Elliot and bug is fixed. Move to Sprint Done please.
