### ISSUE TITLE
Investigate Sysdig notifications

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/CONN-CCBC-portal#1156]
Description: 
We are receiving a lot of Sysdig notifications and should investigate and either fix the issues or reduce the notifications when it is safe to do so.

Risk:  There could be some issues we need to fix that could affect availability of the application.
Too many redundant notifications - makes it difficult to understand the important ones.

Acceptance Criteria:
- [x] Reduce redundant and unimportant notifications (could be by adding a filter)
- [x] Understand what notifications we are getting, why and what.
- [x] Document who is subscribed to notifications and ensure appropriate people on the team are receiving.
- [x] Create tickets of what needs to be fixed - add to Task Column for anything that is not urgent, anything urgent should be discussed with PO and/or added to the this sprint To Do list.

**Comment by MarsRomer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1156?planning-poker) with Zenhub @VB-at-Bis

**Comment by MarsRomer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1156?planning-poker) with Zenhub @marcellmueller

**Comment by MarsRomer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1156?planning-poker) with Zenhub @pdoc1111

**Comment by marcellmueller** [comment]
I have a meeting with Dylan to work on this Tuesday.

**Comment by eazeredo** [comment]
@marcellmueller , has this card something that needs to deploy to test?
Or can this be moved to Sprint Done?
