### ISSUE TITLE
Bug:  Logout for analyst not working

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1161]
**Describe the bug**
When any of the analysts in gov who are successfully logged into the analyst portal click the logout button in the top right, they get an error message

**To Reproduce**
1. Go to analyst portal
2. Log in
3. Click logout in the top right
4. See error:

![image.png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/1a0e8b1d-e53b-4426-a99f-47bbc77bb437)
**Expected behaviour**
Logout should be successful

**Screenshots**
![image.png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/06623cef-5b68-484c-a59b-da73c8159c98)If applicable, add screenshots to help explain your problem.

**Logs/tracebacks**

**Additional context**

**Comment by carreenu** [comment]
Have logged into both the test and live analyst portal and the logout is working as it should. It returns me to the login page. See screenshot.
[https://app.zenhub.com/files/476885245/f33820e9-1488-45c3-9b31-de343012af7e/download](https://app.zenhub.com/files/476885245/f33820e9-1488-45c3-9b31-de343012af7e/download)
