### ISSUE TITLE
Add intake column to Analyst Dashboard

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1167]
As an analyst 
I want an 'Intake' column
so that I can filter, sort, and distinguish applications by intakes

## Acceptance Criteria:
- [x] Intake as a column in analyst dashboard
- [x] Left padding of intake is 0
- [x] Change padding on CCBC ID col to 8px on both sides
- [x] Resize CCBC ID column
- [x] Resize status column
- [x] Resize package column
- [x] Sortable
- [x] Filterable
- [x] Conditional approval Status pill wraps text on the dashboard
- [x] Conditional approval Status pill does not wrap text in the application

## Not included:
-
-

## Technical Analysis
- [ ] .
- [ ] . 
- [ ] .

## Wireframes
![Intake col.jpg](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/0d746057-57b2-4c79-9673-abf435bbfe2b)

**Comment by MarsRomer** [comment]
@elliottSlee can you please add screen design for this ticket?

**Comment by MarsRomer** [comment]
@elliottSlee can you please add screen design for this ticket?

**Comment by elliottSlee** [comment]
@eazeredo the Acceptance criteria for this card has changed. We will need to re-estimate.
cc @VB-at-Bis @marcellmueller @AntBush

**Comment by eazeredo** [comment]
Let's talk about the changes tomorrow in the daily.

**Comment by elliottSlee** [comment]
Why not discuss async here?
