### ISSUE TITLE
Analyst - Expand all & collapse all application sections

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#1168]
As an analyst
I want to expand and collapse all the application sections with a single click
so that I don't have to individually open/close them one by one.

### Screen 

- [**Wireframes**](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=6978%3A58877&t=6awKkUZLPmlSmiwR-4)

![image.png](https://images.zenhubusercontent.com/606c9d37b7ff542cfdb25c53/d9117d67-4693-4fea-b401-db3cd20632fb)

- [ ] KEEP THIS: by default the tabs are all closed except for the tabs where there is missing info

### Page Behaviours

- [ ] Expand all and Collapse all options are both visible on the page at all times
- [ ] The expanded and collapsed state resets to default state for the accordion when applicant clicks away from the Application subpage

### Actions

- [ ] Clicking "Expand all" opens all sections of application
- [ ] Clicking "Collapse all" closes all sections of application including the ones that are missing info
---
- [ ] Make a PR with the update to the Button Toolkit

## Not included:
- .
- .

## Ultra Refinement 
- We're using the toolkit accordion. Has the functionality for default expanded/collapsed, look into what's preventing this to be done to have it be dynamically controlled.

- **DB:**
  - .
  - .
- **Middleware:**
  - .
  - .
- **Frontend:**
  - .
  - .
- **Tests:**
  - .
  - .
- **Documentation:**
  - .
  - .

**Comment by MarsRomer** [comment]
Hey @AntBush I noticed that this is already in prod?
![image.png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/6e7d9651-9c86-48de-9393-1a19109e4322)

**Comment by AntBush** [comment]
Yeah I think this was forgotten to be added in the review column

**Comment by MarsRomer** [comment]
I don't think we explicitly said this in the ticket but should the plus signs change to minus signs when we click 'Expland all' and vice versa to be consistent with how the folders behave? ![image.png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/b6f49a4d-6a45-43a5-a5fd-f46da5132002)

**Comment by elliottSlee** [comment]
@AntBush can we get 4px margin below so it's not touching?

**Comment by AntBush** [comment]
I've created a PR for this: https://github.com/bcgov/CONN-CCBC-portal/pull/1376
