### ISSUE TITLE
Clean up Sonarcloud code smells

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/CONN-CCBC-portal#1169]
We looked through these the other day and noticed some low hanging fruit that would be worth spending a small amount of time to clean up.

- [ ] Clean up code smells
- [ ] Document smells we don't necessarily want to fix right away (maybe some of the TODO comments for example)

**Comment by MarsRomer** [comment]
hey @marcellmueller there are unchecked items in the AC.   Is there someway I can PO review this?

**Comment by marcellmueller** [comment]
For this ticket I cleaned up some of the simple code smells, reducing the number from 58 to 37.

- Fixed a lot of `prefer optional chaining` smells
- Removed some old commented code
- Removed some outdated `TODO` comments
- Fixed a large dependency cycle issue with our RJSF theme and the Review page components
