### ISSUE TITLE
1110 - Add Sentry performance metrics

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/CONN-CCBC-portal#1173]
https://docs.sentry.io/platforms/javascript/guides/nextjs/performance/instrumentation/performance-metrics/

This comes from a discussion we had about diagnosing the upload issue but ideally would be added to most transactions. Having metrics would help inform us about the frequency of any issues and help identify areas of our application that has poor performance.

- [x] Enable traces sampler in sentry client and server configs
- [x] Set up custom transaction for file upload
- [ ] follow up and actually use telemetry to monitor our transactions

**Comment by wenzowski** [comment]
The original ticket included the following:
> - Identify useful metrics
> - Track performance metrics in file uploads (at the absolute bare minimum we need to track whether an upload succeeds or fails)
> - Identify other areas that would benefit

We should ensure we are collecting the standard metrics from the JavaScript Browser SDK, which are representative of [Web Vitals](https://web.dev/vitals/)
> First Paint: fp
> First Contentful Paint: fcp
> Largest Contentful Paint: lcp
> First Input Delay: fid
> Cumulative Layout Shift: cls
> Time to First Byte: ttfb
> Time to First Byte Request Time: ttfb.requesttime

We should also ensure we're monitoring in the context of [standard thresholds](https://web.dev/defining-core-web-vitals-thresholds/).

Does our current Sentry plan include [Dynamic Sampling](https://docs.sentry.io/product/data-management-settings/dynamic-sampling/)? If not we may need to explore opportunities to either adjust the plan or a different technical pathway for custom defined metrics.

**Comment by MarsRomer** [comment]
hey @marcellmueller  is this acceptance criteria one that we can check off?  
" follow up and actually use telemetry to monitor our transactions"

**Comment by marcellmueller** [comment]
> hey @marcellmueller is this acceptance criteria one that we can check off? " follow up and actually use telemetry to monitor our transactions"

Well it's a bit of a weird acceptance criteria that I wrote though this ticket is complete. It's something we will need to discuss at sprint retrospective and build into our normal devops work. 

The custom uploads tracking just went to prod and we will especially want to keep an eye on that as we accumulate more data.
