### ISSUE TITLE
Add LazyLoading to pagination for Sortable/Filterable table component

### ISSUE THREAD

**Issue by AntBush** [bcgov/CONN-CCBC-portal#1176]
Add lazy loading in a DRY manner to the table component for better pagination.

**Comment by elliottSlee** [comment]
Is this a user story or a task? What's the benefit of having it with the # of rows we have?

**Comment by AntBush** [comment]
This would be a task, since the table's pagination would still be functional from a user perspective.

**Comment by AntBush** [comment]
This would be a task, since the table's pagination would still be functional from a user perspective (except for better load times)
