### ISSUE TITLE
Tasklist | Sidebar Iteration

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#119]
### User Story

As an applicant, 
I want to see the pages (tasks) I need to complete
so that I can visualization my progress and jump between pages.

### Research & Design
aka taskbar or stepper
**Wireframe:** https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=2830%3A11729
Based upon [UK Gov Design Research](https://design-system.service.gov.uk/patterns/task-list-pages/)

### Acceptance Criteria
- [ ] Background: #F6F6F6
- [ ] Page that user is on, text is bolded
- [ ] Page that user is on, background: #DDE6EF
- [ ] Can click on any page to navigate directly there
- [ ] Task list titles match page relevant page headings
- [ ] Page that user is on, that section is toggled open and other sections are toggled closed
- [ ] When toggle open is clicked, options expand (e.g., CSS expand animation instead)
- [ ] <s>Floats on left & moves with scroll</s>

![image.png](https://images.zenhubusercontent.com/61e8875b1de5eff8f072cd04/162d9e23-c2c5-4099-a8aa-c538b129a125)

![image.png](https://images.zenhubusercontent.com/61e8875b1de5eff8f072cd04/86d2351c-9ff7-40db-a5b0-b0793747e351)

**Comment by eazeredo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/119?planning-poker) with ZenHub @AntBush @marcellmueller @wenzowski
