### ISSUE TITLE
Analyst Dashboard - Filter V3

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#1192]
# User Story
As an analyst, 
I want to filter applications
so that I can easily find the ones I need to focus on

# Acceptance Criteria
## Design
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/dd3e30b1-606c-4ebb-aad3-ef64705213e1)
#
- [ ] anything that matches, the row is shown (e.g., "com" would return all rows with status reCOMmendation and all rows from organization rogers COMmunications canada inc.)
- [ ] Filtering by two or more words, they will be combined by an inclusive clause ("Received" AND "TELU" in any field)
- [ ] pressing enter while typing in the input box initiates search
- [ ] pressing the button beside the box initiates the search
- [ ] after anything is entered, the clear x appears on the right of the input box
icon: https://fontawesome.com/v6/icons/circle-xmark?s=solid&f=classic
colour: 9B9B9B
size: 1.5em
- [ ] pressing the x icon clears anything in the input box and the search results
- [ ] filter is above "clear sorting"

# Test Cases: 
## Test Data:

- Existing data:
   | ID   | Intake | Status         | Title          | Org       | Lead    |
   |------|--------|----------------|----------------|-----------|---------|
   | CCBC-010001 | 1      | received       | communcation   | citywest  | Rachel  |
   | CCBC-010002 | 1      | recommendation | steward friday | telus     | Justin  |
   | CCBC-010003 | 1      | recommendation | santa Bay      | telus Inc | Rachel  |
   | CCBC-020004 | 2      | received       | bc northem        | rogers    | Rachael |
   | CCBC-020005 | 1      | received       | communication telus   | citywest  | Rachel  |
Searching for "com telus" in all columns

### Test Steps:
1. Open the application and navigate to the search function.
2. Enter the search query "com telus" into the search bar.
3. Click the "Search" button to initiate the search.
#
- [ ] 4. Verify that the search results include the following rows:
   
   | ID   | Intake | Status         | Title          | Org       | Lead    |
   |------|--------|----------------|----------------|-----------|---------|
   | CCBC-010002 | 1      | recommendation | steward friday | telus     | Justin  |
   | CCBC-010003 | 1      | recommendation | santa Bay      | telus Inc | Rachel  |
   | CCBC-020005 | 1      | received       | communication telus   | citywest  | Rachel  |
   
   **Expected Result:** The search should look for the combination of "com" and "telus" in all columns, searching for all the words in any part of the column. The rows that match the search criteria should be returned. In this case, all three rows contain either "com" or "telus" in one or more of the columns, so they should all be returned. The Package column was not listed in the original data, so it should not be included in the search.
#
- [ ] 5. Verify that the search results do not include any other rows.
   **Expected Result:** Only the rows that match the search criteria should be returned. No other rows should be included in the search results.
#
- [ ] 6. Verify that the search results are displayed in the correct order according to the sorting rules of the application.
   **Expected Result:** The search results should be sorted according to the sorting rules of the application, such as by date, ID, or relevance.
#
- [ ] 7. Verify that the search function returns an appropriate message if no results are found.
   **Expected Result:** If no results are found, the search function should return a message indicating that no results were found, or suggesting alternative search terms.

### Test Steps:
1. Open the application and navigate to the search function.
2. Enter the search query "-01" into the search bar.
3. Click the "Search" button to initiate the search.
#
- [ ] 4. Verify that the search results include the following rows:
   
   | ID   | Intake | Status         | Title          | Org       | Lead    |
   |------|--------|----------------|----------------|-----------|---------|
   | CCBC-010001 | 1      | received       | communcation   | citywest  | Rachel  |
   | CCBC-010002 | 1      | recommendation | steward friday | telus     | Justin  |
   | CCBC-010003 | 1      | recommendation | santa Bay      | telus Inc | Rachel  |

## Not included
- The search applies only to the fields shown in the results table.

## Technical Refinement / Subtasks
- **DB:**
  - https://www.postgresql.org/docs/current/functions-textsearch.html
  - .
- **Middleware:**
  - .
  - .
- **Frontend:**
  - .
  - .
- **Tests:**
  - .
  - .
- **Documentation:**
  - .
  - .

**Comment by elliottSlee** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1192?planning-poker) with Zenhub @marcellmueller @wenzowski @AntBush @VB-at-Bis

**Comment by eazeredo** [comment]
@elliottSlee , @VB-at-Bis , @marcellmueller , @AntBush , I added the test cases in the description.

**Comment by MarsRomer** [comment]
Looks pretty good, just a couple of glitchy things happening:
1. Filtering on Intake doesn't work
i typed in 1 and hit enter and I can see 1's and 2's in the intake column.  Same result with entering 2 and hitting enter

2.  Filtering on the lead doesn't clear to show me the full list when I backspace the name in the lead filter and hit enter:
![image.png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/604a47c2-c389-45ea-9911-1125690c55a0)

**Comment by MarsRomer** [comment]
@marcellmueller Looks like the above issues are fixed :)
Quick question:  how does one filter the Lead column to show only 'Unassigned' ones?

**Comment by marcellmueller** [comment]
@MarsRomer hmmm we might need a ticket for this if we want the ability to do that. `Unassigned` is just a placeholder (in the application header we use `Lead` as a placeholder) and is not in the database so it isn't getting filtered. 

Might not be ideal but as the table is now the best way to get unassigned would be to use the sorting.

**Comment by MarsRomer** [comment]
I think that the analysts would like to be able to filter on null values in some way, lets ideate on the least-effort way of implementing this would be in the near future
