### ISSUE TITLE
801 - History: Database implementation

### ISSUE THREAD

**Issue by eazeredo** [bcgov/CONN-CCBC-portal#1208]

**Comment by VB-at-Bis** [comment]
Based on discussion with the team next possible solutions were identified:
- using pgAudit (https://github.com/pgaudit/pgaudit/blob/master/README.md) to generate changelogs and use them to populate history table;
- using triggers in DB to populate history table;
- using custom code and handle CRUD events in the code and insert data to history table.
After initial investigation, second approach seems to be a best choice as it saves a lot of efforts.
Chosen extension: https://github.com/supabase/supa_audit/blob/main/README.md

**Comment by VB-at-Bis** [comment]
## What was done:

- copied code from https://github.com/supabase/supa_audit/blob/main/supa_audit--0.3.0.sql
- updated script to add permissions to ccbc_auth_user, ccbc_analyst, ccbc_admin;
- installed extension uuid-ossp (run in psql `create extension "uuid-ossp";`);
- updated script to expicitly use public schema for calls to uuid_generate_v4 and uuid_generate_v5;

**Comment by MarsRomer** [comment]
Is there something here for PO review?
