### ISSUE TITLE
801 - History:  Backfill data for existing data

### ISSUE THREAD

**Issue by eazeredo** [bcgov/CONN-CCBC-portal#1209]

**Comment by VB-at-Bis** [comment]
Steps to backfill data :

1.  run `kubectl exec -it ccbc-hippo-ha-xzsq-0 -- /usr/pgsql-14/bin/pg_dump ccbc --inserts --on-conflict-do-nothing > backup.sql`

2. Edit the backup file:
- remove data for next tables :
ccbc_private.connect_session
ccbc_public.analyst 
ccbc_public.form_type (name, description) 
ccbc_public.form (id, slug, json_schema, description, form_type)
ccbc_public.form_data_status_type (name, description) 
ccbc_public.application_status_type (name, description, visible_by_applicant, status_order) 
ccbc_public.assessment_type (name, description)

and all sqitch.* tables




 
- add next statements before the `ccbc_public.users` data:
truncate ccbc_public.ccbc_user cascade;

ALTER TABLE ccbc_public.application DISABLE TRIGGER _100_timestamps;
ALTER TABLE ccbc_public.application_status DISABLE TRIGGER _100_timestamps;
ALTER TABLE ccbc_public.attachment DISABLE TRIGGER _100_timestamps;
ALTER TABLE ccbc_public.assessment_data DISABLE TRIGGER _100_timestamps;
ALTER TABLE ccbc_public.rfi_data DISABLE TRIGGER _100_timestamps;

- add next statements in the very end of the file:
ALTER TABLE ccbc_public.application ENABLE TRIGGER _100_timestamps;
ALTER TABLE ccbc_public.application_status ENABLE TRIGGER _100_timestamps;
ALTER TABLE ccbc_public.attachment ENABLE TRIGGER _100_timestamps;
ALTER TABLE ccbc_public.assessment_data ENABLE TRIGGER _100_timestamps;
ALTER TABLE ccbc_public.rfi_data ENABLE TRIGGER _100_timestamps;

3. Run 
psql -d ccbc -a -f backup.sql

Applying backup will generate historic records in `ccbc_public.record_version` table.

**Comment by eazeredo** [comment]
Should we have a SQL script with this code and run it?

**Comment by VB-at-Bis** [comment]
It will be that's backup.sql that will be created on step 1 - after we deploy new extension/triggers (other PR for #1210). There is no sense to create it before, or check it into GitHub (it would contain all data entered by the customers and analysts).
Manual step, that should be done once :)
