### ISSUE TITLE
Do not allow applicant to save multiple versions of the form for the same application

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#1212]
As an applicant
I want to be warned and stopped from having conflicting versions of an application
so that I don't continue working on an application that's different from what I originally created.

## Description
The bug of an application that was submitted without acknowledgements was likely due to multiple versions of the application having been created. It could happen when someone opens the same application in multiple tabs.

## Acceptance Criteria:
- [x] detect conflicting versions of an application on save and autosave
- [x] on Save/autosave, display warning modal on the page the user is on if they have a different version of the form
- [x] Pressing button in modal will update the page with the latest form data
- [x] Database will not save outdated form data

![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/b6ee33bd-5be3-4dde-9c20-4c2bacf12b12)

**Comment by elliottSlee** [comment]
@AntBush does this adequately summarize the issue?

**Comment by AntBush** [comment]
Yup! Thanks Elliot!

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1212?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc @VB-at-Bis

**Comment by elliottSlee** [comment]
@MarsRomer Wireframe updated

**Comment by MarsRomer** [comment]
hey @AntBush  were all the acceptance criteria completed?

**Comment by AntBush** [comment]
Oh yes it was! Sorry should've checked them off

**Comment by MarsRomer** [comment]
I tried editing the same application in different tabs and it works well! I got the pop up modal and the form updated as expected.

**Comment by MarsRomer** [comment]
@AntBush upon more testing it appears that there is some sort of bug where the modal pops up for me even though I don't have multiple tabs open for the application. In this instance I logged into the Applicant test portal, and clicked the button to Start a new Application, and as soon as I typed 2 letters in the project description field I got the modal.
  ![image.png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/840186f9-0393-4b8c-8f9b-6257a4c8d97e)

**Comment by MarsRomer** [comment]
I am no longer getting the previously reported modal error, but now I am not getting the modal when I would expect it.  i.e. I have two tabs open on the same page of the same application, I can go back and forth between the tabs and update the text in the same text box without getting a modal.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWNJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f526a67347b0d0ebe6a5e2c3a8eb30911eb82967/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWdJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c28924375b9da9d994a3d8c92f5a41a5278108b5/image.png)
