### ISSUE TITLE
Bug:  Can't edit draft application after intake closes

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1239]
**Describe the bug**
When the intake is closed, applicants should still be able to edit their draft applications (as long as they haven't submitted it or withdrawn it).  Regardless of if an intake is open or closed.

**To Reproduce**
1. Go to applicant dashboard (TEST env)
2. Use time machine to be within an open intake
3. Create a draft application and return to dashboard
4. Change the time machine data to some time in the future when no intake is open
5. attempt to edit the application - you will see that you only have a 'view' option

**Expected behaviour**
The dashboard has an edit option for draft applications regardless of if an intake is open or closed

**Screenshots**
![image.png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/375253dd-15a2-4d28-9e08-d9013cdcfc69)

![image.png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/2c073d8e-76d5-4404-a966-bf098842d38f)
**Logs/tracebacks**

**Additional context**

**Comment by AntBush** [comment]
Is this a bug? This was the defined behaviour in #121

**Comment by MarsRomer** [comment]
thanks for referencing #121, I see that we made it uneditable in that ticket, I was looking at an earlier ticket where we had decided to allow it to be edited
