### ISSUE TITLE
Bug:  Application CCBC IDs are not sequential

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1240]
**Describe the bug**
The CCBC ID for the second intake should follow a format of 
CCBC-020001
CCBC-020002
CCBC-020003
CCBC-020004
CCBC-020005

instead it is missing some of the sequential number

**To Reproduce**
1. go to meatabase
2. view prod data for Application
3. Notice CCBC IDs for 2nd intake

**Expected behaviour**
Ids should be sequential

**Screenshots**

**Logs/tracebacks**

**Additional context**

**Comment by AntBush** [comment]
Hey Mars, this is defined behaviour for the way we're generating CCBC IDs (see [this](https://help.heroku.com/PRNW4R5Z/why-are-there-gaps-in-my-postgres-id-sequence) article for an explanation). We can change this but it would effectively be tackling #880 as we would no longer be using a sequence. 

Do you want to bring that ticket in, and add this as an AC?

**Comment by AntBush** [comment]
Hey Mars, I just want to have go-ahead on the change to use a counter vs a sequence (the current method) if having gaps is a must-have for the business process. 

The risks of using a counter is that we lose concurrency in this operation, additionally it means we can run into deadlocks which will result in more cancelled operations (and thus fails/rejections when trying to submit). If these risks are acceptable I can go ahead and merge this in once it's ready and reviewed

**Comment by MarsRomer** [comment]
Hey @AntBush can we have a quick chat about it at 930 please so I am confident I understand the implications you have outlined above?

**Comment by AntBush** [comment]
Sure thing!

**Comment by MarsRomer** [comment]
CCBC IDs are not quite assigning correctly
![image.png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/d20f5030-baa6-48ea-888e-58ea1ce5d80c)

**Comment by MarsRomer** [comment]
Thanks Tony, 
Yes please fix the ccbc number so it doesn't seem strange during demos

**Comment by MarsRomer** [comment]
Also we may need to create a 3rd (and 4th) intake in test to test this out

**Comment by AntBush** [comment]
Should be all fixed up now if you want to give it a look over, want to create the other intakes after the demo?

**Comment by MarsRomer** [comment]
yep looks good.  and Yes lets create another intake today, if you do that then I can PO review this by end of sprint.  You can use start date and time as Sept 21, 9am and end date as Dec 21, 2pm 2023

**Comment by AntBush** [comment]
Hey I've added the third intake with those parameters
