### ISSUE TITLE
Maintain Sorting on Analyst Dashboard

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1246]
As an analyst
I want my sorting to be maintained between screen changes for the duration of my session
So that I don't have to come back and sort again each time I leave the dashboard 

**Description:**
Analysts should not have to re-establish their sort order every time they navigate back to the dashboard.  The sorting they had.  This includes coming back using the 'Back' button on the browser as well as the 'Dashboard' button on the portal

# Acceptance Criteria:

## Dashboard

**Page Behaviours**

- [ ] The dashboard should be sorted the way they left it when the user opens an application and:
  - [ ] clicks the back button on the browser
  - [ ] clicks the dashboard link on the analyst review page (regardless of which analyst subpages the analyst was on)
#
- [ ] Sorting is not maintained when 
  - [ ] the session ends for the user - i.e they log out, 
  - [ ] close the browser 
- unless it's easier to maintain sorting between sessions

### Not included:
- The applied filter should be reset
- .

## Implementation Details
- **DB:**
  - .
  - .
- **Middleware:**
  - .
  - .
- **Frontend:**
  - Save the sorting query parameters as a session cookie.
  - .
- **Tests:**
  - .
  - .
- **Documentation:**
  - .
  - .

**Comment by MarsRomer** [comment]
I am not finding that the sorting is maintained.
I sorted by Status, then clicked on one of the applications in the list, then came back to the dashboard by clicking the 'Dashboard' button and the sort had gone back to being sorted by CCBC ID

**Comment by marcellmueller** [comment]
@MarsRomer oh nice catch. It actually does work but you have to click twice. We have a fix already and incoming so it will work on the first sort.
