### ISSUE TITLE
Analyst is brought back to the dashboard list page position where they left off

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1248]
As an applicant when I go back to the dashboard
I want to be taken to the list where I was
so that I can easily navigate the records in the dashboard

**Description:**

# Acceptance Criteria:

## Dashboard - Analyst portal

**Page Behaviours**

- [ ] The dashboard should scroll the page to the same spot in the list where they were when the user open an application and:
  - [ ] clicks the back button on the browser 
  - [ ] clicks the dashboard button on the analyst review page (regardless of which analyst subpages the analyst was on) 

### Not included:
- .
- .

## Implementation Details
- **DB:**
  - .
  - .
- **Middleware:**
  - .
  - .
- **Frontend:**
  - Let's use anchors (#)
  - .
- **Tests:**
  - .
  - .
- **Documentation:**
  - .
  - .

**Comment by eazeredo** [comment]
You have to store the scroll position in `state` on click of post with the use of `window.pageYOffset`
```
this.setState({
    scrollPosition: window.pageYOffset
});
```
And once you click on back button at that time you have to set the window position in the method of `componentDidMount`.
`window.scrollTo(0, this.state.scrollPosition);`
By default you can set the value of `scrollPosition` is `0`.
https://stackoverflow.com/questions/59100931/maintaining-state-and-scroll-position-in-react

**Comment by elliottSlee** [comment]
@MarsRomer What do you think about adding a visual indication of what application analysts returned from, like Gmail uses? https://www.figma.com/proto/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?page-id=6958%3A32778&node-id=10428%3A71961&viewport=1271%2C5047%2C0.52&scaling=min-zoom&starting-point-node-id=10428%3A71961&show-proto-sidebar=1

**Comment by MarsRomer** [comment]
Love it!
