### ISSUE TITLE
Bug:  can't upload multiple files for RFI

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1254]
**Describe the bug**
When applicant tries to upload the Other Supporting Documents from an RFI they can't upload multiple files

**To Reproduce**
1. Go to RFI and create an RFI asking for Other supporting Documents
2. Go to applicant portal and try to upload multiple documents
3. See error - can't upload multiple files

**Expected behaviour**
Applicant should be able to upload multiple files where applicable

**Screenshots**

**Logs/tracebacks**

**Additional context**

**Comment by AntBush** [comment]
Fields that multiple files have been added: 
- Copies of Registration
- Project Schedule
- Community Rural Development Benefits
- Other Supporting Materials
- Current Network Infrastructure
- Upgraded Network Infrastructure

**Comment by MarsRomer** [comment]
Two others that are also supposed to be multifile:
Independently prepare financial statements for the last 3 years 
&
Logical Network Diagram 

But the 'Other Supporting Documentation' is the most urgent so I would like to see that go through to prod as quickly as possible and we can focus on any other missed ones after that.
