### ISSUE TITLE
Move secrets to hashicorp vault in tools namespace

### ISSUE THREAD

**Issue by AntBush** [bcgov/CONN-CCBC-portal#1260]
Move the secrets from 1pass to hashicorp vault in tool namespace, document the kubectl commands to get and put the .env 
Business Value:  Higher security of secrets

- [ ] Store development .env in hashicorp vault or passbolt? https://github.com/passbolt/charts-passbolt
- [ ] Document commands

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1260?planning-poker) with Zenhub @marcellmueller @VB-at-Bis @rafasdc

**Comment by MarsRomer** [comment]
Closing as this ticket is a duplicate of #1878 and #2172
