### ISSUE TITLE
Doc - Proj Tech Information

### ISSUE THREAD

**Issue by eazeredo** [bcgov/CONN-CCBC-portal#1263]
Purpose: Anybody new onboarding can find the instructions to run this project.

## Documentation

- [x] Make a table of contents near the top of our `README.md` with links to various documentation in our project
https://github.com/bcgov/CONN-CCBC-portal/blob/main/docs/Tech_Stack.md
#### Project technical information
- [x] Detail tech stack and why we chose it
- [x] Link to Button Toolkit which could be helpful to future developers

**Comment by MarsRomer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1263?planning-poker) with Zenhub @rafasdc

**Comment by MarsRomer** [comment]
can all the check boxes be checked off on this?  can I request that we get a link to this documentation in the ticket too for PO review and historical reasons?

**Comment by MarsRomer** [comment]
@AntBush  poke (see question above) :)

**Comment by AntBush** [comment]
Sorry! And yeah, I can link that in here. Missed the point about the button toolkit too I'll make a small PR for that.

**Comment by MarsRomer** [comment]
ok great, I will place this ticket in the 'in progress column' for now

**Comment by MarsRomer** [comment]
@AntBush I think that last ac can be checked off now?  
And where would we document Material UI?  Do you think it belongs in this doc or some other?

**Comment by AntBush** [comment]
Yeah it should probably be added in this doc, should be just under/over the toolkit link. Technically should be another ticket, but it's small enough I can just do it

**Comment by MarsRomer** [comment]
OK thanks, I will place this in the in progress column so I know when it's ready for review again
