### ISSUE TITLE
Doc - User roles

### ISSUE THREAD

**Issue by eazeredo** [bcgov/CONN-CCBC-portal#1267]
Purpose: Anybody new onboarding can find the instructions to run this project.

## Documentation

- [x] Make a table of contents near the top of our `README.md` with links to various documentation in our project

#### User roles
- [x] Detail different user roles
- [x] How to set roles in SSO app

**Comment by elliottSlee** [comment]
@AntBush Forgive my naïveté, is `Authentication and Authorization` convention in referring to User Roles?

**Comment by AntBush** [comment]
The "Authorization" portion would be most related to User Roles, with Authentication being how we determine who belongs to which role
