### ISSUE TITLE
Doc - Contributing

### ISSUE THREAD

**Issue by eazeredo** [bcgov/CONN-CCBC-portal#1270]
Purpose: Anybody new onboarding can find the instructions to run this project.

## Documentation

- [x] Make a table of contents near the top of our `README.md` with links to various documentation in our project

#### Contributing
- [ ] Details about bv gov organization requiring signed commmits and how to enable them

**Comment by MarsRomer** [comment]
@marcellmueller should all the acceptance criteria be checked off on this one?
