### ISSUE TITLE
Doc - OpenShift information

### ISSUE THREAD

**Issue by eazeredo** [bcgov/CONN-CCBC-portal#1271]
Purpose: Anybody new onboarding can find the instructions to run this project.

## Documentation

- [x] Make a table of contents near the top of our `README.md` with links to various documentation in our project

#### Openshift information
- [x] Links to bc gov OpenShift documentation
- [x] Steps to deploy the project in a new namespace
- [ ] Disaster recovery documentation
- [x] Cronjobs description and how to run manually if needed

**Comment by rafasdc** [comment]
Added initial info, if any of the devs could take a look and add anything missing that would be awesome :)
