### ISSUE TITLE
Docs: Windows/WSL specific project setup

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/CONN-CCBC-portal#1277]
We need to add Windows/WSL specific project setup information for future government developers.

Doc: https://github.com/bcgov/CONN-CCBC-portal/blob/main/docs/Getting_started_wsl.md

**Comment by MarsRomer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1277?planning-poker) with Zenhub @rafasdc

**Comment by MarsRomer** [comment]
hey @AntBush  would you be able to  post a link to this doc in the ticket please?

**Comment by AntBush** [comment]
Sure! Here you go: https://github.com/bcgov/CONN-CCBC-portal/blob/main/docs/Getting_started_wsl.md and I'll add it in the description as well

**Comment by MarsRomer** [comment]
thank you!  are you also able to add the estimation for this ticket please?  and for #1643 too?
