### ISSUE TITLE
Ability to edit/add information (RFI) post-intake workflow

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/CONN-CCBC-portal#128]
### User Story
As an applicant,
I want to add missing files or information after the intake when requested by the NWBC,
So that I can keep my application moving forward in the process

**Comment by zoeyli-46** [comment]
In discussion: whether users are able to add information and file uploads but select what field they are submitting information for, or edit the entire application, or edit only certain fields

**Comment by elliottSlee** [comment]
Mapped in a few ways here: https://miro.com/app/board/uXjVOANcgPo=/?moveToWidget=3458764526938665710&cot=14

**Comment by elliottSlee** [comment]
Can we close this @zoeyli-46 ?

**Comment by zoeyli-46** [comment]
Closing
