### ISSUE TITLE
Automated Report Capability (replace master spreadsheet)

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1281]
As an analyst
I want to be able to manage all CCBC and old program data and report on it from the portal
So that the data team and the comms team have automated reports from the database

**Description:**
_if needed_

# Acceptance Criteria:

## {Page Name}

**Screen**

[wireframe 1]
[wireframe 2]

- [ ] .

**Page Behaviours**

- [ ] .
- [ ] .
- [ ] .

**Validations**

- [ ] .
- [ ] .
- [ ] .

**Actions**

- [ ] .
- [ ] .
- [ ] .

### Not included:
- .
- .

## Implementation Details
- **DB:**
  - .
  - .
- **Middleware:**
  - .
  - .
- **Frontend:**
  - .
  - .
- **Tests:**
  - .
  - .
- **Documentation:**
  - .
  - .

**Comment by elliottSlee** [comment]
see also #222
