### ISSUE TITLE
Bug:  De-activated analysts are getting removed from places where they were previously assigned.

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1295]
Add new name (Mars)
Assign Lead = Mars on CCBC-010002 on the dashboard
De-activate Mars on Admin tab
Return to dashboard to see that Lead has now changed to unassigned. (error 1)
Return to admin tab and activate Mars
On Dashboard Mars reappears in Lead for that application
Return to list of analysts and Mars is deactivated (error 2)
I was able to recreate this with another name in the list (Mars 2).

Expected behaviour for error 1:
- [x] Name should be visible in the dashboard, but not visible as one of the options in the dropdown
Expected behaviour for error 2:
- [x] When revisiting the list, the name in the list should show the updated value

**Comment by AntBush** [comment]
Hey @elliottSlee error 1 is due to the option (the inactive Lead) no longer being in the list. Would you rather the option be visible but disabled or just unavailable as an option?

**Comment by MarsRomer** [comment]
Looks like the bug is fixed on the dashboard!  Can we also fix it for the individual assessment pages?
It works fine for the list of assessments below:

**Comment by AntBush** [comment]
Ah good catch, I'll make a PR for that. Thanks

**Comment by MarsRomer** [comment]
thanks!  I am moving the ticket to in progress for now
