### ISSUE TITLE
Pre-populate organization & contact information

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#131]
### User Story

As an Applicant, 
I want my organization and contact information to be pro-populated with a make more than 1 application
so that I don't have to enter it every time but can edit it if I need to.

### Research & Design
During usability testing we heard that a large ISP will have multiple applications with all the same organization and contact information. They felt it was a pain point in previous funding programs that they needed to enter all that information repeatedly.

### Acceptance Criteria
- [ ] Scenario: Pre-populate values from the first application
Given I have at least 1 application filled out
When I create a new application
Then all fields of the Organization Profile, Contact Information, Authorized Contact, and Alternate Contact from the first application are pre-populated in the new one
And the _Copies of registration and other relevant documents_ files are linked.

**Comment by eazeredo** [comment]
@elliottSlee , what do you think about duplicating an application? 

I'm wondering if an applicant wants to create the 2nd application from scratch, they will need to delete the content of all fields.

**Comment by eazeredo** [comment]
Is "all files" include the files uploaded?

**Comment by elliottSlee** [comment]
@zoeyli-46 I missed Eduardo's comment above about duplicating an application. Let's discuss this week.

**Comment by zoeyli-46** [comment]
@marcellmueller Is it possible that the first time an applicant enters the form they have to fill out org profile, location, contact, and registration, but for future applications, it has either auto-fill (where if you click into the field the answer from a previous form appears in a drop down) or is already filled by default? Which of these options are possible?

cc: @elliottSlee

**Comment by zoeyli-46** [comment]
Another thing is @elliottSlee they may have different contacts for different applications, whereas the organization profile, location, and registration is probably unlikely to change

**Comment by marcellmueller** [comment]
@zoeyli-46 It's definitely possible though this would require some extra dev time with either making a separate form once they make a new account or saving those details along with their account info once they fill that part of the form or on the first form submission. Dev time could range from small to large depending on some choices.

**Comment by zoeyli-46** [comment]
Regarding duplication:

Pending decision on whether we want to give applicants the ability to duplicate. IF we duplicate, it would only duplicate the form input fields, but not attachments or the project name.

**Comment by MarsRomer** [comment]
I think prepopulating the org and contact info is a nice to have so I am going to de-prioritize this and put it back in the product backlog.  I think this may be release 2.
