### ISSUE TITLE
Create e2e tests for user journeys on analyst portal

### ISSUE THREAD

**Issue by AntBush** [bcgov/CONN-CCBC-portal#1311]
Ticket to write user journey for analysts. 

AC: 
- [x] Happo screenshots 
- [x] Should attempt to save some data in RFI and Assessments page at least 
- [x] Change the status on the analyst side and check if the relevant status change is visible/invisible on applicant side

<mark> What are the User Journeys we want to test?</mark>
- [x] RFI process
- [x] Assessments process
  - [x] Screening
  - [x] Project Management
  - [x] Financial
  - [x] Technical
- [x] Status (change status is reflecting in both portals)

**Comment by eazeredo** [comment]
Is it make sense to have one PR for each e2e test?

**Comment by AntBush** [comment]
I mean we could? The assessments process should/can probably just be one single PR

**Comment by eazeredo** [comment]
Yes, I agree

**Comment by eazeredo** [comment]
We can move them individually if we do not connect the PRs to the issue.
When all PRs are done, we move the card to Sprint Done and connect the PRs to it.

**Comment by AntBush** [comment]
@MarsRomer When I was writing this I mentioned this status change, but right now there are no status changes on the analyst side that would be visible on the applicant side. Want me to create a test with a fake status that would be visible or would you rather split this and make it part of the acceptance criteria of #1338
