### ISSUE TITLE
Enter 'GIS' assessment

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1319]
As an analyst 
I want to enter and view the results of the GIS analysis
So that I can better prioritize applications for funding

**Description:**
A new tab to record GIS analysis results which will behave like the other assessment tabs

# Acceptance Criteria:
- [x] Add the 'GIS 'tab GIS between 'Screening' and 'Technical'

**GIS Assessment form**
- [x] Design matches the screen capture below
- [x] Assigned to drop down has list of analysts, as used in other assessment tabs
- [x] Target date is a date picker and functions the same as in other assessment tabs
- [x] 'Progress' is radio button - Default: 'Not Started'
- [x] User clicks save - save button changes to 'Saved' so that they have confirmation that it has saved.  
- [x] Add History: "[user] saved the GIS Assessment on [date] at [time]"
- [ ] Last Update date shows the last date and time a change was made to the form below the line (below the 'Target Date') Pacific Time

| **Field**                            | **type** | **domain**                                             | **Required** | **MaxLength** |
|-----------------------------|-----------|--------------------------------------------|---------------|------------------|
|  Assigned     |  dropdown   |  [List of active analysts]  |  No   |   |
|  Target date  |  datepicker  |  -  |  No  |   |
|  Progress      |  radio  | "Not Started", <br>"Needs RFI", <br>"Needs 2nd Review",  <br>"No obvious flags <br>identified at this stage" |  No  |   |
|  Comments on  coverage data             |  Textarea  |   | No   |    1,000 |
|  Comments on  household counts              |  Textarea     |  | No   |    1,000 |
|  Comments on  overbuild              |  Textarea    |   | No   |    1,000 |
|  Comments on  overlap  |  Textarea     |  | No   |    1,000 |

**List of Assessments**
- [ ] GIS assessment shows up on the assessment table below 'Screening' and above 'Technical'
- [ ] GIS progress will show in assessment table (use existing pill colours)
- [ ] GIS Analyst will show 'Not Assigned' on assessment table if not selected 
- [ ] GIS Analyst will show name of the analyst if selected
- [ ] GIS Target Date will show blank on assessment table if not set
- [ ] GIS Target Date will show as set on the GIS tab.  Use same formatting as rest of table
- [ ] GIS Decision will show blank on assessment table

## Wireframes

**GIS Assessment form**
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/52b14208-2d48-45a7-8c7a-38a11a6d753a)

**List of Assessments**
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/c0a821ff-4b30-414e-bf75-a5605fca5df6)
[**Wireframe**](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=10848-105913&t=M9oHwsktSJI9w0t6-4)

## Implementation Details
- **DB:**
  - .
  - .
- **Middleware:**
  - .
  - .
- **Frontend:**
  - .
  - .
- **Tests:**
  - .
  - .
- **Documentation:**
  - .
  - .

**Comment by MarsRomer** [comment]
hey @VB-at-Bis @marcellmueller @AntBush I am moving this down in priority temporarily, please don't start working on it for now.  We may either remove it from the sprint or discuss with you a different design.

**Comment by elliottSlee** [comment]
@MarsRomer I noticed that the textareas can't be resized horizontally (using Chrome on Mac). When I copy & pasted some of the data team's real assessment notes into the textarea, it overfills. A nice to have feature would be the area resizes to fit the text and stays that way when saved.

**Comment by MarsRomer** [comment]
thanks @elliottSlee  I hadn't noticed that, lets see if we get feedback from the data team about this and also monitor how much text they put in there and iterate if needed
