### ISSUE TITLE
Show Application Name on each form page

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#132]
### User Story
As an applicant, 
I want my application name to appear on each page of the form
so that I know which application I'm filling out if I have multiple applications in the system.

### Research & Design
During usability testing we heard that applicants will have multiple applications and would like to have a way to know they're working on the one they intend to.
https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=1890%3A6937

### Acceptance Criteria
- [x] **Scenario: Application name appears on each page**
Given that an applicant is creating or editing an application
when they are on any page of the form
then they will see their application name at the top of the page
#
- [x] **Scenario: Long application name is abbreviated**
Given that an applicant is on any page of the form
when the Application Name is > 280px
then it will be cut off and the overflow text replaced with an ellipsis (...)

![Screen Shot 2022-07-04 at 1.28.31 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/6c54eba2-91c9-440d-b5e9-c4a4c672344a)

**Comment by zoeyli-46** [comment]
Moved, pending PO confirmation

**Comment by eazeredo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/132?planning-poker) with ZenHub @AntBush @marcellmueller @wenzowski
