### ISSUE TITLE
Form widget testing < #30

### ISSUE THREAD

**Issue by BryanGK** [bcgov/CONN-CCBC-portal#134]
According to our team agreements we want to have ~80% test coverage for the form and all widgets

ref #127

**Comment by eazeredo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/134?planning-poker) with ZenHub @BryanGK @marcellmueller
