### ISSUE TITLE
Embed Metabase into portal

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1361]
As an analyst
I want to see tables from metabase embeded into the portal
So that I don't have to go to another application to see data

**Description:**
Can we show the metabase reports and dashboards and tables in the portal

# Acceptance Criteria:
- [x] Analysts can see the metabase dashboard for the GIS data in the portal
- [x] The queries and data is kept secure - only visible on the analyst portal, not available publicly or to unauthorized users

bordered = false
titled = true
theme = null

Notes:  
https://www.metabase.com/docs/latest/embedding/introduction
https://embedding-demo.metabase.com/
Prod metabase report:  https://ccbc-metabase.apps.silver.devops.gov.bc.ca/dashboard/87-gis-analyses
Test report:  

### Potential Design
It could look like this, but since we don't know much about embedding yet, please talk with the team about display options.
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/5cd3f6c0-eed7-4eb7-87e3-9216518c8628)

**Comment by elliottSlee** [comment]
https://www.metabase.com/learn/customer-facing-analytics/embedding-charts-and-dashboards#enable-embedding-in-other-applications

**Comment by elliottSlee** [comment]
This could also help with another user story: 
As an analyst I want to create nicer charts and more easily copy info so that I can create reports, one pagers, or the selection deck.
They can't export charts or dashboards from Metabase. However, embedded dashboards have an export option (see
https://github.com/metabase/metabase/pull/7315).

**Comment by elliottSlee** [comment]
Possible tables & dashboards to include:
- GIS analyses -- which would enable comparing applications because it could be set up to select two CCBC IDs
- Application Overview -- the main fields from an application such as $ & HH count
- Replica of the Source of Truth/Master spreadsheet

**Comment by elliottSlee** [comment]
@marcellmueller First of all, this is amazing! 
I realize that this was not part of the AC so let me know if you want it in another ticket. Can the "Visit Metabase to view a dashboard of GIS analysis" card up top be removed?
![Screen Shot 2023-07-13 at 8.40.47 AM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/7120116c-6465-42d7-b3b4-2d542d840d80)

**Comment by marcellmueller** [comment]
Ha yeah that makes sense, I made a pr to remove this.
