### ISSUE TITLE
Spike: How do we give portal access to ISED?

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1363]
Description:
Giving ISED access to the portal is expected to make it easier for ISED to collaborate with NWBC on the applications and projects.
This is a spike ticket to determine the best course of action for providing this access (if feasible)

AC:
- [x] Determine if providing ISED with access to the portal (analyst side) is feasible
- [x] Determine the options for 1-3 different ways to provide this access.
- [x] Make a list of the pro's and con's of the different ways to provide access for each of the different options.
- [ ] Create a new ticket to do the work with the details

**Comment by elliottSlee** [comment]
What are the reasons for this? Observations:
- [Touchpoints](https://miro.com/app/board/uXjVOANcgPo=/?moveToWidget=3458764547202528428&cot=14) are at:
  - Screening & Assessment sharing & adjudication (2-way sharing of documents)
  - Conditional approval (2-way sharing of documents)
  - Due diligence (unsure, but likely 2-way sharing if BC's data team is doing rescoping)
  - Approval (1-way sharing of data from ISED to BC)
  - Announcements (2-way sharing of information)
  - Claims (2-way sharing of documents)
  - Milestones (1-way sharing of documents from BC to ISED?)
  - Communities progress report (1-way sharing of documents from BC to ISED?)
  - Project change requests (2-way sharing of docs & data)
  - Final claim, final implementation report, and attestation letter to the final claim (2-way sharing of data)

**Comment by elliottSlee** [comment]
If using BCeID, it may affect the name in the History tracking because we currently just look for whether they have an IDIR.
Can we get them IDIRs?

**Comment by elliottSlee** [comment]
I'll ask if our ISED contacts know the person listed as account manager.
