### ISSUE TITLE
Change UI for Conditional Approval

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1370]
As a analyst
I want to be able to upload multiple files to the conditional approval
So that I can document the artifacts better

**Description:**
Analyst should be able to upload multiple files and see them in the UI

# Acceptance Criteria:
- [x] Analyst can upload multiple files in the conditional approval section
- [x] change text: _Uploads_ to _Minister’s decision, letter, and response_
- [x] _date sent_ to _Date letter sent to applicant_

After chat with Elliot: 
- [x] On expand, Add file button moves up top
- [x] Word wrap after 250 characters
# Not included:
Shortening of the file name.  
## Conditional approval

**Screen**
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/3d4d6b8b-e7d0-4619-bc72-43e36d4a3e3d)

![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/ed02cb8e-fdcf-40d1-b042-a69c8cb98cc4)

**Comment by elliottSlee** [comment]
Can't click clear date after entered in date picker because the X is in the input box. Options:
- Leave it as is. Users can click cancel to get out of the form without making any changes
- Get rid of the clear button
- Move it outside the box, maybe making the box smaller

**Comment by MarsRomer** [comment]
Who ever picks up this ticket could work with Elliott to figure out how the edit screen looks when there are uploaded files.

**Comment by elliottSlee** [comment]
@AntBush The line-break thing you did for the long filenames works great! Could you do the line-break for the read-only view, too? Should this be put into a different ticket?
![Screen Shot 2023-05-17 at 1.06.16 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/15e1b9dc-547e-4b16-970d-4e0f86ceb14a)

**Comment by AntBush** [comment]
Yeah sure! I can go ahead and do that. We can keep it in this ticket is fine I think
