### ISSUE TITLE
Add Progress options to Permitting Assessment

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1374]
As an analyst 
I want to be able to record that an application needs an RFI, Needs 2nd review, assessment complete
So that it can be flagged for discussions or future actions.

# Acceptance Criteria:

## Permitting assessment

**Screen**
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/794c7890-10df-4b7a-9968-101fe7d0a033)
[**Wireframe**](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=8308-41758&t=OGdpVwMRlcIIxkmC-4)

**Page Behaviours**

- [x] Can click on all the radio buttons
- [x] Saved in the same way as "nextStep" in the other assessments
- [ ] User can get up & dance in between clicking the radio buttons and they still work
- [x] Will show on the assessment table like the other assessments

**Comment by AntBush** [comment]
Wasn't able to test the dancing :/
