### ISSUE TITLE
Happo screenshot threshold and/or rendering engine change to fix spurious diffs

### ISSUE THREAD

**Issue by AntBush** [bcgov/CONN-CCBC-portal#1383]
Happo is currently creating many spurious diffs for Safari that is making identifying real diffs/errors complicated and creating alert fatigue. To solve this I suggest changing the renderer or increasing the diff threshold to prevent any spurious diffs.

- [x] Grant access to someone to be able to access the panel for changing such option (and document the process required for that)
- [x] Change either the render or threshold and test with a PR to see if spurious diffs on Safari are eliminated.

**Comment by marcellmueller** [comment]
Looks like this is solved by increasing the thresholds. I used the same values as the CAS team who recently fixed the same issue. There are still some flakey tests that could be fixed in this issue: #1331
