### ISSUE TITLE
Use same pill for Applicants as Analysts for all statuses

### ISSUE THREAD

**Issue by AntBush** [bcgov/CONN-CCBC-portal#1386]
Description:
Applicant sees the same pills that the analyst sees for statuses that they can see

Acceptance Criteria
- [x] For all statuses that the applicant can see, the status shows with the same pill design that the analyst sees

**Comment by AntBush** [comment]
@MarsRomer this is something I found while doing the e2e, tagging you for visibility since I know the change for `Conditional Approval` on the applicant side is coming up soon

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1386?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc @VB-at-Bis
