### ISSUE TITLE
1131- Record Announcements - Create Announcement DB Only [5sp]

### ISSUE THREAD

**Issue by AntBush** [bcgov/CONN-CCBC-portal#1394]
Select one of the two: 
- [x] RJSF
- [ ] Handwired

The implementation of this ticket will vary if we go RJSF or just handwiring a form, but this ticket involves:

- [x] Create the necessary tables to hold the data (ccbc_public.announcement, ccbc_public.application_announcement)
- [x] Create a custom create mutation for creating a new announcement that will: 
  - [x] Create many rows of ccbc_public.application_announcement doing a look up of CCBC-ID -> application_id
  - [x] Save a new row in ccbc_public.announcement to hold the announcement data
  - [x] Will need RLS to prevent any CRUD operation on announcements by non-analysts/admins
- [x] Shouldn't be able to add the same announcement to the same project twice, but should be allowed to re-add a deleted project (if it's been archived)
- [x] Enable history/auditing on table

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1394?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc @VB-at-Bis
