### ISSUE TITLE
1131 - Record Announcements- Update Announcements DB Only

### ISSUE THREAD

**Issue by AntBush** [bcgov/CONN-CCBC-portal#1396]
Select one of the two (should be the same as 1394): 
- [x] RJSF
- [ ] Handwired

The implementation of this ticket will vary if we go RJSF or just handwiring a form, but this ticket involves:

- [x] Create a custom create mutation for updating an announcement that will: 
  - [x] Check if any of the other_project_ids have been changed and if so
    - [x] Archive any that have been removed or
    - [x] Create a new row for any that have just been made
- [x] Shouldn't be able to add the same announcement to the same application twice, but should be allowed to re-add a deleted announcement (if it's been archived)

**Comment by VB-at-Bis** [comment]
I believe it is already implemented by #1394
