### ISSUE TITLE
1131 - Record Announcements - Create link preview

### ISSUE THREAD

**Issue by AntBush** [bcgov/CONN-CCBC-portal#1397]
Just a ticket to create the link preview component, to match up with the screen below: 

- [x] Set size of area or length for the title and, if exceeded, use `text-overflow: ellipsis`
- [x] Set size of area or length for the description and, if exceeded, use `text-overflow: ellipsis`
- [ ] if possible, title of article is stored in the database
- [x] Fallback if title & description aren't available: display "No preview image" and the URL (linked, `<a>`) where the title would be

![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/49ef0651-bfdb-4b03-82a1-5a40bc14abee)

[**Wireframe**](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?type=design&node-id=11381-109760&t=HjaJXPNyzcOhi8Ke-4)

## Fallback
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/656c0896-6c17-42cf-be7b-e1b2b114bd3f)

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1397?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc @VB-at-Bis

**Comment by MarsRomer** [comment]
Has this been deployed to test, I don't see link previews working yet....

**Comment by marcellmueller** [comment]
Sorry that was me, I saw that this issue was closed so I dragged it back. Though I saw it was merged yesterday, we can make a release today.
