### ISSUE TITLE
Restore access for removed users from the the Realm

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1409]
**Description:**
This ticket is to come up with a plan for how to restore the 3 users that were removed from the realm.

Note: this is an in database function, not a UI

This has become more important as the BCeID bug fix has removed 3 users from the realm

# Acceptance Criteria:
- [ ] Clear and complete steps for the team on how to work internally and with the applicant to transfer the applications
- [ ] Identify & be sure which user identity is connected to each use. Be absolutely sure the application belongs to them. Confirmation from Mars that User & Applications match
- [ ] Mars send email to user
- [ ] Triple check assigning the correct user to the right application
- [ ] View connections of Application ID & User ID in Metabase (3 applicants that were removed from the realm have their access restored with new user credentials?)

Risk: Applying script on production, no way to check it's done until it's done.

**Comment by MarsRomer** [comment]
Needs Refinement:  @VB-at-Bis  put documentation on Scrum Team channel with UUID and user IDs etc and include link to it in this ticket.

**Comment by VB-at-Bis** [comment]
Link to the document: https://bcgov.sharepoint.com/:w:/r/teams/04708-ScrumTeam/Shared%20Documents/Scrum%20Team/removed_users.docx?d=wb94c8200f67a4792ac050375838792db&csf=1&web=1&e=z8bHi4

**Comment by VB-at-Bis** [comment]
@MarsRomer , I added questions to the document

**Comment by MarsRomer** [comment]
Blocked until we reach out to user and decide if user would like us to consolidate their orphaned/abandoned applications.  Mars to reach out to user week of July 17

**Comment by MarsRomer** [comment]
Closing this ticket as we have decided that we are not going to do anything about this issue at this time
