### ISSUE TITLE
GIS Analysis History

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#1416]
As an analyst, admin, or data team member
I want to see which GIS analysis outputs changed in the history of a project
So that I can understand the story of it and make informed judgments during negotiations and announcements

**Description:**
This card is about showing the history of GIS analysis data that's input with a JSON in #1142

# Acceptance Criteria:
- [x] On GIS analysis import success page, show # new, # updated, and # that will be ignored because they're the same
- [x] On GIS analysis import success page show the CCBC ID's under each of the categories "#New", "#updated", "#unchanged".
- [x] By default, toggle is closed toggle arrow is https://fontawesome.com/icons/chevron-right?f=classic&s=solid
- [x] Click on toggle arrow and it turns (e.g., css `transform: rotate(90deg);`) and div containing all CCBC IDs slides down
- [x] On History page, if it's the first time a GIS analysis is uploaded for the project, show just the new values, stating `<User> uploaded the first **GIS analysis** on <mmm dd, yyyy at hhmm am/pm>`
- [x] On History page, if. the GIS analysis is updated for the project, show both the new & old values, stating `<User> updated **GIS analysis** on <mmm dd, yyyy at hhmm am/pm>` -  Reason for change will be in another ticket that follows this one

## GIS Import Success

**Screen**
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/ebf05ece-ad61-43a3-8e45-5f884d55785a)
[**Wireframe**](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=11144-100458&t=gNmtoHECWRA0rRbj-4)

## History page

**First time**
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/4dece34c-8da9-4b18-9e28-5a049f311cc5)
**Updates**
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/b74901e2-786a-4b0e-9e87-df0977f516a5)

**Page Behaviours**

- [ ] .
- [ ] .
- [ ] .

**Validations**

- [ ] .
- [ ] .
- [ ] .

**Actions**

- [ ] .
- [ ] .
- [ ] .

### Not included:
- [ ] Reason for change - will be part of a new ticket

## Implementation Details
- **DB:**
  - .
  - .
- **Middleware:**
  - .
  - .
- **Frontend:**
  - .
  - .
- **Tests:**
  - .
  - .
- **Documentation:**
  - .
  - .

**Comment by elliottSlee** [comment]
Notes: History of Application edits is shown in a table that's vertical (Fields stacked on top of each other, cols are Old & New). This is inconsistent as it's horizontal with the rows being old & new.

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1416?planning-poker) with Zenhub @AntBush @marcellmueller @VB-at-Bis
