### ISSUE TITLE
Make RFI ID sequential and continuous

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1422]
As an analyst 
I want the RFI IDs to follow a sequential and continuous numbering system
So that it makes sense to everyone

**Description:**
the RFI ID is currently not sequential and continuous as it skips numbers randomly
This ticket is to can make the automation follow a sequential ID

# Acceptance Criteria:
- [ ] The RFI ID continues to auto-populate but now follow a sequential and continuous numbering system

**Comment by MarsRomer** [comment]
for this one application it repeated the RFI ID:
![image.png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/41dc81d4-a1e5-4eee-91c5-9a0073f417d7)

**Comment by AntBush** [comment]
Sure! I'll get on that
