### ISSUE TITLE
Restrict uploaded GIS JSON data file size

### ISSUE THREAD

**Issue by VB-at-Bis** [bcgov/CONN-CCBC-portal#1424]
CodeQL complained about maxFileSize for formidable; existing code should be updated to properly set maxFileSize in constructor instead of using `form.maxFileSize = 8000000; `
Additional code refactoring can be done as part of this ticket to improve code legibility (comments from  https://github.com/bcgov/CONN-CCBC-portal/pull/1400)

**Comment by MarsRomer** [comment]
@VB-at-Bis do you have a json file big enough for me to test?

**Comment by VB-at-Bis** [comment]
I tried with big JSON (over 80MB) and backend correctly throws `HTTP 413 Content Too Large` error; however, UI does not display anything. 
I guess error popup need to be added as part #1382 which should provide correct error handling UI instead of current alerts
