### ISSUE TITLE
Configure "Sonar" in the CI pipeline

### ISSUE THREAD

**Issue by eazeredo** [bcgov/CONN-CCBC-portal#146]
Configure Sonar for the coverage reports to go to it.

- [x] Request access to Admin portal for Sonar
- [x] Configure Sonar with coverage 
- [x] Configure Sonar with quality gates + new code definition

**Comment by wenzowski** [comment]
We'll need this to facilitate our STRA

xref https://github.com/BCDevOps/devops-requests/issues/1422
