### ISSUE TITLE
Provide ISED access to the Portal with Business BCeID

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1466]
As an ISED member
I want to access the analyst portal
So that I can better collaborate with NWBC on the applications and projects

**Description:**
This ticket is to provide ISED with access to the Analyst Portal using their Business BCeID

# Acceptance Criteria:
- [x] Get access to a test Business BCeID account for the team 
- [x] ISED can log in with their Business BCeID (use login button in top right corner of login)
- [x] ISED can view and make changes the same as the analysts role
- [x] History table shows the name of ISED person for 'who' made changes

Note:  https://github.com/bcgov/sso-keycloak/blob/dev/docs/migration-guide.md 
## {Page Name}

**Screen**

[wireframe 1]
[wireframe 2]

- [ ] .

**Page Behaviours**

- [ ] .
- [ ] .
- [ ] .

**Validations**

- [ ] .
- [ ] .
- [ ] .

**Actions**

- [ ] .
- [ ] .
- [ ] .

### Not included:
- .
- .

## Implementation Details
- **DB:**
  - .
  - .
- **Middleware:**
  - .
  - .
- **Frontend:**
  - .
  - .
- **Tests:**
  - .
  - .
- **Documentation:**
  - .
  - .

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1466?planning-poker) with Zenhub @AntBush @marcellmueller @VB-at-Bis

**Comment by MarsRomer** [comment]
I don't know if it's the same redirect issue we are having with logging in internally to the analyst portal but I can't seem to be able to get to the analyst dashboard after logging in with the Business BCeID.  After logging in, I get redirectd to the Applicant dashboard and I can't figure out how to get to get to the analyst portal

**Comment by marcellmueller** [comment]
Did you add an analyst role to your BCeID in the SSO dashboard?

**Comment by MarsRomer** [comment]
hah, that was it!  Thank you! It works now!

**Comment by marcellmueller** [comment]
Haha nice, at least you got to confirm that people with regular BCeID with no role added can’t login to the analyst side 🙂
