### ISSUE TITLE
Refactor: use crunchy-postgres repo helm chart

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/CONN-CCBC-portal#1491]
This ticket is to test out the work done on the Helm Chart by our team in collaboration with the Platform Services Team

Business Value:  To test the work done on the Helm Chart so that we can verify it's use and share with the rest of the organization but also to have it ready to use for when needed.

We should replace our `postgresCluster` chart from the [crunchy-postgres](https://github.com/bcgov/crunchy-postgres) repo. This will ensure consistency between projects and will be a good chance to test and use the chart we worked on.

- [x] Replace chart in main CCBC project
- [x] Replace chart in metabase repo

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1491?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc @VB-at-Bis
