### ISSUE TITLE
Bug: History doesn't work for Application changes

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1523]
**Describe the bug**
Certain changes in the application don't show up in the history, such as the Project Title

**To Reproduce**
1. Go to an application
2. Click on the edit icon
3. change the title 
4. In the history it only shows that a change was made, but the details of what changes are not visible

**Expected behaviour**
Expect to see the old value crossed out and the new value beside it

**Screenshots**

**Logs/tracebacks**

**Additional context**

**Comment by rafasdc** [comment]
Will be fixed by #1416
