### ISSUE TITLE
Create success toast for announcements

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/CONN-CCBC-portal#1529]
- [x] Success toast shows as screen design below on 'Save' action
- [x] Success toast shows all the CCBC IDs
- [x] If >3 CCBC IDs have been added, state the 3 CCBC IDs and "and more"
- [x] Success toast slides in from left and appears at bottom left of viewport
- [x] Success toast slides out to the left after 10s
- [x] Click X on success toasts closes it
- [x] Hover over CCBC ID of linked projects, tooltip opens saying "Opens a new tab" [example](https://www.w3.org/WAI/WCAG20/Techniques/working-examples/G201/new-window.html) | [code](https://www.w3.org/TR/WCAG20-TECHS/G201.html)
- [x] Click on other CCBC IDs in the success toast will bring you to the announcement page for that project

![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/40d9df00-0201-47a5-8ef0-53cb09cee670)

**Comment by MarsRomer** [comment]
The success toast successfully works, but only the first time I hit save on the page.  If I add another announcement right after without navigating away to another page, the success toast doesn't show.

**Comment by elliottSlee** [comment]
@marcellmueller looks & works great! Could the link text be updated to be white and underlined?

**Comment by AntBush** [comment]
Do we want it just white and underlined if it's unvisited or white all the time?
