### ISSUE TITLE
Show File Name for upload in History page

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#1546]
As an analyst
I want to see the name of the file uploaded in the history
So that I can understand the history of the file uploads for the application and assessments etc

**Description:**
Currently the history page just states "<User> uploaded a file on <date>." Which give no context to what file or where it was uploaded. To clarify, we need to declare the file name.

<img src="https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/4c6f58ce-c098-40fb-8564-646bfb980b89" width=66%>

# Acceptance Criteria
- [x] The history table states the name of the file that was uploaded
- [x] the file is downloadable

## History
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/01733f46-43a1-4315-8569-6375a71e2a98)

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1546?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc @VB-at-Bis
