### ISSUE TITLE
Deploy Runbook: Deploy to hotfix environment before prod

### ISSUE THREAD

**Issue by rafasdc** [bcgov/CONN-CCBC-portal#1547]
Before deploying a a hotfix to production, deploy to a temporary hotfiix environment so changes can be verified. 

The hotfix environment:

- [x] Deploys a hotfix ccbc deployment on the test environment
- [x] Uses hotfix-ccbc url
- [x] Has a hotfix database that is independent of test
- [x] Sets the database to the latest tag, to match prod
- [x] Keeps the database persistent

For the future:
- [ ] "Imports" data from test

Business value: Allows for quick high priority changes to be verified before going directly to prod.

**Comment by MarsRomer** [comment]
Nothing for PO to review here so moving to Sprint Done
