### ISSUE TITLE
Edit SoW Input

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#1589]
As an analyst
I want to edit the SoW data
So that I can correct mistakes

# Acceptance Criteria:

## 

- [ ] Click edit pen, re-opens form 
- [ ] 

### Not included:
- .
- .

## Implementation Details
- **DB:**
  - .
  - .
- **Middleware:**
  - .
  - .
- **Frontend:**
  - .
  - .
- **Tests:**
  - .
  - .
- **Documentation:**
  - .
  - .

**Comment by MarsRomer** [comment]
closing as part of another ticket
