### ISSUE TITLE
Fix eslint workflow throwing errors for ignored lines

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/CONN-CCBC-portal#1616]
Silence errors on linting so that ignored lines are not flagged.
Business Value:  There are a lot of false positive errors being flagged, and this ticket will filter them out so that we focus on just the legitimate errors, there by saving time for the development team.

Eslint workflow should not show errors for lines we intentionally ignored.

- [ ] Fix Eslint workflow so that it doesn't open messages in our PRs with ignored rules

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1616?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc @VB-at-Bis
