### ISSUE TITLE
SoW upload - Validation

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1617]
As an analyst
I want to see error messages if something goes wrong with the SOW upload 
So that I can make sure that the SOW that I uploaded properly or not and I can fix the issues and re-upload

**Description:**
This ticket is to add validation to the SOW upload

# Acceptance Criteria:
- [x]  While processing file after upload, the upload button is disabled a statement appears to the left of button, "Checking the data..." ellipsis is animated such as this [css animation](https://codepen.io/thetallweeks/pen/yybGra) or this [react animation](https://www.npmjs.com/package/react-animated-ellipsis)
- [x] Colour of text is 1A5A96, ellipsis colours: D8292F, FCBA19, 003366

![Screen Recording 2023-05-29 at 10.48.45 AM.gif](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/42407fde-f325-49c8-9362-a8b76f39557e)

- [x] Check that CCBC ID matches the application it's being uploaded to
- [x] Check for errors in the data and refer to cells
- [x] If import error exists, display error banner below upload field
_Note:_ these are nearly the same style as alert banners just not displayed at the top of the page. Feel free to re-use either the [toolkit](https://button-inc.github.io/service-development-toolkit/@button-inc/bcgov-theme/index.html?path=/docs/components-alert--default) & [BC gov ones](https://developer.gov.bc.ca/Design-System/Alert-Banners)
Error hierarchy: If CCBC # doesn't match, then show that error; 
if there were errors importing particular fields then show the location of those errors; 
else show a generic error.
#### Error banners
![Error banner 1](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/87d24536-8c35-4472-b4e4-a58adc70f563)
![Error banner 2](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/70c8e116-5bd7-4a4d-9c94-cb3a006f9b91)
![Error banner 2_many](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/28750038-801f-4917-bd74-a13db4ea530e)
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/97752968-2163-46ed-9bef-ee6d64ecffa5)

- [x] `finalized map` is optional
- [x] If required fields not filled, when press Save & Import, red outline the fields and do _not_ perform the save & import
- [x] If field outlined in red, when entering valid information, the red outline disappears

- [x] After pressing Save & Import and all required fields are filled, data from SoW tables are imported into the database, files are saved to S3, and date is saved as well.
- [x] User can still press Save & Import if there were import errors. SoW tables do not save see screenshot below
- [x] After pressing Save & Import, form slides out & read-only view slides in using same effect as the announcements

![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/3d1ce145-a138-46d9-8503-16ce3d3700b2)

## Implementation Details
- **DB:**
  - .
  - .
- **Middleware:**
  - .
  - .
- **Frontend:**
  - .
  - .
- **Tests:**
  - .
  - .
- **Documentation:**
  - .
  - .

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1617?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc @VB-at-Bis

**Comment by MarsRomer** [comment]
Hey @AntBush this is looking great!  
Just a couple of requests:  
1. Can we please move the messages up a bit 
![image.png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/55611100-1f7b-413f-97bf-27774b772b6f)

**Comment by MarsRomer** [comment]
2. can we have the 'Checking the data....' right justified, currently it slides to the left with every '.' that adds as part of the animation
![image.png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/b2b40377-b0a6-408b-9fdf-1839ab34b958)

**Comment by MarsRomer** [comment]
3. can we have the error messages disappear as soon as a new file is uploaded:
 ![image.png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/42039bb3-67d1-4604-9017-552b97c1a1e3)

**Comment by MarsRomer** [comment]
4. I think based on the acceptance criteria I should be able to click Import if I have tried uploading the SOW but had error messages, but the button is non-responsive ![image.png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/b7172b68-7e09-4c6c-a1ae-ba27bab69305)

**Comment by MarsRomer** [comment]
I am not seeing any validation happening.  I uploaded random xls files and even SOW tables for different projects and I am not seeing any error messages

**Comment by AntBush** [comment]
Could you add a screenshot? I'm seeing validation on test right now

![image](https://github.com/bcgov/CONN-CCBC-portal/assets/10603033/55b5435a-ddf7-4820-8cc3-93bd90fe971d)
