### ISSUE TITLE
Attachment history doesn't show history of orphaned/abandoned files

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1618]
As an analyst
I want the history of attachments to not show history for files that were abandoned/orphaned
So that I can confidently know which files were truly attached and removed

**Description:**
The history of attachments is difficult to report on, this ticket is to make reporting on the history of attachments is clear and accurate

# Acceptance Criteria:

- [ ] The history of attachments doesn't show uploaded file if the user didn't actually attach it (i.e. they didn't hit save and the file is abandoned/orphaned).  This applies to past and future file uploads

## {Page Name}

**Screen**

[wireframe 1]
[wireframe 2]

- [ ] .

**Page Behaviours**

- [ ] .
- [ ] .
- [ ] .

**Validations**

- [ ] .
- [ ] .
- [ ] .

**Actions**

- [ ] .
- [ ] .
- [ ] .

### Not included:
- .
- .

## Implementation Details
- **DB:**
  - .
  - .
- **Middleware:**
  - .
  - .
- **Frontend:**
  - .
  - .
- **Tests:**
  - .
  - .
- **Documentation:**
  - .
  - .

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1618?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc @VB-at-Bis

**Comment by marcellmueller** [comment]
@MarsRomer I added a `Needs Refinement` tag to this. Maybe we could discuss it further at standup on Monday!

**Comment by MarsRomer** [comment]
@marcellmueller lets talk about it today!

**Comment by elliottSlee** [comment]
Deemed unnecessary with #1663

**Comment by MarsRomer** [comment]
This ticket is being replaced by #1663 with more functionality that will show more details of the history of the file upload making this ticket redundant.
