### ISSUE TITLE
Task/Bug:  Fix issue with hippo-ha-set-pgha1 in dev namespace 

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1629]
Description:
DXC notified us that they are getting notifications that  hippo-ha-set-pgha1” PodDisruptionBudget (PDB) in our  dev namespace does not have enough running pods.  
This ticket is to mitigate this issue.

Acceptance Criteria 

- [ ] DXC no longer gets error notifications about hippo-ha-set-pgha1 in our dev namespace 
- [ ] our team is not adversely impacted by the problem or the fix

**Comment by marcellmueller** [comment]
@rafasdc I fixed the metabase dev environment and we have cronjobs and backups working again. Seeing as there is no PR to review can you just maybe poke in there and check things out for me? Thanks!

**Comment by rafasdc** [comment]
Looks good! Curious on what happened.
