### ISSUE TITLE
Update internal & external status

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#1630]
As an analyst 
I want to change the external status
So that the applicant can see that their project is approved on their dashboard

**Description:**
_if needed_

# Acceptance Criteria:
- [x] Add dropdown to external status. Options in External status dropdown
- Received
- Conditionally Approved
- Approved
- Complete
- Cancelled
- Closed
- On Hold

- [x] **Internal** status options always enabled: All previous ones, closed, on hold
- [x] Internal status options disabled:
- If Internal status == Received, then Screening is enabled but Assessment, Recommendation, Cond Appr, Approved, Complete, and Cancelled are disabled
- If Internal status == Screening, then Received and Assessment are enabled but Recommendation, Cond Appr, Approved, Complete, and Cancelled are disabled
- If Internal status == Assessment, then Received, Screening, and Recommendation are enabled but Cond Appr, Approved, Complete, and Cancelled are disabled
- If Internal status == Recommendation, then Received, Screening, Assessment, and Cond Appr are enabled but Approved, Complete, and Cancelled are disabled
- If Internal status == Cond Appr, then Received, Screening, Assessment, Recommendation, and Approved are enabled but Complete, and Cancelled are disabled
- If Internal status == Approved, then Received, Screening, Assessment, Recommendation, Cond Appr, Complete, and Cancelled are enabled
- [x] External status. All options enabled.
- [x] External status. If user selects conditionally approved, it can only change if (1) Internal Status is Cond Appr and the conditionally approved form has (2) Minister's decision = Approved and (3) Applicant's response = Accepted. If these 3 are not met, a modal appears:
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/cfa0ad6f-fff1-4991-b8a6-a81ebeb6e226)
[**Wireframe**](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?type=design&node-id=11649-114341&t=0PaYkf2EIQh9lpLz-4)
- [x] "Take me there" button links to Conditional Approval form
- [ ] Click x or close, closes the modal
- [x] External status. If user selects Approved, Complete, Cancelled, Closed, or On Hold, it can only change if Internal Status is the same. If it is not the same, show the following modal:
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/9d5d8ffa-d6b5-49bc-89d5-be184e2f092b)
[**Wireframe**](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?type=design&node-id=11650-116937&t=0PaYkf2EIQh9lpLz-4)
- [x] Add space between status name & dropdown arrow in the pill
## {Page Name}

**Screen**

[wireframe 1]
[wireframe 2]

- [ ] .

**Page Behaviours**

- [ ] .
- [ ] .
- [ ] .

**Validations**

- [ ] .
- [ ] .
- [ ] .

**Actions**

- [ ] .
- [ ] .
- [ ] .

### Not included:
- .
- .

## Implementation Details
- **DB:**
  - .
  - .
- **Middleware:**
  - .
  - .
- **Frontend:**
  - .
  - .
- **Tests:**
  - .
  - .
- **Documentation:**
  - .
  - .

**Comment by elliottSlee** [comment]
@MarsRomer I reviewed this and it works as expected. Separately from this card, we should add a confirmation when the external status is changed. Perhaps the reason for change modal appears or the saved indicator circle check mark that shows when entering Assessment HH on the GIS assessment page.

**Comment by elliottSlee** [comment]
@MarsRomer I found one issue: external status can't be set to received unless internal status is received. It should be when internal status is received, screening, assessment, or recommendation

**Comment by MarsRomer** [comment]
Please see Elliott's discovery above

**Comment by marcellmueller** [comment]
Do we need a new design for a modal if the user can't change to received or is the `Change internal status` modal clear.

**Comment by MarsRomer** [comment]
I don't think we need a new modal
