### ISSUE TITLE
SoW upload - Validation - Backend 

### ISSUE THREAD

**Issue by VB-at-Bis** [bcgov/CONN-CCBC-portal#1632]
sow-upload.ts should return validation errors to be used by Front End to display to the user as described in [#1617](https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/gh/bcgov/conn-ccbc-portal/1617)

**Comment by MarsRomer** [comment]
Validations will be PO reviewed with #1617 since this is a back end ticket
