### ISSUE TITLE
OpenShift: PodDisruptionBudget on CCBC namespace

### ISSUE THREAD

**Issue by rafasdc** [bcgov/CONN-CCBC-portal#1639]
Take a closer look at the PodDisruptionBudget set on ff61fb namespace:

- Are the PDB Operator managed or set
- Remove multiple matching PDBs to same pods
- Set them to be managed by the crunchy operator

Business value: prevent future issues where a pod cannot be taken down during an OpenShift upgrade/maintenance which impacts Platform Services ability to drain a node to perform upgrade/maintenance. In addition, ensure that the minimum amount of pods required is maintained and not disturbed.

--
From past OpenShift upgrade pgbouncer and hippo-ha were the ones that caused trouble.

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1639?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc @VB-at-Bis

**Comment by rafasdc** [comment]
The Crunchy operator already creates and manages PDBs for PG and PG bouncer according to the number of replicas requested. This causes a conflict between the previous PDBs created which makes OpenShift choose one arbitrarily which would also block any disruptions. 

Removing the two extra/manual PDBs solves this issue.

**Comment by rafasdc** [comment]
The Crunchy operator already creates and manages PDBs for PG and PG bouncer according to the number of replicas requested. This causes a conflict between the previous PDBs created which makes OpenShift choose one arbitrarily which would also block any disruptions. 

Removing the two extra/manual PDBs solves this issue.
