### ISSUE TITLE
Database tests tech debt

### ISSUE THREAD

**Issue by BryanGK** [bcgov/CONN-CCBC-portal#164]
The copied tests from `cas` have a few tests that are commented out:

Let's un-comment these and see if we can get them passing.

- [x] upsert_timestamp_columns_test.sql has 3 commented out tests
- [x] ccbc_user_test.sql has 2 commented out tests
- [x] Each table should have row level security and permission tests

Pair program with Alec or Matthieu

**Comment by MarsRomer** [comment]
@BryanGK I'm wondering if you can help me understand what this ticket is for

**Comment by MarsRomer** [comment]
@BryanGK I'm wondering if you can help me understand what this ticket is for

**Comment by BryanGK** [comment]
@MarsRomer We copied the tests from `cif` and I had 4 tests that I couldn't get to pass, so in trying to get the ticket done I figured commenting out the failing tests and tracking that with this tech debt card to try again when we had more time.

**Comment by MarsRomer** [comment]
thanks @BryanGK  is there much risk in waiting until August to tackle this ticket?

**Comment by BryanGK** [comment]
@MarsRomer not much risk, most of the tests are there already. Getting these working would be increasing our code coverage on the database.

**Comment by MarsRomer** [comment]
@BryanGK  then if it's ok I will move this to the following sprint, @marcellmueller  you will likely inherit this :)
