### ISSUE TITLE
Implement CI check to prevent sqitch tags from being deleted

### ISSUE THREAD

**Issue by AntBush** [bcgov/CONN-CCBC-portal#1643]
As the title states, we will need a CI check to prevent tags from being deleted in our sqitch.plan, as we've found that our immutable files check doesn't catch this edge case.  
AC:  
- [ ] If a git commit includes a sqitch tag being deleted, then this CI fails.

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1643?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc @VB-at-Bis
