### ISSUE TITLE
Bug: Downloaded application attachments missing files 

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1644]
**Describe the bug**
The files downloaded from the portal do not match what is listed on the portal.  
Is it possible that the portal is incorrectly listing the files?  Or is the download faulty?  We need to investigate this to make sure that the portal is correctly listing the files and then investigate why the download is not matching.

**To Reproduce**
1. Go to one of the applications
2. Click on one of the 2nd intake applications 
3. Go to the application review page and note the list of files there in the 'Other supporting materials (if applicable)'
3. Download zip file from the portal for 2nd intake
4. Notice missing files, and in at least one instance the file name is slightly different than what is listed on the portal - notice the word '(final)' is added to the name

**Expected behaviour**
All files listed on the portal in the application review page should match what is downloaded.  

**Screenshots**

**Logs/tracebacks**

**Additional context**

**Comment by MarsRomer** [comment]
hi @AntBush @marcellmueller @VB-at-Bis @rafasdc  this ticket is now a high priority as we don't quite know the scope of the issues and to prevent issues with assessments we need to make this a higher priority than other tickets. 
  would like us to at least as a first step confirm that what the portal is showing listed for files is accurate, and as a second step, list which applications and files are missing from the download

**Comment by marcellmueller** [comment]
No problem I will do it today!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by marcellmueller** [comment]
Did you want us to verify both intake 1 and intake 2 attachments?

**Comment by MarsRomer** [comment]
@marcellmueller yes please
