### ISSUE TITLE
Questions for NWBC

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#165]
### Description
This card is to collect all the questions we have for NWBC. Responses should be recorded in the comments, at least links to the results of a response.

# Intake Questions
- [x] Will NetworkBC be able to see draft applications? Maybe a use case of helping an applicant during an intake
- [x] Is it ok that intake closes on November 6 at 11:59pm its a weekend and people may have questions on the weekend that don’t get answered
- [x] Benefits page: Final number of Eligible Households targeted by this proposal. This value should match cell F141 in Template 1 - Eligibility Summary
- [x] Benefits page: Number of households on Indigenous lands impacted by this proposal. This value should match cell G55 in Template 1 - Eligibility Summary.
- [ ] What if we had multiple programs under CCBC? what would be description of which program the applicant is applying for
- [ ] Would NWBC like to receive an email when an applicant submits an application?
- [x] Where will program materials be made available to applicants?
- [x] Can we create a document of the application form questions for the applicant to preview, can this be a part of the application package that they download?
- [x] Will applicants know that there are multiple intakes?
     - [ ] If so, will they know the opening & closing dates of the 2nd?
     - [ ] Does NWBC expect applicants to see both intakes in one UI?
     - [x] Should applicants be able to see the intake # for their applications?
- [x] Will the same extra maps be collected as the NDIT intake?
     - [x] How does NWBC use these maps?
     - [x] Does NWBC want them as 1 file? Answer: No, same 2 maps that NDIT collected
     - [x] Check if the additional kmz map file requirements from NDIT program are in the CCBC Application Guide
- [ ] Confidentiality/Trade Secrets. Can applicants declare confidentiality of information? How?
- [ ] ~~Will Template 9 change?~~
- [x] Do we need to add the confidentiality statement from ubf form to the start of the application? Or can we keep it in the application guide?
- [x] In early discussions there was a request to make an obvious difference between UBF & BC questions so that applicants know these are BC questions for BC funding. Can you confirm this is still the case?
- [x] If we incorporate households into the system from Template 1, the total household count on that form includes speeds less than 50/10, should we only ask applicant for anticipated households connected with ≥ 50/10 or total household count?
- [x] What should be the earliest/latest project start date be?
- [x] "One primary contact must be identified for applications submitted on behalf of multiple organizations." What does this mean?
- [x] "The coverage tool allows you to import your proposed coverage or to draw it directly on the map. It must be used in conjunction with Template 1 to identify eligible and ineligible project areas and calculate the impact of the proposed project coverage area against the program objectives."removed from app guide and web form, is this ok
- [x] Signature block, we don't have this on the declarations page is this ok? Can they just upload a pdf or? The UBF form doesn't have a signature block
- [x] Do we want to keep wording the same across the form, for example there is the words "your organization", "the application", and "you", do we want to use only 1 wording throughout or keep it the way it is with the 3 different wordings? 
- [x] "Project" or "proposed project"
- [x] Do we need Gov of Canada logo on the page?

# Post-Intake
- [x] Does NWBC expect applicants to see both intakes in one UI?
- [ ] What was the process for withdrawal & resubmission? What were the pain points? Which can we solve?
- [x] Can we see a sample funding agreement & SOW of the _current_ program? Will it be the same as previous ones?
- [x] Tranches in the system vs deadlines of assessments?
- [x] When an application from an early intake is told to revise & resubmit to a later intake, what's the process?
- [x] Should applicants be able to see the intake # for their applications?
- [x] Is one person responsible for 1 type of assessment for all applications? Or are analysts assigned to an assessment for a particular application then potentially to a different assessment for another application?
- [ ] Should applicants see updated form after an RFI?
- [x] If there's a gap between intakes, can the applicant continue editing draft applications from previous intakes?
- [ ] Does NWBC want existing projects in the portal that are from the same pot of money?

**Comment by zoeyli-46** [comment]
Lets ask these during the 4pm on Thursday

**Comment by elliottSlee** [comment]
Applicants won't know dates of multiple intakes. It's possible that criteria could change between intakes (not likely in earlier intakes but possible in later ones), so we need to plan for that.

**Comment by elliottSlee** [comment]
Same maps will be collected as NDIT. NWBC would find it hard if they were multiple files.

**Comment by zoeyli-46** [comment]
Wording of third-person or first person should be kept as is, there are nuances that need to remain

**Comment by elliottSlee** [comment]
Total household in Template 1 is good enough for intake. Households in Template 9 is from applicant. Template 9 also has tech info that can gleaned from Logical Network Diagram. May need Geonames in database--figure out easiest way.

**Comment by elliottSlee** [comment]
Gov of Canada logo will not be on webform

**Comment by elliottSlee** [comment]
Analysts are assigned to an assessment for a particular application then potentially to a different assessment for another application

**Comment by MarsRomer** [comment]
I am assuming that analysts may be assigned 

> Analysts are assigned to an assessment for a particular application then potentially to a different assessment for another application

I am assuming that analysts may be assigned multiple applications to assess and also potentially multiple types of assessments within each application.

**Comment by elliottSlee** [comment]
NWBC will not see draft applications.

**Comment by elliottSlee** [comment]
Household count cell references updated to match revised Template 1 from ISED.

**Comment by elliottSlee** [comment]
Applicants can't edit applications between intakes

**Comment by elliottSlee** [comment]
@zoeyli-46 Should we close this since we don't use it anymore? We could still see it in the closed column

**Comment by zoeyli-46** [comment]
Closing
