### ISSUE TITLE
History of RFIs

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#1663]
As an analyst
I want to see in the history what changed in an RFI when it's saved
So that I can have the full history

**Description:**
_if needed_

# Acceptance Criteria:

- [x] "Uploaded a file" based upon the attachments database table does not show on the history page, removed from the whole history i.e. orphaned files will not show up in history
- [x] Table header border is 2px CCCCCC
- [x] Width of columns fits / hugs content
- [x] Only display what changed in the form
- [x] File names appear as links. Click starts download
- [x] If a file is added to the email files field, the history states, "<User> added a file to RFI-CCBC-######-# on <date & time>" with the filename below (see wireframe below)
- [x] On the history page, if Template 5 - List of Points of Presence and Wholesale Pricing appears, change it to Template 5 - List of PoPs and Wholesale Pricing
- [x] On the history page, if Template 6 - Community and Rural Development Benefits appears, change it to Template 6 - Community Benefits

To tackle later:

- [ ] If a user adds more than 1 file to the email file upload, one after the other, within a 15 minute period, instead of repeating that same line in the history, group them and state, "<User> added files to RFI-CCBC-######-# on <date & time _of the last upload_>" with the filenames below (see wireframe below)

[**Wireframe**](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?type=design&node-id=9500-53378&t=OOO7MzBu8F4InV5d-4)
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/dc51ff2a-3bd6-4d19-8374-370f91f1ea07)
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/8cf6c1c9-eef4-4b56-a000-711cdb451ae3)
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/732dbc74-429c-4db8-aa62-507916aacac2)

### Not included:
- .
- .

## Implementation Details
- **DB:**
  - .
  - .
- **Middleware:**
  - .
  - .
- **Frontend:**
  - .
  - .
- **Tests:**
  - .
  - .
- **Documentation:**
  - .
  - .

**Comment by rafasdc** [comment]
For: If a file is added to the email files field, the history states, "<User> added a file to RFI-CCBC-######-# on <date & time>" with the filename below (see wireframe below). 

We cannot tell if it was an addition or a removal, changed the wording to "<User> *update the files on* RFI-CCBC-######-# on <date & time>" with the filename below (see wireframe below). "

**Comment by MarsRomer** [comment]
Looks great, just one note is that this acceptance criteria doesn't seem complete: 
- [ ] If a file is added to the email files field, the history states, " added a file to RFI-CCBC-######-# on <date & time>" with the filename below (see wireframe below) 
 I am not seeing this:
- [ ]   ![image.png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/aa81f747-d831-4563-82fc-5cbb94760ea3)
 I've also noticed that when I upload an email file to the RFI without clicking the edit pencil first  it doesn't show in the history, unless I click the edit pencil and then save.
