### ISSUE TITLE
GIS analysis upload display depends on status

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#1664]
As an analyst
I want the GIS analysis to update on the Assessment page only when the status is Received, Screening, Assessment
So that we can have the right snapshot in time for the application.

# Acceptance Criteria
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/b9092200-ab0a-4145-b8d2-5b003b82f5cf)
[**Wireframe**](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?type=design&node-id=11144-100458&t=9bEtzcEfUrnL8iMZ-4)

- [x] If the status of an application is Received, Screening, Assessment, when the GIS analysis JSON is uploaded, then the #s are updated on the GIS assessment page
- [x] If the status of an application/project is Recommendation, Conditionally Approved, Approved, Complete, Cancelled,  Withdrawn or anything other than those mentioned in the previous AC when the GIS analysis JSON is uploaded, then the #s are _NOT_ updated on the GIS assessment page
- [x] Uploader only imports the above data into the DB - Block upload of data that is at or beyond the Recommendation state
- [x] After importing, display which projects were not uploaded due to status rules
<img src="https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/adf7fc2f-77bc-421c-be4b-1b52160e3b89" width="50%">

- [x] Unchanged, not imported sections: colour F1F2F3, radius 8
- [x] Successful import sections: colour DFF0D8, radius 8, icon [font-awesome circle-check](https://fontawesome.com/icons/circle-check?f=classic&s=solid) 2E8540

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1664?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc @VB-at-Bis
