### ISSUE TITLE
SoW Input UI - clear form data if 'No' is selected and saved

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/CONN-CCBC-portal#1680]
As an analyst 
when I click no and save the Project information
then the data I had entered previously should clear out

Acceptance Criteria:
- [x] if there is data entered in the project information and user clicks 'No' to Has Funding Agreement been signed and then clicks save, the project information should not exist on the UI when they subsequently click 'Yes'.  
- [x] Previous project data should be archived in the DB when user clicks No and saves
- [x] Previous SOW data should be archived in the DB when user clicks No and saves
- [x] History table shows change to Has Funding Agreement been signed = No and Yes
- [x] The project information should show as it would before user had entered any information if they click No and save (see screen below)
 ![image.png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/51556524-5c9b-4245-903e-12e2e73616d9)

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1680?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc @VB-at-Bis
