### ISSUE TITLE
Review Metadata

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1692]
As a user of CCBC data
I want to see all the metadata 
So that I know what the different tables and columns are

AC:
- [x] Schema has descriptions of tables and columns
- [x] Metabase shows the description of all the tables and columns 
- [x] Descriptions are meaningful and understandable by the average user

**Comment by MarsRomer** [comment]
hey Marcel, at a first glance I can see that there are tables missing descriptions, I haven't looked at the column descriptions yet though:
![image.png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/87220a4c-5394-4997-8e7a-c23a1d4e5ded)  
Would you mind taking another look please?

**Comment by marcellmueller** [comment]
@MarsRomer I was asked to remove those in code review as they were supposed to be taken care of by Vlad's PR. You can see the comments here:

https://github.com/bcgov/CONN-CCBC-portal/pull/1803

**Comment by MarsRomer** [comment]
OK I saw that none of the acceptance criteria were checked off but thought that was just an oversight.

**Comment by marcellmueller** [comment]
@MarsRomer sorry about that. Though we should try and remember to bring this up tomorrow at standup to make sure that this will be taken care of.
