### ISSUE TITLE
Better metrics for pod health and load balancer

### ISSUE THREAD

**Issue by AntBush** [bcgov/CONN-CCBC-portal#1694]
Currently, the load balancer does not consider multiple factors for pod health when routing requests. To fix this, we need to add more visibility for pod health. 

Benefits: Better routing means our app is more available, and ensures that our resources are used effectively. 
Risks: If there is a cause for a pod to be unresponsive that is not due to CPU, requests will continue to be made to that pod. This means that our application will be unavailable to users even though healthy pods are available.

**Comment by rafasdc** [comment]
Turns out this was because OpenShift injects a cookie to keep a connection stable and sticky to a pod, this is on by default. Turning this cookie off lets the balance algorithm (round robin) work properly.
