### ISSUE TITLE
Spike: How to add descriptions for json

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1695]
Description:  Currently json fields do not have descriptions of every field, this ticket is to investigate how to include that in a viewable and digestible form

Acceptance Criteria
We have a solution for the following:
- [x] The Json metadata should somehow be in GitHub ,
- [x]  and ideally be visible in metabase first 
- [x]  and schemaspy second

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1695?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc @VB-at-Bis

**Comment by VB-at-Bis** [comment]
Run query in DB to find all tables with `json_data` fields:
 table_schema |        table_name
--------------+---------------------------
 ccbc_public  | assessment_data
 ccbc_public  | form_data
 ccbc_public  | rfi_data
 ccbc_public  | gis_data
 ccbc_public  | announcement
 ccbc_public  | conditional_approval_data
 ccbc_public  | application_gis_data
 ccbc_public  | application_sow_data
 ccbc_public  | sow_tab_1
 ccbc_public  | sow_tab_2
 ccbc_public  | project_information_data
 ccbc_public  | sow_tab_8
 ccbc_public  | sow_tab_7

Also, we have next variations of JSON schema, stored in `form_data` table:
    name    |                       description
------------+---------------------------------------------------------
 intake     | Schema for an entire application
 rfi        | Schema for an RFI
 assessment | Schema that is part of the assessment of an application

Suggested approach:
- use existing JSONSchema files https://github.com/bcgov/CONN-CCBC-portal/tree/main/app/formSchema/analyst;
- create JSONSchema files for tables where we do not have schema files yet;
- update SchemaSpy GitHub action to publish all schema files to GitHub pages alongside with SchemaSpy;
- create script (and call it as part of SchemaSpy generation) that creates XML comments for tables above to enhance SchemaSpy doc and include links to JSONSchema files (see [article ](https://schemaspy.readthedocs.io/en/latest/advanced_usage.html#add-markdown-comments-using-additional-metadata) that describes advanced usage of SchemaSpy);
- consider using https://json-schema.app/ to visualize JSONSchema files - i.e. see example [RFI schema](https://json-schema.app/view/%23?url=https%3A%2F%2Fgist.githubusercontent.com%2FVB-at-Bis%2F0c9b65d8e622c4cf4e381b9dd0f3f942%2Fraw%2Fb1937c06d57313ae33713289996bccfbaedff6a7%2Frfi-schema.json);
- add table-level comments in Postgress to provide same links to JSONSchema viewer;
- consider forking https://github.com/atlassian-labs/json-schema-viewer and deploying it in our own OpenShift (or AWS) to ensure that links would not bet broken if Atlassian stops support for json-schema.app

**Comment by VB-at-Bis** [comment]
Example:
- open schemaspy , table details https://bcgov.github.io/CONN-CCBC-portal/schemaspy/ccbc_public/tables/rfi_data.html 
- find `json_data` column and find its comment `The json form data of the RFI information form. See schema`
- click on `schema` link
- see json data description at https://json-schema.app/view/%23?url=https%3A%2F%2Fbcgov.github.io%2FCONN-CCBC-portal%2Fschemaspy%2Fdata%2Frfi_data.json
