### ISSUE TITLE
Create App Test Environment

### ISSUE THREAD

**Issue by eazeredo** [bcgov/CONN-CCBC-portal#17]
# Acceptance Criteria
- [x] Make adjustments on Helm Charts
- [x] Do a manual deployment to test the environment
- [x] Secrets into the GitHub environment 
- [x] Kubernetes
- [x] Refactor

## Not included
- Pipeline (see card #23)
- Password to access test environment (#171)

https://ccbc-test.apps.silver.devops.gov.bc.ca/

**Comment by eazeredo** [comment]
@marcellmueller , as we have the Test environment, is this card done?

**Comment by marcellmueller** [comment]
@eazeredo no, I checked off what is done. Just working on Helm refactor so should be done soon but will need review as well.

**Comment by marcellmueller** [comment]
@MarsRomer 

This is done, just needs your approval. The test environment is here:

https://ccbc-test.apps.silver.devops.gov.bc.ca/

**Comment by MarsRomer** [comment]
Done, thanks!
