### ISSUE TITLE
Add links to Metabase on GIS import pages

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#1702]
As an analyst
I want the GIS import pages to have a link to the Metabase GIS analysis dashboard
So that I can see the GIS analysis for all projects

# Acceptance Criteria:

## Input page
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/621b3755-655f-4467-86ec-3e2cd101a543)
[**Wireframe**](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?type=design&node-id=11639-123483&t=9bEtzcEfUrnL8iMZ-4)

- [ ] Add card for GIS Metabase link
https://ccbc-metabase.apps.silver.devops.gov.bc.ca/dashboard/87-gis-analyses

background: #FFFFFF;
border: 1px solid #D6D6D6;
box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
border-radius: 8px;

- [ ] Convert upload label & description to card

## GIS Import Success Page
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/abb49157-4ccf-4cb0-a249-7cf6cc810e52)
[**Wireframe**](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?type=design&node-id=11144-100458&t=9bEtzcEfUrnL8iMZ-4)
- [ ] Add card to GIS import success page
https://ccbc-metabase.apps.silver.devops.gov.bc.ca/dashboard/87-gis-analyses

## Implementation Details
- **DB:**
  - .
  - .
- **Middleware:**
  - .
  - .
- **Frontend:**
  - .
  - .
- **Tests:**
  - .
  - .
- **Documentation:**
  - .
  - .

**Comment by MarsRomer** [comment]
@VB-at-Bis  can all the acceptance criteria be checked off?
