### ISSUE TITLE
Update metabase link for SOW data 

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1714]
As an analyst 
I want to be able to see the SOW data in metabase that was just uploaded
So that I can verify it was uploaded correctly and I can se the project information important to me

**Description:**
Add a link or links to the SOW data in test and prod for the metabase report with SOW data

# Acceptance Criteria:
- [x] link in Test env for metabase on Project page takes user to test metabase SOW report or reports
- [x] link in Prod env for metabase on project page takes user to the prod metabase SOW report or reports
- [x] link in dev env for metabase on project page takes user to the test metabase SOW report or reports
- [x] Icon & text linked to a Metabase dashboard. Talk to Ali & Elliott for the link

**Comment by elliottSlee** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1714?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc @VB-at-Bis

**Comment by MarsRomer** [comment]
Test link works as expected, I can't test the prod link until we have a SOW uploaded in prod so I will test that later and create a new ticket if the link doesn't work
