### ISSUE TITLE
Provide information about internal and external status of applications

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1716]
As an analyst 
I want to get more information about the internal and external status
So that I can understand the relationships between the external status and internal status

**Description:**
Now that we are allowing analysts to change the external status and use the internal status in more advanced ways, it is important that the analysts understand how the internal and external status are related so that they pick the right status when working in the portal

# Acceptance Criteria:
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/c17eb19e-e233-4695-b367-49c589a7482b)
Icon: https://fontawesome.com/icons/circle-info?f=classic&s=solid
- [x] circle-info icon is to the right of the `main` container
- [x] icon is same size as height of neighbouring dropdown (30px or 1.875em)
- [x] On click, the following modal appears
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/cea21ea6-e129-4515-9290-75c888431251)
[Diagram in svg format](https://buttoninc-my.sharepoint.com/:u:/g/personal/elliott_button_is/EZhW-p4qHCFMn7KocSiO414B6Mg-hGtgogYayNkQ-TEuzg?e=UpozSe)
[**Wireframe**](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?type=design&node-id=11682-116887&t=sZrTTwZ02kKLjjeg-4)
- [x] icon & modal share the same aria-labelledby, "Description of Statuses and Triggers"
- [x] Make all other elements underneath inert ([see explanation & React example](https://larsmagnus.co/blog/accessible-modal-dialogs-using-inert))
- [x] Alt-text for image:
> The happy path for a project from application to completion. The external status, which is what an applicant sees, is different from the internal status, which is what you the analyst sees. After an intake closes, both internal & external status are Received. After eligibility screening is assigned, the internal status can be changed to Screening but the external status remains Received. After it is determined to be eligible, the internal status can be changed to Assessment but the external status remains Received. If it is in the selection package for the Minister, the internal status can be changed to Recommendation but the external status remains Received. After the Minister states Approved in Annex A of the selection package, the internal status can be changed to Conditionally Approved. The external status can only be changed to Conditionally Approved when the applicant responds in the affirmative to the Letter of Conditional Approval. When the Funding Agreement is signed by both the Recipient and the Province, the internal & external statuses can be changed to Approved. After a final implementation report is received & the final claim is processed, both statuses can be changed to Complete.
- [x] Click X or press escape on keyboard closes it
- [ ] Apply these changes to all our modals?

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1716?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc @VB-at-Bis

**Comment by marcellmueller** [comment]
![Screenshot 2023-06-26 at 3 44 44 PM](https://github.com/bcgov/CONN-CCBC-portal/assets/14259474/3df3ac93-a654-46d8-a20a-3ea72bec662b)

@elliottSlee it looks like this is a low fidelity screen? Can we get a finalized version for this ticket?

**Comment by elliottSlee** [comment]
@marcellmueller That's the finalized image. How can I make it better?

**Comment by marcellmueller** [comment]
Oh sorry, it just looks seemed a prototype full of alignment issues and design inconsistencies.

**Comment by elliottSlee** [comment]
@marcellmueller the conditional approvals being staggered (not aligned) was on purpose. Is there something else we could improve? I seriously suck at visual design

**Comment by marcellmueller** [comment]
@elliottSlee well it's not just that, even though it does make it look off. Some other things I noticed right away were the conditional approval pills are different sizes/padding. The yellow diamond things are all seemingly different, some overlapping the pills, some have one side touching the pill, some have a gap on either side.

Anyways I wouldn't worry about it too much, I was just looking at the ticket and thought it wasn't ready.

**Comment by elliottSlee** [comment]
@MarsRomer could we create a ticket to change the font of this modal to BC Sans? Since we used the Material UI (MUI) modal, it defaulted to their font. It's the font-family of the Chips & the Header (MuiTypography H2)
![Screen Shot 2023-07-12 at 9.51.20 AM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/65e9c821-c7c0-4fcf-aa3f-a9143834d7d5)

**Comment by rafasdc** [comment]
Will be fixed by PR #1902
