### ISSUE TITLE
Re-order pages of form

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#172]
### User Story
As an applicant
I want to enter my organization profile, location, and contact info after the map upload page but before the review page
So that my application information can be entered first and the application name can be listed at the top of each page.

### Description
https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=1059%3A6234

### Acceptance Criteria
Order of pages:

1. Project information
2. Project area
3. Geographic names
4. Existing network coverage
5. Budget details
6. Project funding
7. Other funding sources
8. Technological solution
9. Benefits
10. Project planning and management
11. Estimated project employment
12. Template uploads
13. Supporting documents
14. Mapping
15. Organization profile
16. Organization location
17. Organization contact information
18. Authorized contact
19. Alternate contact
20. Review
21. Declarations 1
22. Declarations 2

**Comment by elliottSlee** [comment]
Zoey & Elliott discussed re-ordering declarations & review page.
Outcome: declaring that everything's true & accurate requires reviewing first, so this has to come afterwards. If concerned about printing, applicants can print this & next page off too.

**Comment by marcellmueller** [comment]
@MarsRomer @elliottSlee 

Is it okay to bring this one into the current sprint? It is realistically a one on size the way we have it set up and seeing as we will soon have all the pages implemented I would like to have them in the correct order.

**Comment by MarsRomer** [comment]
Hi @marcellmueller  absolutely, let's bring it in!
