### ISSUE TITLE
Datepicker refactor

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/CONN-CCBC-portal#1722]
The Datepicker widget could use some love and either a total rework with a different library or just a nice cleanup.

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1722?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc @VB-at-Bis

**Comment by elliottSlee** [comment]
@marcellmueller  I noticed this didn't update for the time machine. Does that matter?

**Comment by marcellmueller** [comment]
@elliottSlee oh yeah I did notice that while I was doing the datepicker widget refactor. It is not an RJSF form so it's not using the widget. We would need another ticket for it though I don't think it's too important, it would be good to get out of the way so we can remove `react-datepicker` from our dependencies.

**Comment by MarsRomer** [comment]
Looks great, love the new date picker!
