### ISSUE TITLE
Modified modal when deleting announcements from single project

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1725]
As an analyst
I don't want a modal pop up when deleting an announcement for a single project
So that I am not confused as to why I'm being asked if I want to delete from all projects

**Description:**
Currently when deleting an announcement using the red x in the UI, the user gets a modal asking if they want to delete the announcement from all projects or just this one.  This modal may be confusing to the analyst if the announcement does not have other projects so it should not show.  

# Acceptance Criteria:
- [ ] If the announcement is only for one project then clicking red x deletes then the modal says:
<img src="https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/ce781476-3fd6-444b-88d8-3b7532d1b43a" width=50%>
- [ ] If the announcement is for more than one project - the modal will show as is now.

**Comment by elliottSlee** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1725?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc @VB-at-Bis
