### ISSUE TITLE
Current project number should not show in announcement

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1726]
As an analyst
I want to only see the other project numbers in my announcement
So that I am not confused why my current project number is in the 'other projects' list

**Description:**
Currently if there is one other project selected for an announcement then the 'Other Projects in this announcement' also includes the project they are currently viewing.  This should not happen.
![image.png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/330cbfc1-4213-4da4-8989-ab6ede42faf3)
# Acceptance Criteria:
- [ ] only real other projects should show up in the 'Other Projects in this Announcement', not the current project

**Comment by elliottSlee** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1726?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc @VB-at-Bis
