### ISSUE TITLE
Validate Data types and MaxLength on Org profil & address

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#173]
As ISED
I need to make sure that the character limits and data types are enforced
so that my data import works with the schema I have in Salesforce

This ticket is limited to the forms that have already been created or will be created in the test environment during this sprint

### Description
https://regexlib.com/REDetails.aspx?regexp_id=2790
https://owasp.org/www-community/OWASP_Validation_Regex_Repository

### Acceptance Criteria
**Organization Profile Page**
- Type of org
    - [x] Required
#
Please describe your organization type
   - [x] Required

band number
- [x] number
- [x] Required

Org name
- [x] Maxlength: 200 characters
- [x] Required

Is operating name same as legal name?
- [x] Required

Operating name
- [x] Required

Applicant organization a subsidiary?
- [x] Required

Please enter the name of the parent organization
- [x] Required

organization an Indigenous entity?
- [x] Required

short description of the Indigenous entity
- [x] maxlength: 75 characters
- [x] Required

overview of the organization
- [x] maxlength 3500 characters
- [x] Required

Date of incorporation or registration
- [x] datepicker [month & year drop down](https://reactdatepicker.com/#example-year-select-dropdown) instead where it is more clear that it is an input field?
- [x] Required

Applicant business number (9-digit business identifier provided by Canada Revenue Agency)
- [x] type: number
- [x] maxlength: 9
- [x] Required

**Organization Location Page**
Unit number
- [x] type: text input
- [x] maxlength: 9
- [x]  Optional

Street Number
- [x]  Validation: 1-9 digits and or letter, no symbols
- [ ]  Error message: Must be 9 or fewer numbers or letters, don't include symbols.
- [x]  Required

Street name
- [x]  Required

PO Box
- [x]  Validation: 1-6 digits
- [ ]  Error message: Must be 9 or fewer numbers, don't include letters or symbols.
- [x]  Optional

City
- [x]  Required

Province

- [x]  Dropdown options: "Alberta", "British Columbia", "Manitoba", "New Brunswick", "Newfoundland", "Northwest Territories", "Nova Scotia", "Nunavut", "Ontario", "Prince Edward Island", "Quebec", "Saskatchewan", "Yukon Territories"
- [x]  Required

Postal Code

- [ ]  Validation: see comments for potential solution
- [ ]  Error message: Must be in format H0H 0H0 with no spaces.
- [x]  Required

Mailing address same?

- [x]  Required
- [x]  Scenario: conditionally opens mailing address input
Given that a user is on the organization address page and responding to "Is the mailing address the same as the above?"
when they select no
then all the fields for Mailing address appear below

Mailing address
Same validations, errors, requirements as above

**Comment by elliottSlee** [comment]
![Screen Shot 2022-06-08 at 12.21.29 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/a1c2ae12-7080-4453-8af7-97d7ccdd4ee6)

^(?!.*[DFIOQU])[A-VXY][0-9][A-Z]●?[0-9][A-Z][0-9]$

**Comment by BryanGK** [comment]
This card is complete - missing validations are being tracked in issue #217

**Comment by MarsRomer** [comment]
@marcellmueller @BryanGK The organization location page is showing the address fields as 'Optional'.  Can we please remove that word from the titles?

**Comment by BryanGK** [comment]
@MarsRomer it would appear that when the form pages were split out in separate files my updated pages were not properly copied over. I'll get that fixed ASAP.
