### ISSUE TITLE
Update "date funding agreement signed" labels

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#1731]
As an analyst
I want the dev team to fix Elliott's mistake that was in the wireframes
So that the date signed is correct

**Description:**
_if needed_

# Acceptance Criteria:
<img src="https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/f94fa568-a245-4daf-abcd-215141a310ea" width=50%>

- [ ] On Project page, in the project information form, "Date Funding Agreement signed by Province" P in Province is capitalized

<img src="https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/9f2ba456-2aa9-48fc-8bca-148737af7a93" width=50%>

- [ ] On Project page, in the read-only of project information, "Date funding agreement signed by recipient" is "Date funding agreement signed by Province"

**Comment by MarsRomer** [comment]
hey @elliottSlee I think I beat you to it, I just created a ticket for this #1729

**Comment by elliottSlee** [comment]
Duplicate
