### ISSUE TITLE
Archive old user ID

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#1739]
# Acceptance Criteria:
- [ ] archived duplicate user (duplicate email address) that resulted from BCeID bug

**Comment by VB-at-Bis** [comment]
Data from Production:
<pre>
ccbc=# select count(*), email_address from ccbc_public.ccbc_user group by email_address having count(*)>1;
 count |      email_address       
-------+--------------------------
     3 | aanderson@nwtel.ca
     2 | ali.fathalian@gov.bc.ca
     3 | meherzad.romer@gov.bc.ca
</pre>

Are those records above  we want? Only first one seems to be an issue...

**Comment by MarsRomer** [comment]
Closing as we have decided not to do anything at this point about this issue
