### ISSUE TITLE
Spike - object storage

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#174]
Research different storage solutions for our documents that the applicant uploads.  

The documents will:
1. need to be stored securely - only allow access to who CITZ chooses
2. be easily useable by ISED and CITZ staff (including data team)
3. be backed up properly
4. be linked to the application
5. be cost-effective
6. Will be allowed by security/privacy

### Acceptance criteria:
- [ ] A technical solution to where we are going to store the documents addressing each of the document needs above.

notes: Try terraform from AWS team

https://github.com/bcgov/startup-sample-project-aws-containers
https://github.com/bcgov/mds/blob/develop/.github/workflows/aws-infra-prod.yaml#L28

**Comment by VB-at-Bis** [comment]
![privateS3.drawio.png](https://images.zenhubusercontent.com/621d06da1613ac1631e8f9b6/aaa1ee40-4816-42f6-a66f-e5d8832a0f2b)

**Comment by VB-at-Bis** [comment]
![vpc.jpeg](https://images.zenhubusercontent.com/621d06da1613ac1631e8f9b6/316819d9-b23c-4824-b45f-bebe2d4fbb68)

**Comment by VB-at-Bis** [comment]
After discussions with Julian and Max it was decided to follow the BCGov standards and simplify the approach.
- use Terrafrom Cloud and pre-configured AWS accounts to create S3 buckets;
- code should use special s3_admin account that assumes specific role with FullS3Access permissions;
- no VPC or VPC endpoints in use;
Updated diagram
![image.png](https://images.zenhubusercontent.com/621d06da1613ac1631e8f9b6/8330a214-f255-4731-988c-6b230b37b337)

**Comment by VB-at-Bis** [comment]
PR submitted, approved and merged https://github.com/bcgov/CONN-CCBC-portal/pull/332
S3 buckets created in dev, test and prod; GitHub secrets created for AWS credentials, role ARN and bucket name.
Tested in dev: application was able to connect to s3 and upload files.
