### ISSUE TITLE
Spike:  Investigate Metabase performance issues

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1748]
Description:
Metabase has been running a bit slower since we have updated to the newer version.
This ticket is to investigate the cause for the slow down and create tickets necessary to mitigate any issues that this may cause for metabase and the database.

**Comment by rafasdc** [comment]
Metabase deployment had resources request and limits set to 0, which would make it go to a BestEffort QoS class, more info here https://docs.developer.gov.bc.ca/application-resource-tuning/

During large questions, the cpu usage would spike to 100m - 200m which indicates of it being throttled, the database was not being "hit" or showed any kind of spike during large questions as metabase pulls DB data on a sync interval and caches large queries that take longer than 7seconds (will likely lower to 1 second). 

OpenShift UI might not show real-time resources usage, a terminal is required to check what is being used in a semi real-time. 

The following commands were ran in different namespaces to analyze usage:
`oc -n [Metabase-namespace] top pods` paired with `oc -n [CCBC-namespace] adm top pods`

By running these commands when a large question is running the spike on the CPU of metabase can be observed but no spike on the DB pods on the CCBC namespace. 

Finally, metabase while booting tends to spike to 300m or more, hence the limit on non prod namespaces was set to 300m and 500m on prod. It will idle at around 10m.
