### ISSUE TITLE
DB: SOW Archive

### ISSUE THREAD

**Issue by rafasdc** [bcgov/CONN-CCBC-portal#1749]
- [x] Add archive function to SOW tables (sow_tab_1 - 8 and application_sow_data)
- [x] Create mutation/function that archives all related sow data on one go at the backend level

**Comment by rafasdc** [comment]
Yes, was a bit of extra work related to #1680

**Comment by MarsRomer** [comment]
To test this ticket I deleted a previously uploaded SOW table from application 020189 but in the Application SoW table it didn't archive.  I was expecting the Archive by and Archive at to be populated
![image.png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/25df080f-ed1e-4451-965b-d80bd802b18f)

**Comment by MarsRomer** [comment]
update:  I just uploaded the SOW again and before clicking anything else (just upload) to this application and now it shows the original upload as being archived.  I clicked cancel to not import the data and it still shows the original being archived but the one I just uploaded but then canceled = not archived.  
![image.png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/97f3c6a4-d5d6-4f0d-8488-ca300daaa86e)

**Comment by rafasdc** [comment]
thanks, that's the expected behaviour for the archive, once a new item is inserted into the table it will archive the previous one, if there was any others prior to this ticket for that application (archived or not) they will be left as is. 

For the cancel button: It will import even if you click cancel or save & import, I think there might be a ticket to change for this already?

For the second part of this ticket if you set the "funding agreement signed" to no it will then archive all sow information for that project.

**Comment by MarsRomer** [comment]
ok thanks, I will create new tickets for the archiving functionality in my comments above
