### ISSUE TITLE
Replace proj SoW Tables with change request SoW tables

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#1755]
As an analyst
I want the SoW tables in the Project Information to be the most recent version and a notice that this is the case
So that I am confident that I am looking at the most up to date information

**Description:**

_if needed_  

# Acceptance Criteria:
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/07ec7264-d6ff-4e98-8ef9-3ca3f5249185)
[**Wireframe**](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?type=design&node-id=11716-123324&mode=design&t=waTieHqed7P3XqIA-4)

- [ ] After pressing save & import on a change request where a SoW table is uploaded, then the original SoW table in the Project information section is replaced with the new one from the change request
- [ ] After a change request is submitted, the edit pen of the project information is removed
- [ ] After a SoW is replaced, the yellow notice box appears below and stays there

**Comment by MarsRomer** [comment]
@elliottSlee I don't think we need this ticket anymore, can I close it?

**Comment by MarsRomer** [comment]
Don't need this ticket anymore
