### ISSUE TITLE
Change request - Metadata

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1770]
As an analyst
I want to enter in metadata for the change request 
So that I can have an understanding and be able to categorize the change requests for reporting

**Description:**
There are some pieces of information that we need to capture for the change requests so that the ministry can understand and categorize the change requests

# Acceptance Criteria:
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/89993663-e9a0-4724-b52c-77b522c3c3f1)
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/5113a64b-9c7d-431b-8711-619ce9123028)

- [x] Amendment # is 3 digit integer only. Mandatory.  (validation that it's a unique # is ticket #1777)
- [x] Description of changes: Text  Max 10,000 characters.  Mandatory 1 characters at minimum
- [x] Date requested - Date today or prior to.  validate that it's not in the future
- [x] Date approved - Date today or prior to.  Validate that it's not in the future
- [x] Level of amendment: Radio buttons - all unselected when form opens
- [x] When a SoW Excel file is uploaded, the Save button changes to "Save & Import"
- [x] Additional comments:  text max 10,000 characters

Notes:  
Radio buttons should be designed and built in a way that it enables changes that don't require a lot of effort.

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1770?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc @VB-at-Bis

**Comment by marcellmueller** [comment]
@MarsRomer @elliottSlee what do we mean by `validate that it's not in the future` for both of the new date fields here? Do we want visual feedback and to not allow the form to be saved?

**Comment by MarsRomer** [comment]
I was imagining that the date picker would simply not allow it in the sense that the dates in the future would be grayed out and not selectable.  nip it in the bud.

**Comment by marcellmueller** [comment]
Yeah we can definitely set a max date of the current date. Another thing to consider with date validations is you can now copy/paste or type the dates.

 I think I am going to get started on this ticket soon since it's going to block some other upcoming tickets, I will play around with setting a max date with the new datepicker.

**Comment by MarsRomer** [comment]
good point about the copy and paste, what happens now if they copy paste a garbage date where the month is 15? and day is like 45?

**Comment by marcellmueller** [comment]
I tested this earlier, if the date is past the `maxDate` (ie tomorrow) then there will be that little red outline around the datepicker just as if you are typing and leave a date unfinished/invalid.

**Comment by MarsRomer** [comment]
I think that's good enough
