### ISSUE TITLE
Project Description

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1771]
As an analyst
I want to be able add a short project description
So that it can be used in communications

**Description:**
This ticket is for being able to have the project description in the new 'master spreadsheet'
  

# Acceptance Criteria:
[**Wireframes**](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?type=design&node-id=12755-26568&mode=design&t=tGT5c5mzg7TZb2V1-4)
[Default](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdWllIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d0ef9f1c872519bb72954faa0176c9343b7ad13b/image.png)
[Editing](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdkNlIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bbf90d55ac9b22f393e6766d6cb1dbd8e752ea18/image.png)
[Read-only](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdldlIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--903969e2bddad650d0f2a18589f047d73c4f5d78/image.png)

[Responsive medium](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaGVmIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ad7a548377c963dfea5b62d63897ca7b41d7c648/image.png)

[Responsive small](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaG1mIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--25fb486bcdfb687a594d809d3b9a18722ece5c26/image.png)

- [ ] Display "Click to add internal project description"
- [ ] Inline editing of this field. Click on it and it turns into an editable field
- [ ] Max 320 characters (incl. spaces)
- [ ] # of characters updates while typing
- [ ] Pressing escape cancels and changes made and exits edit mode, turning back to read-only, displaying previously saved version.
- [ ] Pressing enter saves changes made and exits edit mode, turning back to read-only with new
- [ ] Responsive design of read only. Width scales with screen size, height grows to accommodate text. <577px, max height = 60px and editing disabled
- [ ] History is retained if we want to display it later

**Comment by MarsRomer** [comment]
Will the project description come from the ISED Project Summary form or do we write

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1771?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc

**Comment by marcellmueller** [comment]
@MarsRomer what is this ticket? Is is a mistake or a duplicate of #2170? The description is different  as this is about the master spreadsheet so I'm wondering if the acceptance criteria is wrong.

**Comment by MarsRomer** [comment]
@marcellmueller It does seem to be a duplicate, not sure how this happened, but it happens.  I will close it

**Comment by marcellmueller** [comment]
@MarsRomer no worries, just making sure. Though my ticket is merged and completed, I didn't do the acceptance criteria ` History is retained if we want to display it later` since it wasn't in the other ticket.  

I am actually doing an update instead of an insert. The column lives in our `application` table where I don't believe we have been inserting new rows and archiving previous ones (an not sure if it has history auditing enabled).

Maybe something to talk about at standup.
