### ISSUE TITLE
Application form - Estimated project employment

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/CONN-CCBC-portal#178]
## User Story
As an applicant,
I want to submit my "current employment", "estimated direct employees", and "estimated contracted labour" 
so that I can apply to the program.

## Research and Design
https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=1433%3A6096

## Acceptance Criteria

- **Scenario: Validate required fields**
- [x] Current employment: Total number of people employed by the organization
- [x] Number of people to work on the project
- [x] Hours of employment per week (average hours/week)
- [x] Total person months of employment to be created (average months/year)

---
Current employment: Total number of people employed by the organization
- [x] required

Number of people to work on the project
- [x] required 

Hours of employment per week (average hours/week)
- [x] required 

Total person months of employment to be created (average months/year)
- [x] required

![Est proj employment.jpg](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/8e9fd68f-d874-4553-9031-8d8fae869bb8)

## Not included
- Calculation
     - Total estimated full-time equivalent (FTE) Job Creation
     [((people*hours)/35)*(months/12)]
     - Total estimated full-time equivalent (FTE) Job Creation
     [((people*hours)/35)*(months/12)]

**Comment by marcellmueller** [comment]
@MarsRomer can you please review this one, it is on form page 6 (once you are logged in of course).

https://ccbc-dev.apps.silver.devops.gov.bc.ca/form/6
