### ISSUE TITLE
Fix calendar on time machine

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1798]
As an analyst
I want the time machine calendar to be the same as the other calendars on the app
So that I have a consistent experience across all calendars in the app

# Acceptance Criteria:
- [ ] Time machine calendar behaves the same as other calendars on the page

[wireframe 1]

- [ ] Acceptance Criteria 

[wireframe 2]

- [ ] Acceptance Criteria

**Comment by MarsRomer** [comment]
hey @marcellmueller isn't this the old calendar?  ![image.png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/9977cb62-15f5-402e-876b-e1b4ee449a18)

**Comment by marcellmueller** [comment]
Oh sorry I guess this didn't quite make it into the release.

**Comment by MarsRomer** [comment]
Looks good!
