### ISSUE TITLE
Create App Prod Environment

### ISSUE THREAD

**Issue by eazeredo** [bcgov/CONN-CCBC-portal#18]
# Acceptance Criteria
- [x] Make adjustments on Helm Charts
- [x] Do a manual deployment to test the environment
- [x] Secrets into the GitHub environment 
- [x] Kubernetes

## Not included
- Pipeline (see card #24)

https://ccbc.apps.silver.devops.gov.bc.ca/

**Comment by MarsRomer** [comment]
@marcellmueller  should I be getting this error on prod (see attached)
![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/80e76003-0eb3-48fc-afc3-0690cc6a9de2)
