### ISSUE TITLE
Update analyst header & pages incl project accordions

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#1800]
#### Current
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/382b0e90-d821-4338-9507-512339906b26)

#### Desired
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/484a7da3-5f9b-4227-b8aa-95f490f4b10f)

- [x] main (.eYrOMo) change padding from 2em all around to `padding: 1em 2em` (2 on sides, 1 on top & bottom)
- [x] Change `ApplicationHeader__StyledCallout-sc-1yrhrx0-0 evIOfS margin-bottom: 40px` to `margin-bottom: 0.5em`
- [x] On application page, change colour of edit pencil to #1A5A96
- [x] On application page, line-up the line in the sidebar with the top line of the accordions. 
- [x] On Project page, change accordion headers to match the application page
- [x] On Project page, change ReadOnlyWidget__StyledValue padding 8px top & bottom to just 8px on bottom for all read-only form fields
- This last one is true for the read only for all the forms--cond appr, announcements, proj info. Please change it for all of them and all future ones.

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1800?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc @VB-at-Bis

**Comment by MarsRomer** [comment]
hmm I don't think this got pushed into test along with the other tickets  ![image.png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/f66be609-2280-453b-b191-261336e174a7)

**Comment by elliottSlee** [comment]
![Screen Shot 2023-08-01 at 11.16.47 AM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/8ec2e4b5-7937-48bf-b57c-00c2fc723628)
Can we get rid of this margin so that it matches the application?
