### ISSUE TITLE
Update spacing of input elements

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#1802]
The spacing between input elements on all our forms is inconsistent. Let's make the default pattern 8px between label & input (input, textarea, radio, checkbox, date, etc.) and 16px between questions, unless otherwise stated.

Current:
![Screen Shot 2023-06-29 at 12.57.30 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/9e354850-39b6-42b5-9470-cb538ff122cb)

Desired:
![Screen Shot 2023-06-29 at 12.57.11 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/46837ebb-8e85-4b7d-a18b-39a95131f46f)

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1802?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc @VB-at-Bis

**Comment by marcellmueller** [comment]
@elliottSlee I'm not going to die on this hill but I looked into this and I think this will harm the general readability of our forms and make all the forms across our site feel more busy and claustrophobic. All of our form designs were made with this `32px` margin bottom in mind for the widgets. 

It's only a couple of main widgets that this margin was forgotten about such as the checkbox widget groups and textarea. I think it's worth considering just addressing the few widgets with missing margins than to reduce the space between all widgets.

**Comment by elliottSlee** [comment]
Part of the issue we're trying to solve here is that forms with only a small handful of questions are longer than the screen, it shouldn't be this way. A prime example is the project management assessment which only has 5 inputs, but I can only see the top 2.5 when I go there
<img width="1552" alt="Project management assessment screen with too much padding" src="https://github.com/bcgov/CONN-CCBC-portal/assets/93939894/e2e66b73-6b7f-4423-95d3-a5bb93c4f0ec">
Reducing padding on the top of the main container and reducing size of the header are some things that would help. However, the spacing between inputs is quite big and taking up too much room too. I can't find much documentation or research on this, but I found several forms on BC gov sites that have 10, 15, 16, & 20px between input elements and 5 and 8px between label & input. I'd like ours to be similar, hence what's in the card.

**Comment by marcellmueller** [comment]
Looks like it's more of an issue with the size/layout of the application header than the form itself.

**Comment by MarsRomer** [comment]
It's a little bit of everything :)

**Comment by rafasdc** [comment]
Good visual of the changes: https://happo.io/a/336/p/1172/compare/4dcb81975bc0b0fdbd57879ee8a8b9e6fff0f9c8/ab1b320795f67772fae9ec1d37a1a3dc90460506

**Comment by rafasdc** [comment]
Hey @elliottSlee yeah I saw that, it's similar to the project info and the money widgets. They have an extra div to show the error messages:

![image](https://github.com/bcgov/CONN-CCBC-portal/assets/61289255/4fe742be-149f-4a12-8c05-67225f736c6f)

One solution that comes to mind is to change the display logic, right now we have the logic on the error message and not on the div container, so the div will always "render" even if there is no error. We can change it to be on the entire div which will prevent it from displaying.
