### ISSUE TITLE
Silver or gold cluster

### ISSUE THREAD

**Issue by BryanGK** [bcgov/CONN-CCBC-portal#181]
As a stakeholder
I would like to decide on which cluster to use
so that we can know where to deploy our application

**Comment by elliottSlee** [comment]
@BryanGK close this?

**Comment by MarsRomer** [comment]
@BryanGK  do we still need this ticket?

**Comment by BryanGK** [comment]
@MarsRomer @elliottSlee I remember us discussing whether there would be a move to the gold cluster or not. Mars if you consider the matter resolved, then yes close the ticket.

**Comment by MarsRomer** [comment]
@BryanGK thanks for the reminder, I understand now what this ticket is about.  I think at some point it might be worth moving to the gold cluster so I will put this in the product backlog for now

**Comment by elliottSlee** [comment]
@MarsRomer I'm guessing this can be closed?

**Comment by MarsRomer** [comment]
not quite
we may be moving to gold on OpenShift, we haven't done it yet.  Possibly a duplicate ticket though

**Comment by elliottSlee** [comment]
@marcellmueller is this a duplicate of #296?
