### ISSUE TITLE
Read only view of Change request metadata - merge project information and change request

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1828]
As an analyst
I want to see the change request and project information together 
So that it's easy for me to see and get information about the project 

**Description:**

_if needed_  

# Acceptance Criteria
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/2163795d-12af-4a7d-9444-a37a2943bc64)
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/d897d202-8fcc-4b60-959d-5e8a95bc2d0d)

[**Wireframe**](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?type=design&node-id=11918-127943&mode=design&t=4oABshMK52dHeeT6-4)

- [x] Files links only show in the UI if they were uploaded
- [x] Hover over file links shows filename
- [x] If file isn't uploaded, elements still appear in the grid (see Amendment 4 in the wireframes)
- [x] Date is the date change request approved
- [x] Description area is 451x60 (if this needs to change to make it look better, go ahead). `text-overflow: ellipsis;`
- [x] Hover over truncated description shows full description
- [x] Clicking view more slides down the contents using similar animations as forms on this page and rotates chevron to point down (like on GIS upload success page)
- [x] If change request form filename is longer than box width, wrap the text _not the containers_
- [x] Click edit pencil re-opens that form

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1828?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc @VB-at-Bis

**Comment by marcellmueller** [comment]
@elliottSlee can you please clarify acceptance criteria ` Files links only show in the UI if they were uploaded` and `If file isn't uploaded, elements still appear in the grid`, I'm sure I'm missing something but these seem at odds with each other.

**Comment by marcellmueller** [comment]
@elliottSlee hey sorry to bug you again but what is supposed to happen to the metabase link once the `Add amendment` button disappears? I can try hiding it as well but I think it's going to look weird.

**Comment by elliottSlee** [comment]
@marcellmueller the goal is to have all the same files appear in a column so that a user can easily scan up & down to see what's been updated. If a map is not uploaded, the SoW should show up in the same column and not shift into the map's space that's empty
![image](https://github.com/bcgov/CONN-CCBC-portal/assets/93939894/43ed38dc-5afa-4d1a-b52e-c083c454f64a)

**Comment by marcellmueller** [comment]
Oh nice, thanks for clarifying.
