### ISSUE TITLE
Bug: SoW not saving in database

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/CONN-CCBC-portal#1829]
Looks like a bug was introduced with the validation, the SoW is validating but not saving in the database on `Save & Import Data`.

**Comment by MarsRomer** [comment]
the Save and import button is non responsive, not sure if it's related to this ticket 
![image.png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/0bdf0877-0836-42f6-a810-4e89d2e98d77)
