### ISSUE TITLE
Make radio buttons Agile

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1872]
As an analyst
I want the radio buttons labels changed quickly
So that changing business process is easy

**Description:**
Currently a simple update to the label of a radio button requires more effort than the dev team would like to spend, and it takes longer for the business area to update their processes than we would like.   
This ticket is to make small changes such as label wording easy to do.

# Acceptance Criteria:
ANALYST PORTAL:
- [x] Radio button labels can be changed while option selected (existing data does not need migration)
- [x] in metabase the column name/label name stays the same as before, but on the UI the label is updated

## Implementation Details

Note:
We are not anticipating this need for the applicant side so this ticket is for analyst portal only

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1872?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc @VB-at-Bis

**Comment by rafasdc** [comment]
Is this change only for the analyst side of things, or do we also want this for the full application? 

Do we want to make a similar change for all check boxes (multi select) as well?
