### ISSUE TITLE
Research Recovery Best Practices

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1878]
This ticket is to look into recovery best practices that the Platform Services team has recommended and identify and make tickets for gaps in our recovery strategy.

![MicrosoftTeams-image (14).png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/5c17c096-56fa-45c8-95f3-c12d97ecef14)

**Comment by rafasdc** [comment]
This command might be useful `oc get secret -n {project} -o yaml > secrets.yaml`

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1878?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc

**Comment by MarsRomer** [comment]
Decision:  Use Vault

**Comment by rafasdc** [comment]
DB and SSO secrets have been pushed to the Vault for dev, test and prod.
The following following are not stored in OpenShift secrets but on GitHub Env variables: 

- AWS
- Metabase
- TLS

In addition, we should also create a CI step to auto update all the secrets as part of our piepline. Created #2171 and #2172
