### ISSUE TITLE
Remove applicant status from Conditional approval read only

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#1891]
To reduce confusion for analysts if the status in the Conditional Approval section is different from what's above since it's a read-only of the conditional approval form, not of the status table.
#### Current
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/10c25030-1bf3-4625-956b-1e4c27424999)
#### Desired
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/6f7ed5ca-2fab-43b7-9019-003fbb993d3a)
- [x] Remove status that applicant sees from read-only view
- [ ] Move date letter sent to applicant to 3rd column

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1891?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc

**Comment by MarsRomer** [comment]
I don't think it's supposed to show the status: ![image.png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/a09a7e34-9aec-4263-bfd6-4745ba2b37e7)

**Comment by rafasdc** [comment]
I've reproduced it, fix incoming. Sorry about that!
