### ISSUE TITLE
Show RFI attachments in Summary page

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1900]
As an analyst 
I want to be able to see the uploads the applicant did in the summary page
So that all the info I need to assess an application is in one place

**Description:**
Now that the analyst can download the attachments from the application on the summary form, there is a request to also be able to see the RFI attachments in the summary page in the appropriate places.  

# Acceptance Criteria:
[**Wireframe**](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?type=design&node-id=12202-132683&mode=design&t=pTgJ1NRuwszdA7LM-4)
- [x] Analyst can see the RFI uploads by the applicant (and analyst) in the appropriate places on the summary page
- [x] The RFI uploads are visible as hyperlinks to the documents

**RFI replaced a single file upload**
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/c952b7f0-2a13-4d19-8441-9b060c75b6e4)
**Two RFIs for the same single file upload**
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/7c37c92f-bf9b-44a6-8a1f-2810ac6044e3)
**One RFI for multi-file upload**
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/d634a7b9-0b78-4d3f-88de-ef848985bf20)

- [x] Below each file, right aligned, display the date & time the file was uploaded by the applicant or the time entered by the analyst
- [x] Below a group of files from the same RFI, display the RFI #
> Received from RFI-CCBC-000000-0 
- [x] no spacing between filename & "Received from..." or "Original"
- [x] 8px between groups of files
- [x] icon is https://fontawesome.com/icons/star?f=classic&s=solid&sz=2xs **size: 2xs**
- [x] icon only appears on most recent if the section is single file upload
- [x] icon does not appear on any RFI of multi-file uploads
- [x] After an RFI is received, add the word "Original" to the original file(s)
- [x] filename and text below ("Original" or "Received from...") are left-aligned
- [x] icon is to left of the filename and text below
- [ ] indent any rows with**out** a star icon (it may be 14px indent if icon is 12px wide and there's 2px spacing between icon & text

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1900?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc

**Comment by rafasdc** [comment]
Since we changed that all rfi files are now multi file upload the star icon will never show, might be something to discuss.

**Comment by MarsRomer** [comment]
hey @marcellmueller in this one do you know why I wouldn't be able to see this Template 1
![image.png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/c4ce6069-92f5-402a-9733-9324ccaf69c4)
I can see the other supporting document file but not template 1 in the Summary
![image.png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/f8e828e9-9e03-444c-bd58-5de62fa5f956)

**Comment by marcellmueller** [comment]
@MarsRomer Looking into it!

**Comment by marcellmueller** [comment]
Looks like it was due to RFI files not being displayed on any field that had the red error since they were missing files. I totally missed this in development since I was testing on fields that already had files 🤦 Anyways there is a fix incoming!

**Comment by elliottSlee** [comment]
The "RFI" is missing.
In prod it says, "Received from CCBC-000000-0" when it should be "Received from RFI CCBC-000000-0"
