### ISSUE TITLE
Metabase Dashboard - Change prod link to test link

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1901]
**Description:**
To replace the prod link with the test link for metabase dashboard  

# Acceptance Criteria:
Use test link below for GIS dashboard in Test environment after they have uploaded the json file 
https://ccbc-metabase.apps.silver.devops.gov.bc.ca/dashboard/91-gis-data-dashboard-test

![image.png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/a30f7442-ec46-4120-8e85-9680999bf918)

**Comment by MarsRomer** [comment]
It's still taking me to the prod GIS dashboard
![image.png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/da3b8baa-478d-4974-b9bc-4585e1a72315)

**Comment by marcellmueller** [comment]
@MarsRomer this ticket I did was for the embedded link as we discussed

**Comment by MarsRomer** [comment]
Blocked:  we may remove the link and use the metabase imbed instead

**Comment by MarsRomer** [comment]
I am still getting a link to the prod dashboard...
![image.png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/c5f61e3d-55c9-466a-b1bc-1afcedd356d2)
