### ISSUE TITLE
Communities  - add and remove from list

### ISSUE THREAD

**Issue by eazeredo** [bcgov/CONN-CCBC-portal#195]
As an applicant
I need the to be able to add or remove the community names from the list
so that it better reflects my project coverage

Currently the community data is being collected in an xls  ([template 9](https://citz.sp.gov.bc.ca/sites/OCIO/CONN/NWBC/CC/SitePages/Home.aspx?RootFolder=%2Fsites%2FOCIO%2FCONN%2FNWBC%2FCC%2FCCBC%20Program%20Documents%2F01%20C%20Templates%209%2D10&FolderCTID=0x01200004E21CE63380364DB3BA09E02AB82C16&View=%7BE6F214A8%2D542E%2D4A00%2DA7D9%2D286B554B7DAF%7D))

### Acceptance Criteria

- [ ] **Scenario: remove incorrect geographic area**
>Given that a list of geographic names has been created
when an applicant clicks the checkbox beside a name
then it is not saved in the database

- [ ] **Scenario: add geographic area**
>Given that a list of geographic names has been created
when an applicant clicks the button "Add geographic area"
then a new row is added to the table of geographic areas
and an input field appears in the new row under the geographic ID column
and this input field only accepts numbers

- [ ] **Scenario: add geographic area 2**
>Given that an applicant has clicked add geographic area
when they enter a number in the input field
then a list of matching numbers coupled with names will appear in a drop down
when they select one
then the name, type, and zone will be populated in the rest of the row.

### Technical details

- the input field to enter a number only allows geographic ids from the `geoname` table

![image.png](https://images.zenhubusercontent.com/61e8875b1de5eff8f072cd04/b7d0a945-972b-4d38-898f-e39718383bfa)

**Comment by elliottSlee** [comment]
It may be early to have an issue for this since we're still exploring the options. Discussions on Figma, Mural, and meetings with NWBC & data team are still ongoing.

**Comment by MarsRomer** [comment]
@elliottSlee  if we log this user story in the backlog then we can add to it whatever option we end up deciding on.  My priority here is to estimate the effort required for the solution we decide to implement.  I think the use story is true to our understanding just now.

**Comment by elliottSlee** [comment]
Template 9 is also stored in [Research files](https://bcgov.sharepoint.com/:x:/r/teams/04708/Shared%20Documents/Research/Template%209%20-%20Geographic%20Name%20-%20PopulatedDEMO.xlsx?d=wdc70bd76b5824039a59114eff2c79588&csf=1&web=1&e=BMdqss).
_**Note**_ This can change and may not update this file. The source of truth is the one linked in the issue description above.

**Comment by elliottSlee** [comment]
Split into: 
1. uploading map & loading map into UI
2. creating list of communities
