### ISSUE TITLE
Community Progress Reports - View 

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1955]
As an analyst
I want to be able to see the Community Progress Reports that have been uploaded
So that I can download them and know which ones are missing

**Description:**
This ticket is for the user to see the list of reports and be able to download, and edit (#1960 for delete)

# Acceptance Criteria:
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/ce153edf-4255-48c8-bf46-58e1e8666a0e)
[**Wireframe**](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?type=design&node-id=12006-130412&mode=design&t=gNvRO3aRNPDaI2Vw-4)
- [x] After pressing save on the form, this view slides in and the form slides out (same animation as announcements & the funding agreement forms)
- [x] Ordered by Due Date, newest on top & oldest on bottom
- [x] Year is aligned
- [x] Each report shows the quarter that it was for, which is derived from Due Date
April 1 - June 30 = Q1
July 1 - September 30 = Q2
October 1 - December 31 = Q3
January 1 - March 31 = Q4
- [x] Click on "Community Progress Report" link in the view begins the download of the original file
- [x] When user clicks the edit on the view page - the add form opens with form data x

## Implementation Details
Edit functionality will need a create mutation that archives the previous form data.

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1955?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc

**Comment by marcellmueller** [comment]
@elliottSlee hey can you please clarify the acceptance criteria for the dates here. I am confused about getting the year correct ie `23-24` or `24-25` from the due date.

**Comment by elliottSlee** [comment]
@marcellmueller these follow fiscal year which begins Apr 1 and ends Mar 31st. 
In our current fiscal year, since we're August, it's `Q2 (Jul-Sep) 2023-2024`.
Does that help?

**Comment by marcellmueller** [comment]
@elliottSlee I think so, seems like we are just adding a year to whatever they pick. So if they pick `August 8, 2023` that is `Q2 2023-24`, and if they pick `August 8th 2024` that is `Q2 2024-25` unless I'm missing a scenario.

Also, I think we are going to need a form validation ticket unless I missed that in one of them. The validation ticket only covers excel validation though I assume we will want at least the due date to be required for this feature I'm working on. Right now nothing is required and the form will save with no fields filled.

**Comment by elliottSlee** [comment]
@marcellmueller  that's correct. There aren't any other scenarios I can think of.

**Comment by MarsRomer** [comment]
Looks great!
