### ISSUE TITLE
Community Progress Report - Import Spinner and success toast

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1959]
As an analyst 
I want to see feedback that the import is working
So that I can be confident that the changes I made are being implemented

**Description:**
This ticket is to implement the Spinner animation when the Save and Import Data button is pressed and a success toast to appear when it completes.

# Acceptance Criteria:
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/cc35be35-2b91-4082-84d6-d4bf188d3554)
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/ef169e50-3581-4e84-a020-4e00cf8dcb49)
[**Wireframe**](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?type=design&node-id=12006-130412&mode=design&t=gNvRO3aRNPDaI2Vw-4)
- [x] When import is occurring, show spinner (same as the one used for SOW)
- [x] When import is occurring & spinner is showing, save & cancel buttons are disabled
- [x] When import is complete, show success toast (similar to the one used for SOW)
- [x] Success toast slides out after 5 seconds
- [x] If import is not successful, stop the spinner, and  do not show success toast

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1959?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc

**Comment by rafasdc** [comment]
We won't know if the import is successful or not until it has finished verifying, should we update this acceptance criteria "If import is not successful do not show spinner or success toast" to be "If import is not successful do not show success toast and stop spinner"

**Comment by MarsRomer** [comment]
updated

**Comment by MarsRomer** [comment]
Works well!
