### ISSUE TITLE
Community Progress Report - Delete

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1960]
As an analyst
I want to be able to delete a Community Progress Report row
So that I can correct for my mistakes

**Description:**

This ticket is to allow the user to delete a CPR record from the view

# Acceptance Criteria:
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/c0dbc09e-b956-4210-b80e-5ad2217dc17d)
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/8e0f3154-058f-4154-9833-ed0b17435fa0)
[**Wireframe**](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?type=design&node-id=12006-130412&mode=design&t=gNvRO3aRNPDaI2Vw-4)
- [x] When user clicks on the red x on the view page for the CPR, user sees Modal asking for confirmation
- [x] When user clicks 'Yes Delete' then modal disappears and the row with the CPR is deleted (soft delete in backend)
- [x] All data that were imported from the Excel file to the database are archived
- [x] When user clicks 'No Keep' then the modal disappears and the row with the CPR stays the same

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1960?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc

**Comment by marcellmueller** [comment]
@elliottSlee @Alifath57 

I went to start this ticket but realized we have nothing linking the community progress report excel data to the form data unlike the SoW which has the original SoW and then the amendment numbers.

Is just a generic `id` linking the data okay or should we link them by the due date? What would we like to see in metabase?

**Comment by elliottSlee** [comment]
@marcellmueller I think an `id` would work fine. Maybe ask @Alifath57 ?

**Comment by Alifath57** [comment]
@marcellmueller I think a generic id linking the data is ok.
