### ISSUE TITLE
Increase pgBackRest resources

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/CONN-CCBC-portal#1977]
`pgBackRest` containers are regularly triggering sysdig CPU throttling warnings, we should increase the cpu for these containers to mitigate this.

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1977?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc

**Comment by marcellmueller** [comment]
@rafasdc I think I am going to close this as this issue was resolved once we restarted that problematic pod in dev. As far as I can tell from the metrics dashboard this is running well within it's limits. What do you think?

**Comment by rafasdc** [comment]
Sounds good!
