### ISSUE TITLE
Keep spacing consistent between errors/helper labels

### ISSUE THREAD

**Issue by rafasdc** [bcgov/CONN-CCBC-portal#1980]
<s>Right now the helper text and error messages will take space on the forms even though they might have no content which adds extra space in between inputs. 

- [ ] Make helper/error text not render if empty on applicable widgets

</s>

- [ ] Keep the spacing between helper and error messages consistent between existing and non existing errors/helper texts.

**Comment by MarsRomer** [comment]
duplicate of #736

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1980?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc
