### ISSUE TITLE
Add --no-verify to git commit when running the release CI/CD

### ISSUE THREAD

**Issue by AntBush** [bcgov/CONN-CCBC-portal#1981]
Right now the release chore fails every once in a while, a simple fix is to add the --no-verify for the commit to prevent prettier from interrupting our release

Business value: Quicker release and simpler process for the developers to initiate - saving time and de-risking quick fixes

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1981?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc
