### ISSUE TITLE
Move character limits position for 2 fields

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/CONN-CCBC-portal#199]
**Move the character limits information from the Label to below the field (as all other fields)**

Under the "Organization Profile" page
- [ ] Please provide a short description of the Indigenous entity (maximum 75 characters)
- [ ] Provide an overview of the organization...(maximum 3,500 characters)
#
![image.png](https://images.zenhubusercontent.com/606c9d37b7ff542cfdb25c53/bab3b617-29b7-4349-b3b0-273cb79d078b)

**Comment by MarsRomer** [comment]
Looks good, just one request to adjust the spacing on the form to be consistent:
![image.png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/c62418c0-304e-4d33-9092-16f233d45346)

**Comment by rafasdc** [comment]
Thanks, I'll create a ticket for it. This is something that happens everywhere as the helper text and possible error messages still take space on the form even though there might not be anything to show. We can change the logic to only render them when there is actual helper text and/or error messages.
