### ISSUE TITLE
Reduce bcgov backup storage request to allow restore

### ISSUE THREAD

**Issue by rafasdc** [bcgov/CONN-CCBC-portal#1995]
Description:
Business Risk:  Restoring backups will not be successful unless we complete this task 

As per https://docs.developer.gov.bc.ca/netapp-backup-restore/ "If you need to restore your PV, you will need an existing nfs-file-backupPV on the same cluster to use as a destination for the restored data. If you don't have one already, create a new one. If you have an existing PV that you want to use as your destination, you should consider creating a special folder to use as the destination for your restored data - that way, you don't risk overwriting anything by accident." 

Which means that we would need to create a new `netapp-backup-restore` PVC in case we need a restore, currently we are requesting the max available but are only using < 2Gi, we should recreate this volume with way less storage to leave quota in case of a restore.

AC 

- [x] [DEV] BCGOV backup storage used is less than maximum allowed, leaving enough space for a restore.
- [x] [TEST] BCGOV backup storage used is less than maximum allowed, leaving enough space for a restore.
- [x] [PROD] BCGOV backup storage used is less than maximum allowed, leaving enough space for a restore.

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1995?planning-poker) with Zenhub @AntBush @rafasdc

**Comment by rafasdc** [comment]
Did some research on how to approach this ticket. 

For dev and test: 
- We can reduce the pgbackrest requested storage, but this will require us to **delete** the current PVC, which means **we will lose all current backups**. Dev shouldn't matter, do we care about backups in test? 
- We can immediately manually run a full backup on test if we want to.

For prod: 
- Easy solution is to take the same approach as dev and test, but immediately run a full manual backup. 
- We can take the easy solution if we don't need the ability to restore to a point in time, right now we are currently retaining backups for the last 30 days. 
- Once we delete the PVC to resize, it will technically still be recoverable through the BCGOV restore process of the PVC. 

Will need further discussion to proceed on this one.
