### ISSUE TITLE
Edit the empty dashboard's text

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/CONN-CCBC-portal#200]
Iteration on the dashboard's empty state. The text has been iterated to:
"Start a new application, applications can be saved and edited until the intake closes on [Month, date, year]

This sets the expectation that applications do not need to be finished in 1 go and a reminder of when the intake closes

The button and text placement have been swapped so that the order of the page is page title, page description, button, to be consistent with all of the other pages. 
![image.png](https://images.zenhubusercontent.com/61e8875b1de5eff8f072cd04/d50ce564-0238-4cd3-a3ba-87ad086c4b98)

**Comment by zoeyli-46** [comment]
@MarsRomer Would it be possible to move this improvement ticket into one of the sprints?

**Comment by MarsRomer** [comment]
@zoeyli-46 yes lets add it to the dashboard ticket
