### ISSUE TITLE
Claims - Add

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#2002]
As an analyst
I want to enter the claim & progress report information & file
So that we can have it in the portal with all other quarterly reports

**Description:**
This is for the form of entering & uploading the claim & progress report Excel file

# Acceptance Criteria:
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/ab30a05d-f51b-4726-b172-e5397f6a4a41)
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/89262efe-0932-4bd6-ab09-abb875aee094)
[**Wireframe**](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?type=design&node-id=12009-130547&mode=design&t=awLlJr6x7ZLrfYN8-4)

- [x] Click add claim & progress report, animation similar to announcements & funding agreement forms where this slides up and the form slides down
- [ ] Claim period from & to dates are required
- [x] Analyst can upload the report - for this ticket the upload only saves the file, does not import the data - not mandatory. (Note: saves it on the file widget and form data, but hitting submit will go nowhere as there is no backend or DB table)
- [x] When uploading the file, the spinner shows
- [x] Click cancel and the form closes, nothing is saved

**Comment by elliottSlee** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/2002?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc @VB-at-Bis

**Comment by MarsRomer** [comment]
Looks good, the only thing I noticed is that the to and from dates are not required.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbEpWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--dbc4f56275141dc7f16a3de1bd558d02f1d37806/image.png)

**Comment by marcellmueller** [comment]
@MarsRomer I'm confused by this comment. We closed a ticket on Claims form validation:
https://github.com/bcgov/CONN-CCBC-portal/issues/2147

Also we have a ticket in progress to remove these fields altogether and pull that data from the excel:
https://github.com/bcgov/CONN-CCBC-portal/issues/2163

Anyways I've unchecked that acceptance criteria as it probably should have been checked but I am not sure of what the action here is supposed to be.

**Comment by MarsRomer** [comment]
Thanks for unchecking the AC, that's all that needs to be done here
