### ISSUE TITLE
Claims - Import data from Excel file

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#2005]
As an analyst
I want the claims & progress report data from the excel to be imported into the database
So that I don't have to spend valuable time typing it in

[**Excel file with fields highlighted**](https://bcgov.sharepoint.com/:x:/r/teams/04708-ScrumTeam/Shared%20Documents/Scrum%20Team/CCBC%20Claim%20Request%20Form%20%26%20Progress%20Report%20-%20field%20identified.xlsx?d=wd44c26db6e964a958cde2d65371b9e48&csf=1&web=1&e=SkP6w8)
Fields are only on _Claim Request Form_ and _Progress Report_ tabs

# Acceptance Criteria:

- [x] Excel file is imported and ingested into the database
- [x] When excel file is uploaded and validation is successful, then the Save button becomes the 'Save and Import data' button 
- [x] If the excel file is subsequently removed, the Save and Import Data button becomes the 'Save' button again
- [x] When the 'Import and Save' button is clicked, it imports data from the excel file (spinner and success toast are in another ticket)

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/2005?planning-poker) with Zenhub @marcellmueller @VB-at-Bis
