### ISSUE TITLE
Claim - Import Spinner and success toast

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#2007]
As an analyst 
I want to see feedback that the import is working
So that I can be confident that the changes I made are being implemented

**Description:**
This ticket is to implement the Spinner animation when the Save and Import Data button is pressed and a success toast to appear when it completes.

# Acceptance Criteria:
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/a36f0d8e-660f-489a-afa8-8a6b930fa0bd)
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/aaff040f-9e17-4c77-82eb-3105e66e2a65)
[**Wireframe**](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?type=design&node-id=12006-130412&mode=design&t=gNvRO3aRNPDaI2Vw-4)
- [x] When import is occurring, show spinner (same as the one used for SOW)
- [x] When import is occurring & spinner is showing, save & cancel buttons are disabled
- [x] When import is complete, show success toast (similar to the one used for SOW)
- [x] Success toast slides out after 5 seconds
- [ ] If validation errors occur, do not show spinner or success toast

**Comment by elliottSlee** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/2007?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc @VB-at-Bis

**Comment by marcellmueller** [comment]
No PR attached to this as it was handled in #2003

**Comment by marcellmueller** [comment]
I have copied the `If validation errors occur, do not show spinner or success toast` acceptance criteria to #2006 to verify that it is working once the validation is completed.
