### ISSUE TITLE
Claims - Show current payment & cumulative amounts

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#2018]
As a financial analyst
I want to see the current payment & cumulative amounts on the main page
So that I can quickly see them.

# Acceptance Criteria:
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/743efbed-ef0a-4bc8-aac0-d6312d411f87)
- [ ] Acceptance Criteria

**Comment by MarsRomer** [comment]
Not required according to business
