### ISSUE TITLE
RFI attachments date

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/CONN-CCBC-portal#2024]
As discussed in standup getting the date for the RFI attachments should be it's own ticket. Looks like we need a big computed column to accomplish this.

Acceptance criteria
- [x] computed column to extract uuid's from an rfi and return a list of the associated attachments.

**Comment by MarsRomer** [comment]
Hey @marcellmueller is there any acceptance criteria for this ticket?

**Comment by marcellmueller** [comment]
> Hey @marcellmueller is there any acceptance criteria for this ticket?

I don't think there is anything for you to review here. This was backend stuff for rfi file dates on the application page and I believe in the uniting rfi files ticket though I added a small acceptance criteria for records sake.
