### ISSUE TITLE
Task:  Clean out SOW data

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#2084]
Description:
There is some non-numerical data in the SOW Tab7 that is causing metabase to not display numbers correctly.   This ticket is to have SOW show the currency columns with $ signs.   Possibly also discuss how to prevent this in the future.  

Solution is to delete  all uploaded SOWs as well as the related SOW form data.

AC:
- [ ] All SOW data and SOW form data is deleted from TEST database

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc2tCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--dc9b83a7cbc5a821aa18ca220b6d99dc463dd9b0/image.png)

**Comment by AntBush** [comment]
Data Cleared out August 15 ~10:30AM.
