### ISSUE TITLE
History page e2e tests

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/CONN-CCBC-portal#2088]
We don't have an e2e test for our history page, we should catch up on that. Things to test in the history page:

- [x] RFI
- [x] Assessments
- [x] Editing an application
- [x] Conditional Approval
- [x] Announcements
- [x] Sow/Change request
- [ ] ...?

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/2088?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc @VB-at-Bis
