### ISSUE TITLE
Allow delete of uploaded and imported excel data

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#2089]
As an analyst
I want to be able to delete a previously uploaded and imported excel file data from the database
so that if I uploaded the wrong file by mistake I can remove it easily

Description:
For excel files that are uploaded through the portal and their data have been scraped into our database, we still want to give the analyst the option to be able to go back and delete the excel file from the portal and soft delete the data that was imported into our database.

Acceptance Criteria:
- [x] When user clicks Save after deleting a previously imported excel file, soft delete the file and the imported data from our database for Sow/Change request
- [x]  When user clicks Save after deleting a previously imported excel file, soft delete the file and the imported data from our database for Community Progress Report
- [x] If user clicks cancel, do not soft delete the file or the imported data

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/2089?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc

**Comment by AntBush** [comment]
I wasn't able to complete the last AC, because there isn't an easy way to determine between an uploaded file that was then removed vs removing a file that is already there. Currently, archived files can still be removed, but they will still be listed as archived in our DB.
