### ISSUE TITLE
Display Date RFI file Received on RFI upload page

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#2090]
As an analyst 
I want to see the date that the file was received on the RFI upload page
so that I can validate I put in the correct date and it was stored in the db

Description:
When the analyst uploads the RFI file, they use the date picker to assign the date the file was received, use this date to display next to the file name after they have uploaded the file.

![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/c5649c21-aceb-4c6f-8407-999a33454ca9)

AC:
- [x] on RFI upload page show the Date Received next to the file name

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/2090?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc

**Comment by AntBush** [comment]
I think the screen design here is for the review page @elliottSlee

**Comment by elliottSlee** [comment]
@AntBush fixed. Thanks for the flag.

**Comment by rafasdc** [comment]
Note: date received will be shown below the file name due to possibly extra long file names
