### ISSUE TITLE
Investigate increasing rate limit for excel api routes

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/CONN-CCBC-portal#2092]
We should investigate increasing our rate limiting for uploading excel documents. Currently if you upload about 3 in a row you will trigger the rate limit, causing the spinner to stall. We need to find a nice balance that won't overload or crash our pods but that can allow a user to submit multiple files in a row.

- [x] monitor resources used while uploading excel in openshift
- [x] adjust rate limit if our resources allow

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/2092?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc

**Comment by marcellmueller** [comment]
@MarsRomer Not sure if you wanted to review/test this you can now upload 3 (or more) excel files per minute in a row without the spinner timing out.

**Comment by MarsRomer** [comment]
I tried, but the uploads are so quick I can't keep up! hahaha
