### ISSUE TITLE
UI Wording Updates

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#214]
As the wording of fields in the application portal changes in Figma from what's been implemented, we can track it here so that no changes are lost.

Please specify the page, what it currently is, and what it should be changed to.
# 
**Multiple pages**
- [x] Remove oxford commas, remove any commas before the word "and"
          - ", and" should be changed to " and"
#
**Landing page**
- [x] Change "To begin the application, please log in with BCeID Business. If you do not have BCeID Business, please use your BCeID Basic." to what's on [Figma](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=2909%3A12234)
#
**Project information**
- [x] Change **from** "Geographic project area description. Describe the geographic location of the project area (i.e., include the closest communities and the general area which the project will target)." **to** "Describe the geographic location of the project area (i.e., include the closest communities and the general area which the project will target)."
#
**Existing network coverage**
- [x] Change **from** "The applicant intends to make reasonable efforts to make its passive infrastructure available for use by other broadband operators to expand and improve coverage in Canada?" **to** "Does the applicant intend to make reasonable efforts to make its passive infrastructure available for use by other broadband operators to expand and improve coverage in Canada?"
#
**Budget Details page**
- [x] reflect the new wording as per screen capture below
![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/628de955-4e28-4c8f-b271-0f25dae58753)
#
**Project funding page**
- [x] Change **from** "Amount requested under Canadian Infrastructure Bank [year]" **to** Funding from Canadian Infrastructure Bank [year]
- [x] Change **from** "Total amount requested under Canadian Infrastructure Bank" **to** Total funding from Canadian Infrastructure Bank
#
**Technological solution page**
- [x] Change the colon ( : ) to a period in "Please specify the backbone technology type (check all that apply)"
- [x] Change **from** "Please specify the last mile technology type (check all that apply)." **to** "Please specify the last mile technology type (check all that apply). If you select fixed wireless, you must complete Template 7."
#
**Benefits page**
- [x] Change first question to:

> Sustainability. Please summarize the benefits that the project will bring to the targeted areas. Describe the benefits and sustainability of the project in terms of:
> - Social and economic benefits
> - Improvements to community connectivity
> - Facilitation of commercial or industrial development
> - Improvement of public services or social programs delivery
> - Improvement of small businesses
> - Enhancement of entrepreneurship capacity
> - The Applicant organization’s corporate social responsibility policy and philanthropic practices, including how the organization promotes reconciliation, gender equality and diversity or how your organization gives back to the community.

>To support claims of social and economic benefits, applicants should provide letters of support and the accompanying Template 6: Community and Rural Development Benefits at the uploads section.

- [x] Household question: Change to: "Final number of Eligible Households targeted by this proposal. This value should match cell F141 in Template 1."
#
**Organization profile page**
- [x] Change **from** "In your own words describe your organization type" **to** "Please specify your organization type"
- [x] Add period at end of the question "Provide an overview of the organization..."

- [x] Change **from** "Is this applicant organization an Indigenous entity?" **to** "Is this applicant organization an Indigenous identity?"
- [x] Add the following ([wireframe](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=1059%3A6234) if needed):
>An Indigenous identity may include: 
>- A profit or non-profit organization run by and for First Nations, Metis, or Inuit peoples; 
>- A band council within the meaning of section 2 of the Indian Act; 
>- An Indigenous government authority established by a Self-Government Agreement or a Comprehensive Land Claim Agreement
#
**Authorized contact**
- [x] Change from "Given name of person who will be the authorized contact" **to** Given name
- [x] Change from "Family name of person who will be the authorized contact" **to** Family name
- [x] Remove "Contact this person for communication regarding this application" checkbox
- [x] Change the page description **from** "Provide the contact information for the authorized contact" **to** "The authorized contact should have full authority to bind said organization through funding agreements. One primary contact must be identified for applications submitted on behalf of multiple organizations."
#
**Alternate contact**
- [x] Change from "Given name of person who will be the alternate contact" **to** Given name
- [x] Change from "Family name of person who will be the alternate contact" **to** Family name
- [x] Remove "Contact this person for communication regarding this application" checkbox
- [x] Change the page description **from** "Provide the contact information for the alternate contact" **to** "Provide the contact information for an alternate contact in the event that the primary contact becomes unreachable. If there is no alternate contact, leave this section blank."
#
**Review page**
- [x] Change **from** "By checking this box, you acknowledge that there are incomplete fields and incomplete applications may not be assessed. If the incomplete fields are not applicable to you, please check the box and continue." **to** "By checking this box, you acknowledge that there are incomplete fields and incomplete applications may not be assessed. If the incomplete fields are not applicable to you, please check the box and continue to the declarations page."

**Comment by elliottSlee** [comment]
I just noticed that this card says to change Applicant to lowercase but #281 - Uppercase the defined terms says the opposite. @zoeyli-46 do you remember why?
@MarsRomer please advise.

**Comment by MarsRomer** [comment]
@elliottSlee  @zoeyli-46  I don't remember why we said to lowercase it, if it's a defined term then I think it should be upper case.  good catch!

**Comment by elliottSlee** [comment]
Removed

**Comment by MarsRomer** [comment]
On the benefits page, missed one bullet "Improvement of small businesses"
On benefits page, the text should be changed to "Household question: Change to: "Final number of Eligible Households targeted by this proposal. This value should match cell F141 in Template 1."
