### ISSUE TITLE
Update Cypress to version 13

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/CONN-CCBC-portal#2143]
Cypress version 13 has some pretty major updates including a fix for the infamous detached DOM errors. There are some breaking changes so there is a bit of extra work involved though it looks like the [CAS-CIF](https://github.com/bcgov/cas-cif) team is using it if we need a reference.

Business Risk:  not updating will mean we end to end testing will not work in the future.

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/2143?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc
