### ISSUE TITLE
Add link to Metabase CPR

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#2159]
As an analyst
I want to be able to open the CPR report in metabase
So that I can see the CPR data in a tabular format 

# Acceptance Criteria:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdGREIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--aa01375dc1bbf96d77f91e2e82e4f8d528f36014/image.png)
[**Wireframe**](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?type=design&node-id=11941-127184&mode=design&t=DdmsS3R2nQmQqx4S-4)

- [x] Link for _test_ https://ccbc-metabase.apps.silver.devops.gov.bc.ca/dashboard/94-community-progress-report works in test
- [x] Link for prod  https://ccbc-metabase.apps.silver.devops.gov.bc.ca/dashboard/95-community-progress-report-prod works in prod

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/2159?planning-poker) with Zenhub @marcellmueller @VB-at-Bis

**Comment by Alifath57** [comment]
The prod CPR link is: 
https://ccbc-metabase.apps.silver.devops.gov.bc.ca/dashboard/95-community-progress-report-prod

**Comment by MarsRomer** [comment]
thanks @Alifath57
