### ISSUE TITLE
Upload Master Spreadsheet

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#2160]
As an analyst
I want the master spreadsheet data in the portal db
So that I can report out on the CBC and CCBC programs together

**Description:**
There is a need for the division to be able to tally numbers and for CBC and CCBC together.  In order to make this work easier, it would be helpful for the data for both programs to be accessible in one system in a way that enables easy sorting, filtering, adding, counting.  

# Acceptance Criteria:
- [x] Data from master spreadsheet ('CBC Projects' tab) can be imported into the CCBC db using url 
test.connectingcommunitiesbc.ca/api/sharepoint/cbc-project
- [x] Column names in our db from master spreadsheet will be abbreviated or shortened as required 
- [x] Date formats are validated upon upload - dates not formatted correctly are skipped
- [x] Should be able to track changes (diffing) 
<S>- [ ] Growthbook flag so we can turn it off in prod</S>
- [x] Includes a column for sharepoint modified timestamp 

# Design:
<S>Upload page looks similar to this but with appropriate changes to wording in the Admin tab create a new tab called 'Master spreadsheet'
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcXA2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--74490739004e18a4411a6f27e6a05d4c54a0b16d/image.png)
</S>

Implementation Note:
- [x] Use insert instead of update
- [x] Enable auditing and history

Data Dictionary Here (sept 15) version:  
https://bcgov.sharepoint.com/:w:/r/teams/04708-ScrumTeam/Shared%20Documents/Scrum%20Team/Data%20Dictionary%20-%20Master%20Spreadsheet_Sept15.docx?d=wa925450db348491ea19f0cc4956d8785&csf=1&web=1&e=UbCWwJ

TEST version of Master Spreadsheet:
https://bcgov.sharepoint.com/:x:/r/teams/04708-ScrumTeam/Shared%20Documents/Scrum%20Team/Connecting%20BC%20Program_Approved%20Projects%20(restructured)_Sept15_TEST_DATA.xlsx?d=w2acb6c456920461b8b32f9ee03f7362f&csf=1&web=1&e=Mc5RIB

Real Master Spreadsheet (sept 15 version)
https://bcgov.sharepoint.com/:x:/r/teams/04708-ScrumTeam/Shared%20Documents/Scrum%20Team/Connecting%20BC%20Program_Approved%20Projects%20(restructured)_Sept15.xlsx?d=w7e7638d816bf4d11ba8618cc29f4e7ab&csf=1&web=1&e=fAAsRC

The master spreadsheet will reside here:
https://bcgov.sharepoint.com/:x:/r/sites/CITZ-CONN_NETWORKBC_COM/Shared%20Documents/CBC%20Program%20Data/CBC%20Program%20Data.xlsx?d=w21ab4960b7c24dfa8876dfb1599245c0&csf=1&web=1&e=tbRI0b

## Implementation Details
Table in db to be named 'cbc_project'

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/2160?planning-poker) with Zenhub @marcellmueller @rafasdc @VB-at-Bis

**Comment by marcellmueller** [comment]
@elliottSlee did you say you had some designs for a button you could put in this ticket?

**Comment by marcellmueller** [comment]
oh yeah we said that would be in a separate ticket and that Mars would use the URL, sorry I forgot

**Comment by MarsRomer** [comment]
Yeah no need for a UI for this ticket
