### ISSUE TITLE
Analyst can withdraw applications

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#2164]
As an analyst 
I want to withdraw an application 
So that I have control over the application status

**Description:**
This ticket is to allow the analyst to withdraw an application for the applicant

# Acceptance Criteria:
- [x] Analyst can set internal and external status to withdrawn for any application that DOES NOT have the status of  Approved, or Completed
- [x] When analyst changes the internal and external status to withdrawn, display modal asking for reason for change each time
- [x] Analyst must change the internal status to withdrawn before they can change the external status to withdrawn
- [x] Applicant dashboard shows the application with 'Withdrawn' status
<S>- [ ] Update status diagram to include "Withdrawn" as a status</S> 
- [x] Applicant view of the application is all fields disabled
- [x] If it's withdrawn, analyst can still change status
- [x] Withdrawn option is above 'Closed' in dropdown
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcnBzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e4d22fecf29cf80120486132d28c1922ac6c7e55/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc0JzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e804a43918c69a7cd423421a32c4f185ef157a23/image.png)

**Comment by elliottSlee** [comment]
Why can't they change it when Conditionally Approved? If an applicant chooses to withdraw an application that's been conditionally approved, it should be withdrawn, not closed.

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/2164?planning-poker) with Zenhub @marcellmueller @rafasdc @VB-at-Bis
