### ISSUE TITLE
Community Progress Report - erroneous warning 

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#2167]
**Describe the bug**
I get a warning that a community progress report has already been created for a quarter even though there isn't.  Could be related to #2168

**To Reproduce**
1. Go to CCBC-010002 in test 
2. Click on edit pencil next to either of the two community progress reports
3. See error where it tells you a community progress report is already created

**Expected behaviour**
I would expect to see this error only when there truly is a community progress report already uploaded for that quarter

**Screenshots**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBblJOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f5aaf0e3f7f61abb47589f0308a09f279468b0df/image.png)

**Logs/tracebacks**

**Additional context**

**Comment by marcellmueller** [comment]
The bug here is just that the validation is checking all quarters including the one being edited, so we need to ignore the current community progress report if it's an edit.
