### ISSUE TITLE
Community Progress Report - reports disappear when adding one

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#2168]
**Describe the bug**
When I add a community progress report, it hides other reports added previously.  This could be the cause of bug #2167

**To Reproduce**
1. Go to ccbc-010002 where there are two community progress reports
2. Click on 'Add community progress report'
3. Scroll choose a date for which we don't already have one displayed
4. Click Save and notice that you can only still only see 2, one of them has disappeared.  
**Expected behaviour**
All submitted (undeleted) community progress reports show

**Screenshots**

**Logs/tracebacks**

**Additional context**

**Comment by marcellmueller** [comment]
I can't reproduce this, maybe you can show me at standup tomorrow thanks.

**Comment by MarsRomer** [comment]
I can't reproduce it either, but it happened to me multiple times yesterday...

**Comment by MarsRomer** [comment]
fixed via #2167
