### ISSUE TITLE
Input constraints & warning messages

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#217]
### User Story
As an applicant
I want the input fields to detect whether the information I enter is formatted correctly and give me guidance on how to input the correct information
so that I don't make preventable errors.

### Description
Errors should be formatted by the input box changing to a 2px red box (#E71F1F) and red warning message (#E71F1F) per the [BC Design System](https://developer.gov.bc.ca/Forms).

### Acceptance Criteria
<details>
  <summary><strong>Budget details page</strong></summary>

<br>

**Total eligible costs & Total project cost**
- [x] Must be greater than or equal to 0

</details>
<br/>

<details>
  <summary><strong>Project funding page</strong></summary>

<br>

**All input fields**
- [x] Must be greater than or equal to 0

</details>
<br/>

<details>
  <summary><strong>Other funding sources page</strong></summary>

<br>

**Amount requested under funding partner** (input fields for the next 5 years and total)
- [x] Must be greater than or equal to 0

</details>
<br/>

<details>
  <summary><strong>Technological solution page</strong></summary>

<br>

</details>
<br/>

<details>
  <summary><strong>Benefits</strong></summary>

<br>

**Final number of Eligible Households targeted by this proposal**
- [x] Must be greater than 0

</details>
<br/>

<details>
  <summary><strong>Project planning and management page</strong></summary>

<br>

- **<s>Start date</s>**
    - [ ] <s>validation: later than today</s>
    - [ ] <s>no error message but enforce through calendar date selectability</s>
#
- **<s>Completion date</s>**
    - [ ] <s>validation: before March 31, 2027 (not a hard error that prevents them from continuing)</s>
    - [ ] <s>error message: Start date should be before March 31, 2027 (TBD)</s>
#
- **relationship between the project manager and the Applicant**
    - [x] maxlength="2500" (yes, this is shorter)
</details>
<br/>

<details>
  <summary><strong>Estimated project employment</strong></summary>

<br>

**Current employment**
- [x] Must be greater than or equal to 0

**Hours of employment per week** 
- [x] Must be greater than or equal to 0

**Average months per year of full time employment that will be created**
- [x] Must be greater than or equal to 0
</details>
<br>

<details>
  <summary><strong>Organization contact information</strong></summary>

<br>

**Email**
- [x] Validation: is an email
- [x] Error message: Please enter a valid email address

</details>
<br>

<details>
  <summary><strong>Authorized & alternate contact</strong></summary>

<br>

**Email**
- [x] Validation: is an email
- [x] Error message: Please enter a valid email address

</details>

### Source of Truth for Questions
Full information for input fields such as max length for text fields and the contents of drop-downs can be found in the Research channel Files/[DataMapping.xlsx](https://bcgov.sharepoint.com/:x:/r/teams/04708/Shared%20Documents/Research/DataMapping.xlsx?d=w5224cb99a79b48008b9105279418b6e3&csf=1&web=1&e=k1VR5C)
#

**Comment by eazeredo** [comment]
@marcellmueller and @AntBush, is this card clear enough to be developed? (cc @elliottSlee )

**Comment by marcellmueller** [comment]
@eazeredo Yes I think so though it is probably massive card and should be broken down into smaller parts.

**Comment by eazeredo** [comment]
@marcellmueller is it better to organize by validation type or by page/form section?

**Comment by marcellmueller** [comment]
Validation types maybe something like:

-input field type validations (eg number, currency, phone etc)
-date validations
-file upload validations

As well as a card to run the validations.

**Comment by eazeredo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/217?planning-poker) with ZenHub @AntBush @marcellmueller @wenzowski

**Comment by elliottSlee** [comment]
Breakdown to (1) email, number, telephone and (2) actual validation constraints (e.g., date constraints, at least 1 checkbox selected, etc)

**Comment by MarsRomer** [comment]
This should be max 2500 characters which it seems to enforce but the text should refelect that
![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/334e7552-bb25-45b9-ba7f-e7d7d4f33d17)
