### ISSUE TITLE
Project Description 

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#2170]
As an analyst
I want to add and see a brief project description
So that our organization has a 1-2 sentence summary of each project

**Description:**
This ticket is to add the project description that NWBC comes up with 

# Acceptance Criteria:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdlY2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e558e2cff75e35f3a0eece06d4f8ac99981e0e7c/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdmQ2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--58600824fa94edc1d51b1ba7bb43b861576abcc8/image.png)
- [x] field is inline editing
- [x] max 320 characters
- [x] character count changes in real-time
- [x] max height of read only is 3 lines
- [x] Below small screen breakpoint, truncate text.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaGQ3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c7680b618084bd40f8e911e2c636e238456c090e/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaGg3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--40db68dbf29e46bef2878c591433fbcea231e1a6/image.png)

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/2170?planning-poker) with Zenhub @marcellmueller @rafasdc @VB-at-Bis

**Comment by elliottSlee** [comment]
@marcellmueller nice touch with the expanding animation. Looks great!

**Comment by marcellmueller** [comment]
> @marcellmueller nice touch with the expanding animation. Looks great!

Thanks! I had a lot of fun with that ticket.

**Comment by MarsRomer** [comment]
I typed in the description then clicked away, the text disappeared
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODhoQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bf5654ab5b95d755a8d871ef4c9959ee1dec9477/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUFoQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--efd631322d6b10d2fbe65063c3be75cb25a96c71/image.png)

When I click in the box I see my text again, but there it goes away every time I click away

**Comment by MarsRomer** [comment]
I typed in the description then clicked away, the text disappeared
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODhoQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bf5654ab5b95d755a8d871ef4c9959ee1dec9477/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUFoQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--efd631322d6b10d2fbe65063c3be75cb25a96c71/image.png)

When I click in the box I see my text again, but there it goes away every time I click away

**Comment by marcellmueller** [comment]
You need to press enter to save

**Comment by MarsRomer** [comment]
I did but nothing happened

**Comment by MarsRomer** [comment]
works nicely now!
