### ISSUE TITLE
New GH Actions step for secrets backup

### ISSUE THREAD

**Issue by rafasdc** [bcgov/CONN-CCBC-portal#2172]
A new step that pushes all the GitHub environment variables over to vault to keep them up to date automatically.

Business Risk:  Completing this ticket will mitigate the risk of losing secrets altogether if they are lost on GitHub.  

AC
- [ ] Save AWS, Metabase and TLS secrets to vault as backup, same as DB and SSO secrets.
- [ ] Rest of the GH env variables are also backed up in the Vault

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/2172?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc
