### ISSUE TITLE
Spike: Removing questions from application form

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#2182]
This ticket is to research the feasibility and effort required to complete #400

AC 
- [x] Refined and estimated ticket #400

**Comment by marcellmueller** [comment]
@MarsRomer this spike actually went really well. 

I have a working test branch where you can create a new application with the new schema (no estimated employment page) and with a few tweaks I made the application works seamlessly including the stepper and review pages which won't display that field.

Likewise if you view an application that was created before the new schema the estimated project employment will show up on the application, review pages and stepper.

The only blocker is the acceptance criteria for already created draft applications to use the new schema will require us to update the draft applications in prod. I suggest creating a separate ticket for that.
