### ISSUE TITLE
Spike:  Use alternate method for Form Data entry

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#2199]
This ticket is to help refine #2142 for the requirements that are listed there

- [x] Explore different ways to solve #2142
- [x] Step by step instructions of how the form data will be entered into prod including uploaded files.

Notes:
Different methods to explore:
1. Analyst creates the application in prod and uploads the files in prod (intake is not opened to public)
2. Analyst creates the application in test and dev migrates it to prod including the uploaded files
3. Analyst creates the application in test and dev migrates it to prod, files are uploaded later using RFI

**Comment by VB-at-Bis** [comment]
Pros and cons for different approaches:

Analyst creates the application in prod and uploads the files in prod (intake is not opened to public)
-	pros:
o	no need to move uploaded files from Dev or Test AWS account to Prod AWS;
-	cons:
o	risk of unwanted exposure to public ability to create/submit application while intake is closed

Analyst creates the application in test and dev migrates it to prod including the uploaded files
-	pros: 
o	no risk of opening intake to public
-	cons:
o	complexity of developing script that moves files from Dev or Test AWS account to Prod AWS

Analyst creates the application in test and dev migrates it to prod, files are uploaded later using RFI
-	pros: 
o	no risk of opening intake to public
o	no need to develop solution for file migration
-	cons:
o	existing code needs to be modified to allow submission of application without uploaded document 
        or (if user uploads placeholder files just to pass validations)
o	need to develop custom scripts to clean form data in the database that references uploaded files and clean history


Draft PR created to demonstrate how first approach can be implemented. 
Main benefits:
- very minor changes to database (extra column in intake table and new function);
- very minor changes to source code (two files affected with few lines of code in each);
- alternative data entry functionality unlocked by using special URL parameter which can be controlled by Growthbook feature flag and/or environment variable

Suggested approach mitigates risk of exposure to public by using cryptographic hash function to validate URL parameter, and requires least amount of efforts to allow user to enter and submit application directly in Production even when intake is closed.

**Comment by VB-at-Bis** [comment]
**How to create new application using alternative method**

Development team:
-	insert intake 99 record into ccbc_public.intake table with `hidden` column set to 1;
-	enter secret key as a variable in Growthbook and enable it;
Analyst
-	open application portal in browser (i.e. https://test.connectingcommunitiesbc.ca/applicantportal );
-	modify URL by adding the key (i.e. https://test.connectingcommunitiesbc.ca/applicantportal/secret_key) and hit Enter;
-	observe that page now indicates that intake is open;
-	login with BCeID to access dashboard;
-	modify URL by adding the key (i.e. https://test.connectingcommunitiesbc.ca/applicantportal/dashboard/secret_key) and hit Enter;
-	observe that “create Applicatiion” button is enabled;
-	proceed entering application data and uploading files;
-	when done click on Submit button;
Development team:
-	manually (script or directly in database) change status of the application to Received;
Analyst
-	open analyst portal (i.e. https://test.connectingcommunitiesbc.ca/analyst);
-	login with IDIR;
-	continue processing the application (adding RFI if needed etc.)

P.S. Steps may change after final implementation - i.e. step to manually update dashboard URL may be removed if we use cookies etc.
