### ISSUE TITLE
Dependabot

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#2209]
Enable dependabot PRs for all dependency updates, not just dependencies with potential security issues as is currently setup.

- [x] Dependabot opens PRs for outdated dependencies

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/2209?planning-poker) with Zenhub @marcellmueller @rafasdc @VB-at-Bis

**Comment by AntBush** [comment]
Updated env settings for dependabot, CI now running fine
