### ISSUE TITLE
Get Sharepoint Access - Master Spreadsheet

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#2213]
Description:
This ticket is to be able to get access to the Master Spreadsheet for our system to be able to import data

- [ ] Connect to the Master Spreadsheet on Sharepoint without using a user token

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/2213?planning-poker) with Zenhub @marcellmueller @rafasdc @VB-at-Bis

**Comment by MarsRomer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/2213?planning-poker) with Zenhub @rafasdc

**Comment by rafasdc** [comment]
The library used for authentication node-sp-auth currently has two vulnerabilities on their packages, will need a patch.
