### ISSUE TITLE
Automate Updating of Master Spreadsheet

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#2214]
As an analyst
I want the master spreadsheet data in the portal database be updated automatically on a regular basis
so that I don't need to spend time managing that myself

Description:
This is to automate the updating of the master spreadsheet data in our database the xls on sharepoint

AC:
- [x] Upload from sharepoint on a regular basis, twice a day, noon and 430pm Pacific Time
- [x] Data is updated in our database 
- [x] Only upload the data IF the file was modified since the last time it was uploaded
- [x] our db captures the 'created at' based on our upload date and time
- [x] our db records the 'modified date and time' from sharepoint for when the xls was last modified by user

Implementation notes:
- [x] look into libraries for automation?

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/2214?planning-poker) with Zenhub @marcellmueller @rafasdc @VB-at-Bis

**Comment by rafasdc** [comment]
For automation an OpenShift CronJob is being used that runs a very basic nodejs script that triggers the API. To confirm max frequency.

**Comment by MarsRomer** [comment]
@rafasdc will the change in bi-annual time zone be taken into consideration?

**Comment by MarsRomer** [comment]
Hey Rafa can you please confirm that the AC for: Only upload the data IF the file was modified since the last time it was uploaded is in effect?  The test spreadsheet wasn't updated since yesterday but the script still ran today as I can see in the Error list  
[Uploading... image.png]

**Comment by rafasdc** [comment]
Yes, the AC is working as expected. On the last triggers in test it returned `Response {"message":"No new data to import"}` 

Note that I believe that DEV also pushes to the same list and since that DB gets cleared very often it will always "think" the data has never been imported.

The DB on test has the correct data no imported twice, we might have to create a DEV list or disable the trigger on dev to avoid the list overly growing.

**Comment by MarsRomer** [comment]
ok that's good to know, yes I think we should probably disable it in dev somehow, but keep it flexible to bring it back in dev if we need to

**Comment by rafasdc** [comment]
I've set it to once a year which is they max we can give it, but we can keep pushing forward indefinitely. Next run is scheduled for October 15th, 2024.
