### ISSUE TITLE
Master Spreadsheet Excel upload Validation - Add Error to Row of data imported

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#2216]
As an Analyst
I want to see errors in data types that did not upload correctly
so that I know that the data needs to be fixed 

Description:
This ticket is to help analyst see if there were errors in the data uploaded due to incorrect type of data (i.e. string instead of numbers, incorrect date format)
This ticket is also for preventing issues downstream in Metabase reports that would cause columns to change data types due to incorrect data type imported from the master spreadsheet.

This is to implement some sort of feedback when the master spreadsheet upload has errors:
This ticket will complement feedback of master spreadsheet upload fails - e.g change to file name, file moved to another location - covered with #2260

AC

- [x] "Error log" column exists in our db for each row of data imported.  Error message in row formatted like "[Column name 1]  - not imported due to formatting error;  [Column name 2]  - not imported due to formatting error;"
- [x] Validate date formats - if not as expected then do not import date, use null instead (import rest of row) put error message in Error Log column
- [x] Cell type checks - for numbers. - if not as expected then do not import value, import null instead (import rest of row) put error message in Error Log column.  
- [x] Numbers - keep decimal places as found in excel spreadsheet

TEST version of Master Spreadsheet:
https://bcgov.sharepoint.com/:x:/r/teams/04708-ScrumTeam/Shared%20Documents/Scrum%20Team/Connecting%20BC%20Program_Approved%20Projects%20(restructured)_Sept15_TEST_DATA.xlsx?d=w2acb6c456920461b8b32f9ee03f7362f&csf=1&web=1&e=j7tEAh

Real version of Master Spreadsheet:
https://bcgov.sharepoint.com/:x:/r/teams/04708-ScrumTeam/Shared%20Documents/Scrum%20Team/Connecting%20BC%20Program_Approved%20Projects%20(restructured)_Sept15.xlsx?d=w7e7638d816bf4d11ba8618cc29f4e7ab&csf=1&web=1&e=qZnkED

Numeric Fields:  
Communities and Locales Total Count
Indigenous Communities
household Count
Transport Km
Highway Km
BC Funding Request
Federal Funds
Applicant Amount
Other Funding
Total Project Budget
% Project Milestone Complete

Date fields:
Date Application received
Date conditionally approved
Date agreement signed
Proposed start date
Proposed completion date
reporting completion date
date announced
construction completed on
Last Reviewed

NOT PART OF THIS TICKET
Creating records in the Sharepoint list will be part of #2260

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/2216?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc

**Comment by marcellmueller** [comment]
@MarsRomer do you also want error messages when the fields are empty/null or only when they are filled but not the expected type.

**Comment by MarsRomer** [comment]
lots of fields will be empty/null, we don't need to do any validation about that.  One exception to that may be the 'Project Number' which should never be null
@marcellmueller

**Comment by MarsRomer** [comment]
Works well, love this!
