### ISSUE TITLE
Provide 'master spreadsheet' capabilities

### ISSUE THREAD

**Issue by MarsRomer-zz** [bcgov/CONN-CCBC-portal#222]
As an analyst 
I want to see all my project information in once place 
so I can track it's progress

As an analyst
I want to be able to manage all CCBC and old program data and report on it from the portal
So that the data team and the comms team have automated reports from the database

NWBC analysts are used to working with what is known as the 'master spreadsheet' which holds several important pieces of information that can be used to track the progress of the project in it's process.  

This ticket is to recreate the capabilities that the analysts find useful in the master spreadsheet.

**Comment by elliottSlee** [comment]
@MarsRomer can we close this card?

**Comment by MarsRomer** [comment]
closing this ticket as it's part of othe rwork
