### ISSUE TITLE
Do a deployment to AWS

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#2227]
Description:
To test the terraform for AWS deployment as part of the vendor handoff 

AC:
- [x] Request a new dev environment to practice on
- [x] Successful deployment to AWS dev environment

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/2227?planning-poker) with Zenhub @AntBush @rafasdc

**Comment by rafasdc** [comment]
Successfully applied terraform plan to empty tools namespace and then destroyed it. 

Updated README with a bit of extra description and steps needed and minor updates through the process.
