### ISSUE TITLE
Multiple Login Buttons for BCeID providers

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#223]
### User Story
As an applicant 
I want the login button to lead directly to BCeID
So that I don't try using options not relevant to me

### Acceptance Criteria
- [x] Update landing page to include buttons for login to Business BCeID, Basic BCeID, and Register for Basic BCeID
- [x] **Business BCeID Login button** bypasses login options and leads directly to the Business BCeID login page
- [x] **Basic BCeID Login button** bypasses login options and leads directly to the Basic BCeID login page
- [x] **Register for Basic BCeID button** leads directly to the Basic BCeID registration page

### Technical Details
- Each login button should call `/login` with a `kc_idp_hint` parameter
- The `authorizationUrlParams` option of the  `sso-express` need to be defined as a function, forwarding the `kc_idp_hint` value (not without ensuring that it's one of the accepted values first, as blindly forwarding request parameters is a security issue)

![Screen Shot 2022-10-05 at 2.27.59 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/2fe0391e-aa92-4845-a585-bb8f1e1acde1)

**Comment by elliottSlee** [comment]
@MarsRomer before we develop this can we discuss it some more? Applicants would be able to see this option on every page, which isn't very good UX. Instead of the link in footer, what do you think of having two login buttons on the landing page:
![Screen Shot 2022-08-23 at 2.26.30 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/d29b97be-5190-4207-bf6c-11bcf640272f)

**Comment by MarsRomer** [comment]
@matthieu-foucault we have decided that we don't need an IDIR login for the prod env (at least not for now).  I just want to confirm that if we don't implement this ticket, then the login will not have the IDIR option, or will it?  Perhaps we need to reword this ticket for Removing IDIR only?

**Comment by matthieu-foucault** [comment]
We need the first acceptance criteria of this ticket, "Login button bypasses login options and leads directly to the BCeID login page"

Github login isn't an option anymore, so we can update the AC to have IDIR login as the conditional login for dev/test only

**Comment by matthieu-foucault** [comment]
Blocked on SSO config issue, see https://chat.developer.gov.bc.ca/channel/sso?msg=AsTDGZXxWhkR9E49m

**Comment by elliottSlee** [comment]
Looks like BCeID both includes Business or Basic. If that unblocks this from needing designs, then awesome. If not, we have [a design ready](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=5653%3A25247).
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/b284b7e0-79bb-48f6-b13c-cfb297fbe183)

**Comment by matthieu-foucault** [comment]
@MarsRomer from our discussion between devs and designers today, I think that we'll need to implement this, with two separate login buttons, before we add idir login (#26). As soon as we add IDIR login, that option would show up for all users on the keycloak page, leading to confusion.

The alternative would be to have a separate application altogether for analysts vs applicants, but I think this would lead to much greater maintenance costs.

**Comment by MarsRomer** [comment]
if we wanted a different login page for the analysts would that mean we are asking creating a separate application?  I had imagined that the analysts would access their features through a url like www.connectingcommunitiesbc.ca/analystportal

**Comment by matthieu-foucault** [comment]
Not necessarily. Our single application could handle both analyst and applicants, while having a different login page for both user groups.
I don't see any obvious benefits to having a separate applications in our case. The only thing that comes to mind is load balancing, but it's not a concern with our scale.

**Comment by MarsRomer** [comment]
ok great.  I don't know if I see a reason for needing an IDIR login for the applicant portal, just BCeID options should be good enough.  IDIR would be only for the analyst side of things.  So two buttons like you have done with the CAS team would be fine I think for the applicant portal

**Comment by elliottSlee** [comment]
We discussed that analysts would not have their own login page at a different URL because that would require a different app. This means 1 landing page, which means that if we used the SSO login page, all three Basic BCeID, Business BCeID, and IDIR logins would appear. Showing these 3 would be confusing to users, so we'd need three buttons on the Landing page. Here's a first pass at the design:
>![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/31485d70-1035-450a-838a-2177611477a5)

**Comment by matthieu-foucault** [comment]
@elliottSlee I think there was a misunderstanding. We can have a separate landing page for analysts *and* have a single app.

**Comment by elliottSlee** [comment]
Sorry for my confusion. So it'd be:
![image](https://user-images.githubusercontent.com/93939894/191520406-b3826b3d-7253-415b-9b79-a6f72b6b31c0.png)
AND
![image](https://user-images.githubusercontent.com/93939894/191520816-7321b75d-88fd-4c15-a4bf-d0714a40c39d.png)

**Comment by matthieu-foucault** [comment]
Given that our root url, `connectingcommunitiesbc.ca`, redirects to the applicant portal, should we have a link in there somewhere to go to the analyst portal, or will analysts have to bookmark `connectingcommunitiesbc.ca/analystportal` ?

**Comment by elliottSlee** [comment]
I'd expect analysts to bookmark connectingcommunitiesbc.ca/analystportal to help avoid any confusion for public-facing side

**Comment by matthieu-foucault** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/223?planning-poker) with Zenhub @VB-at-Bis
