### ISSUE TITLE
Show status of application on each form page

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#224]
As an applicant 
I want to see the current status of my application when navigating in it

<s>If the applicant has not completed the application, the status is 'Draft'
If the applicant has completed the application, the status is 'Submitted'
If the applicant edits a completed application, the status remains as 'Submitted'</s>

- [ ] Status is 16px away from the project title

![image.png](https://images.zenhubusercontent.com/61e8875b1de5eff8f072cd04/0d7f5009-b340-43bf-8465-2c002e2f5c05)

**Comment by elliottSlee** [comment]
@zoeyli-46 do you have any suggestions for how this could look?

**Comment by zoeyli-46** [comment]
pill status near application name, snackbars and banners are usually things that are supposed to disappear. I'll reflect this on the wireframe. great flag!

**Comment by elliottSlee** [comment]
Done with #91 - Autosave
