### ISSUE TITLE
Claims history

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/CONN-CCBC-portal#2240]
Created, updated or deleted Claims should be shown on the history page

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdGVlIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fc7a68366a492093c0c2257d19d52d9b1b9ef57d/image.png)

Icon is https://fontawesome.com/icons/dollar-sign?f=classic&s=solid colour 1A5A96

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/2240?planning-poker) with Zenhub @AntBush @rafasdc

**Comment by MarsRomer** [comment]
Is it possible to show more detail about the deleted claims file?  In the screenshot below you can see that I created a new claim and it is good at telling me details such as the file name etc, but in the blue underlined line, the history only says I deleted a claim, but doesn't provide the same level of details.  
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3BIQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0a9e974ee4bcb4e8af5a8e14f5740420e03f8303/image.png)

**Comment by marcellmueller** [comment]
Of course it's possible, though we aren't showing anything for any other history items on the project page. I would consider making a ticket to update these if that is important.
