### ISSUE TITLE
Milestones history

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/CONN-CCBC-portal#2241]
Created, updated or deleted Milestones should display on the history page

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdFNlIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--04c911750ea60eb2654d219402b296577c4eec14/image.png)
Icon is https://fontawesome.com/icons/signs-post?f=classic&s=solid colour: 1A5A96

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/2241?planning-poker) with Zenhub @rafasdc @AntBush
