### ISSUE TITLE
Bug: Incomplete CCBC ID 

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#2265]
**Describe the bug**
An application that was created a few days ago had an incomplete CCBC ID assigned somehow.  
This ticket is to research why this would have happened in order to avoid this from happening again in test and never happening in prod.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBclNoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6d066ba5a9858bf6fe40c9d4e9caf08471ddd466/image.png)

- [ ] Delete record with incomplete CCBC ID

**Comment by rafasdc** [comment]
This bug is occurring for all of intake 1. To replicate set time machine to an intake 1 date range, for example October 19, 2022) and submit an application. No number/id will be assigned to it.

**Comment by rafasdc** [comment]
I am not entirely sure why/how but the gapless counter related to intake 1 is gone from the test DB. There is no ID associated with the intake 1 on the table `intake`, further there is no counter that matches the current ID (76) of intake 1 on the test DB on the table `gapless_counter`. 

The function for submit_application requires the gapless_counter to generate the final piece of the ID. 

We will need to manually create a gapless counter entry for intake 1 and associate it with it so this stops happening.

**Comment by rafasdc** [comment]
Updated DB, applications without ID for intake 1 now have one, new applications created for intake 1 will now get the ID added at the end. 
Note: apps were not deleted but updated with the proper ID.
