### ISSUE TITLE
Remove Primary Legal name question - Org Profile page

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#228]
On the Organization Profile, currently, we are asking the question "Is this the primary legal name?"  
This ticket is to remove that question and the radio buttons associated with it.  We will not be asking this question since it was meant for bilingual forms where they could have a French name and English name, and this question was used to identify which of the two names was the primary legal name.

https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=1059%3A6234

### Acceptance Criteria
- [x] Remove the question "Is this the primary legal name?" from the Organization Profile section

**Comment by BryanGK** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/228?planning-poker) with ZenHub @marcellmueller @wenzowski

**Comment by MarsRomer** [comment]
@marcellmueller  would be able to see if this made it to to test too? I still see the question in question.  
![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/a29cb8e2-788c-48fa-8383-2da20ce3d567)

**Comment by MarsRomer** [comment]
@marcellmueller I am still seeing the primary legal name question on the form, perhaps it never got pushed to test?
