### ISSUE TITLE
MUI styled components bug

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/CONN-CCBC-portal#2283]
Styling for the new accordion (`components/Accordion.tsx`) was working locally but doesn't seem to be applied when building the app due to a webpack issue. 

We could fix this by passing in the styles with the `sx` prop like we have done before eg `CcbcIdWidget` or we could setup MUI to work properly with styled components:

https://mui.com/material-ui/guides/styled-components/

**Comment by elliottSlee** [comment]
@AntBush Does MUI's Joy UI help address the issue of styling? https://mui.com/joy-ui/getting-started/
> Joy UI applies new approaches to customization, enabling you to customize every piece of the components to match your unique design.

**Comment by AntBush** [comment]
@elliottSlee taking a quick look through the documentation I'd say it would probably face the same problems as they're likely using the same theming engine under the hood to apply styles so we'd face the same issues. It's also still in beta, so I couldn't recommend it for the project. One cool thing that it has (that I'd like to see for MUI and may be the same honestly) is their [theme builder tool](https://mui.com/joy-ui/customization/theme-builder/) that can quickly make a theme for your project. Would be worth looking into more
