### ISSUE TITLE
Runbook: extracting test DB backup

### ISSUE THREAD

**Issue by rafasdc** [bcgov/CONN-CCBC-portal#2295]
When there are DB errors, such as sqitch on the test instance it is very helpful to take a copy of the test DB and debug locally. This ticket is to document the steps and commands to run to get this copy. 

AC: 

- [x] Instructions on generating and extracting a full copy (with data) of the test db from OpenShift
- [x] Instructions on generating and extracting a copy with no data of the test db from OpenShift

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/2295?planning-poker) with Zenhub @AntBush @rafasdc
