### ISSUE TITLE
Fix Prod env bug

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#230]
prod site opens and welcome screen present for just a sort period of time and then disappears.

**Comment by BryanGK** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/230?planning-poker) with ZenHub @marcellmueller @wenzowski

**Comment by marcellmueller** [comment]
https://ccbc.apps.silver.devops.gov.bc.ca/

@MarsRomer can you please review this? Thanks!

**Comment by MarsRomer** [comment]
Thanks @marcellmueller   This works for me!  BTW how do I get access to the portal?  Should my BCEID and/or IDIR work?
