### ISSUE TITLE
Spike - How to make an editable table

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#2305]
Key features are single-click editable (dropdown & datepicker), sort, and filter/search

### Options:
1. Table with toggle to see more, each column has a filter
2. Table with subtext (more than 1 piece of information in a cell) and a single search field instead of filter
3. Freeze column
3. Other

Spike into which package has the features we need

**Comment by AntBush** [comment]
So looking through I found this that is completely free: https://www.material-react-table.com/ under the MIT license

There's the library it's based off of: https://tanstack.com/table/v8/

There's this called rc-table: https://table-react-component.vercel.app/demo/expanded-row-render it's been updated quite frequently but documentation isn't great

A lot of the libraries that has the features we want usually has table subtext behind a pay wall. 

Other than building out our own table library I am having trouble finding a library that is much more powerful than we need (usually these libraries are expecting thousands of rows). We can probably get away with using the current table we've got and adding in a [Collapse MUI component ](https://mui.com/material-ui/transitions/#collapse)that'll hold the components we need in it? I don't think it would be very accessible though, but I'm also not sure if any of these free ones hit that same metric.

**Comment by rafasdc** [comment]
One more library in addition to the ones Tony mentioned above https://github.com/adazzle/react-data-grid. Seems to have: 

- Frozen columns
- Dropdowns (Row grouping)
- Column grouping (not really subtext, but kind of) 

[Demo of all features](https://adazzle.github.io/react-data-grid/#/all-features])
