### ISSUE TITLE
Migrate from Terraform Cloud to AWS

### ISSUE THREAD

**Issue by rafasdc** [bcgov/CONN-CCBC-portal#2316]
Description:
Currently using the BCGOV instance of Terraform cloud, due to price changes in 2024 need to migrate to using AWS S3 + DynamoDB to handle remote state files.

Guide provided by PS: https://github.com/bcgov/startup-sample-project-aws-serverless-OIDC/blob/main/docs/tfc_to_s3_migration.md

**Deadline**
We're aiming for everyone to make the move by **Wednesday, 18th October 2023**.

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/2316?planning-poker) with Zenhub @AntBush @rafasdc @marcellmueller
