### ISSUE TITLE
Assessment assignment table - Edit

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#2318]
As an analyst 
I want to edit project information
So that I can assign assessments

**Description:**
Trying to recreate the project assignment spreadsheet.
Key is to display a lot of information clearly to enable users to scan it, make it editable
# Acceptance Criteria:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcnpUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9124a15155c5983a2adb0f2f6bba50930fc10c40/image.png)

[**Wireframe**](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?type=design&node-id=12854-64515&mode=design&t=GcuLo9jyMmDsyuVR-4)

- [x] Edit of the Assessment cells (PM, Tech, Permitting, GIS) is a Select of the List of Analysts
- [x] Changes saved as soon as user picks from drop down list

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/2318?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc

**Comment by elliottSlee** [comment]
The dropdown of analysts in the table contains those marked Inactive. It should only include active analysts.

**Comment by elliottSlee** [comment]
Also, would it be possible to change the styling of the dropdown to look more like a cell and less like a dropdown in a form? For example: [Uploading... Screenshot 2023-10-24 at 10.33.56 AM.png]

**Comment by marcellmueller** [comment]
Okay I'll fix the inactive analysts issue. As for styling, make a styling ticket.

**Comment by MarsRomer** [comment]
@marcellmueller @elliottSlee  I had created a bug ticket for the inactive users yesterday #2484
