### ISSUE TITLE
Update optional fields in the project page

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#2327]
- [x] **Change request form** - Project Change Request form file upload should state "if available, can be added at another time"
- [x] **Change request form** - Map file upload should state "(optional)
- [x] Evidence of milestone completion should state "if available, can be added at another time"

### Current
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUFEQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--13c9a4ae9f4e84731359c9bfe412265c4b404233/Screenshot%202023-10-04%20at%209.52.10%20AM.png)
### Desired 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUVEQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f21adbcd7d1a39f570e6604add60f7da2c857957/Screenshot%202023-10-04%20at%209.53.40%20AM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU1EQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1c88da134620d0f0ec3a70787efd1a71832e8b7b/image.png)

**Comment by elliottSlee** [comment]
@MarsRomer as requested, here's the card to increase consistency regarding optional & required fields.
The only one I didn't change was conditional approval because that form is completed in stages.

**Comment by AntBush** [comment]
Hey @elliottSlee I notice that AC and the desired screens are a bit off. I added in the change for the `Upload the updated statement of work Excel file (if available...` that's in the screen. Let me know if this is in error or not
