### ISSUE TITLE
Update text in community progress reports section

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#2328]
To increase consistency in the UX

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbWpaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--121637568817378b754832522ba7b79979e9f5e0/image.png)
- [x] Make accordion header plural (i.e., report**s**)
- [x] Move description from above the upload field to the top of the form
- [x] Change label of file upload from "Progress report file" to "Upload the community progress report"

**Comment by AntBush** [comment]
Hey @elliottSlee want me to move the metabase url here? [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeG1MQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f02a79aa77c6fbfadfc5cddf791486f194846874/image.png)

I'm not a fan of how it's placed as is

**Comment by elliottSlee** [comment]
@AntBush Could you put the text to the left of the link?

**Comment by AntBush** [comment]
Yeah, I can make another PR for that since this has already been merged
