### ISSUE TITLE
Delete Milestone data

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#2334]
Delete all TEST data for these tables
Application Milestone Excel Data 
Application Milestone Data

**Comment by MarsRomer** [comment]
The delete modal doesn't go away after I click Yes Delete 
[Uploading... image.png]

**Comment by MarsRomer** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcFRpIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1413cebc76bb875dc70d44be780b0fd7c2187df3/image.png)

**Comment by MarsRomer** [comment]
Also I am pretty sure I had deleted this record at the top but it shows in metabase as 'created' instead of 'deleted' and no archive info
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcC9pIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8666ca9ec9eacdb0539ffacd5720228243ecd7f7/image.png)

**Comment by marcellmueller** [comment]
Sorry but can you give more details in your bug reports because the delete modal goes away each time for me, I need more info if I am to recreate this bug.

**Comment by marcellmueller** [comment]
@MarsRomer also the one that isn't deleted is a different application then in the picture. I can still see the milestone report in the one you mentioned:

![Uploading Screenshot 2023-09-27 at 9.43.42 AM.png…]()

**Comment by MarsRomer** [comment]
sorry this is the wrong ticket to post the error in
