### ISSUE TITLE
Doc:  How to change environment variables for Connecting BC Program Data on GitHub

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#2339]
Description:
We need an instruction manual for how to change the location of the Connecting BC Program Data spreadsheet

AC:
- [x] Step by step document on how to change environment variables for the Connecting BC Program Data 
        - [x]  SP Site, Doc name, Doc library

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/2339?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc

**Comment by MarsRomer** [comment]
@rafasdc can we check off the AC?

**Comment by rafasdc** [comment]
Done, sorry!
