### ISSUE TITLE
Applicant - Hover and click to view applications from dashboard

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#236]
### User Story
As an applicant
I want to be able to easily get to my application
So that I can have a better experience opening my application

### Description

Applicants want to be able to click anywhere on the row in their dashboard to open their application.

### Acceptance criteria
- [ ] Given an application status is "Draft"
When I click anywhere in the row of an application (except the action buttons)
Then I'll be redirected to the last edited page
#
- [ ] Given an application status is "Submitted" or "Received"
When I click anywhere in the row of an application (except the action buttons)
Then I'll be redirected to the review page

**Comment by eazeredo** [comment]
@elliottSlee , is this duplicated? What is the difference between this and #31 - Dashboard?

**Comment by eazeredo** [comment]
@elliottSlee  and @zoeyli-46, should the same Business Rules be applied to the "Edit" button?

**Comment by elliottSlee** [comment]
This ticket is imperative for viewing withdrawn applications and for viewing submitted applications after intake closes.

**Comment by elliottSlee** [comment]
@matthieu-foucault @wenzowski @AntBush @marcellmueller the acceptance criteria have changed. Change you please re-estimate?

**Comment by MarsRomer** [comment]
@elliottSlee just so you are aware I have removed the hover state from the acceptance criteria for now, we will need another ticket for it if we are going to bring that in later

**Comment by MarsRomer** [comment]
Not required - closing ticket
