### ISSUE TITLE
Automate Local Dev DB Set up

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#2361]
Automating the onboarding of new developer, for the DB: 

- [x] [Mac] Run DB and deploy dev data
- [x] [Windows] Run DB and deploy dev data
- [x] [Mac] Able to run e2e tests against database
- [x] [Windows] Able to run e2e tests against database
- [x] [Mac] Able to run pgTAP tests against database
- [x] [Windows] Able to run pgTAP tests against database

**Comment by rafasdc** [comment]
To see the docs/scripts created: https://github.com/bcgov/CONN-CCBC-portal/tree/db-local-setup/local_setup
