### ISSUE TITLE
Bug:  clicking on row in Dashboard does not load application

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#2370]
To recreate:

1. Log into the prod analyst portal
2. Click on any row in Dashboard
3. Error - click on row does not take the user to the application page.
4. After logging out and logging back in a couple of times this bug seems to resolve it self.

Expected behaviour:
When clicking on the row, it should take the user to the application page for that row.

**Comment by marcellmueller** [comment]
@MarsRomer I'm not sure what to do with this one as it is working fine for me. It may have just been a one time networking issue as there has been no changes to the dashboard for some time and we haven't seen it before. Can you please let us know if it happens again.

**Comment by MarsRomer** [comment]
@marcellmueller is their anything in our monitoring logs that would shed some light on this.  Since it happened to someone else as well around the same time I am hoping there is some information that would tell us if there was a networking issue or something else going on at the time
