### ISSUE TITLE
Create CI/CD for Prod

### ISSUE THREAD

**Issue by eazeredo** [bcgov/CONN-CCBC-portal#24]
- [ ] Receive the SSO credentions for the production environment
- [x] Secrets into GitHub environment 
- [x] Dev (main)-> Prod
- [x] Update GitHub Workflow

## PO Acceptance Criteria
- [x] Prod URL

https://ccbc.apps.silver.devops.gov.bc.ca/
## Not included
- Feature Flag #145

**Comment by elliottSlee** [comment]
@marcellmueller & @BryanGK is this done?

**Comment by BryanGK** [comment]
@elliottSlee No we don't have a path to prod yet.
