### ISSUE TITLE
Application number - Make it work legit

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#240]
Application number should be CCBC-010012
- first 2 digits are the intake number, 
- the last four are sequential numbers for the application number in that intake.

**Comment by eazeredo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/240?planning-poker) with ZenHub @AntBush @marcellmueller @wenzowski
