### ISSUE TITLE
Rename "Claims" Accordion to "Claims & Progress report"

### ISSUE THREAD

**Issue by AayushAnand007** [bcgov/CONN-CCBC-portal#2418]
**Description:**
Need to rename the "Claims" accordion to "Claims & Progress reports" to improve user understanding, and align with the report name.

# Acceptance Criteria:

 - [ ] Claims accordion page now reads "Claims & Progress reports"

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/2418?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc
