### ISSUE TITLE
Bug:  Erroneous message about duplicate claims upload

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#2434]
When I upload a claims document I get an error message that it's a duplicate claim number even though there are no claims currently in the form.  

To recreate:
1.  Go to CCBC-020043
2.  Upload claim document attached to this ticket
3.  See error message in screenshot below

Note:
I had just deleted 3 claims document, one of them probably had the same claim number as the one I am trying to upload. 
 I don't think they archived properly which could by why this is happening.

![image](https://github.com/bcgov/CONN-CCBC-portal/assets/120044407/4f4898e7-3e4c-4c0d-97f6-34af0b053e26)

[CCBC Claim Request Form & Progress Report CCBC-020043 -2.xlsx](https://github.com/bcgov/CONN-CCBC-portal/files/12967985/CCBC.Claim.Request.Form.Progress.Report.CCBC-020043.-2.xlsx)

**Comment by AntBush** [comment]
So I've found the way to replicate this:
1. save a claim
2. edit the claim and replace the file and save
3. delete the claim
4. create a new claim and attempt to upload a claim with the same claim number and it will return the above error.

**Comment by AntBush** [comment]
@MarsRomer the current fix I've got for this does not resolve the issue but prevent it from happening again as the validation step happens before we have a chance to change the database. Let me know if you'd like me to whip something up to fix the data in test

**Comment by MarsRomer** [comment]
what would be the fix in the data?  would that be setting the deleted records as archived?
