### ISSUE TITLE
Change Approved Status display to Agreement Signed

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#2454]
Description:
Change the Approved status to stay in line with the CBC data

AC:
 - [x] Displayed status for Approved will now show 'Agreement Signed' for internal and external status on Applicant and Analyst portal
- [x] Update info graphic showing status changes descriptions and triggers
[Image on Scrum Team](https://bcgov.sharepoint.com/:u:/r/teams/04708-ScrumTeam/Shared%20Documents/Scrum%20Team/State%20Maching%20Swim%20Lane%20-%2020231019.svg?csf=1&web=1&e=PYtAcs)

- [x] Image alt-text updated:

> The happy path for a project from application to completion. The external status is what an applicant sees and the internal status is what you the analyst sees. After an intake closes, both internal and external status are Received. After eligibility screening is assigned, the internal status can be changed to Screening but the external status remains Received. After it is determined to be eligible, the internal status can be changed to Assessment but the external status remains Received. If it is in the selection package for the Minister, the internal status can be changed to Recommendation but the external status remains Received. After the Minister states Approved in Annex A of the selection package, the internal status can be changed to Conditionally Approved. The external status can only be changed to Conditionally Approved when the applicant responds to the Letter of Conditional Approval, accepting the offer. When the Funding Agreement is signed by both the Recipient and the Province, the internal and external statuses can be changed to Agreement Signed. After a final implementation report is received and the final claim is processed, both statuses can be changed to Complete.

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/2454?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc

**Comment by marcellmueller** [comment]
@MarsRomer @elliottSlee I noticed that the rest of the two word status descriptions only have the first word capitalized. 

I am making it `Agreement signed` instead of `Agreement Signed` for consistency. Let me know if you have other thoughts.

**Comment by elliottSlee** [comment]
@MarsRomer the bottom of the "g" is cut off. If we change the pill to have less padding (it's currently 6px on top & bottom, could be reduced to 2px), the pill will remain the same size and the g will be fully visible.
