### ISSUE TITLE
Styling of Assessment table

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#2494]
- [x] Remove border around drop downs
<img width="294" alt="Screenshot 2023-10-24 at 10 33 56 AM" src="https://github.com/bcgov/CONN-CCBC-portal/assets/93939894/141a3dad-710c-4755-891b-63a40630492f">
 
- [x] Fix font - change to BC Sans
- [x] make each CCBC ID color: #1A5A96
- [x] hover state for CCBC ID hyperlink is color: blue <s>and underlined</S>
- [x] Fix permitting assessment filter alignment
- [x] After clicking on the hyperlink & on the assessments page, when "Dashboard" is clicked in the sidebar, it brings the user back to the assessment table, the filtering & sorting that were applied before they navigated away remain
- [x] Remove words 'Assessment'  from headers <S> and narrow columns to show first 9 characters</S>

**Comment by MarsRomer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/2494?planning-poker) with Zenhub @marcellmueller

**Comment by MarsRomer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/2494?planning-poker) with Zenhub @AntBush

**Comment by MarsRomer** [comment]
@marcellmueller  can you please see if this AC is working for you:  After clicking on the hyperlink & on the assessments page, when "Dashboard" is clicked in the sidebar, it brings the user back to the assessment table, the filtering & sorting that were applied before they navigated away remain

**Comment by marcellmueller** [comment]
> @marcellmueller can you please see if this AC is working for you: After clicking on the hyperlink & on the assessments page, when "Dashboard" is clicked in the sidebar, it brings the user back to the assessment table, the filtering & sorting that were applied before they navigated away remain


Just tried it in test and sorting and filtering is saved for me when I click the link and return, or refresh the page.

<img width="1422" alt="Screenshot 2023-10-31 at 9 42 26 AM" src="https://github.com/bcgov/CONN-CCBC-portal/assets/14259474/80cfb7ce-9326-492d-80cd-26124aaf991d">

**Comment by MarsRomer** [comment]
I clicked on the CCBC hyperlink in the assessment table, then I clicked 'Dashboard' and I was expecting to be brought right back to the assessment  tab but it brought me here
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUtMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e5425f81c628d4b0f2b89f59df47c80ec73fdcb0/image.png)

**Comment by marcellmueller** [comment]
> I clicked on the CCBC hyperlink in the assessment table, then I clicked 'Dashboard' and I was expecting to be brought right back to the assessment tab but it brought me here [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUtMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e5425f81c628d4b0f2b89f59df47c80ec73fdcb0/image.png)

Oh, well the dashboard link brings you back to the root of the /dashboard which is the main dashboard. This is the issue with trying to squeeze in multiple complex acceptance criteria in one giant sentence. 

In addition to that I am not really sure if that is a good idea having the same link do different things depending on where you came from.

**Comment by marcellmueller** [comment]
@MarsRomer I made a separate ticket for that here:

https://github.com/bcgov/CONN-CCBC-portal/issues/2575

Re-reading the acceptance criteria in this ticket I am unsure if you wanted the table filters and sorting to be saved when hitting back or refresh or only when they click the dashboard tab.

**Comment by MarsRomer** [comment]
thanks @marcellmueller  for the new ticket.  yes we want the filters and sorting to be saved when they hit back or refresh and when they click the dashboard tab
