### ISSUE TITLE
Text formatting - Existing network & Project planning page

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#256]
### Existing network coverage

- [ ] Remove the break after "...broadband operators to expand and..."
- [ ] Remove the break after "...towers, poles, rights of way or other similar..."

![Screen Shot 2022-06-29 at 5.15.28 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/2cccbd9f-1524-4ed7-aac6-cadaf54dae3e)

### Project Planning Page 

- [ ] Remove the break after "... is different. Please"
- [ ] Review any other wrong break lines

![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/c9d164be-cb28-4c35-a861-051b03f1983c)

**Comment by eazeredo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/256?planning-poker) with ZenHub @AntBush @marcellmueller @wenzowski
