### ISSUE TITLE
Analysts dashboard - remember which table tab was last visited

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/CONN-CCBC-portal#2575]
If an analyst has been using the assessments dashboard at `/analyst/assessments` route we would like to remember that and send them there when they go to the default `/analyst/dashboard` route.

Acceptance criteria:

- [ ]  Visiting `/analyst/dashboard` reroutes to `/analyst/assessments` if that was the table the analyst last visited

**Comment by rafasdc** [comment]
I think this one is not referring to visiting the URL directly but the Dashboard back link? 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOCtMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fa123353e1acf4b8c6b3524d09bb7ec4d3da4411/image.png)
