### ISSUE TITLE
Log in - internal users (IDIR)

### ISSUE THREAD

**Issue by eazeredo** [bcgov/CONN-CCBC-portal#26]
### User Story
As a user, 
I want to login with IDIR 
so that I can securely access the received applications.

### Preconditions
Developers have a list of IDIRs that are granted Analyst access to all features in the Portal, and IDIRs that are granted Administrator additional access to configuring intake dates

### Authentication (User identity verification)
- [x] Given the SSO is enabled 
When a User accesses the login page
And the user is previously authenticated 
Then the user is redirected to the analyst dashboard, 
#
- [x] Given the SSO is enabled 
When a User accesses the login page
And the user is NOT previously authenticated 
Then the user is automatically redirected to the Landing page url: www.connectingcommunitiesbc.ca/analyst
AND "Login with IDIR" button leads directly to IDIR login page.
#
- [x] If the IDIR credentials are correct, but the user with the IDIR does not have access to the analyst portal, then the user is redirected to the error page 

### Authorization (Permittion verification) 
- [X] Create `Analyst` and `Admin` roles in Single Sign On app
#
- [x] Enable IDIR IDP in CSS app
#
- [ ] Assign list of IDIRs to the `Analyst` and `Admin` roles 
#
- [x] Validate Permission (if a role has permission to perform an action)
#
- [x] When the credentials do not match the list of IDIRS with access, 
Then they will receive an error alert saying "Your IDIR has not been granted access"
#
- [x] Train PO to manage roles

##  Design
**Landing Page**
![Screen Shot 2022-10-05 at 2.29.48 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/1d158a01-c8ee-4517-85fb-1a7e0a49289a)
#
**Error**
![image.png](https://images.zenhubusercontent.com/61e8875b1de5eff8f072cd04/cf5ef635-7912-4871-a801-76c9aa960f2d)

**Comment by AntBush** [comment]
> If there is SSO, Analyst is automatically authenticated and redirected to the analyst dashboard,

Can we remove this? Matthieu has identified that this is not possible

**Comment by MarsRomer** [comment]
Blocked by:  need to determine if we will use siteminder or Azure for login

**Comment by MarsRomer** [comment]
needs design for if log in fails

**Comment by matthieu-foucault** [comment]
@MarsRomer @marcellmueller did the meeting with SSO team and security happen, and do we have recommendations for the identity provider choice?

**Comment by MarsRomer** [comment]
yes, we decided to use the IDIR route through SSO instead of Azure.

**Comment by elliottSlee** [comment]
Super duper minor, but maybe we should change "NWBC members" to "Government of BC employees" seeing as some people from connectivity & other divisions will likely also have access.

**Comment by matthieu-foucault** [comment]
@marcellmueller FYI I have run Mars through the role management process

**Comment by MarsRomer** [comment]
there is a small bug where the user has to logoff after their first attempt otherwise when they try to come back to https://test.connectingcommunitiesbc.ca/analyst they are autorouted to show the 'you do not have access' banner and don't have the option to log in, but the top right of the header has a logout button.
![MicrosoftTeams-image (3).png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/75c26279-b7fb-49dd-bc87-c155eb2433c1)
