### ISSUE TITLE
UI update and Automate calculations

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#262]
As an applicant 
I would like the portal to auto-calculate values 
so that I don't make a mistake.

## Description
1. Auto-calculate the funding totals for each fiscal
2. Auto-calculate the FTE numbers as per total:

Formula for both fields:
e * ( r/35) * (p/12)

e = NUMBER OF PEOPLE TO WORK ON THE PROJECT
r = HOURS OF EMPLOYMENT PER WEEK
p = TOTAL PERSON MONTHS OF EMPLOYMENT TO BE CREATED

## Acceptance Criteria
- [x] Fields are laid out as per screen designs
- [x] Add two calculated fields (same formula)
- [x] totals are saved in the db

![image.png](https://images.zenhubusercontent.com/61e8875b1de5eff8f072cd04/aeb823ba-cde7-4196-bfa5-699032916caa)

**Comment by AntBush** [comment]
Calculation RJSF example: https://codesandbox.io/s/calculation-react-json-schema-form-demo-i8x9g

**Comment by MarsRomer** [comment]
This is working well, just one thing I noticed that the total  current employed needs to move up to above 
![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/16e89fbc-bfa9-4eb3-8e5a-77ca2a8f20af)

**Comment by marcellmueller** [comment]
@MarsRomer Nice catch, I have fixed this and also set decimal place to 1 as Elliott asked me to.
