### ISSUE TITLE
Update NextJS SDK

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#2620]
As per email from Sentry on November 9, we need to update the Sentry Next.JS SDK to 7.77.0 or higher

**Comment by MarsRomer** [comment]
As per email from Sentry on November 9, we need to update the Sentry Next.JS SDK to 7.77.0 or higher

**Comment by rafasdc** [comment]
Update breaks our app, we don't use the functionality we are attempting to upgrade but added a full turnoff on the config anyways for double proofing. Created issue #2624 for investigation on why the upgrade is breaking for us.
