### ISSUE TITLE
Add Zones map to applicant portal

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#2656]
As an Applicant
I need to know what the zones are in BC
so I know how to fill out the form and if my area meets the intake requirements

Description:
We ask applicants to check off zones on the application but we don't provide any visual representation of the zones.

AC:
- [ ] The page with the zones has a visual of the zones, jpg? webmap? 
- [ ] The banner has a link to the zones map? tbd

Figma Designs:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTRUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8c53f1fc9f10eb138b4db5bb82d4058d148a04f7/image.png)

**Comment by AayushAnand007** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXdUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9da8b0baa1ca4ef5c04fa6e9b5985f1f68e4da80/image.png)
