### ISSUE TITLE
Connect Metabase to test database

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#270]
## Acceptance criteria

- [x] Connect the Metabase to the CCBC test database so that we can show our data there to NWBC and the data team
- [x] Add network policy
- [ ] <s>Configure the SSO</s> ( moved to #358)
  - https://www.metabase.com/docs/latest/enterprise-guide/authenticating-with-jwt.html
  - ~The metabase enterprise docker image isn't openshift-compatible, this requires customization similar to what was done in `bcgov/cas-metabase`~ The official metabase docker image works with an arbitrary uid as long as it's using a postgresql database instead of h2

**Documentation**
https://www.metabase.com/docs/latest/operations-guide/environment-variables.html

**Comment by matthieu-foucault** [comment]
@MarsRomer is the intent here to grant access to metabase to NWBC team members, or to do a demo of metabase's capabilities?
If we want to grant access via IDIR using Metabase Enterprise's SSO integration, we will need first to migrate our SSO realm to the gold environment (#296), as silver does not support roles management

**Comment by MarsRomer** [comment]
Hey @matthieu-foucault  yes idea is to grant access to metabase to the NWBC team members.  I would also like a demo and training for the team but that's not part of this ticket.   Let's chat about this tomorrow morning at the stand up

**Comment by matthieu-foucault** [comment]
How time-sensitive is this? There are a couple of extra steps and exploration to get metabase enterprise running. If we want to demonstrate capabilities and grant access to team members as early as tomorrow, it can be done, with the caveat that it would be a temporary instance of metabase, and their accounts would potentially be deleted once we deploy the enterprise version

**Comment by MarsRomer** [comment]
Hi @matthieu-foucault  it's not super time sensitive but it would be very nice to have done by monday.  I know you have limited hour so no worries if it doesn't get done

**Comment by MarsRomer** [comment]
@wenzowski  given that it will likely be a few weeks before the SSO team makes the changes that will allow us to implement idir logins, do we want to remove the SSO acceptance criteria into another card and call this one done?
