### ISSUE TITLE
Tested helm chart for Crunchy

### ISSUE THREAD

**Issue by MarsRomer-zz** [bcgov/CONN-CCBC-portal#273]
Description:
This ticket will help us develop a shortcut for others who want to use CrunchyDB.  The shortcut will set up CrunchyDB in a manner that follows best practices and security and privacy requirements. 

Work to be done here: https://github.com/bcgov/crunchy-postgres

AC:
- [X] Set up BC gov repo (https://github.com/bcgov/crunchy-postgres)
- [x] Boots a working cluster in an extra small namespace (klab namespace for testing)
- [x] Provides a good default postgres resource tuning to function with minimal resources
- [ ] Follows all BC DevOps Security Considerations
- [x] Has a single configurable container image repository variable, with a default to the organizational artifactory instance containing a mirror of the official published images (eg. https://artifacts.developer.gov.bc.ca/artifactory/redhat-docker-remote/crunchydata/crunchy-postgres/ubi8-15.1-0/)
- [x] By default, successfully backs up to a volume with a configurable platform storageclass (by default netapp-file-backup)
- [x] Does not deploy metrics and monitoring by default (but provides a variable to do so)
- [x] Demonstrates ejecting from helm to raw yaml (for users who don't want to use helm directly)
- [x] Has asserted the deployed version of the crunchy operator is compatible with the version of the helm chart being deployed
never (create job from cronjob pattern with docs)
- [x] Is deployed with the specified operator version

Edits by Marcel:
pgAdmin4 dashboard requires PGO v5.1 so this is now a separate issue
- [ ] Does not deploy admin dashboard by default (but provides a variable to do so, and instructions for SSO integration)

Object storage requires PGO v5.0.5 (we are on 5.0.4) so this will be done in the future
- [ ] Backup works with object storage buckets as a secondary backup location

Todo (after MVP): 
- [ ] Is compatible with shared instance of ArgoCD
- [ ] Has cron jobs for each of the common patroni interventions documented in established runbooks where each cron is scheduled to run

**Comment by AntBush** [comment]
Use pgbench to test a helm chart for the crunchydb operator and run tests in klab namespaces provided by Cailey

**Comment by dleard** [comment]
> Exploration:
> 
> * Can one prometheus be deployed to tools to monitor databases in dev/test/prod?

This is how we have crunchy-monitoring set up for CAS. It is deployed to a tools namespace and watches a defined list of namespaces that we provide in the values.yaml
https://github.com/bcgov/cas-pipeline/tree/master/helm/crunchy-monitoring

**Comment by MarsRomer** [comment]
I am going to move this to done, I don't think there are any more reviews we are waiting for
