### ISSUE TITLE
Uploads - Delete uploaded file

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#274]
### Delete file
- [x] **Scenario: Delete upload**
Given an application in Draft or Complete state
And I am the application owner
And I'm on the mapping upload page and have uploaded a file
When they click the red x beside the file name
Then their upload will be (<s>hard</s>) soft deleted
And the filename will be removed from the UI.

- [ ] <s>Implement "Delete By" and "Delete At" in the attachments table.</s>
- [x] Save "Archived By" and "Archived At" in the attachments table.

### To discuss
- [ ] For how long a soft deleted file will be in the server?

**Comment by matthieu-foucault** [comment]
Are deleted files removed from object storage and our database?
What about when applications are revised? Should we plan for a different behaviour in that scenario?

**Comment by MarsRomer** [comment]
yes, deleted files should be removed from object storage and our database.  Applications can be revised until the intake date ends (first intake ends around Nov 1) and the same applies to deleted files, i.e. they should be removed from object storage and our database.

**Comment by wenzowski** [comment]
Allowing any hard deletes creates a security hotspot. We'll need to put testing effort into ensuring that we cannot delete files from a submitted application, possibly via applying a retention policy to attachments when applications are submitted?

**Comment by wenzowski** [comment]
Configuring soft deleted objects to eventually expire [may be an option](https://docs.aws.amazon.com/AmazonS3/latest/userguide/how-to-set-lifecycle-configuration-intro.html).

**Comment by MarsRomer** [comment]
I am not seeing the deleted by and deleted date showing up in the metabase table:  ![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/c6b9b7b9-5562-4f0e-af26-190320361d19) 
Side note: How will the Archive columns be used?
