### ISSUE TITLE
Uploads - Replace file

### ISSUE THREAD

**Issue by eazeredo** [bcgov/CONN-CCBC-portal#276]
- [x] **Scenario: back-end - first file is replaced by 2nd**
- **Conditions**
Given an application in Draft or Complete state
And I am the application owner
And I'm on the template upload page 
And a file has been uploaded
- **Trigger**
When they click on replace and upload a new file
- **Actions**
Then the original file will be soft deleted
And the filename will be removed from below the upload area
And the new file will be uploaded

**Comment by MarsRomer** [comment]
I don't know if we need this ticket still....
