### ISSUE TITLE
Uploads - Validations

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#277]
### User Story
As an applicant
I want to be guided about what file types & how many I can upload for each upload field
so that I can 
#
- [x] **Scenario: Validation - Max file size (as defined by ISED)**
Given that a user is trying to upload a file
When they try to upload a file larger than 100mb
Then they see an error message that says, "Files must be less than 100mb."
<br> <br>
- [x] **Scenario: All empty required fields must be coloured in red on the review page**

#

<details>
  <summary><strong>Template uploads</strong></summary>

- [x] only 1 file allowed
- [x] show 'Replace' button when file already uploaded
- [x] only accepted file type is xlsx for all
- [ ] Templates 1 - 4, 6, 9, & 10 are required
</details>
<br/>

<details>
  <summary><strong>Supporting Documents upload</strong></summary>

<br>

**Copies of registration and other relevant documents**
- [x] multiple files allowed
- [x] no file type restrictions
- [x] required

**Independently prepared financial statements for the last three (3) years**
- [x] multiple files allowed
- [x] no file type restrictions
- [x] required

**Logical network diagram**
- [x] multiple files allowed
- [x] show 'add file' button when file already uploaded
- [x] accepted file formats: PDF, PNG JPEG, VSD/VSDX, DOC/DOCX, PPT, PPTX
- [x] required

**Project schedule**
- [x] multiple files allowed
- [x] show 'add file' button when file already uploaded
- [x] accepted file formats: MPP or XLSX
- [x] required

**Community and Rural Development Benefits supporting documents**
- [x] multiple files allowed (could be >50 or a zip)
- [x] no file type restrictions
- [x] required 

**Evidence of connectivity speeds (such as screen captures of speed test results)**
- [x] multiple files allowed
- [x] no file type restrictions
- [x] required if template 8 was submitted 
</details>
<br/>

<details>
  <summary><strong>Mapping uploads</strong></summary>

**ISED's Eligibility Mapping Tool - Coverage Assessment and Statistics**
- [x] only 1 file allowed
- [x] required
- [x] show 'replace' button when file already uploaded
- [x] only accept file type *.kmz 

Current Network Infrastructure
- [x] multiple files allowed
- [x] required
- [x] show 'add file' button when file already uploaded
- [x] only accept file types *.kmz and *.kml

Proposed or Upgraded Network Infrastructure (project specific)
- [x] multiple files allowed
- [x] required
- [x] show 'add file' button when file already uploaded
- [x] only accept file types *.kmz and *.kml

Statistics email
- [x] only 1 file allowed
- [ ] required
- [x] accepts eml, msg, txt, pdf, doc, docx, xlsx, xlsx, xml, jpg, jpeg, png

</details>

**Comment by wenzowski** [comment]
Confirmed by @MarsRomer: only client side validations are needed here

**Comment by zoeyli-46** [comment]
@marcellmueller we confirmed the format for the last checkbox that's unmarked, do you mind if we add in the update here? Aware that this is already in review

**Comment by MarsRomer** [comment]
I uploaded files for templates 1-10 and then deleted template 5, 7, 8, but in the review page I still see them listed:  Do you want me to create a bug ticket or do you want to fix it as part of this ticket? 
![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/194a65d9-f37a-46ba-a1cc-413a16481f86)

**Comment by MarsRomer** [comment]
the Review page is not showing the required templates as being missing: ![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/29abb580-52e7-44e1-ab39-90b713ff776e)

**Comment by MarsRomer** [comment]
This attachment should be mandatory:  ![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/7a57ff38-c5a3-47ab-ac04-cef6727402a1)

**Comment by MarsRomer** [comment]
@marcellmueller I noticed that the 'Templates 1 - 4, 6, 9, & 10 are required' is not checked and the review page isn't validating that these files are missing.  Is this happening in a different ticket?

**Comment by marcellmueller** [comment]
@MarsRomer Ah sorry this got done though a spelling mistake snuck in an is causing them to not show up.

**Comment by MarsRomer** [comment]
that's ok, I'm putting it back in In Progress for now until it's fixed.  
Also noticed it's allowing multiple kmz files (ISED's Eligibility Mapping Tool )
![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/5aba6be8-a06b-435a-b061-ca44587562cb)
I think everything else looks good though!
