### ISSUE TITLE
Uploads - Upload multiple files

### ISSUE THREAD

**Issue by eazeredo** [bcgov/CONN-CCBC-portal#279]
### User Story
As an applicant
I want to upload multiple files to some file upload sections
so that I can submit all the necessary files.

### Description
The following file uploads take multiple files: Copies of registration and other relevant documents, Independently prepared financial statements for the last three (3) years, Community and Rural Development Benefits supporting documents, and Evidence of connectivity speeds

### Dev checklist
- [x] ...

**Comment by elliottSlee** [comment]
@matthieu-foucault, @marcellmueller, @AntBush Could you add the necessary tasks for this card?
