### ISSUE TITLE
User session expiration handling

### ISSUE THREAD

**Issue by eazeredo** [bcgov/CONN-CCBC-portal#28]
### User Story
As an applicant
I want to be able to logoff
so that I can close my session and come back to it later without compromising the security of my application(s).

### Acceptance Criteria
- [x] Logoff SSO
- [x] Logoff BCeID
- [x] Logoff App
- [x] Session expiration handling ([session expiry modal](https://www.npmjs.com/package/@bcgov-cas/sso-react))
- [x] After re-login, you are redirected to the previous page

**Comment by eazeredo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/28?planning-poker) with ZenHub @AntBush @marcellmueller @wenzowski

**Comment by wenzowski** [comment]
Presumably we'd want to reuse [@bcgov/sso-react](https://github.com/bcgov/cas-template-app/tree/develop/packages/sso-react) component for this

**Comment by wenzowski** [comment]
We're goint to need to modify the the [workaround implemented by CAS](https://github.com/bcgov/cas-template-app/blob/develop/packages/sso-express/src/controllers.ts#L21) since it relies on being on the gov.bc.ca domain to nuke the `SMSESSION` cookie. Instead we'll have to implement [the chained logout approach](https://github.com/bcgov/entity/issues/12565).

**Comment by MarsRomer** [comment]
@marcellmueller  how long is the session expiry time?

**Comment by MarsRomer** [comment]
when the session expires, should it keep you on the same page or should it load the landing page?  Currently it keeps me on the same page where I was (Review Page)

**Comment by MarsRomer** [comment]
@elliottSlee @zoeyli-46 do either of you know what we meant by this:
[ }  After re-login, you are redirected to the previous page

**Comment by elliottSlee** [comment]
I'm not sure what that redirection means. @eazeredo do you know?

**Comment by matthieu-foucault** [comment]
I see that the session expires even as the user is active on the page, we probably want to change this setting to `true`: https://github.com/bcgov/CONN-CCBC-portal/blob/46d7ff846f3314d635e54903344c2d3ccf9ee75f/app/components/SessionExpiryHandler.tsx#L67

**Comment by matthieu-foucault** [comment]
Redirection means that, once you log in after you session times out (or if you request a page that is access-protected), you are seeing the requested page after logging in, instead of the dashboard. This was implemented in the CAS projects, with a `login-redirect` page

**Comment by VB-at-Bis** [comment]
Submitted new PR: https://github.com/bcgov/CONN-CCBC-portal/pull/409

**Comment by MarsRomer** [comment]
Are all the items in the acceptance criteria checklist completed?

**Comment by eazeredo** [comment]
@MarsRomer , all good here. You can test it.

**Comment by MarsRomer** [comment]
Hi @VB-at-Bis how long did you make the timeout modal countdown for?  I think it's set to 20 min currently, weren't we thinking of setting it to 2min?
![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/a9e87221-2581-488b-a391-6f7a3b4d73a7)

**Comment by VB-at-Bis** [comment]
Hmm.. in settings we have `modalDisplaySecondsBeforeLogout={120}` which means 2min .. (https://github.com/bcgov/CONN-CCBC-portal/blob/main/app/components/SessionExpiryHandler.tsx#L64) 
I'll check how it is handled in '@bcgov-cas/sso-react'

**Comment by VB-at-Bis** [comment]
@matthieu-foucault .. Can you please check if we set the SessionTimeoutHandler properly? In the README I see references to `sessionRemainingTimePath` server route that seems to be contributing in calculation of the modal display duration, but I dont see it being set in CIF project which we use as a reference.

**Comment by matthieu-foucault** [comment]
I cannot identify the source of this issue, and I can't reproduce it either. @VB-at-Bis can you reproduce it? @MarsRomer , any extra details on what you did to see the modal above? Was the browser tab active?

**Comment by MarsRomer** [comment]
@matthieu-foucault  @VB-at-Bis interesting that you can't reproduce it.  I wonder why it would be happening to just me.  I can't remember if the tab was active or not, I think I was working on other things but the tab was most likely not active.  It happened to me again yesterday during one of our meetings, you would have been able to see it on my screen, though I didn't bring attention to it.  I can leave my session running again today to see

**Comment by MarsRomer** [comment]
I'm going to move this forward but create a bug ticket to fix the 20min timeout issue, the reason is that we can live with the bug for now, but there are more important things to do and I don't want to take up all our time working on this.
