### ISSUE TITLE
Validate required checkbox fields on the Acknowledgment page

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#280]
### Description
**Declarations page**
https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=1630%3A5945

### Acceptance Criteria
- [x] **Scenario: disable/enable continue button on 1st declarations page**
Given I'm on the 1st Declarations page
While one or more checkboxes fields are not checked
Then the "Continue" button is disabled 
#
- [x] **Scenario: disable/enable complete button on 2nd declarations page (now called Submission page)**
Given I'm on the 2nd Declarations page (Submission page)
While one or more input fields are empty 
Then the "Submit" button is disabled 
#

![Screen Shot 2022-07-04 at 12.40.23 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/e580e1ed-e26d-417b-b9dc-62818dc938c3)
![Screen Shot 2022-07-04 at 12.40.39 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/82ea3923-e48e-4372-a831-7ad01b6ce3b3)
#
![image.png](https://images.zenhubusercontent.com/61e8875b1de5eff8f072cd04/b751c82e-04b8-4fda-8bbc-2d8ecc33a842)![image.png](https://images.zenhubusercontent.com/61e8875b1de5eff8f072cd04/57e3c34f-ae5b-4c24-9185-351ffdd1196c)

**Comment by eazeredo** [comment]
@AntBush , do we have a Draft PR for this?
