### ISSUE TITLE
Uppercase the defined terms

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#281]
The application guide has defined terms that need to be in upper case in the application guide and on the application portal.

All the defined terms below are in the application webform and need to be changed.

### Defined terms to change

- [x] Applicant
- [x] Application Form
- [x] Backhaul/Backbone Access Points
- [x] BCeID Business or Basic account
- [x] Broadband Service(s)
- [x] Confidential
- [x] Coverage
- [x] CRTC
- [x] Declarations
- [x] Eligible Costs
- [x] Logical Network Diagram
- [x] Network (see comment below)
- [x] Passive Infrastructure
- [x] Point-of-Presence (PoP)
- [x] Program (the Connecting Communities BC Program. The term Program or CCBC may be used interchangeably.)
- [x] Project (the activities described in the application for which Program funding is being requested.)
- [x] Project Budget
- [x] Project Completion Date
- [x] Project Start Date
- [x] Project Costs
- [x] Project Zones
- [x] Proprietary
- [x] Scalability
- [x] Speed Test
- [x] Third Party

**Comment by MarsRomer** [comment]
Hi Elliot, are you able to look in the Application Guide to see how they have handled this before we decide.  If I get a moment I can ask Maria too

**Comment by zoeyli-46** [comment]
We have not changed network in the page titles as titles are all sentence case, but it is all capitalized throughout the form elsewhere

cc: @marcellmueller

**Comment by marcellmueller** [comment]
@MarsRomer Zoey and I went through this today. Normally I wouldn't ask you to look at a PR but seeing as it is all text changes can you please take a quick look through the changed files in this and see if there is any changes we should make before we merge this in? Thanks!

https://github.com/bcgov/CONN-CCBC-portal/pull/324/files

**Comment by MarsRomer** [comment]
hey @marcellmueller  thanks for the opportunity to look through the PR, I find it quite challenging to look at it this way though.  I prefer to see it on the UI so that I can see the change in the context of the entire form and application portal.  Is there another way to look at this before you merge but in the UI?  perhaps on your local if you share your screen?

**Comment by zoeyli-46** [comment]
Should this be moved to PO review now that all have been changed?

**Comment by MarsRomer** [comment]
@marcellmueller  I'm satisfied if Zoey has done a review here, I will look at it in test so feel free to push it through when you want

**Comment by marcellmueller** [comment]
@MarsRomer sounds good, incoming shortly!
