### ISSUE TITLE
Update required fields throughout form

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#283]
### Description
Some fields are currently marked as optional but are actually required.

#### Other funding sources
- [x] If answer to first question (Will you have other funding sources?) is yes, subsequent fields should be required except Name of program and amount requested by year
><img src="https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/a911e060-f8af-4ffa-a980-655ff586b31f" alt="Other funding sources screenshot" width="80%"/>

#### Technological solution
- [x] All fields are currently optional but should be required

#### Project planning and management
- [x] All fields are currently optional but should be required

#### Supporting documents upload
- [x] Community and Rural Development Benefits supporting documents should be required

#### Authorized contact
- [x] Family name is currently required but should be optional
- [x] Given name is currently optional but should be required

#### Alternate contact
- [x] Family name is currently required but should be optional
- [x] Given name is currently optional but should be required

**Comment by elliottSlee** [comment]
@MarsRomer @zoeyli-46 Usability testing showed a few fields marked as optional should be marked as required, so I created this ticket for it.

**Comment by MarsRomer** [comment]
looks good!  Only a couple of things I noticed.  
1. it should not say optional in the Name of Program text on the Other Funding Sources page.
2. some of the spacing between lines seems tight on the Other Funding Sources page (see scren cap below)
![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/f359e147-d20d-41a4-bb61-3aea6cf1223b)

**Comment by marcellmueller** [comment]
@MarsRomer the first checkbox of this ticket says that Name of program text is optional:

"If answer to first question (Will you have other funding sources?) is yes, subsequent fields should be required except Name of program and amount requested by year"

**Comment by MarsRomer** [comment]
@marcellmueller  yes and it already says '(if applicable)' so the word 'optional' is redundant

**Comment by MarsRomer** [comment]
@marcellmueller  there are a few more that I think weren't asked for in this ticket, would it be ok to add them or would you prefer a separate ticket?

**Comment by marcellmueller** [comment]
@MarsRomer another ticket would be nice, it should be an easy one so I’ll get to it asap.
