### ISSUE TITLE
Define release process to Production

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/CONN-CCBC-portal#292]
We need a documented release process and tooling to ensure that the proper guardrails are in place before deploying changes to production, and changelog generation to help identify what changes are about to be deployed. 

- [x] Needs some discussion on how often we want to deploy to prod (bi-weekly? Weekly? Everyday? (never Friday)) 

- For now, update frequency is once a week

- [x] See https://github.com/bcgov/cas-cif/pull/784 for an example of sqitch guardrails (Risk without sqitch guardrails: High - code for prod could change in test but not get applied to prod.)

- [x] Need dev team discussion and document release process and implementing changes (e.g. use semver parser, deploy RC tags to test, ...)

**Comment by eazeredo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/292?planning-poker) with Zenhub @AntBush @marcellmueller @matthieu-foucault @wenzowski

**Comment by AntBush** [comment]
From Mars: Once a week but never on Fridays to start

**Comment by matthieu-foucault** [comment]
@wenzowski , you were considering using tags to deploy to test and prod, was the idea to have GH actions automatically deploy to test/prod upon creation of a tag? 

When would sqitch tags be created and committed to the repo?

**Comment by wenzowski** [comment]
Yes the idea was to have GH actions automatically deploy to test/prod upon creation of a tag, and use gh actions to validate the tag is a commit in main, semver validate that tag represents a release increment (ie not a version less than current latest git tag in repo), that commit is deployed to dev, generate changelog from conventional commits (GH actions committing), generate and commit sqitch tag from git tag, run usual CI on resulting commits, and deploy. Or something like that. I'm in favor of simple, given time constraints, so if there's something that works differently we can proudly find elsewhere let's just be absolutely sure we're enforcing immutability of sqitch migrations as of latest tag via CI.

**Comment by matthieu-foucault** [comment]
For a simple version, generation of tags could be done manually, with a single `make release` command. 
A PR would have to be pushed and reviewed.
This could be updated to be a GH workflow later

Sqitch guardrails would ensure that:
 - the plan ends with a tag before deploying to test
 - changes before a tag are immutable

**Comment by wenzowski** [comment]
Works for me. Can we adopt a branch naming convention for the simple version?

**Comment by matthieu-foucault** [comment]
all of them are called `chore/release` ?
