### ISSUE TITLE
Remove dashboard link on landing page for not logged users

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#294]
As an applicant
I want the dashboard link to not be visible in the header when I'm not logged in
so that I can only see actions that I can do.

### Description
Currently, when on the landing page & not logged in, the dashboard link is visible in the header. It would be nice to have it removed when not logged in.

### Acceptance Criteria
Given that a user is not logged in
when they are on the landing page
then the link to the dashboard in the header will not be visible.

>![Screen Shot 2022-07-06 at 11.02.28 AM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/c13eec0a-1b91-478d-ab8d-1a72853379a9)

**Comment by VB-at-Bis** [comment]
PR https://github.com/bcgov/CONN-CCBC-portal/pull/408
