### ISSUE TITLE
Automate fields on Submission page

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#295]
### User Story
As an applicant
I want the fields "Completed for" and "On this date" to be auto-populated on the submission page
So that I don't make preventable mistakes.

### Description

[Wireframe](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=3229%3A12828)

### Acceptance Criteria:
- [x] Replace input field **Completed for** with the [Organization name (legal name)] field value that was entered on Organization profile page
- [x] Completed on date - Draft
Given that an application is in _Draft_ status
When the applicant is on the submission page
Then the current date will be displayed beside Completed on
- [x] Completed on - Submitted or beyond
Given that an application is in any state other that _Draft_
When on the submission page
Then beside the completed on will display the date submitted 

- [x] **If** the field [Organization name (legal name)] is empty
**Then** it shows the error message "No legal organization name was provided. Please return to the <ins>Organization Profile</ins> page (link to the page) and enter one." 

![default state](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/82cc57de-a208-4ab4-a546-3ccb135a6770)

![error state](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/79ed8d87-2280-4431-bab2-0fbae0094776)

**Comment by eazeredo** [comment]
@zoeyli-46 and @elliottSlee, Where is the field [Applicant Legal Name]?

**Comment by elliottSlee** [comment]
I removed:
- [ ] "Completed for" and "Completed on" fields are saved in the database
because these are not in the csv from ISED. Additionally, Completed for is already in the database from the org profile page and Completed on is already being saved with Application - Mark as complete (aka Submit) #92

**Comment by matthieu-foucault** [comment]
@elliottSlee , if the application is already submitted, should "Completed on" display the submission date instead?

**Comment by elliottSlee** [comment]
@matthieu-foucault Good catch. Acceptance criteria's updated.
