### ISSUE TITLE
Migrate keycloak to gold cluster

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/CONN-CCBC-portal#296]
Our keycloak clients are using the silver cluster, which will be unsupported as of January 2023. 

- [x] Request Gold keycloak integration
- [x] Update SSO middleware with new url and realm
- [x] Refactor database to new sub type
- [x] Update client secrets in github environments (after review/merge but before deployment)

Todo:
- [x] Follow up on redirect uri error issue (SSO team says fix incoming)
- [ ] <s>Follow up on Github authentication. Our team will have to use IDIR for now.</s>

**Comment by matthieu-foucault** [comment]
@marcellmueller , do you know if we have any actual data to migrate to gold, or if we should just create a new project via the CSS app? Given that we're not in prod yet, I would assume we don't have any users to migrate, since the db will get reinitialized upon deploying, right?

**Comment by marcellmueller** [comment]
@matthieu-foucault I don’t believe we have any data that would need to be migrated. This would also solve our current account issue so it seems like the best path forward.

**Comment by wenzowski** [comment]
JSON for each environment [provisioned via req 3934](https://bcgov.github.io/sso-requests/request/3934?status=applied) & provisionally copied to 1Pass for installation into pipeline

**Comment by MarsRomer** [comment]
Hey @marcellmueller  would you mind adding a comment to note why this is blocked please :)

**Comment by marcellmueller** [comment]
@MarsRomer apologies. It's blocked because the team needs IDIR access and emails.
