### ISSUE TITLE
Application - Create a Organization Profile form

### ISSUE THREAD

**Issue by eazeredo** [bcgov/CONN-CCBC-portal#30]
As an Applicant
I want to create my organization profile
So that I can report who I am

What is not included in this story:
- The navigation sidebar.
- Help link
- Back link
- Logoff link
- autosave

**Actor**
-
- External User - Applicant

**Screen**
-
- Organization Profile 
**Wireframe**
https://www.figma.com/proto/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=647%3A2355&scaling=min-zoom&page-id=647%3A2321

**Fields**
-
**Source of Truth for Questions**
Full information for input fields such as max length for text fields and the contents of drop-downs can be found in the Research channel Files/[DataMapping.xlsx](https://bcgov.sharepoint.com/:x:/r/teams/04708/Shared%20Documents/Research/DataMapping.xlsx?d=w5224cb99a79b48008b9105279418b6e3&csf=1&web=1&e=k1VR5C)

**Validations**
-
- none

**Actions**
-
- Save in the database 
- Show the success page/message (https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=647%3A3003)

---
- [x] posting to database
- Styling (adding BC gov theme)
- [x] Header
- [x] Footer
- [x] Form field - Input
- [x] Form field - Radio
- [x] Form field - Radio Yes/No
- [x] Form field - Datepicker
- [x] Form field - Textarea
- [x] Form buttons
- [x] Success Page

---  
- [ ] application number
- [ ] form status

**Comment by zoeyli-46** [comment]
Here is a link to our Figma wireframes https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=0%3A1

**Comment by eazeredo** [comment]
@rgreensp , can you confirm the structure of the "Application Number"?

**Comment by BryanGK** [comment]
Form issue list:
- "Other" option for org type, having the text input there may be difficult (don't know how)
-

**Comment by BryanGK** [comment]
Form issue list (for designer discussion):

Budget page:
- drop down menus 'status of funding' and 'funding type' do they have more options available?

**Comment by BryanGK** [comment]
Trying to fix form issues - BLOCKED by #82

**Comment by wenzowski** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Connectivity-Intake-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/30?planning-poker) with ZenHub @BryanGK @marcellmueller
