### ISSUE TITLE
Add new upload

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#303]
### User Story
As an applicant
I want to upload the ISED coverage stats email
so that I can provide the full application package.

### Description
On the mapping page, a new upload field is needed called ISED's Eligibility Mapping Tool - Coverage Assessment and Statistics.

- [x] single file upload

![Screen Shot 2022-07-12 at 2.23.21 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/b1ce7419-fe8f-4011-bcb5-3fbdd6ed9d33)

**Comment by MarsRomer** [comment]
(optional) needs to be removed but that is part of ticket #283
