### ISSUE TITLE
Change "Please specify the last mile technology type" checkbox field to required

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#304]
### User Story
As an applicant
I want to be notified if I don't select the field "Please specify the last mile technology type" on the Technological solution
page
so that my project will be categorized as the correct type.

### Description
The last mile technology is an important question and needs to be a required question.

### Acceptance Criteria
- [ ] **Scenario: none selected gives error on review page**
Given that an applicant has _not_ selected any last mile technology checkboxes
when they are on the review page
then the question will be flagged as missing.

- [ ] **Scenario: at least one selected give no error review page**
Given that an applicant has selected at least one last mile technology checkboxes
when they are on the review page
then no error message will appear.

**Comment by zoeyli-46** [comment]
@elliottSlee was this not showing up as required? When testing, it works as of today so we closed this ticket during refinement

**Comment by elliottSlee** [comment]
It works! This ticket was created mainly for the review page.
