### ISSUE TITLE
Add statement about ISED

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#306]
Landing page new text with ISED statement, with adjustments from Legal:
https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=4188%3A16509
This is the statement to add 
> "Despite the streamlined application process, ISED has its own decision-making process and the Province does not represent ISED or make determinations regarding the UBF. "

See design below
Links not created yet 

![Screen Shot 2022-08-23 at 10.06.46 AM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/b0f01091-a3a8-45a9-bdb9-ae771ec8de60)

**Comment by MarsRomer** [comment]
@elliottSlee @zoeyli-46 this is the ticket for the statement we need to add in lieu of ISED logo

**Comment by MarsRomer** [comment]
Currently blocked by required legal review

**Comment by zoeyli-46** [comment]
We received the updated wording on landing page from Legal, but during our meeting on July 29 with ISED they suggested adding in a sentence that would need to be reviewed by Legal, if we want to add in the statement.

 

**Original statement:** 
CCBC is a program jointly funded by Canada and British Columbia. Applications selected by CCBC may be funded by both the Province and Innovation, Science and Economic Development Canada's (ISED) UBF.

 

**New statement:**
CCBC is a program jointly funded by Canada and British Columbia. Applications selected by CCBC may be funded by both the Province and Innovation, Science and Economic Development Canada's (ISED) UBF. **However, ISED does not delegate BC the authority to act on behalf of ISED.**

**Comment by eazeredo** [comment]
Is this unblocked?

**Comment by elliottSlee** [comment]
cc @zoeyli-46

**Comment by zoeyli-46** [comment]
@MarsRomer can we confirm if we want to add the additional statement about ISED? 

additional statement in bold:
CCBC is a program jointly funded by Canada and British Columbia. Applications selected by CCBC may be funded by both the Province and Innovation, Science and Economic Development Canada's (ISED) UBF. **However, ISED does not delegate BC the authority to act on behalf of ISED.**

**Comment by MarsRomer** [comment]
I will check with what was decided for the wording in the Guide and copy paste that I think

**Comment by MarsRomer** [comment]
This is unblocked now, we have decided on the wording

**Comment by AntBush** [comment]
To be clear, the "However, ISED does not delegate BC the authority to act on behalf of ISED." is what we want to add to the statement correct? It's what I've added for this PR

**Comment by elliottSlee** [comment]
@AntBush It should say, "Despite the streamlined application process, ISED has its own decision-making process and the Province does not represent ISED or make determinations regarding the UBF."
Sorry for the confusion in the card & the comments.
