### ISSUE TITLE
Application - List (aka Dashboard)

### ISSUE THREAD

**Issue by eazeredo** [bcgov/CONN-CCBC-portal#31]
### User Story
As an Applicant
I want to view my applications on one page,
So I know what applications I have created

### Research & Design
https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=1331%3A5987

### Acceptance Criteria
- [x] Scenario: Visualize my applications
	Given I am a logged applicant 
	And I have created at least one application
	When I open the dashboard page
	Then I see a list of my applications (Bug #341)
- [x] Application ID, shortened Application name, status are piped in
- [x] Scenario: Visualize New Application button
	Given that I am on the dashboard page
	When I click on New Application button
	Then I see the first page of a new application
	And a new application is added to the dashboard
- [ ] <s>Applications should be shown in order of last edited, not in order of CCBC ID</s>
- [x] sorted by newest creatd at top
#

![image.png](https://images.zenhubusercontent.com/61e8875b1de5eff8f072cd04/11da9832-5a10-4869-bac5-5653ab579a9f)
### Not included
- Don't implement "Edit". It has its own card #34
- Don't implement "Withdaw"
- Don't implement a way to open an existing application. It has its own card #236

### Empty state of dashboard
- [ ] Updated text on the dashboard's empty state. The text currently says "No applications yet
Start a new application; applications will appear here". This has been updated to:

"Start a new application; applications can be saved and edited until the intake closes on YYYY/MM/DD /n Applications will appear here"

This sets the expectation that applications do not need to be finished in 1 go and a reminder of when the intake closes. The button and text placement have been swapped so that the order of the page is page title, page description, button, to be consistent with all of the other pages. 

![image.png](https://images.zenhubusercontent.com/61e8875b1de5eff8f072cd04/2794474e-8863-4dcb-a299-fa73d5a32a45)

**Comment by eazeredo** [comment]
@elliottSlee , I rewrote the acceptance criteria below. What do you think?

- [ ] Scenario: Visualize my applications
	Given I am a logged applicant 
	 And I didn't create an application
	 When I open the dashboard page
	 Then I see an empty list of applications
#
- [ ] Scenario: Visualize my applications
	Given I am a logged applicant 
	And I have created at least one application
	When I open the dashboard page
	Then I see a list of my applications
#
- [ ] Scenario: Action - Redirect to the application
	Given I can see the list of my applications
	When I try to edit an application
	Then I am redirected to the first page of the respective application
#
- [ ] Scenario: Visualize New Application button
	Given I am a logged applicant  
	When I open the dashboard page
	Then I see the New Application button
#
- [ ] Scenario: Action - Redirect to the new application form
	Given I am visualizing the New Application button
	When I click on it
	Then I am redirected to the first page of the application form 
#

@Skip @Not_included 
Scenario: Action - Withdraw an application
	Given I can see the list of my applications
	When I try to withdraw an application
	Then a confirm message "Are you sure that you would like to withdraw this application?" with "Yes" and "No" buttons
	When I select "Yes"
	Then the status of the application is changed to "Withdraw"

**Comment by elliottSlee** [comment]
@eazeredo Looks good. I think there may be a typo in there where you tagged someone @ Skip. You may want to remove that.

**Comment by zoeyli-46** [comment]
@eazeredo I edited the first scenario, when the applicant logs in instead of seeing an empty application list, they should see the text "Start a new application, applications can be edited until the intake closes on MM/DD/YYYY" 

--- Design reasoning ---
The reason why we took out the empty application list is that we want to avoid information that distracts the applicant from the key action on the page which is to start a new application. By letting them know that applicants can be still edited, it sets the expectation that they don't need to complete applications in one go.

**Comment by MarsRomer** [comment]
The status is listed but not correct, all applications show as draft despite some of them being complete or submitted

**Comment by eazeredo** [comment]
#92 is the card where we change the status. When 92 is ready, we will see applications with status = "Submitted".

**Comment by MarsRomer** [comment]
@elliottSlee @zoeyli-46  were we thinking that the list of applications would be ordered with newest application at top or bottom?  and does the edit date play into the ordering at all?

**Comment by elliottSlee** [comment]
Great question. We don't have any insight from research for the applicant view and we're currently exploring that question for analysts.
Personally, I feel CCBC ID would be a good default order (same as date created). Do you think we'll have the opportunity to include sorting & filtering during release 1?

**Comment by MarsRomer** [comment]
@elliottSlee I don't think we will have time to include filtering, but this ticket included sorting by last edited.  Only submitted applications will have a CCBC ID so I'm not sure if that would work.  since we are not providing a 'created on' date and 'last edited' date on the dashboard, I kinda feel that most recently created should be on top, this will give them a list that is a bit more static in it's ordering and not shift around everytime they edit one.   Making it more predictable for them where to find which application in the list.  We could test this out in our user research.

**Comment by MarsRomer** [comment]
that's a good point too! :)

**Comment by MarsRomer** [comment]
@AntBush can we please have the list of applications on the dashboard sorted by newest creatd at top?
