### ISSUE TITLE
Helm chart linting in CI

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/CONN-CCBC-portal#322]
We need to add a step to lint and verify our Helm chart in CI before a branch can be merged into main.

Risk of downtime if SSL certificate needs to be re-issued/requested from Entrust

- [ ] SA in our tools namespace that has permission to lint
- [ ] https://github.com/bcgov/cas-cif/blob/develop/.github/workflows/lint-chart.yml

**Comment by eazeredo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/322?planning-poker) with Zenhub @AntBush @marcellmueller @matthieu-foucault @wenzowski

**Comment by wenzowski** [comment]
https://github.com/bcgov/cas-cif/blob/develop/.github/workflows/lint-chart.yml

**Comment by elliottSlee** [comment]
https://redhat-cop.github.io/ci/linting-testing-helm-charts.html
