### ISSUE TITLE
Export attachments to ISED - ZIP file

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#328]
### User Story
As an Analyst 
I want to download all the attachments for applications,
so that they are in one place to send to ISED

**The process**
Analyst downloads attachments from the Dashboard to their local drive.
Analyst uploads the zip file into SharePoint.  Renaming of files is handled by this API.

1st Alternate solution:  Build a secure API to download all attachments ~~(filtered as needed)~~.  API provides date that attachment was uploaded so that ISED can see when it was uploaded.  Re-naming is handled by this API.

<s>2nd Alternate: Analyst or admin clicks a 'download for ISED' button and the attachments automatically download into a Sharepoint site below

NWBC and ISED  have a Teams channel where files can be stored on the Sharepoint.  Max storage in this space is 200GB of which 199.95GB are still available.  
https://bcgov.sharepoint.com/teams/053702/Shared%20Documents/Forms/AllItems.aspx?FolderCTID=0x012000CA34C709521FD04A89C9C95DF25451BE&id=%2Fteams%2F053702%2FShared%20Documents%2FGeneral%2FCCBC%5FApplications&viewid=f1e5a84d%2D914a%2D4255%2Db7b4%2Db0a5b94b7be3
</s>
### Acceptance Criteria
- [x] **Export attachments button begins download**
Given that an analyst is on the dashboard 
when they click the Export Attachments button
Then a download will begin of all the attachments of all of the applications as a Zip file with the name "CCBC attachments - [currentdate].zip"
Example: `CCBC attachments - 20230115.zip`
#
 - [x] **Rename files**
Given that an analyst is on the dashboard 
when they click the Export Attachments button
then the filenames will have their CCBC ID as a prefix
Example: `Template 1.xlsx` -> `CCBC-010001 - Template 1.xlsx`
#
- [x] Folder Structure:
![Screen Shot 2022-11-01 at 3.35.58 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/42a9b33a-b1f1-4f82-8e74-303514595613)
#
- [x] **Cancel download**
Given that an analyst has clicked "Export attachments"
and the download has begun
when they cancel it through their browser
then the download will stop

### Wireframe
https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=7010%3A35991

![Dashboard export.jpg](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/192fdb04-77b1-46ac-9af8-5cf6ffe4042a)

**Comment by AntBush** [comment]
Are we going the sharepoint route for this? I remember discussion around this to have this available as a download instead of us dropping it in sharepoint

**Comment by MarsRomer** [comment]
Sharepoint is a possibility.  Ideally I would like to implement the effort that requires the least amount of effort on our side to build and test that with ISED to see if it works for their needs.

**Comment by wenzowski** [comment]
I'd lean towards zip on the fly with something like [archiver](https://github.com/archiverjs/node-archiver)

**Comment by eazeredo** [comment]
@MarsRomer The team can implement the feature, but can't test it as the system cannot identify a profile that can access multiple applications (e.g.: Analyst)

For now, the feature can be tested as the Applicant.

**Comment by elliottSlee** [comment]
@zoeyli-46 we've heard this will require a UI. Can we define the user story, how they want it organized (we have it in our note), and full acceptance criteria? Then we can work on a wireframe?

**Comment by zoeyli-46** [comment]
Can we edit the first acceptance criteria to 
- [ ] Bulk export applications with the Status is not ("Withdrawn", "Closed") AND the Eligibility Assessment outcome is Eligible. 

Do we need ability to export based on a filter? NWBC has mentioned wanting to send off the top 10 applications in package 1 to ISED first, and then send off more later on. An export by filter can work by: Filter > Package > Package 1 > Export. Otherwise, NWBC can do this sorting the top 10 applications in their downloads after. 

Do we want to add in the miro frame with the ISED file structure to this card, so we can see what the file structure looks like

**Comment by elliottSlee** [comment]
This is blocked by understanding how ISED will receive files. We are waiting for their sftp to see capabilities & discuss with dev team what we can & should provide.

**Comment by eazeredo** [comment]
@elliottSlee Let's see if we need to simplify this card, as what we are building for the MVP is just the export ALL (we don't have filters yet)

**Comment by zoeyli-46** [comment]
@eazeredo should this ticket be merged with #747? Also to simplify the card I propose this AC: 

 - [ ] Given that an analyst is on the dashboard and has clicked the Export Attachments button
then a download will begin of all the attachments of all of the applications as a Zip file with the name "UBF-BC-CCBI-XXXX"

**Comment by elliottSlee** [comment]
Discussion on scrum team channel on November 1, 2023 about how to handle download: ![Screen Shot 2022-11-02 at 12.16.40 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/3238df1d-8feb-4dc8-9a85-18666062f595)

**Comment by marcellmueller** [comment]
@MarsRomer there is a fix incoming for this. Anthony's PR that got merged yesterday changed how we handle form data so I need to make a minor update to this.

**Comment by MarsRomer** [comment]
I see that test was deployed 34 min ago so I think this ticket should be ready to test?  If so I am getting a network error (see bottom left of screen shot)
![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/6fe560bd-52cf-4c5b-9f7f-e70f431f5106)

**Comment by marcellmueller** [comment]
@MarsRomer I'm having issues with it in test though it's working great on my machine. Sorry about this, trying to debug it.

**Comment by marcellmueller** [comment]
@MarsRomer I've tested this in dev with a few applications and about 150MB total attachments and the upload fix and it's working well. I think all that is left is to discuss what to do with the applications in `test` that have bad files attached to their form data. 

We can discuss at standup what options we have tomorrow though I'd like to keep as many of the test applications in there as possible.
