### ISSUE TITLE
Analyst Dashboard - Column sorting

### ISSUE THREAD

**Issue by eazeredo** [bcgov/CONN-CCBC-portal#33]
## User story
As an analyst, 
I want to be able to sort by the column headers, 
So that I can easily find an application

## Acceptance Criteria
- [x] Column heading & icon are clickable
icons: 
sort-up https://fontawesome.com/icons/sort-up?s=solid&f=classic
sort-down https://fontawesome.com/icons/sort-down?s=solid&f=classic
colour: 939393
size: width 1.25 em (if this looks terrible, feel free to change it)
- [x] cursor changes to a pointer when hovering over the the column heading and icon
#
- [x] Colors: 
- First click changes bottom arrow colour to 3D9B50 & top arrow remains 939393
- Second click changes bottom arrow back to 939393 & top arrow to 3D9B50
- Third click goes back to First Click above
![image.png](https://images.zenhubusercontent.com/606c9d37b7ff542cfdb25c53/4193fc7a-6194-4813-97dc-54325acb0a43)
#
- [x] When a sort has been selected, the words "Clear sorting" appear 24px above the table
text colour is 3F5986
#
- [ ] <s>Null values are at the top of the list on the first click and the bottom of the list on 2nd click</s>
#
- [x] CCBC ID order
First click - Ascending (0 - 9)
Second click - Descending (9 - 0)
#
- [x] Status order
First click:
> Received
> Screening
> Assessment
> Recommendation
> Conditionally approved
> Approved
> Complete
> On hold
> Withdrawn
> Cancelled
> Closed

2nd click is the reverse of above
#
- [x] Sort by Project Title
First click - Ascending (Null-A-Z) 
Second click - Descending (Z-A-Null)
#
- [x] Scenario: Sort by Organization
First click - Ascending (Null-A-Z) 
Second click - Descending (Z-A-Null)
#
- [x] Scenario: Sort by Lead
First click - Ascending (A-Z-Null) of the first name ( unassigned at top)
First click - Descending (Null-Z-A) of the first name (unassigned at bottom)

## Not included
- Multiple sorting

## Ultra refinement
- DB:
- [ ] .
- Frontend:
- [ ] . 
- Integration/API:
- [ ] .
- Tests:
- [ ] .
- Documentation:
- [ ] .

## Wireframe
![Sort.jpg](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/34bda1dc-40e2-49ba-a15a-3198149f0b7c)
![Sort descend.jpg](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/20d567ec-423f-4da6-9e50-f6b17027daa6)
![sort ascend.jpg](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/53992f4d-f2d6-4a7c-a2f1-673f40b6d707)

**Comment by elliottSlee** [comment]
@zoeyli-46 we can adapt this ticket

**Comment by zoeyli-46** [comment]
If an auto-complete list is difficult to create if there are many applications, then only displaying results that match the exact values of the search is fine

Should status column be multi-select?

**Comment by AntBush** [comment]
Columns can be added as comments for computed columns, so we all columns should be supported

**Comment by carreenu** [comment]
Functionality mostly working. Note that Project title column blanks are ordered at the bottom of alphabet, which is not a problem. However "unassigned" in the Lead column doesn't seem to sort. See attachment. Do not move to Sprint Done yet![Screenshot 2023-02-09 081453.png](https://images.zenhubusercontent.com/63d2ed3bbca5bfb5269f7981/daea97cf-30fa-444d-a228-4fb7c51150af).

**Comment by elliottSlee** [comment]
From what I can tell, the split of unassigned is that the ones on top were assigned to someone then changed back to unassigned and the bottom ones have never been assigned.
