### ISSUE TITLE
Practice Disaster Recovery

### ISSUE THREAD

**Issue by MarsRomer-zz** [bcgov/CONN-CCBC-portal#330]
Testing our backup process by restoring a backup to OCP

## Acceptance criteria:
- [x] Define what types or levels of "Disaster" this document will approach
- [x] Define what the Vendor team's responsibility is. 
- [Our shared responsibilities - BC Gov website](https://cloud.gov.bc.ca/private-cloud/your-product-team-in-the-private-cloud-paas/our-shared-responsibilities/)
- [Your plan for resiliency, reliability and continuous support - BC Gov](https://cloud.gov.bc.ca/private-cloud/your-product-team-in-the-private-cloud-paas/your-plan-for-resiliency-reliability-and-continuous-support/)
#
- [x] Create a CCBC Runbook for point-in-time recovery (Use CAS Runbook as inspiration)
- [x] Multiple team members have had the opportunity to go through disaster recovery together using the CCBC Runbook
- [x] Write the DR code
- [ ] Run CCBC Runbook in Dev or Test environment

**Comment by pdoc1111** [comment]
added Patroni documentation and recommendations for testing cluster switching and disaster recovery. See /docs/ccbc.disaster.recovery.patroni.txt
