### ISSUE TITLE
Export test data 

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#333]
ISED would like to have an export of our test data in json format so that they know what it is they will be getting from us.  
The export should have **enough test data** (perhaps multiple applications) so that we cover majority of the data fields and test case iterations of different data they may get.

Data team would like to have an export of our test data so that they know how they will be handling it for their analysis.

- [ ] <s>Export Application data (through Metabase)</s>

**Comment by eazeredo** [comment]
@MarsRomer , Ali is working on this front.

There is no development work for this card.
