### ISSUE TITLE
Application - Edit

### ISSUE THREAD

**Issue by eazeredo** [bcgov/CONN-CCBC-portal#34]
### User Story
As an Applicant
I want to be able to edit my application 
So that it can have the most recent information to be evaluated

NOTE:  Applicants can only edit their applications if the following conditions are met:
1.  Application = 'Draft' - can edit anytime

2. Application = 'Submitted' then they can only edit the application if the intake is open.  The intake in question is the intake in which they submitted the application.
e.g. Submitted application in intake 1, they can edit it until intake 1 ends.  After intake 1 ends they can't edit it.  If they submit another application in the second intake then they can edit it while intake 2 is open.

### Research & Design
https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=1331%3A5987

### Acceptance Criteria
- [x] Implement last edited page in the database
#
- [x] **Scenario: Edit a submitted application**
	Given I am an Applicant
	And the application has a "Submit" status (#92)
        AND the intake is still open
	When I click on edit 
	Then I am redirected to the first page of the respective application
	And I can edit all fields
#
- [x] **Scenario: Edit a draft application**
	Given I am an Applicant
	And the application has a "Draft" status 
	When I click on edit for an application
	Then I am redirected to the _last edited page_
	And I can edit all fields
#
- [x] **Scenario: Show "Edit" link**
	Given I am an Applicant
	And the application has a status Draft or Submit
	When I open the list of applications
	Then I see the edit button and I can edit the application content.

## Not now
- Application = 'withdrawn' then they can never edit it. They are taken to the review page, and they cannot edit the form, the form fields are disabled and if the user goes to another page there is a warning alert on the page that says "Withdrawn applications cannot be edited".

![image.png](https://images.zenhubusercontent.com/61e8875b1de5eff8f072cd04/9fb30fe9-6907-4aeb-8a1d-8ad25d4606b0)

![image.png](https://images.zenhubusercontent.com/61e8875b1de5eff8f072cd04/047deb6a-f140-4d53-8fce-623f76805ba9)

**Comment by eazeredo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/34?planning-poker) with ZenHub @marcellmueller @BryanGK

**Comment by zoeyli-46** [comment]
@elliottSlee acceptance criteria may change, noting this in a comment here. what the state is changed to (whether draft or complete, etc.) is to be finalized.

**Comment by zoeyli-46** [comment]
@elliottSlee can we edit the acceptance criteria for editing submitted application: 

Given I am an Applicant
And the application has a "Submit" status (#92)
AND the intake is still open
When I click on edit
A modal appears on the dashboard saying "Edits made to submitted applications will be saved automatically. You will not need to submit this application again" with a "Edit application" button
Then I am redirected to the first page of the respective application
And I can edit all fields
The status remains as "Submitted"
The autosave message changes to "Changes submitted: [Time]

**Comment by marcellmueller** [comment]
@zoeyli-46 just flagging this ticket is done and in review

**Comment by MarsRomer** [comment]
@marcellmueller can we temporarily set the intake end date to tomorrow morning so that I can test the scenarios where the intake is closed?

**Comment by marcellmueller** [comment]
@MarsRomer what are the scenarios you are looking to test in this card for after the intake has closed? I'm actually just worried we missed an acceptance criteria for what to do with submitted application after the form has closed. I assume it should show `View` and take them to review page?

As it currently is we are doing a check for the intake date for the first checkbox in this ticket. Though the behaviour is exactly the same as it always was, ie takes you to the first page of the form.

We aren't currently locking down the submitted pages after the intake closes as I think there is a ticket incoming about submitting attachments 30 days after the intake closes.

**Comment by marcellmueller** [comment]
@MarsRomer I just spoke to Zoey and it sounds like this is incoming in another ticket. I'm not sure the best way to show you that the code for the intake being closed is working given that the behaviour is the same as normal (starting on the first form page) but I'm happy to jump on a call.

**Comment by MarsRomer** [comment]
I am looking to see that when the intake closes that the submitted application is no longer showing an 'edit' button, instead it will have a 'view' button.  And when I click on it, it will take me someplace in the application (possibly the review page)
Also the draft applications will continue to show the edit button.
