### ISSUE TITLE
Others applications exposed when session logged off

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#341]
After logging in if I let my session idle for several minutes, clicking on the dashboard gives me access to applications that belong to me.  I can see them in the dashboard and click edit and see the contents of the application.  
The same happens when I log off and then click on the 'dashboard' link in the header.
Possibly related to #28

- [x] If a user is not log in, it should be redirected to login page.
- [x] Fix the API (add details here)
- [x] Add tests

![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/6afb40d3-70ac-4354-86be-69e3497a8c0d)

**Comment by VB-at-Bis** [comment]
Fix included in PR https://github.com/bcgov/CONN-CCBC-portal/pull/368

**Comment by VB-at-Bis** [comment]
Updated PR https://github.com/bcgov/CONN-CCBC-portal/pull/387 - added pgTap tests. 
Tests passed:
```
vb@vbpro:/mnt/c/Workspace/Button/CONN-CCBC-portal/db/test/unit/tables$ pg_prove -d ccbc ccbc_user_test.sql
ccbc_user_test.sql .. ok
All tests successful.
Files=1, Tests=21,  0 wallclock secs ( 0.03 usr  0.00 sys +  0.05 cusr  0.01 csys =  0.09 CPU)
Result: PASS
```
