### ISSUE TITLE
Link to BC Data Catalogue

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#343]
Provide a link to BC Data Catalogue on the Project Zones page for the applicant to be able to see the underserved areas.  This has yet to be set up in BC Data Catalogue but it will be similar to what was used for the RTP. 
Use this link --> https://catalogue.data.gov.bc.ca/group/connectivity-in-bc

The site will be set up by the data team.

**Comment by MarsRomer** [comment]
hi Zoey - lets work on this for sprint 8, we need copy and a strategic place to put this link on our application form.  I am not sure which page it will go on yet, but hoping it will become clear soon.

**Comment by zoeyli-46** [comment]
Is this to see where the 14 project zones are or is this just to see the areas that already have coverage/areas that do not have coverage yet within the 14 zones?

**Comment by MarsRomer** [comment]
its to see the underserved areas... we may discuss this at 4pm today

**Comment by MarsRomer** [comment]
BTW the data team has already created a group that we can use for the link:  https://catalogue.data.gov.bc.ca/group/connectivity-in-bc
The only thing we are trying to figure out is what data layers are we providing in this group

**Comment by zoeyli-46** [comment]
@MarsRomer If the goal of showing the underserved areas is for the applicant to know where they want to propose their project for, would it make the most sense to put it on Project Area page? If this is the case, we could just add it to the current question.

Current question:
"Referring to the project zones shown in the application guide, which zone(s) will this project be conducted in?"

New question with link:
"Referring to the project zones and underserved areas shown in the application guide, which zone(s) will this project be conducted in?"

cc: @elliottSlee

**Comment by MarsRomer** [comment]
Blocked as we need to decide where the link will present itself
