### ISSUE TITLE
UUID not storing with attachment

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#348]
In the database UUID is not being stored with the attachments

**Comment by marcellmueller** [comment]
Yes it is, it's under the file column as that is what the file names are in AWS. I can rename it to uuid if you want but other than that this is a non issue.

**Comment by marcellmueller** [comment]
@MarsRomer Okay I looked into this and you were right, I will fix this up sorry for the mix up. It is saving mine locally and some in the database so I thought it was all good.

**Comment by marcellmueller** [comment]
@MarsRomer fix for this incoming shortly, I appreciate the heads up

**Comment by marcellmueller** [comment]
Fixed, may have to reset database as attachments saved with no uuid can't be deleted.
