### ISSUE TITLE
Wording Updates

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/CONN-CCBC-portal#351]
**Landing page**
- [x] Landing page wording https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=3702%3A15006 

**Project information**
- [x] change page description to: For successful applicants receiving funding under CCBC, the contribution amounts will be made public via government websites, media releases or other similar materials. Information provided in the application may be used, in whole or in part to assist the Province of BC and ISED in the preparation of any public announcements. 
- [x] change question to: Project title. Be descriptive about the geographic region. Please refrain from using years in the title. 

**Project area**
Typo: If yes, select the provinces or territorities (check all that apply):
- [x] change to: If yes, select the provinces or territories (check all that apply):

**Existing network coverage**
Currently: Does the Applicant’s Project require access to Third Party Passive Infrastructure (including for example, towers, poles, rights of way or other similar assets and infrastructure)? 
- [x] Change to: Does the Applicant’s Project require access to Third Party Passive Infrastructure (i.e., towers, poles, rights of way or other similar assets and infrastructure)? 

**Benefits**
Add " - Eligibility Summary" to the counts
- [x] Add the bolded text: Final number of Eligible Households targeted by this proposal. This value should match cell F141 in Template 1 **– Eligibility Summary**.
- [x] Add the bolded text: Number of households on Indigenous lands impacted by this proposal. This value should match cell G55 in Template 1 **– Eligibility Summary**. 

**Estimated project employment**
Currently: Hours of employment per week (average hours/week)
- [x] Change to: Hours of employment per week (average)

Currently: Total person months of employment to be created (average months/year)
- [x] Change to: Total person months of employment to be created (average)

**Organization type**
Currently: "Please provide a short description of the Indigenous entity"
- [x] change to: Please provide a short description of the Indigenous identity

**Organization Profile** 
- [x] Change Organization Profile to Organization profile
- [x] Change '...you...' to 'your' in description at top

**Organization location** 
- [x] Change everything to sentence case: Unit number (optional), Street number, Street name, PO box (optional), Postal code (H0H0H0)

**Project planning and management**
- [x] change question to: Operational plan – Describe key factors to indicate how the project participants will be prepared to operate, manage and maintain the proposed broadband network including any external managed services which will support network management or operations functions. Identify how the project participants will ensure that the necessary sales, operational, technical and billing support systems are or will be in place to supply the proposed services.

**Template uploads**
- [x] change page description to: Please upload all templates. Please do not include special characters in the file name. The maximum size per file is 100MB. 

**Supporting documents**
- [x] change page description to: Please upload additional attachments. Please do not include special characters in the file name. The maximum size per file is 100MB.
- [x] change project schedule description to: "Project schedule (preferably a Gantt chart). Please refer to Annex 3 of the application guide for the Project schedule requirements. (optional)"
missing closing bracket - (required for fixed wireless Projects.
- [x] add missing bracket: "(required for fixed wireless Projects)."

**Declarations**
- [x] Rename the page with all the checkboxes to Acknowledgements. 
![image.png](https://images.zenhubusercontent.com/61e8875b1de5eff8f072cd04/dc94c5f7-4258-4ad4-ab0d-bfa30ea18594)

**Comment by zoeyli-46** [comment]
@marcellmueller have we already changed indigenous entity to indigenous identity in the form? I can't find if a ticket has already been logged for this

**Comment by MarsRomer** [comment]
@zoeyli-46  looks like entity was changed to identity in a couple of places in test but do we want to change this one too:
![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/9c07b3e6-fc6f-4c4a-a927-7198a3da1bce)

**Comment by zoeyli-46** [comment]
yes, the short description should be changed to "Indigenous identity"
