### ISSUE TITLE
CCBC ID tooltip on dashboard

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/CONN-CCBC-portal#360]
### User Story
As an applicant, I want a tooltip with an explanation for the CCBC ID and when it'll be assigned so I know what it is.

### Description
Show an explanation of the CCBC ID on the applicant portal.

### Acceptance Criteria
Given that an applicant is on the dashboard page
When hovering over the i 
Then the following text will appear above the i:
"A CCBC ID will be assigned when you submit the application"

Icon is from https://materialdesignicons.com/icon/information-outline

<img src="https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/b19ae5e9-bfa8-413e-88f4-1818dc00a6e5" width="75%">

~~See [accessibility suggestion](https://inclusive-components.design/tooltips-toggletips/)~~

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/360?planning-poker) with Zenhub @rafasdc @VB-at-Bis
