### ISSUE TITLE
Implement Authorization feature

### ISSUE THREAD

**Issue by eazeredo** [bcgov/CONN-CCBC-portal#363]
**As a** user 
**I want** to log in as a designated role
**So that** I can have access to specific features in the system

----

## Description
1) Identify a list of users in a designated Role
2) Set Permissions
3) Assign Permissions to one or more Roles

## Acceptance Criteria
- [ ] .

- [ ] .

- [ ] .

**Comment by elliottSlee** [comment]
Is this a duplicate of #26 or #29?
