### ISSUE TITLE
Implement Time Travel

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/CONN-CCBC-portal#367]
As dev team, 
We need the ability to artificially change the current date
so that we can test the functionality of the portal at different dates.

- [x] Implement the time travel feature, allowing a user to change "Current date and time" in Dev and Test
- [x] Place it on the footer

#

![image.png](https://images.zenhubusercontent.com/606c9d37b7ff542cfdb25c53/6b9997e7-0b94-4247-83c0-9c9e29fe9e33)

**Comment by VB-at-Bis** [comment]
Discussion points:
- Date.now() is used in both React code and db scripts;
- library https://www.npmjs.com/package/mockdate can be used to override `new Date()` etc Javascript function calls
- discussion at https://pgsql-hackers.postgresql.narkive.com/5ErBDnGh/overriding-current-timestamp# could be used as a starting point for now() overriding;

**Comment by matthieu-foucault** [comment]
- If we rewrite all date usage on the front-end to use `luxon`, we can easily mock the current date by [overriding  `Settings.now()`](https://github.com/bcgov/CONN-CCBC-portal/blob/71557df4860571b6fe5b16a1f94c7d025dd13cf4/app/tests/components/Form/ApplicationFormStatus.test.tsx#L49)
- Back-end date mock is done in CIIP with a [`mocks` schema](https://github.com/bcgov/cas-ciip-portal/tree/develop/mocks_schema) ([a bit of docs here](https://github.com/bcgov/cas-ciip-portal/blob/cc0920a680d1ecffe9acff41ee77d4e820f7a1a5/docs/database-mocks.md)), which relies on a [`ENABLE_DB_MOCKS`](https://github.com/bcgov/cas-ciip-portal/blob/dceb5331fa17902b1100e6faccac9d36eeb8b4a5/app/server/helpers/databaseMockPgOptions.js) env variable to alter the postgres search path and forward cookies as postgres settings

**Comment by eazeredo** [comment]
@VB-at-Bis , is this In Progress? if yes, could you move the card to the correct column?

**Comment by VB-at-Bis** [comment]
PR submitted https://github.com/bcgov/CONN-CCBC-portal/pull/567

**Comment by MarsRomer** [comment]
How do I use/test the time travel?  I don't see anywhere to set the time/date for today in the test environment

**Comment by matthieu-foucault** [comment]
#661 has the missing steps to enable it on openshift, do you want us to bring it in the sprint backlog?

**Comment by MarsRomer** [comment]
I guess so, if this ticket isn't done until we do the work outlined in 661 then we have to bring it in.  Would be good to have an estimate on that ticket though.  I would normally think that whatever is in that ticket would be part of the work required to finish this ticket for this one to be independent, so we wouldn't necessarily create a new ticket to finish this one.
