### ISSUE TITLE
Data Modeling - application revision management

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#369]
Continue data modeling that was started in July.
https://miro.com/app/board/uXjVOnpFeNI=/?track=true&utm_source=notification&utm_medium=email&utm_campaign=approve-request&utm_content=go-to-miro

How are we going to deal with changes and versions of the applications we receive from the applicant

Outcome:
Tickets/user stories that we need - create and estimate

**Comment by matthieu-foucault** [comment]
What does "continue data modeling" mean? The previously discussed model isn't implemented yet.

**Comment by eazeredo** [comment]
Meeting scheduled to Monday, 15.

**Comment by matthieu-foucault** [comment]
Issues have been created
