### ISSUE TITLE
Share form schema and data with ISED

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#376]
- [ ] Export the JSON schema 
- [ ] Create mock data
- [ ] Send it to ISED

**Comment by matthieu-foucault** [comment]
can we have more details for "Create mock data" ?

**Comment by wenzowski** [comment]
Any reason the mock data might need to be more complex than [randomly generated values of the correct type](https://json-schema-faker.js.org/) for each field? Do we need invalid mock data as well as valid mock data so we're not exclusively looking at happy path?
