### ISSUE TITLE
Wording updates

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/CONN-CCBC-portal#380]
**Landing page**
- [x] Add this line below Before you begin, "Full information about the Connecting Communities British Columbia (CCBC) program can be found at the program webpage."
- [x] Change "Please review the non-fillable application questions" to "Please review the pdf of application questions"
- [x] Add this line to the Please note, "All questions are mandatory unless indicated otherwise."
- [x] Add this line to Before you begin: Please review the project zones, underserved pseudo households, and connectivity infrastructure projects
- [x] Login button change to "Login with BCeID"
![image.png](https://images.zenhubusercontent.com/61e8875b1de5eff8f072cd04/5abfdeb6-b7fb-4b96-903e-fab7bde083bf)
#
**Project area**
- [x] Referring to the project zones (application guide Annex 6), which zone(s) will this project be conducted in?

#
**[Project Funding](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=4130%3A16269)**
- [x] Make Amount requested under CCBC per fiscal year required
- [x] Make Amount the applicant will contribute per fiscal year (April 1 - March 31) required
- [x] Make totalInfrastructureBankFunding optional.  
- [x] Add "(if applicable)" to the line "Funding from Canadian Infrastructure Bank per fiscal year (April 1 - March 31) (if applicable)"
![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/f9911ea4-7038-457b-b38c-bc6251b0e13d)
#
**Other funding sources**
- [x] For the years under "Amount requested from funding partner per fiscal year (April 1 - March 31)" make them required
![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/91170d54-0563-4810-8e27-595cdd2e0a1c)

#
**Templates**
- [x] add 'If applicable' to templates 5, 7, 8.
https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=2329%3A8222

#
**Mapping**
- [x] Change page title from Mapping to Coverage (we're making this change because not everything uploaded on this page is map)
- [x] Change page description to: "Please submit the following coverage data." 
&nbsp;<be> 

- [ ] Change statistics question description to: Please upload the XML file that was attached to the email you received upon completion of the project coverage
- [x] Change "Geographic coverage map from ISED's Eligibility Mapping Tool." to "Geographic coverage map from ISED's Eligibility Mapping Tool. KMZ is required."

- [x] Current network infrastructure in a geo-coded format
- [x] Proposed or Upgraded Network Infrastructure (project-specific) in a geo-coded format

#
**Benefits**
- [x] Change to: Final number of Eligible Households targeted by this proposal. This value should match cell G50 in Template 1 - Eligibility Summary.
- [x] Change to: Number of households on Indigenous lands impacted by this proposal. This value should match cell G55 in Template 1 - Eligibility Summary.

#
**Organization profile**
For the first bullet on "Is this applicant organization an Indigenous identity? An Indigenous identity may include:"
- [x] Change to: A for-profit or non-profit organization run by and for First Nations, Métis, or Inuit peoples; 

#
**Supporting documents**
Currently: Please refer to Annex 3 of the application guide for the community letters of support requirements. 
- [x] change to: Please refer to Annex 3 of the application guide for the community letters of support requirements. If you do not currently have these, you will have a 30-day grace period after the intake closes to submit them.

#
**Submission**
Currently: You certify that you have the authority to submit this information on behalf of the Applicant.
- [x] change to: Certify that you have the authority to submit this information on behalf of the Applicant. After submission, you can continue to edit this application until the intake closes on November 6, 2022 at 9:00AM Pacific Time (PT).
- [x] Change "Completed for (Applicant Name)" to "Completed for (Legal organization name)"

#
**Confirmation page**
- [x] Change "We have received your application for [project title]" to "We have received your application, _[project title]_,". Note that the project title is italicized and it has commas on either side.

#
**All pages**
Currently the button at the bottom says 'Continue'.
- [x] change to: 'Save and continue'

**Comment by AntBush** [comment]
@zoeyli-46  I notice in the screenshot that some words on the landing page are hyperlinked. Are we waiting on #313 to add those in or are those part of this card?

**Comment by zoeyli-46** [comment]
Just added in the statement to the ticket under Landing page @AntBush

**Comment by AntBush** [comment]
To update this, the unchecked "Change statistics question description to: Please upload the XML file that was attached to the email you received upon completion of the project coverage" is to be reverted until we figure out what we want to do with ISED's eligibility mapping not being present with the initial release.

**Comment by zoeyli-46** [comment]
@elliottSlee are we taking this out "you will have a 30-day grace period after the intake closes to submit them."

**Comment by elliottSlee** [comment]
@MarsRomer ^^
