### ISSUE TITLE
Add Editing Alert Banner

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/CONN-CCBC-portal#381]
As an applicant,
I want an alert to tell me that my edits will be saved to my submission
so that I know NWBC will receive my most up-to-date information 

### Design
https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=4206%3A16882

### Acceptance Criteria 
- [ ] **Scenario: alert appears when editing**
Given that an application is submitted
when an applicant edits this application
then an info alert appears on the page that can be dismissed if user clicks the close icon 

- [ ] <s>**Scenario: close alert**
Given that user has the alert on the page
when they click on the x in the alert
then it will disappear</s>

![Screen Shot 2022-08-25 at 1.57.20 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/c9572b0e-302a-4f6f-b66e-b4eda98ca50b)

**Comment by zoeyli-46** [comment]
@MarsRomer  ticket for editing application after submission, it is currently in new issues column as which sprint it goes in hasn't been decided yet

**Comment by MarsRomer** [comment]
@zoeyli-46  I am not completely sure I understand the acceptance criteria but it seems important for upcoming sprint so I'll put it there to discuss.

**Comment by elliottSlee** [comment]
Should this be done after #224 - Show status of of application on each form page

**Comment by MarsRomer** [comment]
Blocked until wording is finalized

**Comment by zoeyli-46** [comment]
@MarsRomer @elliottSlee lets test out if we need to disable to submit button or not, i think the alert here is pretty clear. We can test if we need to display the alert on every page, or just 1 time

**Comment by eazeredo** [comment]
@marcellmueller , would you mind assigning yourself to this card?

**Comment by matthieu-foucault** [comment]
@MarsRomer @zoeyli-46  can you confirm that the finalized wording is "Edits to this application are automatically submitted.", as displayed in Figma, rather than what is in the screenshot in the issue description

**Comment by MarsRomer** [comment]
@zoeyli-46  @elliottSlee  I believe we had landed on what's in the screen capture 'Edits are automatically saved submitted' right?

**Comment by zoeyli-46** [comment]
@matthieu-foucault the finalized wording is the text in the screenshot 'Edits are automatically saved and submitted'
cc @MarsRomer @elliottSlee

**Comment by MarsRomer** [comment]
Looks great! works great!
