### ISSUE TITLE
Dashboard wording updates in different states

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/CONN-CCBC-portal#382]
### User Story
As an applicant
I want the dashboard to tell me when an intake is closed or open and show my applications if I have any
so that I know what I can do in the portal.

- [x] **Scenario: Intake closed**
Given that an intake is **_closed_** 
when they navigate to the dashboard
then the text will state" Applications are currently not being accepted. Please check the [program webpage](https://www2.gov.bc.ca/gov/content/governments/connectivity-in-bc/20601/20601-63737) for updates.
and the create application button will be disabled
![Screen Shot 2022-10-05 at 12.10.11 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/c40e76f5-ae56-4c87-aee8-2673d41ba736)
![Screen Shot 2022-10-05 at 12.11.54 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/ae276981-c622-46b7-aeec-549d4baa4c06)
#
- [x] **Scenario: Intake open**
Given that an intake is **_open_** 
when they navigate to the dashboard
then the text will state, "Review of applications will begin on [current intake close date]. You can edit draft and submitted applications until this date."
and the create application button will be enabled.
![Screen Shot 2022-10-05 at 12.12.52 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/0f3b49c0-167b-480c-bbf4-9450d20de82f)
![Screen Shot 2022-10-05 at 12.12.27 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/814ce1c0-d696-4836-a70e-2cda0a840d4f)
#
- [x] Scenario: **No applications**
Given that an applicant has _no_ applications
when they navigate to the dashboard
then there will be no table of applications
and there will be a statement, "Applications will appear here"
![Screen Shot 2022-10-05 at 12.02.36 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/c90030e2-08f4-4cb5-953a-b49e4b6b979d)
![Screen Shot 2022-10-05 at 12.05.46 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/2e12ce56-1aeb-46de-97cf-006ff990cfd6)

**Comment by zoeyli-46** [comment]
@MarsRomer tagging for visibility and review!

**Comment by MarsRomer** [comment]
@zoeyli-46  would it make sense to show an empty dashboard table when applications = 0?

**Comment by MarsRomer** [comment]
@zoeyli-46  can we change 'complete' to 'submit' if applications > 0

**Comment by zoeyli-46** [comment]
@MarsRomer changed the word to submit

We originally thought about having an empty dashboard when applications = 0 but we decided against it because we want applicants to just immediately see the next action to take, which is to click the new application button.

Other than this, this ticket is ready to be placed in a sprint! :)

**Comment by MarsRomer** [comment]
@zoeyli-46 do you think  the places where we say 'applications can be edited until the intake closes' can possibly be clarified?  i.e. Draft applications can be edited anytime, regardless of when the intake closes.  Submitted applications can be edited until the intake closes.

**Comment by zoeyli-46** [comment]
Regarding "draft applications can be edited anytime regardless of when intake closes", is this to say that the draft application can be edited for the following intake if not submitted?

Because the application questions may change in following intakes, it might confuse the applicant to allow them to edit a draft application from a previous intake. Because they do not know what questions changed, they may just start a new application altogether instead of editing the old one.

**Comment by MarsRomer** [comment]
and I think we were going to let them do that, they can continue to edit the drafts.  If we add a question we will need a banner to alert them of this, and it will also show up in the review page as something missing.  If we remove a question, that can be a banner to let them know.  We will try very hard to limit changing the intent of any of the questions.  How does that sound?

**Comment by MarsRomer** [comment]
I'm wondering if this ticket should be split in 2 tickets, one for when the urgent things we need done for when the intake opens, and then another for when the intake closes.

**Comment by zoeyli-46** [comment]
I agree! I think what you mention about allowing them to edit drafts is another ticket, I'll create it in the new issues column.

I think this ticket is focused on what the dashboard page description should say, not how to the dashboard table should behave/alert banners in the form

**Comment by AntBush** [comment]
Can we add wording updates rather than just behavioural updates? Also will be hard for Mars to check the 0-count states before this passes from PO Review -> Sprint DOne

**Comment by VB-at-Bis** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/382?planning-poker) with Zenhub @AntBush @matthieu-foucault

**Comment by elliottSlee** [comment]
@zoeyli-46 @elliottSlee make wording as general as possible

**Comment by MarsRomer** [comment]
I just noticed by using time travel that after the first intake closes, the dashboard disappears.  Do we need a separate ticket for the dashboard to persist in between intakes?

**Comment by MarsRomer** [comment]
Looks good, but scenario 1 isn't as expected.  I still see the ISED message when I set the current date to be in between 2 intakes (December 20, 2022).  but works fine when I set the current date to April 2023.  
I think we wanted just the message in scenario 1 regardless of an upcoming intake date in the database (except for the very first intake of course since it's a special case)
![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/64504807-e806-46a4-b841-2fe71fa51c4d)

**Comment by marcellmueller** [comment]
The ISED alert is a separate issue. We added it in hastily to solve the issue when we were expecting to launch shortly and didn't spend much development time on it to cover all scenarios as the messaging would likely be outdated either way by next intake. In it's current, simplistic implementation it just displays when there is no open intake. 
  
I believe we discussed last week to just remove it from our codebase when the intake opens.

**Comment by MarsRomer** [comment]
I think we should do what ever is the simplest solution, but keeping in mind that it's not entirely out of the question that we may need this banner again down the road.  ISED is talking about updating their maps more regularly moving forward, so there may be another update in January which would require this banner to show again with similar wording.  Is there a simpler way to add/remove this banner?  growthbooks perhaps?

**Comment by elliottSlee** [comment]
@marcellmueller & @MarsRomer I thought there was a card about updating the banner to say applications are now being accepted. We discussed lumping in removing the current banner with that card. I can't find it.

**Comment by marcellmueller** [comment]
Sounds good @MarsRomer, we can talk about this during backlog refinement though I think it will be a new (even if likely small) ticket.
