### ISSUE TITLE
Disable submission button until complete

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#386]
- [ ] **Scenario: Validate mandatory fields to allow to submit**
**If** any of the fields on submission page ("Organization name (legal name)", "Completed by", "Title") are empty, 
**Then** Submit button is disabled 
**Else** Submit button is enabled
#
![image.png](https://images.zenhubusercontent.com/606c9d37b7ff542cfdb25c53/bab509fc-ccdb-45de-b286-72395abf60d1)

**Comment by AntBush** [comment]
Is this not a duplicate of the second user story on #280

**Comment by MarsRomer** [comment]
Yes it's a duplicate, good catch!
