### ISSUE TITLE
Update confirmation page data

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/CONN-CCBC-portal#388]
![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/a852de6b-3b51-425c-8bfb-57d0a8b291ba)

- [x] The project title currently says `"Sudden Valley"`, change this to be the dynamic data that the user inputs in the Project title field
- [x] The `intake number` is currently hard coded, change this to be dynamic

**Comment by zoeyli-46** [comment]
@MarsRomer Hey Mars, when creating these tickets is it best to leave them in New Issues for you to drag into sprints later on?

**Comment by MarsRomer** [comment]
Hi @zoeyli-46  yes please put them in the new issues and tag me to get my attention to them, I will drag them into the sprint backlogs

**Comment by MarsRomer** [comment]
Hate to pixel peep but can we have a bit more space between the two lines of text as it shows in the design please?

**Comment by marcellmueller** [comment]
@MarsRomer of course we can do style improvements though that is beyond the scope of this ticket. I'd suggest starting a new ticket where we can collect style issues to improve before launch as well as having the designers do a style review.

As for the time/date that is being taken care of in this ticket:
https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/314

**Comment by MarsRomer** [comment]
Fair enough, I need to get better at making sure we have all the acceptance criteria listed.
