### ISSUE TITLE
Application - Withdraw

### ISSUE THREAD

**Issue by eazeredo** [bcgov/CONN-CCBC-portal#39]
As an Applicant
I want to withdraw my application when a major change is needed
So that I can resubmit a new application with the most up to date information

Acceptance criteria:
- [x] Withdraw option should be available only for applications with the status "Submitted", withdraw option is disabled for applications in "Withdrawn"
- [x] A warning should appear "Applications submitted are deemed as property of BC. Withdrawing this application will remove it from consideration for Connection Communities BC funding program. You will not be able to re-submit the application. If you would like to re-submit, you must start a new application.
/n You cannot undo this action. Are you sure you want to withdraw this application?" 
With the options: "Yes, withdraw" and "No, keep this application"
- [x] A success modal <s>toast</s> should appear on the dashboard when it has been withdrawn
- [x] After withdrawal, the status should say "Withdrawn"
- [x] All form fields for the relevant application are disabled
- [x] A warning modal is on all relevant form pages saying, "You can no longer edit this application because it is withdrawn."
~~- [ ] pgtest~~ this is getting done in PR #429

Design
https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=1622%3A5952

![image.png](https://images.zenhubusercontent.com/61e8875b1de5eff8f072cd04/2b85506e-a066-400d-9584-41dc4f652748)
![image.png](https://images.zenhubusercontent.com/61e8875b1de5eff8f072cd04/0c1e818f-0be6-4ac2-994b-7768931cb833)
![image.png](https://images.zenhubusercontent.com/61e8875b1de5eff8f072cd04/e1f8b2d2-8e91-4096-98d2-7a062f070e10)
![Screen Shot 2022-08-04 at 2.02.58 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/493dbcdd-74bc-4fcc-88b6-e0d84577fd50)

Question for NWBC:  Can we delete the application completely from the database?

**Comment by elliottSlee** [comment]
Need to design how analysts will be notified that an application has been withdrawn.

**Comment by MarsRomer** [comment]
The UI seems a bit off:  ![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/b10e1b3c-1f13-4986-91c2-c49e7afbbb57)

**Comment by MarsRomer** [comment]
hmm I can't seem to submit for some reason:
![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/e9174353-2319-4924-807f-183bec81e49e)

**Comment by marcellmueller** [comment]
@MarsRomer obviously this is a serious bug but this ticket is for Withdraw :)

**Comment by MarsRomer** [comment]
@marcellmueller  haha yes I get that.  I was trying to review this ticket when this came up and since we were in a meeting at the time I thought this would be quickest way to see if perhaps it was something quick to fix but now I know it isn't so I've created a new ticket #474

**Comment by MarsRomer** [comment]
Withdraw works and the status changes right away.  The popup works as well.  The only thing that we may want to refine in a future sprint is how clicking on edit and then on withdraw behaves.  It's a bit tricky to slide from the edit button to the withdraw button without losing the withdraw button.

**Comment by marcellmueller** [comment]
I think the withdraw could be done differently as well. Though you are just supposed to hover over the down arrow to get the withdraw button, nothing to do with the edit though maybe it’s confusing.
