### ISSUE TITLE
Remove application.owner column

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/CONN-CCBC-portal#395]
### Description

- [ ] The `application.owner` column is unnecessary, and 
- [ ] we should use `created_by` instead.

**Comment by AntBush** [comment]
Is this blocked by the row level security ticket? As that owner column is required for it (for now)

**Comment by VB-at-Bis** [comment]
This ticket is not blocked by row level security - just need to find/replace `owner_id` with `created_by` in DB deploy sql files.

**Comment by matthieu-foucault** [comment]
Following developers discussion, this change is not needed, and there may be use cases for having a separate field for owner vs created_by
