### ISSUE TITLE
TechDebt: Assign ccbc id in one transaction

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#396]
When submission is done, there are two transactions that make the ccbc id so the risk exists that some submitted applications may not get the ccbc id. This ticket is to use one transaction so that the risk is removed.

**Comment by MarsRomer** [comment]
When submission is done, there are two transactions that make the ccbc id so the risk exists that some submitted applications may not get the ccbc id.  This ticket is to use one transaction so that the risk is removed.

**Comment by matthieu-foucault** [comment]
Related to #494
