### ISSUE TITLE
Others applications exposed when logged in

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#398]
Tech Debt: Row level permissions in DB so that I can only see my applications.  Security risk for applicants applications are exposed to others

Update:
- [x] We need to add ALTER TABLE application ENABLE ROW LEVEL SECURITY; 
- [x] and make other related changes (CREATE POLICY on applications etc.) To facilitate SELECT from application table for analyst (where current_user != owner) we can create VIEW. 
PostgreSQL views always adhere to the permissions of their owner (the postgres superuser) rather than the current user.

**Comment by VB-at-Bis** [comment]
We need to add `ALTER TABLE application ENABLE ROW LEVEL SECURITY;` and make other related changes (`CREATE POLICY on applications` etc.) To facilitate `SELECT ` from `application` table for analyst (where `current_user` != `owner`) we can create VIEW. PostgreSQL views always adhere to the permissions of their owner (the postgres superuser) rather than the current user.

**Comment by VB-at-Bis** [comment]
As discussed - we need to document and confirm with PO the relationships between roles, tables and permissions. 
Current tables:
- Application
- Application Status
- Attachment
- CCBC User
- Intake

Current Roles:
- Guest User (unauthenticated)
- Applicant

Future Roles:
- Analyst (GIS, Technical, etc)
- Admin

Suggested format of the documentation is a matrix with roles and table names/CRUD operations where permissions are defined at the crossing.

**Comment by wenzowski** [comment]
Would it make sense for the proposed matrix to be drafted plain text in this repo as a PR? There may be more than one scenario for each CRUD operation type for each role, so making sure we pick a matrix format that can accommodate that as well. Shall we scope the matrix creation work in this card to only the roles that currently exist, excluding the future roles for now?

**Comment by VB-at-Bis** [comment]
In plain text:
- unauthenticated user can see list of intakes (start/end dates - `select` from intake table) and cannot see or perform CRUD operations on any other table;
- authenticated user can see and perform CRUD operations only on records created by the user (`application` and `attachment` tables);
- records in internal(technical) tables can be accessed/created/edited/deleted only by the code which uses account with `superuser` role.
Attached is Excel spreadsheet with the matrix.[https://app.zenhub.com/files/476885245/983426e8-0aff-4685-988f-cfe846691555/download](https://app.zenhub.com/files/476885245/983426e8-0aff-4685-988f-cfe846691555/download)

**Comment by VB-at-Bis** [comment]
Steps to verify:
- open application in one browser, login with one GitHub account and create new application;
- open application in another browser, login with different GitHub account and create new application;
- go to Dashboard in both browsers and observe that only applications created by the logged in user are displayed;
