### ISSUE TITLE
Design how BC will collect UBF forms

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#4]
**As an** executive, 
**I want** to know how the UBF information will be collected 
**so that** I can know how to share the information with ISED.

### Acceptance Criteria
- [x] Choose fields from UBF forms that need to be input instead of upload, as required for reporting
- [x] Confirm what information is required by ISED. Do they want application form, all templates, and attachments they currently collect?
- [x] Lo-fidelity wireframes - https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=24%3A534

**Comment by eazeredo** [comment]
@zoeyli-46 , is this story done?

**Comment by zoeyli-46** [comment]
@eazeredo yes, I thought it had been closed already. I've marked it closed now.
