### ISSUE TITLE
Database schema cleanup on dev/test deployment

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/CONN-CCBC-portal#402]
To enable updating our sqitch deploy scripts, 
- [x] we need to clean the database schemas prior to deploying in the dev and test environments

CIF example: https://github.com/bcgov/cas-cif/blob/develop/chart/cas-cif/templates/db-pre-upgrade-job.yaml

**Comment by AntBush** [comment]
By cleanup do you mean to consolidate the tables?

**Comment by matthieu-foucault** [comment]
I mean delete the schemas before deploying, so that we can edit our sqitch changes
