### ISSUE TITLE
Load Testing - baseline

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#404]
## Description

**Important**:
- prior to the load test, the target namespace and route should be communicated to platform services, (in devops-operations rocketchat channel)
- the load testing scenario should not go above 100 concurrent sessions (i.e Virtual Users)
- the load testing scenario should not go above 50 requests per second.

From previous experience and our user research, we are expecting an increased load on the last few days of the intake. Load testing should be conducted prior to that.

NWBC expects approx 100 applications for the first intake. To be safe, we can load test for 1K applications and 100 individual users.

Using [k6](https://k6.io/docs/), we can
 - test our page loading via http requests: https://k6.io/docs/using-k6/http-requests/
 - test our API: https://k6.io/docs/testing-guides/api-load-testing/

To simplify the load testing scripts, we can temporarily deploy our application to the development environment, with mock authentication enabled.

The goals of the load testing are twofold:
- identify slow queries on the database
- fine-tune resource requests and limits

To identify slow queries, one can use the [`pg_stat_statements` view](https://www.postgresql.org/docs/14/pgstatstatements.html), in addition to the k6 output.

Using Sysdig's metrics and correlating with the load testing progress, you can identify the required resources for our various containers.

## Acceptance criteria
Assuming that the load testing scenario completes without errors (or with an acceptable error rate), the acceptance criteria are:
- [ ] record the metrics in the repository, providing us with a baseline for any performance tuning we might want to do
- [ ] Identify any long-running database query or API request, and whether their performance can be improved
- [ ] Create a smoke-test script to run on CI (i.e. load-test with a single user). This may not need to be a required check. We could run it on `main` in a workflow that doesn't block deployment, see https://k6.io/docs/test-types/smoke-testing/

## Notes 
Platform services load testing guidelines: https://developer.gov.bc.ca/Load-Testing-Guidelines

Not part of this ticket:
Stress Testing - Rate limiting.  
Technical solution:  Implement a slowdown - prevents a crash of the application.

**Comment by eazeredo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/404?planning-poker) with Zenhub @AntBush @marcellmueller @matthieu-foucault @wenzowski

**Comment by wenzowski** [comment]
https://github.com/bcgov/cas-ciip-portal/tree/develop/app/tests/perf

**Comment by matthieu-foucault** [comment]
The CIIP load tests were written prior to having working server-side rendering, so they could be improved

**Comment by matthieu-foucault** [comment]
@MarsRomer @wenzowski  My vote on this is currently 21pts, as the [load testing guidelines](https://developer.gov.bc.ca/Load-Testing-Guidelines) make it impossible to perform effective load testing. It has to be done after 5:30pm on a weekday and has scheduled with platform services. This does not leave any room for tuning our resources and re-running load tests. This is assuming we want to follow the guidelines, they're just guidelines after all, not requirements...

**Comment by MarsRomer** [comment]
Is the 21 pts strictly the effort time for our team?  Or does that include wait time?

**Comment by matthieu-foucault** [comment]
@MarsRomer I see this has been de-prioritized. A conservative approach would be to plan the load testing two sprints before the end of the first intake, leaving the team one full sprint to make any necessary performance enhancement(s).

**Comment by MarsRomer** [comment]
I didn't see this comment until now, I have put it in the next-sprint candidates with your advice.

**Comment by matthieu-foucault** [comment]
@VB-at-Bis @marcellmueller @AntBush 

There's still improvements to be made but tweaking the resource limits seems to be the most effective solution.

Initial load test results: 

```
checks.........................: 100.00% ✓ 1000     ✗ 0
     data_received..................: 699 MB  324 kB/s
     data_sent......................: 11 MB   4.9 kB/s
     http_req_blocked...............: avg=40.25ms  min=1.35µs   med=54.89ms max=1.28s    p(90)=79.96ms p(95)=84.58ms
     http_req_connecting............: avg=18.5ms   min=0s       med=22.74ms max=1.24s    p(90)=36.5ms  p(95)=38.68ms
   ✗ http_req_duration..............: avg=13.08s   min=27.44ms  med=10.94s  max=52.92s   p(90)=30.04s  p(95)=31.03s
       { expected_response:true }...: avg=10.87s   min=27.44ms  med=5.72s   max=52.92s   p(90)=28.35s  p(95)=31.49s
     http_req_failed................: 11.53%  ✓ 1115     ✗ 8549
     http_req_receiving.............: avg=1.39s    min=31.57µs  med=100.5ms max=23.38s   p(90)=4.79s   p(95)=6.56s
     http_req_sending...............: avg=105.96µs min=9.95µs   med=89.3µs  max=922.33µs p(90)=193.1µs p(95)=244.52µs
     http_req_tls_handshaking.......: avg=21.6ms   min=0s       med=30.14ms max=1.19s    p(90)=43.41ms p(95)=46.93ms
     http_req_waiting...............: avg=11.68s   min=27.26ms  med=8.85s   max=31.25s   p(90)=30.02s  p(95)=30.03s
     http_reqs......................: 9664    4.473815/s
     iteration_duration.............: avg=29.85s   min=550.98ms med=30.77s  max=1m23s    p(90)=1m0s    p(95)=1m1s
     iterations.....................: 4322    2.00081/s
     vus............................: 6       min=1      max=100
     vus_max........................: 100     min=100    max=100
```

After improvements in #852

```
checks.........................: 100.00% ✓ 1000      ✗ 0    
     data_received..................: 5.9 GB  2.8 MB/s
     data_sent......................: 28 MB   13 kB/s
     http_req_blocked...............: avg=64.61ms  min=1.34µs   med=10.07µs  max=12.76s p(90)=144.2ms  p(95)=341.24ms
     http_req_connecting............: avg=37.37ms  min=0s       med=0s       max=7.25s  p(90)=65.33ms  p(95)=159.65ms
   ✗ http_req_duration..............: avg=1.77s    min=23.14ms  med=1.46s    max=1m0s   p(90)=3.57s    p(95)=4.38s   
       { expected_response:true }...: avg=1.77s    min=23.14ms  med=1.47s    max=49.32s p(90)=3.57s    p(95)=4.38s   
     http_req_failed................: 0.03%   ✓ 27        ✗ 67482
     http_req_receiving.............: avg=569.54ms min=24.43µs  med=332.24ms max=57.34s p(90)=1.31s    p(95)=1.85s   
     http_req_sending...............: avg=134.86µs min=6.4µs    med=46.88µs  max=2.65s  p(90)=110.23µs p(95)=145.51µs
     http_req_tls_handshaking.......: avg=27.15ms  min=0s       med=0s       max=9.06s  p(90)=66.88ms  p(95)=148.26ms
     http_req_waiting...............: avg=1.2s     min=22.76ms  med=920.23ms max=19.42s p(90)=2.65s    p(95)=3.19s   
     http_reqs......................: 67509   31.253617/s
     iteration_duration.............: avg=3.86s    min=225.07ms med=3.24s    max=1m5s   p(90)=7.03s    p(95)=8.43s   
     iterations.....................: 33254   15.395099/s
     vus............................: 2       min=1       max=100
     vus_max........................: 100     min=100     max=100
```

You can see a dramatic reduction in requests failed and in the http request duration. The throughput has greatly increased too.

There are still some extremely slow requests though and clues as to which functions should be optimized (e.g. `application_project_name`, `application_form_data`) which I have presented to the team.

There is a case to be made that this load test is in fact a stress test. Not sure if we'll have 100 active users at the peak usage, or a 30 request/s throughput. Sentry and Sysdig should be able to report on the number of sessions and requests, so you might want to look at that.

Given our limited quota, the application pods will be throttled currently under heavy load. The current limit is at 500m for application pods. I set it at 750m during the load test, but I don't think our current quota can safely support that (we need to leave enough room in the quota to deploy one more application and db pod when a release is made)

Next steps for performance improvement include:
 - connecting to the db via pgBouncer, instead of connecting directly to the primary node (#888)
 - setting up a horizontal pod autoscaler (#889)
