### ISSUE TITLE
implement Sysdig

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#405]
Will send us alerts if the application is down

- [x] YAML - make part of our pipeline
- [x] Set up dashboards
- [x] set up alerts - storage capacity (PVCs) and, number of replicas (application pods are down)

The following alerts can be added:
- No database pod: `sum(kube_statefulset_status_replicas {kube_namespace_name="ff61fb-prod", kube_statefulset_label_postgres_operator_crunchydata_com_instance_set="pgha1"}) < 1`
- No pgBouncer pod: `kube_replicaset_status_replicas {kube_namespace_name="ff61fb-prod", kube_deployment_label_postgres_operator_crunchydata_com_role="pgbouncer"} < 1`
- No application pod: `kube_replicaset_status_replicas {kube_namespace_name="ff61fb-prod", kube_replicaset_name!~".*postgres.*"} < 1`
- PVC > 50%: `((kubelet_volume_stats_used_bytes/kubelet_volume_stats_capacity_bytes {kube_namespace_name="ff61fb-prod"} by (persistentvolumeclaim, kube_namespace_name)) * 100) >= 50`
- PVC > 75%: `((kubelet_volume_stats_used_bytes/kubelet_volume_stats_capacity_bytes {kube_namespace_name="ff61fb-prod"} by (persistentvolumeclaim, kube_namespace_name)) * 100) >= 75`
- PVC > 90%: `((kubelet_volume_stats_used_bytes/kubelet_volume_stats_capacity_bytes {kube_namespace_name="ff61fb-prod"} by (persistentvolumeclaim, kube_namespace_name)) * 100) >= 90`
- CPU > 75%: `avg(sysdig_container_cpu_quota_used_percent {kube_namespace_name="ff61fb-prod"}) by (kube_pod_name, kube_namespace_name) >= 75 and on() (hour() < 5 or hour() > 9)`
- CPU > 90%: `avg(sysdig_container_cpu_quota_used_percent {kube_namespace_name="ff61fb-prod"}) by (kube_pod_name, kube_namespace_name) >= 90 and on() (hour() < 5 or hour() > 9)`

**Comment by matthieu-foucault** [comment]
Sysdig was demoed to developers and the PO. Alerts will need tweaking, as they might be too noisy with their current setup
