### ISSUE TITLE
Enable analysts to edit application & history is saved

### ISSUE THREAD

**Issue by eazeredo** [bcgov/CONN-CCBC-portal#41]
## User Story
As an analyst
I want to edit an application
so that I have the most up-to-date information when assessing.

## Acceptance Criteria
- [x] Clicking on the edit pencil allows analyst to edit the form data on a different page (reuse edit pages for applicants to save time)

#
- [x] **Don't show "Edit pencil" for the sections below:**

- Template Uploads
- Supporting Documents Uploads
- Coverage uploads
- Review
- Acknowledgements
- Submission

 - [x] On the edit page when user clicks save they get a modal (see screen design below)
#
- [x] **Scenario: Modal**
Clicking Save on the modal will save the changes and take the user back to the application
Clicking cancel on the modal will only cancel the text entered into the modal and take the user back to the edit application page with the previous changes still there.

#
- [x] **Scenario: Save**
Given I changed the application with valid information
When I click on Save
Then the changes are saved 
And I'm redirected to the Application page
And to the same section where they clicked the edit button (if time allows for development)
#
- [x] **Scenario: Cancel on Edit Page**
Given I changed the application with valid information
When I click on Cancel on the edit page
Then I'm redirected to the Application page (no confirmation)
And all information changed is discarded
#
- [x] **Scenario: Applicant can see changes**
Any changes that the analyst makes to the form data will also by default be visible to the applicant on the portal
#
## Technical Analysis
- [ ] Reuse the SaveForm from ApplicationForm (to take advantage of splicing in the latest information along with the rest of the data)
- [ ] The RLS should allow an applicant to see the latest changes on the applicant side of the portal. (Should be the "default" as who can see form data is dependent on the application owner)
- [ ] No Autosaving
- [ ] Add a column on Form Data for a note
- [ ] Use the same method of updating data as rfiData (insert only, archive old form)
- [ ] May need to update the computed column for displaying formData
- 
- What is the front-end complexity?
- Do it require creating or updating a component?
- Any work on the back-end?
- Integration?
- Any changes in database structure?
- What types of tests that we need to create and run?
- Impacts on DevOps?
- Other risks and potential side effects?
- Which documentation needs to be updated?

## Wireframes
**Application page - before update (old value)** 
<img src="https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/efb5ecca-8bd2-4d4a-8a51-3e870210731d"> 
#
**Edit application page**
![image.png](https://images.zenhubusercontent.com/606c9d37b7ff542cfdb25c53/65603115-e1d2-4ab5-951f-0080f4eb77f7)
#
Modal
Adding text is optional
Save will close the modal and return the user to the Application and to the same section where the user clicked the edit pencil icon to begin with.
![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/c2814b49-2fd5-4115-bb68-cb97f75a6d4e)
**Application page - after update (new value)** 
New values show in the application page
<img src="https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/742b91b1-07c1-46bd-adec-33815c30dbc8">
#

**Comment by MarsRomer** [comment]
@elliottSlee @zoeyli-46 Do we mean this is for after the 60 day period?  If not then let's discuss the business need for the audit during the 60 day period.

**Comment by zoeyli-46** [comment]
@MarsRomer This is for the analyst post-intake (after 60 days), they do not see the applications before the intake ends. This is the audit log for the analyst, the business need is to have an auditable trail of changes made to an application such as change of status from open to closed etc.

**Comment by MarsRomer** [comment]
Thank you, that makes it much clearer for me!

**Comment by elliottSlee** [comment]
@zoeyli-46 we can use this for the edit card

**Comment by eazeredo** [comment]
Acceptance criteria updated.

**Comment by MarsRomer** [comment]
@eazeredo  what was the update and the reasoning behind it?

**Comment by eazeredo** [comment]
Reason: I forgot to add it on Monday.
Changes: Added the User Story template, AC rewritten for clarity, and wireframes updated.

**Comment by MarsRomer** [comment]
Mars to check with NWBC that there are no concerns to show the updated edited form to the applicants

**Comment by MarsRomer2** [comment]
I think this ticket was already reviewed by me and the changes are in prod.  Can someone please confirm?

**Comment by marcellmueller** [comment]
I thought so but it was in the dev review column so I wanted to make sure you were good with it! This did get pushed to prod Tuesday morning so I will move it to the done column thanks.
