### ISSUE TITLE
Only allow 1 eligibility tool coverage map

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#412]
### User Story
As an applicant I want to be able to only upload 1 coverage map from the eligibility mapping tool so that I can submit the single, correct file.

### Description
We bounced around whether single or multiple files should be allowed for the coverage output of the eligibility mapping tool. Older versions of the tool didn't allow contiguous coverage, but the current version does. NWBC has expressed concern over getting multiple proposed coverage maps for a project, but this would mess up the coverage statistics which are integral for assessing applications. So we need to limit it to 1.

### Acceptance Criteria
Geographic Coverage Map from ISED's Eligibility Mapping Tool
- [ ] Only allows a single file to be uploaded

**Comment by MarsRomer** [comment]
Interestingly I just bumped up across this bug just now too!  Also I noticed that it's allowing for multiple kmz's but I'm pretty sure it was only allowing 1 kmz earlier this week which is the way we actually want it
