### ISSUE TITLE
Required fields are not marked in red on the Review page 

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#414]
- [ ] **Conditional required field:**
**If** _Does your Project span multiple provinces/territories?_ == Yes **AND** _Provinces_ is not answered
**Then** _Provinces_ should show up red in dashboard but it doesn't currently appear.
<table>
 <tr>
  <td>
  <img src="https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/7f3f724e-8699-4dff-b9b4-8606e921226e">
   </td>
  <td>
   <img src="https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/08e8f71f-5ea1-440c-ad6d-d467df6a6913">
  </td>
 </tr>
</table>

#
- [ ] Missing fields of other funding sources page are not highlighted red but should be.
<img src="https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/686927a2-19ca-4d1f-831a-fff48a0c7063" width="75%">

#
- [ ] Type of organization marked as missing even though something is entered.
<table>
 <tr>
  <td>
    <img src="https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/0039a4aa-8828-43a4-b716-4974865b560d">
  </td>
  <td>
    <img src="https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/3c36711f-df2b-4bc1-b945-e3b7d0390cfd">
  </td>
</tr>
</table>
This doesn't occur if all fields are filled: 
<table>
 <tr>
  <td>
    <img src="https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/3a384ae8-1953-4f2f-9b0b-96cd280f8279">
  </td>
  <td>
    <img src="https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/4bca50fb-4be7-47b3-915c-76ecab26a2bd">
  </td>
</tr>
</table>

#
- [ ] _Is this Applicant organization an Indigenous identity?_ question doesn't appear on the review page. The answer does.

<img src="https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/e564843b-410e-46e1-b41c-aebc2c8ebf2d" width="75%">

#
- [ ] Organization profile section missing open-ended responses that appear dependent on previous question.
![Screen Shot 2022-08-17 at 4.39.52 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/723c8233-440c-46cb-871f-c2397a72f679)

#
- [ ] Organization location shows false flag that something's missing when _Is the mailing address the same as above?_ == no despite all fields filled. If mailing address same == yes, it correctly does not have a flag.

<img src="https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/1db9e80c-b3a5-4526-a255-0c2315aa2a50" width="75%">

#
- [ ] When all required fields are completed, the review page correctly has no fields with red background, but it has the error at the top saying, "There are empty fields in your application. Applications with unanswered fields may not be assessed."

**Comment by elliottSlee** [comment]
@marcellmueller if we refactored this review page, as was suggested the other day, would some of these errors be fixed? If so, which ones? I'd like to clarify this card before sprint planning.

**Comment by marcellmueller** [comment]
Maybe ask @matthieu-foucault. I don’t see the value in rebuilding the entire review page instead of some minor bug fixes given the time constraints.

**Comment by matthieu-foucault** [comment]
The value is in ensuring code quality, removing code duplication and avoiding future bugs. If we're looking at short term value, then those bugs can definitely be fixed without refactoring, but similar bugs will come up whenever changes are made to the form schema.

**Comment by MarsRomer** [comment]
Looking good, but just noticing that the total funding for CIB should not be showing as red - it's optional (and autocalculated)
![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/3168b129-8409-40df-ab1b-86a35c8aab19

**Comment by MarsRomer** [comment]
in addition to above, I believe this should be a mandatory quesiton: 
![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/66391563-26a1-47fb-9860-af164552179d)

**Comment by MarsRomer** [comment]
in addition to above, I believe this should be a mandatory quesiton: 
![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/66391563-26a1-47fb-9860-af164552179d)

**Comment by matthieu-foucault** [comment]
I created #704 and #705 for those two new issues, as they are different bugs than what is listed in this issue's description.

**Comment by MarsRomer** [comment]
I am a little concerned about this.  We made the decision to take the extra time to do the rjsf refactor because it would fix all the bugs on the review page and would remove the need create new bug tickets for the review page and fix them individually thereby saving us effort in the future.  After all the effort in the rjsf refactor I am concerned that there are still bugs on the review page, and I wonder if we were better off fixing the bugs piecemeal.

**Comment by matthieu-foucault** [comment]
These bugs are not on the review page, but either the JSON Schema itself, or with the way calculated components work. You don't see them until the review page because it's the only place we're doing validation.
The fixes will not involve updating the review page, which appears to be doing its job of displaying the form data and JSON schema as specified.
