### ISSUE TITLE
Switch up some requireds, optionals, & if applicables

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#415]
### Fields to change
Change "Optional" to "If applicable"
- [x] Change word "optional" for Alternate contact _family name_ to "if applicable." (It remains optional)
- [x] Change ~~_Evidence of connectivity speeds_~~ other supporting documents uploads to "if applicable." (It remains optional)
- [x] Change word "optional" for Authorized contact _family name_ to "if applicable." (It remains optional)

Change "Required" to "Optional" 
- [x] Make _Backbone technology_ question optional. Wording is still the same. 

Change "Optional" to "Required"
- [x] Make _Is this person an authorized signing officer of the Applicant?_ for Authorized contact required
- [x] Make _Is the mailing address the same as above?_ required
### Reasons, if you're nosy
Last-mile only projects are eligible for CCBC funding. Therefore, an applicant could have no backbone entered here. In fact, of all the current projects that are in due diligence or beyond, 80% are last-mile with no backbone component.

For calculated fields, seeing as they're not input fields, it doesn't make sense to have them marked optional. 🤪

Evidence of connectivity speeds isn't required, it's only necessary if an applicant is disputing connection speeds.

If someone has a family name, we want to collect it so it's not optional. It needs to be marked as if applicable in case someone doesn't have a family name.

**Comment by eazeredo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/415?planning-poker) with Zenhub @AntBush @marcellmueller @matthieu-foucault @wenzowski

**Comment by MarsRomer** [comment]
@marcellmueller  the 'Is the mailing address the same as above' is not showing up as required in the review page (red background) but I assume this will happen with the refactor.  The rest looks good so I will mark this one as done.
