### ISSUE TITLE
Bug:  Error saving

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#421]
I copied and pasted a large piece of text 832,209 characters into the project title and ever since then I have been having issues with navigating back and forth on the form and autosaving is having an issue:

Perhaps the bug is more with the fact that the position/title on the **Alternate Contact** and **Authorized Contact** pages allows for a large number of characters.  Can we put a limit of 
- [x] add max length of 128 characters on these 2 field please?  that would also be in line with what ISED has in their schema
- [x] Add max length of 32000 chars for all fields that doesn't have a limit yet.

![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/96e9022c-991c-4523-aead-73d925df5afc)

**Comment by marcellmueller** [comment]
@MarsRomer did you want me to set all fields on alternate/authorized contact pages to 128 character limit? Other than the phone number fields they don't have a limit set.
