### ISSUE TITLE
Wording updates

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#431]
#### Dashboard
- [x] Capitalization issue: currently "CCBC Id", change to "CCBC ID" 
- [x] Currently: " Project name", change to "Project title"
- [x] Change "New application" button to "Create application"

#### Project Funding
- [x] Change page description to: "Please note: CCBC is funded by both British Columbia and ISED (UBF). With this one application, you are applying to funding from both partners. You are expected to enter into a separate agreement with both partners."

#### Coverage page
- [x] Change "Use ISED’s Eligibility Mapping Tool to generate the Project Coverage that is to be included in your application." to "Use ISED’s Eligibility Mapping Tool to generate the project coverage for this application."
If this issue is done after #313, ensure [Eligibility Mapping Tool](https://www.ic.gc.ca/app/scr/sittibc/web) is linked to https://www.ic.gc.ca/app/scr/sittibc/web

#### Organization Profile Page
- [x] Change Type of organization option "Incorporated company - private **of** public" to "Incorporated company - private or public"

<img src="https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/55d84a2b-6824-40ab-ad63-9181bd21c573" width="50%">

- [x] educational is spelled wrong, typo

![image.png](https://images.zenhubusercontent.com/61e8875b1de5eff8f072cd04/e0967d3b-8e11-4458-93f9-fe80c024eaca)

#### Authorized contact page
- [x] Change page title to "Authorized business contact"

#### Alternate contact page
- [x] Change page title to "Alternate business contact"
- [x] Change "Provide the contact information for an alternate contact in the event that the primary contact becomes unreachable." to "Provide the business contact information for an alternate contact in the event that the primary contact becomes unreachable.

#### Review Page
- [x] Change "Please ensure your responses are accurate. You may continue to edit your application after marking it as Ready for Assessment until the intake closes on [YYYY/MM/DD]." to "Please review your responses."
- [x] Change word Declarations to Acknowledgements on "By checking this box, you acknowledge that there are incomplete fields and incomplete applications may not be assessed. If the incomplete fields are not applicable to you, please check the box and continue to the **acknowledgements** page."

#### Confirmation page
- [x] Change "Application completed" in the title of the card to "Application submitted"
- [x] Change received sentence from "We have received your application, [application title], on [date] at [time]." to "The application, [application title], was submitted on [date] at [time]."

**Comment by eazeredo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/431?planning-poker) with Zenhub @AntBush @marcellmueller @matthieu-foucault @wenzowski

**Comment by MarsRomer** [comment]
![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/0f3a2569-8642-4734-bce7-a3240e5653fd)

**Comment by marcellmueller** [comment]
This is fixed now!
