### ISSUE TITLE
Rename `applications` table to `application`

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/CONN-CCBC-portal#438]
This should only affect database code, the resulting graphql api should be the same

- Search and replace `ccbc_public.application`
- applications_project_name function needs to be renamed too

**Comment by eazeredo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/438?planning-poker) with Zenhub @AntBush @marcellmueller @matthieu-foucault @wenzowski
