### ISSUE TITLE
Ensure linting and formatting rules are followed using pre-commit

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/CONN-CCBC-portal#449]
- [x] See CIF pre-commit rules
- [ ] <s>add pgFormatter </s>
- [x] add `"before:git:beforeRelease": "./.bin/pre-commit-format.sh CHANGELOG.md"` to root package.json

**Comment by AntBush** [comment]
PG Formatter was scrapped since the yarn wrapper doesn't pick up on the configuration (and doesn't apply it uniformly). pgFormatter is a perl program but without a cpan module to use in a friendly way.

**Comment by matthieu-foucault** [comment]
pgFormatter was also scrapped because it did not result in increased readability (especially with plpgsql functions)
