### ISSUE TITLE
Calculate $ totals from the years

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#450]
### User Story
As an applicant
I want the totals for each funding amount to be automatically calculated from the years
so that I am less likely to make mistakes copying & pasting from Template 2.

### Description
Template 2 sums the total amount from the years for:
- Total amount requested under CCBC
- Total amount applicant will contribute
- Total funding from Canadian Infrastructure Bank
- Total amount requested from funding partner
We would like the application portal to do the same

### Acceptance Criteria:
- [x] Total amount requested under CCBC is sum of each year of funding request
- [x] Total amount applicant will contribute is sum of each year of amount they'll contribute
- [x] Total funding from Canadian Infrastructure Bank is sum of the 4 years of CIB funding
- [x] Total amount requested from funding partner is sum of each year of amount from other funding source. This is repeated for each additional funding source.
- [x] Round the total to 2 decimals

### Technical details

This should be implemented via a custom RJSF field, similar to [CIIP's handling of CO2e emissions](https://github.com/bcgov/cas-ciip-portal/blob/develop/app/containers/Forms/EmissionGasFields.tsx)

#
>![Screen Shot 2022-09-08 at 1.06.41 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/c6d3d632-e9a7-43bc-a3a3-848d94a705d0)
#

**Comment by AntBush** [comment]
Do we want this stored as well in the schema or just displayed?

**Comment by elliottSlee** [comment]
@AntBush Stored as well. This is to replace the current input, so instead of inputting the value it'll be calculated and stored.
