### ISSUE TITLE
Shorten length of Project Title

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#451]
### User Story
As an applicant
I want my project title to be limited to the correct character limits
so that I don't go over what I was instructed to do.

### Acceptance Criteria
- [ ] Set maxLength of the project title to 200 characters
- [ ] **Scenario: wrap long title in dashboard**
Given that an applicant has provided an application title
when their application title is longer than 400px in the dashboard
then it will wrap underneath with 8px spacing between lines
and the row height increases accordingly

![Screen Shot 2022-08-24 at 4.02.51 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/36a07cc7-750a-4d41-9fd5-c38d955feb21)

**Comment by eazeredo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/451?planning-poker) with Zenhub @AntBush @marcellmueller @matthieu-foucault @wenzowski

**Comment by MarsRomer** [comment]
@elliottSlee @zoeyli-46 would you mind taking a look to see if need this ticket?  from my look at the test env it seems we already have 200 character limit and text wrapping implemented. I think some of that may have happened as part of another ticket

**Comment by elliottSlee** [comment]
I don't think we do. I realized the problem of the expanding width of the dashboard table is when there are no breaks/spaces. It starts to expand beyond the normal table limits at about 76 characters. I'm doubtful that there are any words that'll be that long. I skimmed the geonames list and didn't see anything extremely long there.

**Comment by MarsRomer** [comment]
I see what you mean about not having spaces.  
but we have the 200 character limit right? so perhaps this is an edge case and we don't need to prioritize it for next sprint....

**Comment by elliottSlee** [comment]
We do have a 200 character limit. So I don't think anything needs to be done.

**Comment by marcellmueller** [comment]
@MarsRomer @elliottSlee can we close this ticket then or is there anything you would like for us to update?

**Comment by MarsRomer** [comment]
@marcellmueller we need to have the project title text in the dashboard to wrap if they enter in a long string without any spaces in it.  Currently it wraps fine if there are spaces in the text, but if there aren't any spaces then it extends that column.  Please only do this if it's a super quick fix, this is an edge case and not a high priority anymore.

**Comment by eazeredo** [comment]
@marcellmueller , would you mind assigning yourself to this card?
