### ISSUE TITLE
Add 'Home' link to navbar

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#457]
Add a link called _Home_ that is linked to the landing page

![Screen Shot 2022-08-22 at 1.10.02 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/0ef31f03-b78f-44b7-8ce1-da7f0313fd99)

https://developer.gov.bc.ca/Design-System/Navigation-Bar-Basic

**Comment by eazeredo** [comment]
Please, move this into card #119

**Comment by elliottSlee** [comment]
This is part of navbar, not sidebar so I don't think it should be combined with #119

**Comment by eazeredo** [comment]
Oh... gotcha! Thanks!
