### ISSUE TITLE
Wireframe application - 1st iteration

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#46]
Create user journey of proponent from learning about program to completing proposal at intake to interacting with NWBC & ISED to project execution.

This is a low-fidelity wireframe of the following forms (# is in reference to [List of CCBC Program Documents.xlsx](https://citz.sp.gov.bc.ca/sites/OCIO/CONN/NWBC/CC/_layouts/15/DocIdRedir.aspx?ID=XCMZ5RSJMXW7-1605152785-1)):
- [x] 13	Section 2: Funding Application Form ("UBF Form")
- [x] 19	UBF Template 1 - Eligibility and Impacts Calculator
- [x] 21	UBF Template 2 - Detailed Budget
- [x] 23	UBF Template 3 - Financial Forecast
- [x] 25	UBF Template 4 - Last Mile Internet Service Offering
- [x] 26	UBF Template 5 - List of Points of Presence and Wholesale Pricing
- [x] 27	UBF Template 6 - Community and Rural Development Benefits
- [x] 28	UBF Template 7 - Wireless and Mobile Addendum
- [x] 29	UBF Template 8 - Supporting Connectivity Evidence
- [x] 30	UBF Document Attachment: Copies of registration and other relevant documents
- [x] 31	UBF Document Attachment: Independently prepared financial statements for the last three (3) years
- [x] 32	UBF Document Attachment: Logical network diagram
- [x] 33	UBF Document Attachment: Project schedule (preferably a Gantt chart)
- [x] 34	UBF Document Attachment: Community and Rural Development Benefits supporting documents 
- [x] 35	Attachment guidance: Community letter(s) of support or resolution
- [x] 36	Attachment guidance: Corporate social responsibility and philanthropic practices
- [x] 37	Attachment guidance: Commitment by executive management of an applicant to facilitate access to its passive infrastructure
- [x] 38	Attachment guidance: Evidence of imminent access to third party infrastructure (if needed for project completion)

https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=24%3A534

**Comment by eazeredo** [comment]
@MarsRomer , can you take a look at this card?

Once this card is approved, it can be closed as it is just about prototyping and not going to be developed.

**Comment by eazeredo** [comment]
correction ... the prototypes here will be developed, but not in this card.

**Comment by MarsRomer** [comment]
I think the prototypes can be considered done for the sake of this ticket, noting that there could be updates in the future,
