### ISSUE TITLE
MVP application stepper 

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/CONN-CCBC-portal#467]
### User Story
As an applicant I want a navigation sidebar (aka stepper or task list)
so that I can navigate between different pages of the form.

### Acceptance Criteria
- [x] List of all form pages, except submission
- [x] Each page is linked
- [x] **Scenario: sidebar on form pages, top aligned, bold current page**
Given that an applicant is logged in
when they are on any page of the form
then they will see the sidebar on the left-hand side
and the top of it will be aligned with the form title
and the page they are on will be bolded & underlined
- [x] **Scenario: not on narrow screens**
When the viewport is narrower than 768px
then the sidebar will not be visible.
- [x] Stepper should have same horizontal location when you navigate between pages.
~~- [ ] **Scenario: error on page**
Given that there is an error
when a user presses another page in the stepper
then they will not be redirected (will stay on the same page)
and the screen will scroll to where the error is.~~

![Screen Shot 2022-08-29 at 5.01.45 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/472181e8-c364-47c6-82cb-95e9f766c0c5)

**Comment by zoeyli-46** [comment]
Are we going to keep the acknowledgements section and the submit page once they have submitted the application? 
- From user feedback, if an applicant wants to edit a submitted application, they may want to click the submit button again

**Comment by matthieu-foucault** [comment]
@zoeyli-46 
- does "Stepper is floating" mean that the top of the stepper aligned with the form title?
- do we need any layout change on a half screen (i.e. 600px wide)?

**Comment by zoeyli-46** [comment]
@matthieu-foucault 

- top of stepper is aligned with form title, the stepper may be longer than the screen, if this is the case then scrolling the page will show the rest of the stepper. 
- Can it continuously scale down until a min-width of 280px wide? This will ensure there is still some padding on the longest word in the stepper. Otherwise, wrap the text into a new line

**Comment by elliottSlee** [comment]
For this MVP version, are we prioritizing responsive designs?

**Comment by zoeyli-46** [comment]
Yes, since the government screen dimensions are smaller, then instead of setting a min-width let's just scale the stepper width down continuously where the text can wrap into a new line
