### ISSUE TITLE
Service Blueprint

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#47]
As a program admin or a developer, I want to see the whole program, who is involved at which phase, support processes, and evidences (places and documents) that are involved in Connecting Communities BC so that I can understand it more wholly.

"Detailed Service Blueprint - 2.1"
https://miro.com/app/board/uXjVOANcgPo=/?moveToWidget=3458764523811216227&cot=14

- [x] Describe all phases
- [x] Determine who is involved at each phase
- [x] Describe key processes at all phases (note: not tasks)
- [x] Determine documents needed at each phase
- [ ] Define criteria for changing one phase to next
- [ ] Gather questions
- [ ] Present to Howard
- [ ] Maybe present to Susan

**Comment by elliottSlee** [comment]
https://miro.com/app/board/uXjVORZW4n4=/?moveToWidget=3458764523318854909&cot=14

**Comment by zoeyli-46** [comment]
"Define criteria for changing one phase to next" This is related to the state machine, correct?

**Comment by elliottSlee** [comment]
Yes, that seems related.
