### ISSUE TITLE
application_status table records a history of application_status_type changes

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/CONN-CCBC-portal#470]
![image.png](https://images.zenhubusercontent.com/575f1a78bf93871ccd9c8bcd/44ac8a16-c7cb-4b06-bbf3-ea36ae81c6fd)

The application_status table should contain the history of application_status_type changes. An application_status should not be updated.

- [x] The `application_status` table only grants insert and select permissions to `ccbc_auth_user`
- [x] Only created_by/at columns should be added. 
- [x] Row-level security should be aligned with the application table (i.e. users can only insert their application's status) and tested with pgtap
- [x] The application table should have an `application_status` computed column, returning the latest status (ordered by id. Ordering by `created_at` would cause difficulties when testing)
- [x] The `application_status_type` table should be populated with the following records:
  - draft
  - submitted
  - withdrawn

- [x] The `application_status_type` table only grants select permissions

- [x] Given that I am logged in as an applicant
When I start an application
Then an `application_status` record with the `draft` status is inserted in the `application_status` table

- [x] Given that I am logged in as an applicant
When I submit an application
Then an `application_status` record with the `submitted` status is inserted in the `application_status` table

- [x] Given that I am logged in as an applicant
When I withdraw an application
Then an `application_status` record with the `withdrawn` status is inserted in the `application_status` table
- [x] A custom `create_application` mutation should enforce that applications can only be created when an intake is opened

**Comment by eazeredo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/470?planning-poker) with Zenhub @AntBush @marcellmueller @matthieu-foucault @wenzowski
