### ISSUE TITLE
json schema should be stored in the database and linked to the form data

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/CONN-CCBC-portal#471]
Required for the RFI form enablement.

Benefit:  Good back end validation so that data is coherent.
Risk:  acknowledgements could be bypassed

![image.png](https://images.zenhubusercontent.com/575f1a78bf93871ccd9c8bcd/7ebafa5a-e9c2-4979-bc7f-ff07a5194348)

- [ ]  Update the application JSON schema to be a JSON object
- [x] Create a `form` table that contains a single record, with an `intake1schema` slug. The record must be inserted after deploying the sqitch changes, in an idempotent way, allowing for non-breaking changes in prod (see [ciip](https://github.com/bcgov/cas-ciip-portal/blob/develop/schema/data/prod/form_json.sql)]. If we want to keep our json schema in multiple files, we can consider having a server-side function writing it to the DB (if needed) at boot time.
- [x] The `ApplicationForm` component retrieves the json schema from the db
- [ ] The `submit_application` mutation takes the total number of acknowledgements from the json schema rather than the constant
- [x] The `application_form_data` computed column filters `form_data` records based on the `form_id`

**Comment by eazeredo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/471?planning-poker) with Zenhub @AntBush @marcellmueller @matthieu-foucault @wenzowski

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/471?planning-poker) with Zenhub @VB-at-Bis @wenzowski

**Comment by marcellmueller** [comment]
@MarsRomer I seem to have issues with it in test though it's working great on my local machine. Sorry about this.
