### ISSUE TITLE
Bug: Submit not working

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#474]
Submit button is un-responsive 

![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/2b24fd16-9d13-4a4d-babe-77a0f79d0acf)

**Comment by MarsRomer** [comment]
@matthieu-foucault  is this only waiting for dev review now?  Would be good to get it into test for tomorrows demo

**Comment by matthieu-foucault** [comment]
Just got merged. We can deploy to test this afternoon
