### ISSUE TITLE
Disable acknowledgements & submission during edit

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#477]
As an applicant,
I want to have **the fields disabled** on the acknowledgments & submission pages and a button to return to the dashboard on the submission page
so that I don't remove any required fields when editing an application.

## Acceptance Criteria
- [x] **Scenario: acknowledgment checkboxes disabled**
Given that an applicant has submitted an application and clicked _Edit_
when they navigate to the acknowledgements page
then the checkboxes will be disabled
#
- [x] **Scenario: submission page fields disabled & return to home button**
Given that an applicant has submitted an application and clicked _Edit_
when they navigate to the submission page
then the input fields will be disabled
and the submit button will be disabled & changed to say, "Changes submitted"
and a secondary button will be visible that says, "Return to dashboard"
#
- [x] updating uses a custom mutation that enforces immutability of `acknowledgment` and `submission` fields (i.e. compares the json before updating) for submitted applications
#
- [x] **Scenario: return to dashboard**
Given that an applicant is editing their application and they are on the submission page
when they click "Return to dashboard"
then they are directed to the dashboard
#
![Screen Shot 2022-08-24 at 3.13.04 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/63eb2dee-a7a9-47a7-b748-df8907fcb15b)

<img src="https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/b6742d61-b728-48e9-9203-17524f49d89f" width="80%">

**Comment by eazeredo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/477?planning-poker) with Zenhub @AntBush @marcellmueller @matthieu-foucault @wenzowski

**Comment by MarsRomer** [comment]
please add backend (db validation) and buttons for return to dashboard and change the button to continue on the acknowledgements page.

**Comment by marcellmueller** [comment]
@AntBush just flagging for merge conflict reasons that I'm almost finished a PR (as long as review goes okay ha) for the 'Save as draft' button which moves the submit buttons to a separate component. Up to you if you want to branch of my branch or what, just giving a heads up.

https://github.com/bcgov/CONN-CCBC-portal/pull/656/files

**Comment by AntBush** [comment]
I think I'll need to branch off of your branch since I'll need to edit the behaviour of the submit application mutation as well and don't want to conflict with the `sqitch rework`

**Comment by marcellmueller** [comment]
`submit_application` mutation changes are in #295 :(
