### ISSUE TITLE
Add xls to uploads validation

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#478]
All uploads that have a validation rule that they file should be an xlsx should also allow xls.  Currently uploads such as the Templates uploads only allow xlsx.

**Comment by matthieu-foucault** [comment]
Are we planning on ever parsing automatically those xls files? Parsing an `xls` isn't the same as parsing an `xlsx`

**Comment by MarsRomer** [comment]
possibly

**Comment by MarsRomer** [comment]
it would only be template 9 that I can see we would want to automate extracting the list of communities from.
