### ISSUE TITLE
Update CCBC OSD entries for BCeID

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/CONN-CCBC-portal#498]

**Comment by eazeredo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/498?planning-poker) with Zenhub @AntBush @marcellmueller @matthieu-foucault @wenzowski

**Comment by matthieu-foucault** [comment]
No work from the devs required, PO task
