### ISSUE TITLE
Add Editing Modal

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#499]
### User Story
As an applicant
I want a modal to appear when I click edit that tells me about editing deadline & how my responses are saved
so that I am aware of what happens to my application when I am editing

### Acceptance Criteria
- [ ] **Scenario: modal appears**
Given that an applicant is on the dashboard
and have submitted applications
when they click edit on a submitted application
then a modal will appear in the centre of the window
and the background will be darkened

- [ ] **Scenario: Edit button in modal**
Given that an applicant has clicked edit
and the modal is visible
when they click the "Edit" button in the modal
then they are directed to the first page of the application

- [ ] **Scenario: Cancel button in modal**
Given that an applicant has clicked edit
and the modal is visible
when they click "Cancel"

Modal header: Edit application
Modal body: "You may edit the application until the deadline on [intake close date DD/MM/YYYY] at [intake close time 9:00AM].
Any edits you make are automatically submitted."
![Screen Shot 2022-09-08 at 10.20.09 AM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/1f4fb22e-3f35-4d93-a3cd-68acd68b8340)
[**Wireframe**](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=2301%3A9343)

**Comment by eazeredo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/499?planning-poker) with Zenhub @AntBush @marcellmueller @matthieu-foucault @wenzowski

**Comment by AntBush** [comment]
This only applies to a submitted Application yeah? A draft application wouldn't be "automatically submitted" and can be edited after the intake deadline

**Comment by elliottSlee** [comment]
Yes, only for submitted applications.
