### ISSUE TITLE
Define a process to manipulate data in production

### ISSUE THREAD

**Issue by eazeredo** [bcgov/CONN-CCBC-portal#502]
### Description:
Draft a formal process for
- [ ] the Product Owner request data manipulation in the production environment and 
- [ ] the Development Team to respond to the request.

Ad-hoc (by-passing the pipeline)

**Comment by wenzowski** [comment]
This is currently blocking a request from PO to manipulate data in prod

**Comment by wenzowski** [comment]
A thread with [some inspiration](https://news.ycombinator.com/item?id=29563226)

**Comment by matthieu-foucault** [comment]
Interesting suggestions from the thread (other than "use a data migration tool", which is our default behaviour):
- do a backup before manipulating data
- pair program
- make your change in a transaction, and verify the state of your data before committing
Other things to consider:
- Put the app in maintenance mode to prevent concurrent transactions (we might need an alternative to growthbook here that supports backend feature flags)

**Comment by matthieu-foucault** [comment]
Important part of the process to add: don't connect as superuser

**Comment by marcellmueller** [comment]
Okay I wrote some notes on this from pairing with Mattieu earlier:

- Always pair with someone on this. Modify/write the query and get both team members to ensure it looks fine. Testing it locally is also an option.

- Don't commit changes as superuser, change to database user.
`set role ccbc;`

- Always do changes in a transaction:
`begin;`
\
`insert/alter statement here....`
\
- If there is an error user rollback:
rollback;

- If the command was successful select the data to verify
`select column from ....`
\
-Both team members verify that updated data looks good.
\

- If everything looks good commit the transaction:
`commit;`

If data is testable in the app such as an intake date check the site and make sure everything is in order

Next repeat the same steps in test and message PO once complete. Once PO verified the changes and gives approval do prod next.

**Comment by eazeredo** [comment]
@marcellmueller , small adjustment for data manipulation:

Only `insert/update/delete`. 

`Alter` is to change the database structure.

**Comment by matthieu-foucault** [comment]
Proposal: The PO should specify a deadline in the change request

**Comment by marcellmueller** [comment]
@MarsRomer you can review this one here:
https://github.com/bcgov/CONN-CCBC-portal/blob/main/docs/process_to_manipulate_data.md

**Comment by MarsRomer** [comment]
Thanks @marcellmueller  looks good to me.  I don't see a line about pushing to prod though.  Once pushed to prod the PO should once again be notified.

**Comment by MarsRomer** [comment]
Should we add:
 step 10:  Make changes to prod and notify PO
step 11: change intake dates in test to previous values or new values provided by PO

**Comment by marcellmueller** [comment]
Yep sounds good.

**Comment by marcellmueller** [comment]
Updated here: https://github.com/bcgov/CONN-CCBC-portal/blob/main/docs/process_to_manipulate_data.md
