### ISSUE TITLE
Refactor review component to use an rjsf read-only theme

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/CONN-CCBC-portal#505]
The review page should 
 - [ ] use a custom field, that renders a form with a read-only field
 - [ ] have a field to automatically record whether there are validation errors or not
 - [ ] have a field to record whether the applicant acknowledges validation errors

**Comment by elliottSlee** [comment]
Is [this accordion components from SSO](https://bcgov.github.io/sso-react-components/?path=/story/accordion--open) relevant?
