### ISSUE TITLE
Application data should be stored in the form_data table

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/CONN-CCBC-portal#508]
### Description

Because an application may have multiple revisions in the future, i.e. multiple form data, we need to store the json data in a separate table.
From a user's perspective, the current behaviour of the app should remain the same.

- [x] create a `form_data` table, containing a `json_data jsonb` column
- [x] create an `form_data_status_type` table, with the `draft` and `submitted` records hardcoded in it
- [x] create an `application_form_data` table, with an id and the following foreign keys: `application_id`, `form_data_id`
- [x] add a `form_data` computed column on `application`, to retrieve the current form data (ordering form_data by id)
- [x] the `application_form_data` table change should add RLS policies on the `form_data` table, ensuring that form_data can only be created by users if they have access to the corresponding application.
- [x] when creating an application, a `form_data` and `application_form_data` records should be created

This can be done after prod release, but will be more costly then as we will need to migrate existing forms, which will result in a short (<2min) outage

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/508?planning-poker) with Zenhub @wenzowski @VB-at-Bis

**Comment by AntBush** [comment]
Is the `application_form_data_status_type` any different than `application_status_type`?

**Comment by matthieu-foucault** [comment]
Yes, an application can have more statuses than the form itself. The form itself is either draft or submitted, that's it. I'm wondering it should be `form_data_status_type` instead of `application_form_data_status_type`, so that this type table is reused for the other forms we will create.

**Comment by elliottSlee** [comment]
For whoever takes this on, please communicate whether it will or won't be shipped to prod before Wednesday, September 28th.

**Comment by MarsRomer** [comment]
yes go ahead and delete the test env data
