### ISSUE TITLE
Applicant - Reply RFI - Upload documents 

### ISSUE THREAD

**Issue by MarsRomer-zz** [bcgov/CONN-CCBC-portal#533]
## User Story
As an analyst
after the intake closes
I want applicants to have the ability to upload documents that I am asking for
so that they are properly stored and named for retrieval and review.

## Acceptance Criteria

#
- [x] **Trigger UI for applicant to upload files**
Given that an analyst is on the New RFI page
and has selected checkboxes to request files
When they press save
Then a link appears in the action column of the _applicant's_ dashboard for the application to "Upload files"
and when an applicant presses this
then the selected upload fields will show on a page.
#
- [ ] **Scenario: deadline**
Given that an analyst has created an RFI
and requested files in the New RFI form
when the current date is before the due by date
then link appears in the action column of the _applicant's_ dashboard for the application to "Upload files"
and the due date will be displayed in the page header
when the current date is after the due by date
then the "Upload files" link will not be available and the upload files page will not be accessible

> email template says "end of day". Deadline could be midnight that day just to be safe.

#
- [x] Given that an analyst has _not_ selected a due by date
and has requested file(s)
when an applicant is logged in on their dashboard
then they will see an upload files option.
#
- [ ] **Scenario: file name & upload in progress**
Given that a user clicks on upload file
when they press upload
then they will see their file name below the relevant section
and the upload button will show a loader gif (Use existing one)
#
- [ ] **Scenario: Loader gif replaced by delete button**
Given that a file is currently being uploaded
when the file is successfully uploaded
then the loader gif will disappear
and a red x will appear beside the filename 
#
- [ ] **Scenario: Delete upload**
Given that user is on a file upload page and has uploaded a file
when they click the red x beside the file name
then their upload will be deleted
and the filename will be removed from the ui.
#
- [x] **Old file retained**
Given that an applicant is on the file upload page
when they upload a new file
then the old files are retained on the server and can be linked back to the CCBC ID, date originally uploaded, and original filename.
#
- [ ] page remains available until due by date

- [ ] files show up in list RFI page for analysts
- [ ] analyst can click filename to each download file

## Technical
- Press button creates json schema
OR
In applicant upload page, depending on what was selected, different things are rendered.

## Ultra refinement
- DB:
- [ ] .
- Frontend:
- [ ] . 
- Integration/API:
- [ ] .
- Tests:
- [ ] .
- Documentation:
- [ ] .

## Wireframes
[**Wireframe**
](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=8072%3A44162)

![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/0e161705-848c-4572-b4fe-8a2914657bad)

![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/49e0f97e-ed7f-4df1-942d-4b800e0af9b8)

![Analyst view after response.jpg](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/120c36bd-7159-498d-b6cd-04863a0cc971)

### Deprioritized
~~- [ ] **Scenario: first file is replaced by 2nd**
Given that an applicant is on the file upload page
when they click on replace and upload a new file
then the original filename will be removed from the ui
and the new file will be uploaded~~
#

**Comment by elliottSlee** [comment]
@MarsRomer since supporting letters will be due @ intake close with no grace period, is this part of the RFI?

**Comment by MarsRomer** [comment]
@elliottSlee  yes RFI only.  Not to say that NWBC won't extend the deadline for the supporting letters at some point, but at this time there are no plans to.  I.e. supporting letters should be submitted with the application by Dec 15

**Comment by zoeyli-46** [comment]
@MarsRomer we originally imagined the applicant would select from a list which file they are uploading, but if we design the RFI screen where Analysts can select what files applicants are allowed to upload, then it can help limit applicants from submitting other unwanted files

Here are some wireframes if the process is for analysts to select what files they want from the applicant  ![image.png](https://images.zenhubusercontent.com/61e8875b1de5eff8f072cd04/e38877dd-b6f6-4fdc-b716-1472d6869973)
![image.png](https://images.zenhubusercontent.com/61e8875b1de5eff8f072cd04/ee11aa97-9791-4d16-8d6c-01bc2bd62618)

**Comment by MarsRomer** [comment]
love the designs!

**Comment by MarsRomer** [comment]
once the applicant has uploaded the required documents, how does the analyst then remove the applicants access?

**Comment by elliottSlee** [comment]
Applicants would have a single shot to upload them. Once uploaded, they would no longer have access. The new uploads could appear in the review page

**Comment by MarsRomer** [comment]
what if we are asking for more than one document for a category such as missing letters of community support? can they upload multiples?

**Comment by elliottSlee** [comment]
After the applicant presses the "Submit files" button, they would no longer have access.

**Comment by MarsRomer** [comment]
so they would have to make sure they have all their files ready to submit as asked by the RFI before they start the submission process.  If they want to do some now, some later then there will have to be another RFI request from the analyst.  I don't know how often this would happen, is there some way to make sure they know that they will not be able to upload more files once they hit submit?

**Comment by elliottSlee** [comment]
Wait, what was I thinking! Applicants are given a deadline for RFIs and we've been informed that they always meet this deadline (barring 1 experience). We can close their access to this uploads page after that deadline. However, this would rely on the business process of sending an RFI and entering the info in the portal to be completed concurrently.

**Comment by zoeyli-46** [comment]
If the RFI is overdue, do we still want those files? If so, then instead of the deadline being the trigger, once all files have been received can be the trigger for disable the ability to append new files. 
<img width="457" alt="image" src="https://user-images.githubusercontent.com/77090142/191794950-418646d2-cd71-44ad-b02c-634eadbe09c6.png">

**Comment by elliottSlee** [comment]
@eazeredo The new AC overlaps with the existing AC. Please remove or clarify.

**Comment by elliottSlee** [comment]
Need to add AC for what happens when press save:
1. page remains available until due by date
2. files show up in list RFI page for analysts (yes, files should appear there before the due by date. Think of when you call your phone company for support, you want them to have the information available in front of them. It won't be touched by analysts until the due by date).

**Comment by MarsRomer** [comment]
I've added the Need Refinement label to this ticket - we can look at this at planning meeting

**Comment by MarsRomer2** [comment]
I was able to get the RFI to work, I think the issue was due to the date changing back 1 day.  One question:  Should I expect to be able to click on the file name here in the analyst portal to download it?  If so, that is not working for me just now:
![image.png](https://images.zenhubusercontent.com/638e5e789d9295d36fe268e9/c6eebdce-ff47-4ad1-96c0-3df5b841ef76)

**Comment by MarsRomer2** [comment]
tried it again right after my comment above and now I can download the RFI file, not sure why it didn't work the first time.
This ticket is complete, I will put it in the done column
