### ISSUE TITLE
Status changes to Received (automated)

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#538]
### User Story
As an applicant
I want my submitted applications to be received by NetworkBC
so that my application will be assessed.

### Acceptance Criteria
- [ ] **Status changed to Received**
  Given that an application status is _Submitted_
  When the current date & time are after intake closing date & time (or current DateTime-TimeTravel feature)
  Then the date & time are recorded in the database
  And the status is changed to _Received_.

Note: Will need to handle scenarios here where the intake close date changes. Updates to the job will be required if the closing date changes.

### Dev notes
- [x] add `receive_applications()` function that adds a 'Received' status for every application that is submitted and where the intake is closed.
- [x] create `ccbc_job_executor` role in the DB
- [x] `ccbc_job_executor` can see all applications, intake, application statuses, etc...
- [x] `ccbc_job_executor` can insert `application_status`
- [x] configure cronjob in helm chart to call `psql -d ccbc -c 'set role ccbc_job_executor; select ccbc_public.receive_applications();'` twice a day at 9am/pm PST
- [x] cronjob should be run with `ccbc_app` user and `ccbc_job_executor` role
- [x] add received status type for applications

**Comment by MarsRomer** [comment]
Are the newest changes in test?

**Comment by matthieu-foucault** [comment]
They are, yes. To run this in the test environment, we need to:
- manually update the intake close date
- manually trigger the cron job

**Comment by MarsRomer** [comment]
thanks was just making sure :)
