### ISSUE TITLE
Metabase - duplicate attachments inserted

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#568]
I uploaded an attachment in test environment in the template 1 upload.  
![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/23b26769-3686-42bf-9ff1-456f15efa499)

But when I looked in the attachments table in metabase I see the entry duplicated:  See ID 1 and 2.

![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/8580e36a-ad09-45f3-9517-5aec90a05026)

I was expecting to only see one entry for that attachment.

**Comment by MarsRomer** [comment]
@matthieu-foucault I have put this bug in the next sprint candidates but if you think it's urgent enough perhaps we can move it into the current sprint.  I suspect we don't need to fix this until sept 7 but prob by sept 15

**Comment by VB-at-Bis** [comment]
PR created https://github.com/bcgov/CONN-CCBC-portal/pull/594
