### ISSUE TITLE
Wording updates

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/CONN-CCBC-portal#570]
### Project information
- [ ] Add "Provide a" to the project title question
"**Provide a** Project title. Be descriptive about the geographic region. We advise not using years in the title."

### Benefits 
- [ ] Remove the word "Sustainability." from the first question
"~Sustainability~. Please summarize the benefits that the project will bring to the targeted areas..."

### Project planning and management
 - [ ] Change "Completion Date" to "Project Completion Date"

### Template uploads
- [ ] Rename template 9 to "Template 9 - Backbone and Geographic Names"

**Comment by elliottSlee** [comment]
Combined with #597
