### ISSUE TITLE
Bug: 2 calendars open at same time

### ISSUE THREAD

**Issue by MarsRomer-zz** [bcgov/CONN-CCBC-portal#572]
When I click on the white space in the 'Completion date' box it opens two calendars.  I think the top one is for the 'Project Start date'.
Strangely this only happens when I click in the white space and not on the calendar icon itself.  
Also it appears to happen only when the project title in the top left is long enough to make the title of the form page wrap around.

![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/0f64d8b4-1db6-4f8d-a527-0908e268fc08)

**Comment by marcellmueller** [comment]
Closing as this was taken care of by switching the datepicker to MUI datepicker in #1722
