### ISSUE TITLE
SSO Middleware

### ISSUE THREAD

**Issue by BryanGK** [bcgov/CONN-CCBC-portal#58]
As a stakeholder
I want to have SSO capabilties
So that users can easily sign up and login to the application

- [ ] Set up session middleware
- [ ] sign up for keycloak thru platform services
- [ ] create login view
- [ ] create login/logout buttons
- [ ] test and ensure proper login/logout functionality

**Comment by matthieu-foucault** [comment]
we already have the SSOs
