### ISSUE TITLE
Only deploy to test and prod on a tag push

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/CONN-CCBC-portal#582]
In the release docs, it says we only deploy to test/prod on a tag push, but this check was removed as the implemented solution didn't work.

- We might want to update release-it to issue a v1.x.x tag, instead of 1.x.x
- [ ] Create a separate release workflow, triggered on a tag push, that waits for the deploy workflow to complete, using https://github.com/marketplace/actions/wait-on-check

**Comment by AntBush** [comment]
So, if I get this right, we will only be deploying to test when we also want to deploy to prod?

**Comment by matthieu-foucault** [comment]
Correct. Test acts as a pre-prod environment. As of v1.0.0, we're not wiping the test environment on deploy anymore
This allows us to update sqitch changes and continuously deploy to dev until we're ready to ship a release, and verify in test that said release would deploy well, since the test schema is always aligned with prod

**Comment by AntBush** [comment]
Question about the second bullet point: the release workflow will run the deploy workflow(?) and wait for the deploy workflow. I'm not seeing the reason why we'd want the waiting behaviour there.

**Comment by matthieu-foucault** [comment]
We only want do deploy to test once the dev deployment succeeds, to make sure we're not attempting to deploy a broken configuration, and to ensure that the containers are built.
We also only want to deploy to test on a tag. If you find a solution that does not involve a release workflow waiting on the dev deployment, go for it. 

What I had done was adding `if: startsWith(github.ref, 'refs/tags/v')` do the workflows (I undid it in 590dfe827), but this doesn't work because `github.ref` is the branch ref when the workflow is triggered by a push. You could just [get check the tags pointing to the commit](https://roadfiresoftware.com/2012/06/git-pro-tip-how-to-list-tags-that-contain-a-commit-with-git/).

I would recommend trying with adding your filter to one of the build workflows to test, and to push tags to your branch

**Comment by AntBush** [comment]
>We only want do deploy to test once the dev deployment succeeds, to make sure we're not attempting to deploy a broken configuration, and to ensure that the containers are built.

From my understanding, isn't that already the defined behaviour? Couldn't we just add a 
```
on:
 push:
   tags:
     - v1.* #or none since I don't think we really care
```
on our main.yaml? Then it would run the tests/build/deploy to dev and would fail if any of those steps fail.

**Comment by matthieu-foucault** [comment]
If we add this to our main, won't it run the workflow twice? Once for the branch push, and once for the tag push?

**Comment by matthieu-foucault** [comment]
> From my understanding, isn't that already the defined behaviour?

Yes

**Comment by matthieu-foucault** [comment]
@AntBush I think this issue and the documentation should be revised a bit. Rather than only deploying to test if the pushed commit is tagged, I would like to push if any of the commits that just got pushed are tagged. 

This would allow us to merge a release branch with a merge commit, which is what happens when we enable auto-merge (and is what I just did). 

We cannot enforce that release branches are merged with a fast-forward, so it's best to not rely on tired developers to follow this convention (and we should remove it from the readme).

For this to happen, I think we need a custom job that looks at all the commits that are part of the [push event](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#push)  and has an [output](https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs) depending on whether one of these commits has a `v*` tag.
