### ISSUE TITLE
Update CI/CD

### ISSUE THREAD

**Issue by MarsRomer-zz** [bcgov/CONN-CCBC-portal#588]
Business value: reduce errors and dependencies on the GitHub Actions CI/CD pipeline will allow for less delays on deployments to dev/test/prod and reduce the wait time on checks required for PRs.

Description: Update CI/CD so they only depend on what is needed. 

AC: 

- [x] Update CI/CD pipeline so tasks only depend on what they need and can run concurrently
- [x] Turn setup-dev-env into a separate task
- [x] Make steps that require dev env wait for it, other steps can run without it (Update test-containers)

**Comment by rafasdc** [comment]
Looks like `install-test-env` might not be needed, letting cache update and re-runing later to confirm.
