### ISSUE TITLE
Wording updates

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#597]
#### Navbar
- [x] Change "Help" to "Email us"

#### Project information
- [x] Add "Provide a" to the project title question
"**Provide a** Project title. Be descriptive about the geographic region. We advise not using years in the title."

#### Benefits 
- [x] Remove the word "Sustainability." from the first question
"~Sustainability~. Please summarize the benefits that the project will bring to the targeted areas..."
- [x] Change cell G50 to F151 # in "Final number of Eligible Households targeted by this proposal..."

#### Project planning and management
 - [x] Change "Completion Date" to "Project Completion Date"

#### Template uploads
- [x] Rename template 9 to "Template 9 - Backbone and Geographic Names"

#### Supporting documents
- [x] Community and Rural Development Benefits supporting documents. Remove any reference to 30-day grace period
- [x] Add "Accepted file types: .pdf, .png, .jpg, .jpeg, .vsd, .vsdx, .doc, .docx, .ppt, .pptx" to Logical Network Diagram
- [x] Add "Accepted file types: .xlsx or .mpp" to Project schedule
[See Wireframe](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=1059%3A7602)

#### Review Page
- [x] Change page description to "Please review your responses before proceeding to the acknowledgement and submission pages."
- [x] Remove 30 day grace period sentence from "Community and Rural Development Benefits supporting documents"

**Comment by elliottSlee** [comment]
@MarsRomer I added this card to the upcoming sprint

**Comment by elliottSlee** [comment]
fyi @MarsRomer I added "Change cell G50 to F151 # in "Final number of Eligible Households targeted by this proposal..."

**Comment by MarsRomer** [comment]
I took a closer look at template 1 and it looks like G50 formula is =F151 so I guess they are the same number but prob not a bad thing to change the cell number because template 1 is more clear on what cell F151 is
