### ISSUE TITLE
Add Save as Draft button to Submission page

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#598]
### User Story
As an applicant
I want an action button on the submission page to save & return to the dashboard
so that I can do something other than submitting.

### Acceptance Criteria
- [x] **Scenario: Save as draft button**
Given that an application is in _Draft_ status
when on the submission page
then a secondary button is visible with the label, "Save as Draft"

- [x] **Scenario: No Save as draft button for other statuses**
Given that an application is any status other than _Draft_
when on the submission page
then a secondary button with the label, "Save as draft" is NOT visible

- [x] **Scenario: Save as draft changes to Saved and toast pops up**
Given that an application is in draft
and the user is on the submission page
when they click on "Save as draft"
then the button text changes to "Saved"
and a toast appears beside the button saying, "Saved as Draft. Return to dashboard."
and the toast is colour: 2E8540

- [x] **Scenario: Toast interactions - Return to Dashboard**
Given that an applicant has clicked "Saved as Draft"
and the toast has appeared
when they click on "Return to dashboard" in the toast
then they are directed to the dashboard.

- [x] **Scenario: return to page**
Given that a user leaves the page or refreshes the page
when they return to the page
then the button will show "Save as Draft"

 - [x] **Scenario: changes on the page**
Given that a user has pressed the save as draft button
and it is displaying "Saved"
when they make a change on the page
then the toast will disappear
and the button will change back to "Save as Draft"

#
>![Screen Shot 2022-09-08 at 9.58.35 AM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/c77744c7-8b8a-4b8b-9877-783fccddfff3)
#
>![Screen Shot 2022-09-08 at 1.32.03 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/e2f77120-1c96-4a6e-927e-9c9000745175)
#

**Comment by matthieu-foucault** [comment]
Did this need UX tweaks before being ready? Do we have a tag to indicate that?

**Comment by MarsRomer** [comment]
Blocked until we have designs for this (cc @elliottSlee)

**Comment by elliottSlee** [comment]
@MarsRomer @matthieu-foucault updated.
