### ISSUE TITLE
Include favicon at new url

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#624]
### User Story
As any user of the portal
I want a favicon of the BC 
so that the site seems legitimate and I can find it in a row of tabs.

The favicon was working before we moved to the new vanity URL.

### Acceptance Criteria
- [ ] Given that any page of the portal is open
then the favicon of the will appear in the browser tab

https://developer.gov.bc.ca/images/favicon.ico
https://developer.gov.bc.ca/favicon-32x32.png

**Comment by matthieu-foucault** [comment]
I see some 404s, looks like a bug: ![image.png](https://images.zenhubusercontent.com/575f1a78bf93871ccd9c8bcd/bb26873e-821a-4db3-b66d-0b25c74f4db9)

**Comment by elliottSlee** [comment]
Favicon is working now.
