### ISSUE TITLE
Landing page - internal users

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/CONN-CCBC-portal#635]
### User Story
As an analyst, I want a portal website so that I can review applications.

### Acceptance Criteria
Landing page url: www.connectingcommunitiesbc.ca/analyst
"Login with IDIR" button leads directly to IDIR login page.

### Design
**Landing Page**
https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=5431%3A23182

**Comment by zoeyli-46** [comment]
Related to [ticket #26]? (https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/26)

**Comment by AntBush** [comment]
> Related to [ticket #26]?

Would definitely be a pre-requisite before this, since we wouldn't want to deploy with this being accessible to any auth user.

**Comment by matthieu-foucault** [comment]
Should this ticket and #26 be merged? The "Login with IDIR" button is in the acceptance criteria

**Comment by zoeyli-46** [comment]
Merging with #26 and closing this
