### ISSUE TITLE
Create a file with all intake form questions

### ISSUE THREAD

**Issue by eazeredo** [bcgov/CONN-CCBC-portal#64]
The main goal is to have on file to be the single source of truth, which the Dev Team and different Stakeholders can consult. The Dev Team is creating this file to be further maintained by the PO.

- [x] Create master list of questions
- [x] Create a word document on the [CCBC Sharepoint Folder](https://citz.sp.gov.bc.ca/sites/OCIO/CONN/NWBC/CC)
- [x] Copy all the questions and answers from the UBF form into the document [CCBC Master Question List.docx](https://citz.sp.gov.bc.ca/sites/OCIO/CONN/NWBC/CC/_layouts/15/DocIdRedir.aspx?ID=XCMZ5RSJMXW7-1605152785-217).
The technical details of each questions is in the XLSX file (CONN - Agile Development < Research < Files < [DataMapping.xlsx](https://bcgov.sharepoint.com/:x:/r/teams/04708/Shared%20Documents/Research/DataMapping.xlsx?d=w5224cb99a79b48008b9105279418b6e3&csf=1&web=1&e=XJFQ3r))
- [x] Enable "Tracking changes"

### Note
To access CCBC Sharepoint folder, click on internal user access and login with IDIR@gov.bc.ca & IDIR password

**Comment by eazeredo** [comment]
@rgreensp , is this card accurate?

**Comment by elliottSlee** [comment]
Current iteration is a spreadsheet in CONN - Agile Development < Research < Files < [DataMapping.xlsx](https://bcgov.sharepoint.com/:x:/r/teams/04708/Shared%20Documents/Research/DataMapping.xlsx?d=w5224cb99a79b48008b9105279418b6e3&csf=1&web=1&e=XJFQ3r)

**Comment by elliottSlee** [comment]
Final file is [CCBC Master Question List.docx](
https://citz.sp.gov.bc.ca/sites/OCIO/CONN/NWBC/CC/_layouts/15/DocIdRedir.aspx?ID=XCMZ5RSJMXW7-1605152785-217).
It's stored on BC Gov old sharepoint. Maria F from NWBC who is in charge of creating the application guide has been notified that this is the master list of questions and we would appreciate her keeping it up to date. I will work with her on this.

**Comment by elliottSlee** [comment]
@rgreensp can you review that this is complete?

**Comment by elliottSlee** [comment]
@rgreensp can you review that this is complete?

**Comment by eazeredo** [comment]
@elliottSlee , @zoeyli-46 , @rgreensp 
At some point soon, for each field, we need to specify and define:
- Mandatory
- Max length
- Type (text, number, currency, dropdown, radio, checkbox, etc)
- Domain (options for dropdown, radio, checkbox)
- Any other information necessary.

**Comment by elliottSlee** [comment]
@eazeredo All of this is defined in CONN - Agile Development < Research < Files < [DataMapping.xlsx](https://bcgov.sharepoint.com/:x:/r/teams/04708/Shared%20Documents/Research/DataMapping.xlsx?d=w5224cb99a79b48008b9105279418b6e3&csf=1&web=1&e=XJFQ3r)
Let's chat with devs about how we can best identify this for them: in the wireframes, in the acceptance criteria for the issues, in this spreadsheet, by fax, by document carried by carrier pigeon...

**Comment by eazeredo** [comment]
@elliottSlee , the file is pretty good! Well done! Let's present this tomorrow during the standup.
I created the "Maxlength" column for this info.
And add the column "Page Section".

**Comment by eazeredo** [comment]
Checking the file against the wireframe, I spotted missing questions from the page "Project Info" starting with the Zone question. I added a few lines and marked them as yellow.

**Comment by eazeredo** [comment]
@rgreensp and @MarsRomer , can you review the card?

**Comment by eazeredo** [comment]
Is there any other work to be done here?

**Comment by MarsRomer** [comment]
I believe this is done.  Closing ticket now :)
