### ISSUE TITLE
Analyst - Click application in dashboard to view

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/CONN-CCBC-portal#640]
### User Story
As an analyst, 
I want to be able to click anywhere in the row to view the application
So that I can quickly get to the application page 

## Acceptance Criteria
- [x] Hover state
Given the mouse cursor hovers over anywhere in the row,
Then the row background colour changes to #F3F3F3
And the cursor changes to pointer 
#
- [x] Clicking row leads to the application
Given an analyst is on the dashboard
When they click on anywhere in the row
Then they are redirected to the respective application page (will redirect to 404 for now, until #32 is completed)

## Developer Notes:
Includes dynamic routing
/analystportal/application/[applicationid]

## Not included in this ticket:
Form data displaying as per figma designs

## Prototype 
with hover working
https://www.figma.com/proto/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?page-id=6958%3A32778&node-id=6982%3A38670&viewport=359%2C-5999%2C0.59&scaling=scale-down-width&starting-point-node-id=6982%3A38670

**Comment by zoeyli-46** [comment]
@elliottSlee have we finalized that clicking row in dashboard goes to overview rather than application? or should we do more tests before making that decision?

**Comment by elliottSlee** [comment]
Long-term I think that's best since leading to application is only necessary during assessment.
