### ISSUE TITLE
Default order table of applications

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/CONN-CCBC-portal#641]
- [ ] Given that an analyst is on the dashboard page
and the project table is visible
when applications exist
then the list is ordered by CCBC ID by default, starting from smallest to largest number

**Comment by zoeyli-46** [comment]
@elliottSlee 
analysts come to the dashboard to find applications to take action on next, do you think it should be in order of received, eligibility assessment, assessment, recommendation, conditionally approved, in flight, complete, or do you think it should be the above in the description?

**Comment by zoeyli-46** [comment]
Or maybe package in order smallest to largest? Because when they send their top 10 applications first those will be in package 1, they may want those applications to appear at the top of the list by default

so ranking in order of: package, status, org name

**Comment by elliottSlee** [comment]
Hm. this is much different than my expectation, but I'm not a user. I expected by CCBC ID since they often use that to find applications. Let's have them do it in the master spreadsheet so we can see it in action.

**Comment by zoeyli-46** [comment]
great plan! 

Yeah, ccbc ID could be one of the default ranking too. I was thinking when you have 10 applications that are in the ccbc-01100 - 01110 range that are now in Recommendation phase, do you want to scroll all the way down to find that?
