### ISSUE TITLE
View Intake Dates

### ISSUE THREAD

**Issue by MarsRomer-zz** [bcgov/CONN-CCBC-portal#651]
As an Administrator
I want to view intake dates
So that I can see what the past, present and future intakes open and close

### Screen 

![image.png](https://images.zenhubusercontent.com/606c9d37b7ff542cfdb25c53/560627ec-69ed-4c44-818f-37ce79f7f88e)
[**Wireframe - with 3 intakes**](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=9611%3A55158&t=CjF6XHQbMagCbYdH-4)

- On the Intake Dates sub-tab admin can see content as per screen design above

### Fields and info

- [x] **Fields:** Intake '#', start date, end date, description (if not null)
- [x] **Sort by:** intakes are in descending chronological order (most recent at the top)
- [x] **Behaviour:** Current intake has left stroke of 3px 3D9B50 

### Validations

- No validation

### Actions

- No action

## Not included:
- Add intake
- Edit button
- Delete button

## Ultra Refinement 
- **DB:**
  - .
  - .
- **Middleware:**
  - .
  - .
- **Frontend:**
  - .
  - .
- **Tests:**
  - .
  - .
- **Documentation:**
  - .
  - .

**Comment by matthieu-foucault** [comment]
@MarsRomer we need this not only for test, but for prod as well. 
I would recommend that this is blocking #370.
To confidently support multiple intakes, we need to ensure that the intake dates do not overlap. We should do this check in our mutations, but if we keep updating the intake dates in the database directly, it's going to be difficult to enforce this check.

**Comment by eazeredo** [comment]
Should we do issue #880 first?

**Comment by AntBush** [comment]
@eazeredo for just viewing, we don't need to do #880 first but for #1122 we do

**Comment by elliottSlee** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/651?planning-poker) with Zenhub @rafasdc
