### ISSUE TITLE
FileWidget test is flaky

### ISSUE THREAD

**Issue by AntBush** [bcgov/CONN-CCBC-portal#655]
The FileWidget test produces flaky results. As seen in this action ([attempt 1 ](https://github.com/bcgov/CONN-CCBC-portal/actions/runs/3055725858/attempts/1)/ [succeeded attempt](https://github.com/bcgov/CONN-CCBC-portal/actions/runs/3055725858)) 

This implies that a race condition is present, and the purpose of this ticket is to:

- [ ] Determine whether this race condition is present in the test or the widget to determine severity
- [ ] Resolve this race condition

**Comment by AntBush** [comment]
[Logs Archive](https://app.zenhub.com/files/476885245/ea4005a2-34b1-42a9-8ab3-da9fbce2d56d/download)

[Relevant Section](https://app.zenhub.com/files/476885245/e52e579b-842e-4d5c-8408-5a9a349be3d8/download)

**Comment by matthieu-foucault** [comment]
Nothing for PO to review here, only code
