### ISSUE TITLE
Enable time travel in dev and test namespaces

### ISSUE THREAD

**Issue by VB-at-Bis** [bcgov/CONN-CCBC-portal#661]
### Description

The time travel feature was added, but is only enabled if the appropriate env variable is set (`ENABLE_MOCK_TIME`).

The `config.js` file has some mechanism to enable it, but it incorrectly relies on the `NODE_ENV` env variable. `NODE_ENV` is always `production` when running the docker container.

The three `json` config files are at in the `app` folder and would be more visible if moved to a `config` folder

### AC

- [x] create an `app/config` folder, containing
  - `index.js`, moved+renamed from `app/config.js`
  - `local.json`, moved+renamed from `app/development.json`
  - `dev.json`, `test.json` and `prod.json`, containing env variables for the three openshift environments, respectively
- [x] update the `app/config/index.js` behaviour to:
  - load `local.json` if `!NODE_ENV || NODE_ENV === 'development'`
  - load the appropriate json file otherwise, based on `OPENSHIFT_APP_NAMESPACE` (defaulting to prod)

```
const tokens = config.get("OPENSHIFT_APP_NAMESPACE").split('-');
const env = tokens[tokens.length - 1];
```

- [x] The `dev.json`, `test.json` and `prod.json` should only contain the necessary env variables. Anything defined in the helm chart (https://github.com/bcgov/CONN-CCBC-portal/blob/49ea4c04486abc4bb6905bb98d0d009cc95f18ad/helm/app/templates/deployment.yaml#L148-L188) will be overridden anyway, so it shouldn't be in those json files. `prod.json` might be an empty json object as a result, and that's okay.
- [x] The `dev.json`, `test.json` and `prod.json` should not attempt to set `NODE_ENV`

**Comment by VB-at-Bis** [comment]
@matthieu-foucault  I saw it in Makefile: https://github.com/bcgov/CONN-CCBC-portal/blob/main/Makefile#L118 and assumed that's enough...
- you mean add `sqitch --chdir mocks_schema deploy` in  helm\app\templates\deployment.yaml after line 142?

**Comment by VB-at-Bis** [comment]
PR submitted: https://github.com/bcgov/CONN-CCBC-portal/pull/678 @matthieu-foucault

**Comment by matthieu-foucault** [comment]
The problem is that our deployment script isn't using the Makefile, that should probably be refactored at some point
