### ISSUE TITLE
View & Change Status

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/CONN-CCBC-portal#669]
## User Story
As an analyst
I want to view & change the status of an application
so that I can track its progress through the process.
## Acceptance Criteria
- [x] **Scenario: visible status on application pages**
Analyst can change the status of the application on the following pages: Application, assessments, history.  
<img width="689" alt="Screen Shot 2022-11-02 at 9 55 50 AM" src="https://user-images.githubusercontent.com/93939894/199508325-cd7e532d-83f6-490e-abef-f35dd14882b7.png">

#
- [x] **Scenario: change status**
A dropdown of status appears when use clicks on the arrow beside pill status
![image.png](https://images.zenhubusercontent.com/61e8875b1de5eff8f072cd04/a029c042-2f1a-4406-a5f3-1dcb9cf2d122)
<a href="https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=5201%3A22386"><img width="35%" src="https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/0d553c8e-dc48-4f38-8696-c6d46b5357b0"></a>
Dropdown options:
> Received
> Screening
> Assessment
> Recommendation
> Conditionally approved
> Approved
> Complete
> On hold
> Cancelled
> Closed
#
- [x] **Scenario: Modal**
A modal appears when the analyst selects a status
Modal asks for reason for change (1000 characters max)
User can save changes or cancel changes
If user clicks cancel changes then the state does not change - undo the change
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/da96ff05-c454-4348-950b-a54ca415c37f)

#
- [x] **Scenario: Can't choose Draft Submitted or Withdrawn status**
Analysts should not be able to change the status to Draft or Submitted or Withdrawn

#
- [x] **Scenario: visible only to analysts**
For the near future, the only states visible to the applicant for now should be 'Draft', 'Submitted', 'Received', 'Withdrawn'
If the analyst changes the state from Received to any other state, for now the applicant should continue to see their state as 'Received'
**Note**: This will change when it comes to conditionally approved and subsequent statuses but more testing with business area needed to determine how & when the applicant will see the status.

### Technical details

- Add a nullable `change_reason` column to the `application_status` table
- RLS policies restricts which `application_status` records are visible to the `ccbc_auth_user`
- Add a `visible_by_applicant` column to `application_status_type`
- 
- What is the front-end complexity?
- Do it require creating or updating a component?
- Any work on the back-end?
- Integration?
- Any changes in database structure?
- What types of tests that we need to create and run?
- Impacts on DevOps?
- Other risks and potential side effects?
- Which documentation needs to be updated?

**Comment by zoeyli-46** [comment]
@elliottSlee should an application status Assessment be triggered when an analyst has been assigned to any of the assessments OR when the eligibility assessment has been uploaded (signifying that the eligibility assessment is complete)?

**Comment by elliottSlee** [comment]
Eligibility template uploaded may be first review. Status should switch to assessment when outcome of eligibility is "eligible", "ineligible", or maybe "incomplete". Incomplete could also mean RFI necessary so we need to create a clear, intuitive flow for that.

**Comment by elliottSlee** [comment]
@zoeyli-46 I wonder if this card can be scrapped and instead we have cards for each of the user stories involved:
- [ ] manually change status with dropdown of status pill in top right of every page when within an application
- [ ] changed to eligibility when an action occurs
- [ ] change to assessment when an action
- [ ] change to ... when ...

**Comment by zoeyli-46** [comment]
@elliottSlee have each of the statuses as separate cards you mean? I agree we can create separate ones for each user story but what about the following? Those ones are manually set and not automatically changed when any action occurs 
Conditionally approved
 In-flight
 Complete
 On hold?

**Comment by elliottSlee** [comment]
Can the dropdown menu be in the following order?
- Received
- Screening
- Assessment
- Recommendation
- Conditionally approved
- Approved
- Complete
- On hold
- Cancelled
- Closed

**Comment by elliottSlee** [comment]
When clicking the X in the modal, the status still changes in the interface, but not permanently. You can go to the dashboard or refresh and it goes back to the original. This doesn't happen when clicking _Cancel changes_. It should behave the same as _Cancel changes_.

**Comment by elliottSlee** [comment]
Does another card need to be created that indicates the same colour scheme for the pills would display on the dashboard? It wasn't part of the AC for this card.

**Comment by marcellmueller** [comment]
> Does another card need to be created that indicates the same colour scheme for the pills would display on the dashboard? It wasn't part of the AC for this card.

Yes

**Comment by marcellmueller** [comment]
> When clicking the X in the modal, the status still changes in the interface, but not permanently. You can go to the dashboard or refresh and it goes back to the original. This doesn't happen when clicking _Cancel changes_. It should behave the same as _Cancel changes_.

Nice catch. This X is actually getting removed in the edit application ticket since it wasn't in the design and I made a reusable modal.

**Comment by elliottSlee** [comment]
Since adding the status change, the _Project title_ line breaks at a narrower width.
![Screen Shot 2022-12-21 at 2.43.10 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/bb0d41f2-5c63-4b77-ac34-55a9d7776f5d)

**Comment by MarsRomer2** [comment]
When I change the status a second time, the previous change comment shows in the modal comment box.  I think ideally the modal opens with the comment box blank
