### ISSUE TITLE
Allow decimals for number of households

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#679]
### User story
As an applicant I want to be able to enter decimals in the household counts
so that I can enter the information exactly as I receive it from the eligibility mapping tool.

### Acceptance criteria
- [ ] Allow two decimal places for Final number of Eligible Households targeted by this proposal.
- [ ] Allow two decimal places for Number of households on Indigenous lands impacted by this proposal.
- [ ] max for each is 100,000.00

**Comment by elliottSlee** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/679?planning-poker) with Zenhub @AntBush @marcellmueller @matthieu-foucault @VB-at-Bis @wenzowski

**Comment by matthieu-foucault** [comment]
@elliottSlee how is the max value enforced, other than showing a red cell on the validation page if it's above the max?

**Comment by elliottSlee** [comment]
We had designed our error states to be the input box turns red with description of error, which occurs live as a user types (like used for email). For this issue, the description could be, "Value must be less than 100,000.00"
![Screen Shot 2022-09-27 at 6.39.15 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/c0acca3a-0467-4542-81dc-77a9acfd2ef3)
HOWEVER, since that's updating the AC of a card that's in a sprint and this is a low priority feature (I don't think any of our other fields have max values and other validations were deprioritized earlier such as validating incongruent start & end dates), I'd like to ask the PO. In absence of our regular PO this week, we could get a team temperature check or ask the acting PO.
