### ISSUE TITLE
Landing page UI improvement/wording updates

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/CONN-CCBC-portal#691]
Wording updates 
- [ ] Change text under "Before you begin"
> "Refer to program details for application materials and full information about the Connecting Communities BC (CCBC) program"
> "Applications are accepted until [intake close date]." in bold text
- [ ] Change "Get started" to "Begin application"

UI updates 
- [ ] Put text under "Before you begin" into a Callout 
![image.png](https://images.zenhubusercontent.com/61e8875b1de5eff8f072cd04/d8b440c3-ccd5-4ce5-b541-2cf108c98413)
- [ ] Add a divider #C0C0C0 between Begin application and Application form overview

![image.png](https://images.zenhubusercontent.com/61e8875b1de5eff8f072cd04/eec0c899-697c-45dd-8b05-7c21b81c763f)

**Comment by elliottSlee** [comment]
@zoeyli-46 which of these changes have been implemented with the new updates in test?

**Comment by zoeyli-46** [comment]
this ticket is out of date, everything has been implemented according to the latest figma, i am closing this ticket
