### ISSUE TITLE
Banner on submission page when no intake open

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#700]
### User Story
As an applicant
I should not be able to submit a **draft** application when in between intakes 
so that I can't submit something that won't be accepted.

### Acceptance Criteria
- [ ] Banner on submission page shows a message that no intake is open

### Design
https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=6344%3A28862
https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=6344%3A29198

**Comment by elliottSlee** [comment]
Blocked pending discussion with NWBC about whether drafts can be editable between intakes

**Comment by VB-at-Bis** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/700?planning-poker) with Zenhub @AntBush @matthieu-foucault

**Comment by MarsRomer** [comment]
@elliottSlee would you agree we can close this ticket as the decision to not allow draft applications to be edited when no intake is open has been handled by https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/121

**Comment by elliottSlee** [comment]
@MarsRomer Let's close it. The banner is not necessary if the fields are already disabled and the landing page says the intake is closed.
