### ISSUE TITLE
Dashboard enabled when in between intakes

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#701]
As an applicant
I want to be able to access my applications on the dashboard when in between intakes

Acceptance criteria
The dashboard allows all the same functionality after an intake ends as when the intake was open.  
- [x] applicants can see all their applications in the dashboard list
- [x] Previously submitted applications have a received status
- [ ] Submitted applications are viewable and withdrawable
- [ ] Draft applications can be edited and viewed

**Comment by zoeyli-46** [comment]
Merge with ticket #382?

**Comment by AntBush** [comment]
- [ ] Submitted applications are viewable and withdrawable 
- [ ] Draft applications can be edited and viewed
is encapsulated in the design found in #382: 
**If intake is closed and an intake is upcoming and application count is 1+**
 https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=6362%3A28411

So I'd say this can be merged in. 

> - [x] Previously submitted applications have a received status

Should this be marked as complete/checked?

**Comment by elliottSlee** [comment]
Submitted applications are viewable (already a card #236) and withdrawable (already implemented with #39)

**Comment by zoeyli-46** [comment]
Seeing as all checkboxes in the AC are either already implemented or in another card, I will close this ticket!
