### ISSUE TITLE
New Applications can be started when in between intakes

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#702]
As an applicant
I want to be able to create new applications in between intakes
so that I can get a jump start on the next intake

Acceptance Criteria:
- [ ] The 'Create Application' button is enabled when in between intakes

**Comment by matthieu-foucault** [comment]
With this user story, there appears to be a risk that users are starting an application with an oudated form. Was this considered? I see this is at the top of the "next sprint candidates" too. Is this that high priority?

**Comment by elliottSlee** [comment]
Blocked by discussion with NWBC about whether they want to allow applicants to create applications between intakes.

**Comment by elliottSlee** [comment]
Feedback from NWBC
"There is a risk that Intake 2 might be different, or have a different focus...Current risk mitigation would be not to let them create new applications in case criteria change."

**Comment by VB-at-Bis** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/702?planning-poker) with Zenhub @AntBush @matthieu-foucault

**Comment by elliottSlee** [comment]
Closing because current functionality is what we want: applicants can't create applications between intakes.
