### ISSUE TITLE
Allow applicant to delete drafts on dashboard

### ISSUE THREAD

**Issue by MarsRomer-zz** [bcgov/CONN-CCBC-portal#703]
As an applicant
I want to delete draft applications 
so that it is not cluttering up my dashboard

# Acceptance Criteria 
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/d6f5416c-586e-41bd-8b1c-d37d05b83863)
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/db3d1668-4936-44d9-a36c-21080f36fea1)
- [x] Applicant can only delete DRAFT applications
- [x] Applicant gets an informational prompt to confirm deleting
- [x] Confirming delete removes it from the dashboard (applicant can't see it on their dashboard anymore)
- [x] Deleting from dashboard soft deletes from database (archive form data)

##Not included:
- Hard deleting the attachments from the S3

**Comment by matthieu-foucault** [comment]
> After 30 days the application is hard deleted from database and S3

Is this an organizational requirement, or purely for storage usage considerations? If it's the latter, I'd consider splitting this feature off in a separate issue

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/703?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc @VB-at-Bis

**Comment by MarsRomer** [comment]
Needs Refinement : Screen designs
