### ISSUE TITLE
bug: can create multiple draft applications by accident 

### ISSUE THREAD

**Issue by AntBush** [bcgov/CONN-CCBC-portal#720]
When clicking the "Create Application" button, the button isn't disabled while it's waiting for the response from the server. If a user clicks it multiple times then multiple draft applications are created. Should add a flag to disable the button (and maybe change the cursor to a spinner?) while awaiting for the request to finish. 

@elliottSlee @zoeyli-46 Thoughts on what behaviour should be in place?

**Comment by elliottSlee** [comment]
This is a great flag. Disable the button is a minimum. I'd love to also have it switch to a waiting cursor would be a nice to have feature. Generally, loading spinners are good if the wait is less than 10s ([source](https://boldist.co/usability/loading-spinner-ux-killer/)) so we're good there unless something goes wrong in which case the loader would have the opposite effect--the user would think it's still working. Could the server fail to return the action? If so, would the button just stay disabled?

**Comment by AntBush** [comment]
The server could fail to respond, but we'd still have an error in that case we can display that error (in some meaningful way) and enable the button. On the 10s time, it should be <10s on most normal networks but I'm sure on spotty/slow networks it can take longer. 

If the server takes too long/the connection is slow, the request will timeout after 30s (on firefox at least)
