### ISSUE TITLE
Allow changes to banners on dashboard and landing page

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#722]
#### Given that an intake is open 
 - [x] and the `open_intake_alert` feature flag has a value of `{"variant": "success", text: "Intake is now open" }`
      When I am on the landing page and dashboard
      Then an alert with the matching variant and text is displayed
 - [x] and the `open_intake_alert` feature flag is disabled
      When I am on the landing page and dashboard
      Then no alert is displayed

#### Given that an intake is closed 
 - [x] and the `closed_intake_alert` feature flag has a value of `{"variant": "warning", text: "Intake is closed", "displayOpenDate": true }`
      When I am on the landing page and dashboard
      Then an alert with the matching variant, text, and open date is displayed

 - [x] and the `closed_intake_alert` feature flag has a value of `{"variant": "warning", text: "Intake is closed","displayOpenDate": false }`
      When I am on the landing page and dashboard
      Then an alert with the matching variant and text is displayed

 - [x] and the `closed_intake_alert` feature flag is disabled
      When I am on the landing page and dashboard
      Then no alert is displayed

#

- [x] Usage of the feature flags is documented (in the docs folder), including growthbook screenshots

![Screen Shot 2022-09-26 at 4.58.50 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/cc98e1c9-ff25-462c-b8a4-a924192cbeec)

**Comment by elliottSlee** [comment]
Dupe of #689

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/722?planning-poker) with Zenhub @marcellmueller @matthieu-foucault @AntBush @VB-at-Bis

**Comment by matthieu-foucault** [comment]
@VB-at-Bis, is this still in progress? We need a PR for the documentation
