### ISSUE TITLE
Sunset RTP namespaces

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/CONN-CCBC-portal#734]
- [x] verify database backup is safely stored
- [x] test database backup restore
- [x] run `helm delete` in each namespace
- [ ] request sunsetting OpenShift namespaces

**Comment by marcellmueller** [comment]
@MarsRomer this ticket should be good to go now that we have moved metabase deployment to it's own repo. 

How do you feel about bringing it into next sprint? I don't believe it would be a big ticket and platform services would be grateful that we aren't consuming resources that aren't being used anymore.

**Comment by MarsRomer** [comment]
lets retire the SSO silver cluster first as that is a request I have received a couple of times now

**Comment by marcellmueller** [comment]
@MarsRomer-zz this is good to go except for requesting sunsetting the OpenShift namespaces. Can you do that if you have the ability to? It is in the `bc5936` namespaces, let me know if you need any other information.
