### ISSUE TITLE
Refactor: RSJF widgets should not render help or errors

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/CONN-CCBC-portal#736]
The help and errors should be rendered by the field template, not the widgets

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/736?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc

**Comment by MarsRomer** [comment]
Replaced by #1980
