### ISSUE TITLE
enable squash-merging development workflow + release automation

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/CONN-CCBC-portal#739]
## Description

Using squash merges is beneficial because...

If we enable squash merges without updating our release pipeline, there is a risk that our release requests get merged with a squash, which would not trigger the release.

We can add more automation to our release process to eliminate that risk

To consider: https://github.com/tibdex/autosquash

**Comment by AntBush** [comment]
https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-multi-paragraph-body-and-multiple-footers 

To consider when squash-merging
