### ISSUE TITLE
Bug: submitted date and time are incorrect

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#745]
When I clicked the submit button on a draft application I got this confirmation.  The submission date and time are incorrect.

![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/2f5f9d76-eb71-415f-a1fb-db2089388122)

**Comment by matthieu-foucault** [comment]
Are they? Your time travel component screenshot says your current date is 2022-10-19

**Comment by MarsRomer** [comment]
oh haha, didn't realize thats the date and time it was picking up on!
