### ISSUE TITLE
Export applications - Data -> CSV

### ISSUE THREAD

**Issue by MarsRomer-zz** [bcgov/CONN-CCBC-portal#747]
As an analyst
I want to export applications data, 
So that ISED can import into their system 

## Acceptance Criteria
- [ ] Given I'm on the Dashboard page
And there are one or more applications
When I click on `Export Applications (CSV)`
Then the system will generate a CSV file with the list of applications to be downloaded.

## Other Details
- The template is an Excel file. ISED wants to receive a CSV file.
- XLSX file template: https://bcgov.sharepoint.com/:x:/r/teams/04708/Shared%20Documents/Research/UBF%20csv/BC_UBF_Intake_Template.xlsx?d=wfac202f8bc964d0b8ecd148295597d49&csf=1&web=1&e=mF8doD

## Technical Details
- . 
- . 

## Wireframe
![image.png](https://images.zenhubusercontent.com/606c9d37b7ff542cfdb25c53/33895cee-85cd-41bf-a360-b405bd9ee17a)

**Comment by elliottSlee** [comment]
@AntBush are you including these columns in the table of applications/analyst dashboard #639?

**Comment by AntBush** [comment]
No I am not, but question concerning this: I'm guessing we want to keep a history of those assigned yes (I'm assuming multiple will be)? So the data of an analyst being assigned to an application should not be edited in-place. 

Question about the package, I'm guessing an application will only be assigned to a package once, and we don't care for tracking if it changes right?

**Comment by eazeredo** [comment]
This card is just to add the Lead and the Package information on the Dashboard. Let's not mix the content with the "Assign Package" (the card doesn't exist yet).

**Comment by eazeredo** [comment]
Also, @elliottSlee , can we Add only the `Lead` information for now as we don't have a story to assign the package yet?

**Comment by elliottSlee** [comment]
Should this story be merged with #758 - Assign Lead & #824 - Add Package?

**Comment by MarsRomer** [comment]
I am ok with it but I would like to leave it to the dev team to decide

**Comment by eazeredo** [comment]
Card repurposed.

**Comment by eazeredo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/747?planning-poker) with Zenhub @AntBush @marcellmueller @matthieu-foucault @VB-at-Bis

**Comment by MarsRomer** [comment]
Moving this ticket to the backlog - for MVP we will generate the csv from Metabase
