### ISSUE TITLE
Assign lead

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#758]
### User Story
As an Analyst 
I want to assign a lead to each application 
So that we have a person to drive the application through the assessment process.

### Acceptance Criteria
- [x] **Add the `Lead` column to the dashboard**
Given that an analyst is logged in
when they are on the dashboard
then they will see a column with the header, "Lead"
#
- [x] **Assign lead in dashboard**
Given an application does not have a `Lead` assigned
When an analyst opens the dashboard
Then they will see the "Assign analyst" dropdown in the `Lead` column
When they click on "Assign analyst"
Then a dropdown will appear with the List of Analysts (#759)
and when a name is selected
Then the value is saved 
#
- [x] **Lead name shows in dashboard**
Given an application has a `Lead` assigned
When an analyst opens the dashboard
Then they will see the name of the person assigned
and an arrow indicating that it is still a dropdown
#
- [x] **Text overflow uses ellipses** 
Given that the lead has been assigned
and its width in the dashboard column is > 114px,
then text overflow will use ellipses
(so that the lead column is < 140px including the dropdown arrow and spacing)
#
- [x] **Lead in Application header**
Given that the lead has not been assigned
when an analyst is on any application page (application, assessment, or history)
then they will see the "Select lead" on the right of the header
Given that the lead has been assigned
when an analyst is on any application page (application, assessment, or history)
then they will see the name of the lead (and the dropdown arrow) on the right of the header
#
- [x] **Date and user is tracked**
Given that an analyst assigns a lead
then the date it was selected is recorded
and the user is recorded
#
- [x] **Assigned analyst is static if list of analysts changes**
Given that the eligibility assessment has been assigned to someone
when their name is removed from the list of analysts
then their name will remain as a response to "assigned to"
#
## Technical Details
1. .
1. .

#### Dashboard
![Dashboard_Lead.jpg](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/434c4c2c-f708-4676-944d-00aa67fdeca4)

#### Header
![Header_unassigned.jpg](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/256453c7-838a-40d5-a5ef-5e318428fce9)
![Header_assigned.jpg](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/4684a884-08db-4c0f-95ca-5a349260b273)

**Comment by zoeyli-46** [comment]
"then the dropdown disappears" I think we should remove this from the AC, if they accidentally assigned 1 person but meant to assign someone else, or they want to change it, they should be able to edit it

**Comment by eazeredo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/758?planning-poker) with Zenhub @AntBush @marcellmueller @matthieu-foucault @VB-at-Bis

**Comment by MarsRomer** [comment]
There seems to be some glitchy behaviour.  
E.g. when I set the Lead = unassigned
![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/cf93f453-f42a-4d81-b6fd-f6357b560f6a)
![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/2e80453f-d821-4a8e-9a44-0ecf04839e9e)
the lead resets to Rachel 
![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/9d3e082e-9477-4377-ab5a-1531da1292b3)

**Comment by marcellmueller** [comment]
@MarsRomer this is updated and in test if you want to give it a try before sprint review!
