### ISSUE TITLE
Navigation Sidebar

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#760]
### User Story
As an analyst I want a navigation sidebar so that I can go between pages of an application, assessments, history, and more later.

### Acceptance Criteria
- [x] Dashboard icon is [fa-chevron-left](https://fontawesome.com/icons/chevron-left?s=solid&f=classic); fixed width (fa-fw); colour is #38598A
- [x] Application icon is [clipboard-list from font-awesome](https://fontawesome.com/icons/clipboard-list?s=solid&f=classic); fixed width (fa-fw);colour matched to text
- [x] Assessments icon is [check-double from font-awesome](https://fontawesome.com/icons/check-double?s=solid&f=classic); fixed width (fa-fw);colour matched to text
- [x] History icon is [clock-rotate-left from font-awesome](https://fontawesome.com/icons/clock-rotate-left?s=solid&f=classic); fixed width (fa-fw); colour matched to text
#
- [x] **Visible on application pages**
Given that an analyst is on a page about an application (application, assessment, history, more to come later in the roadmap)
then they will see a navigation sidebar on the left side.
#
- [ ] **Pages linked**
Given that an analyst sees the navigation sidebar
when they click on application
then they will be directed to the application page
when they click on assessments
then they will be directed to the eligibility assessment page
when they click on history
then they will be directed to the history page.
#
- [x] **Current page**
Given that an analyst is on a page with the sidebar
then the current page in the sidebar will be bolded
and have a background colour of F1F2F3
#
- [x] **Hover**
Given that an analyst is on a page with the sidebar
when they hover over a page
then the background of that link will change to F8F8F8
#
- [x] **Responsive -- just show the icons when <1007px**
Given that an analyst is on a page with the navigation sidebar
when the viewport is <1007px
then the words of the navigation sidebar will not visible
and only the icons will be visible
#
- [x] **Sticky**
Given that an analyst is on a page with the navigation sidebar
when they scroll
then the navigation sidebar will scroll to the top of the viewport and stick there.
> Sticky - risk is that menu gets taller than view port & can't view bottom. Consider the importance of this....
#
- [x] **Hide icon from screen readers**
Given that an analyst is using a screen reader
when they are on a page with the navigation sidebar
then the icon will not be read because the `aria-hidden="true"` attribute

![image.png](https://images.zenhubusercontent.com/606c9d37b7ff542cfdb25c53/7082d1d0-3a5b-41c5-8213-f497959d6155)

**[Wireframe](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=6978%3A59934)**

**[Prototype](https://www.figma.com/proto/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?page-id=6958%3A32778&node-id=6978%3A58877&viewport=359%2C-5999%2C0.59&scaling=min-zoom&starting-point-node-id=6978%3A58877)**

For each button:
- Padding above & below is 8px
- Padding on left is 8px
- Spacing between icon & text is 8px

Margin between each button is 4px

If font size is 16, width is 139px
If font size is 18, width is 152px

**Comment by AntBush** [comment]
- [ ] **Pages linked**
Given that an analyst sees the navigation sidebar
when they click on application
then they will be directed to the application page
when they click on assessments
then they will be directed to the eligibility assessment page
when they click on history
then they will be directed to the history page.  
#
In the meantime, since some of these pages aren't done, how do we want this to work?

**Comment by elliottSlee** [comment]
@AntBush Would it be better to have blank pages or add these links when we build the respective pages?

**Comment by AntBush** [comment]
Honestly, I'm not sure, I think the links being added in when we build the respective pages is a good idea since adding in new links would be a 1-pointer added in while we're making the pages. We could probably make the UI now and hide them behind a feature flag too.

If it just goes to a blank page it could be confusing for the users, especially if it's never clear as to when the page is now populated.

**Comment by zoeyli-46** [comment]
I removed the "except when they hove on the Dashboard link"  from the hover acceptance criteria, the dashboard link should still have a hover state to show that it's clickable, and should have the same hover effect as the other links

**Comment by marcellmueller** [comment]
@MarsRomer @zoeyli-46 @elliottSlee slight visual bug made it in when I fixed something else. The padding to the right of the icon should be a bit larger. I will fix that but let me know if there is anything else you notice thanks.

**Comment by elliottSlee** [comment]
Will the padding be there at smaller screen sizes so that it's even padding on either side when it's just icons?

**Comment by marcellmueller** [comment]
No it'll actually just be increased on the text element.

**Comment by elliottSlee** [comment]
Current page should be bolded, it currently isn't
