### ISSUE TITLE
Update Docker base images

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/CONN-CCBC-portal#762]
Our Trivvy scan is failing due to vulnerabilities in `gnutls` package in our Docker images. We discussed using a lighter image so this is a good opportunity to switch images.

![Screenshot at 2022-10-12 07-36-03](https://user-images.githubusercontent.com/14259474/195373336-47f3c034-3a5b-4b64-859d-71b48e8bd401.png)

- [ ] <s>Discuss which base image we should use</s> moved to other ticket
- [ ] <s>Update base image in database Docker file</s>
- [ ] <s>Update base image in app Docker file</s>
- [x] Use dependabot to listen for updates and open PR?

Risk of not doing this:  security risk

**Comment by AntBush** [comment]
We will not be going with renovate as our dependency updater for docker is because it does not recognise (at this time) digests in dockerfiles https://github.com/renovatebot/renovate/issues/1027
