### ISSUE TITLE
CI: Set-output and set-state is deprecated

### ISSUE THREAD

**Issue by AntBush** [bcgov/CONN-CCBC-portal#777]
The set-output and set-state action are going to be disabled sometime in the near future, so we will need to update our actions to use the new environment files option. May also mean we will have to update some actions we're calling as well.

The last day to use the set-output will be May 31st, 2023

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files
#
AC
- [x] set-output is no longer used in any of our actions
- [x] update any actions that are using set-state or set-output

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/777?planning-poker) with Zenhub @AntBush @marcellmueller @VB-at-Bis

**Comment by MarsRomer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/777?planning-poker) with Zenhub @rafasdc
