### ISSUE TITLE
Application Form - Contact info

### ISSUE THREAD

**Issue by eazeredo** [bcgov/CONN-CCBC-portal#78]
### User Story
As an applicant
I want to submit my organization's, authorized contact's, and alternate contact's information
so that the analysts know who to contact about an application.

### Description
**Wireframes**
Organization Contact Information
https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=1059%3A6566

Authorized Contact
https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=1059%3A6615

Alternate Contact
https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=1059%3A6680

**Source of Truth for Questions**
Full information for input fields such as max length for text fields and the contents of drop-downs can be found in the Research channel Files/[DataMapping.xlsx](https://bcgov.sharepoint.com/:x:/r/teams/04708/Shared%20Documents/Research/DataMapping.xlsx?d=w5224cb99a79b48008b9105279418b6e3&csf=1&web=1&e=k1VR5C)

### Comments by Bryan 06/13/22:

The 3 pages are complete except for the following:

Missing elements from Authorized contact and Alternate contact page:
- [ ] Yes/No RadioWidget for the "Is this person an authorized signing officer of the applicant?" question
- [ ] CheckboxWidget for the "Contact this person for communication regarding this application" question

### Not Included
Validations are captured in ticket #217 - Input Field Validations

![Screen Shot 2022-06-16 at 12.52.16 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/1bec7a8c-1bc9-464f-a466-92861d9741da)
![Screen Shot 2022-06-16 at 12.54.37 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/051fd1b2-3fcc-4433-a889-09ccfbe16753)
![Screen Shot 2022-06-16 at 12.56.37 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/c2980100-5e4b-42af-adae-0cc00566f846)

**Comment by elliottSlee** [comment]
@marcellmueller & @BryanGK do you want acceptance criteria for the continue button or is it a given that will work on each page?

**Comment by BryanGK** [comment]
@elliottSlee the continue button does not need any kind of AC. The button is attached to the form and not individual pages of the form.

**Comment by elliottSlee** [comment]
@marcellmueller & @BryanGK could you add a development checklist to this card?

**Comment by elliottSlee** [comment]
@marcellmueller & @BryanGK could you add a development checklist to this card?

**Comment by MarsRomer** [comment]
@marcellmueller @BryanGK can you please identify which of the validation requirements on this ticket are going to take some effort?

**Comment by elliottSlee** [comment]
@BryanGK mentioned
Validations that will take the most time:
- [ ] Telephone mask
- [ ] Email format

**Comment by MarsRomer** [comment]
@marcellmueller  Looks good, just a couple of things that need changing:
Organizational contact info:  The telephone number should not say optional.
Authorized contact - please remove the word optional as per the screen captures in this ticket
The last question should be a yes/no
