### ISSUE TITLE
History: View changes to application and assessment

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/CONN-CCBC-portal#801]
### User Story
As an analyst, 
I want to track changes to an application and its' assessment,
So that I can know when things were changed and by whom 

### Acceptance Criteria

- [ ] **Page linked in sidebar**
Given that an analyst is on any page of an application
and can see the sidebar
when they click on “History” in the sidebar
then they will be directed to the History page for that application
#
- [ ] **Date format:** [MMM DD, YYYY] [hh:mm]
#
- [ ] **Order:** Most recent on top
#
#### Status
- [ ] Icon: https://fontawesome.com/icons/circle-small?s=solid&f=classic stacked on https://fontawesome.com/icons/circle?s=regular&f=classic
- [ ] Statement: {User} changed the **status** to {status pill} on {date} at {time}
- [ ] Reason for change: If none, “None provided”

#### Edited application
- [ ] Icon is same as in sidebar: https://fontawesome.com/icons/clipboard-list?s=solid&f=classic
- [ ] Statement: {User} **edited the application** on {date} at {time}
- [ ] Reason for change: If none, “None provided”

#### RFI
- [ ] Icon is same as in sidebar: https://fontawesome.com/icons/envelope?s=solid&f=classic
- [ ] Statement: {User} saved **{RFI #}** on {date} at {time}
- [ ] When an applicant uploads files: icon: https://fontawesome.com/icons/paperclip?s=solid&f=classic 
- [ ] When an applicant uploads files: Statement: The applicant uploaded file(s) in response to **{RFI #}**

#### All Assessments
- [ ] Icon is same as in sidebar: https://fontawesome.com/icons/check-double?s=solid&f=classic
- [ ] Statement: {User} saved **{type of assessment}** on {date} at {time}

#### Lead 
- [ ] Icon: https://fontawesome.com/icons/user?s=solid&f=classic
- [ ] Statement: {User} assigned the **Lead** on {date} at {time}
#
- [ ] Icons are colour: 1A5A96; size: 1em. Icons are in a container that's 1.5em (24px) square

## Ultra refinement

**DB:**
- [ ] .
**Frontend:**
- [ ] . 
**Integration/API:**
- [ ] .
- Should use something like: 
```
 allApplications {
    nodes {
      ccbcUserByCreatedBy {
        givenName
        familyName
      }
    }
  }
```
 to get the user who created the record
**Tests:**
- [ ] .
**Documentation:**
- [ ] .

## Wireframe
[**Wireframe**](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=9478%3A50769&t=c6mdtFi3Ybh4ja9V-4)
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/2387c099-c1db-4389-ac76-73b87f3b29e9)

**Comment by AntBush** [comment]
A good candidate for finding diffs between the two JSON objects: https://www.npmjs.com/package/deep-object-diff

**Comment by AntBush** [comment]
The reason that I've made this a 13: since this is a consolidated timeline (not just of the application data/separated out) then needing to grab all the data and then organize each piece of data (probably on the client side? Probably happening on the server since we're using Next) before then diffing on each relevant type of data (application form data, rfi data, lead, and status) is probably going to be a complex piece of work. May be more accurate as an 8 but this is my estimate.

**Comment by MarsRomer** [comment]
Looks great and seems to be working great! 
Can I request a couple of  modifications please? I don't mind putting these in another ticket for next sprint if you like.
1. Can we have the history to be ordered with most recent on top
2. Can we have the history start at 'Received'.  i.e. the oldest entry show in the history is when the application was 'Received'.   I don't think we explicitly said that in the ticket.

**Comment by marcellmueller** [comment]
@MarsRomer yep no problem, I have submitted an update which should be merged in shortly.
