### ISSUE TITLE
Enable data team to access GIS data

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#803]
### User Story
As a GIS data team member
I want to have access to the current application form data & files
so that I can do my analyses.

### Description
GIS team will need the KMZ files as soon as the intake ends to populate their webmap of applications that NWBC leans on for assessment. They need key info from the applications such as project name, org name, household count, and more.

They would like to be able to read from our database using python and/or ArcGIS. Alec may remember their tech better.

Maybe we could parse KMZ & have them in our database then data team just needs api to access our database. Give them a rest API & a key then they can grab the data.
APIs are recommended by [BC Gov Devhub](https://developer.gov.bc.ca/Data-and-APIs/BC-Government-API-Guidelines)
Data team would like to parse KMZ and could pull it from Sharepoint.

MVP option:  We offer them access to the tabular data in metabase, and they access the KMZ files in a sharepoint folder, possibly re-using the code for sharing uploads with ISED.

**Comment by eazeredo** [comment]
@elliottSlee @MarsRomer 
The Data Team will be able to retrieve these pieces of information when we complete #747 (CSV) and #757 (Download individual attachments from the application page).

**Comment by elliottSlee** [comment]
We should validate with the data team & @MarsRomer whether that process will suffice for the data team and our MVP analyst release. They wanted something more automated/not manual because the main pain point in the past has been lack of communication when files are updated.

**Comment by elliottSlee** [comment]
De-prioritized for first release of analyst portal. #737 & #747 will work for MVP

**Comment by MarsRomer** [comment]
as MVP I think we will only have time for the manual process but will continue to iterate and automate where there is value in the effort
