### ISSUE TITLE
Enter Screening Assessment

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#804]
## User Story
As an analyst 
I want to complete the eligibility/screening assessment 
so that I can manage it and record the outcomes.

## Acceptance Criteria
- [x] **Linked in navigation sidebar**
Given that an analyst is on any page of an application
When they click on "Assessments" 
Then they will be brought to the eligibility assessment page
#
- [x] **Show analyst list in the dropdown**
Given that an analyst is on the eligibility assessment page
When they click on the dropdown beside `Assign to`
Then I see the #759 - List of Analysts  in the dropdown
#
- [x] **Show Datepicker**
Given that an analyst is on the screening assessment page
When they click on the input field beside `Target date`
Then a date picker will appear
When they select a date
Then it will appear in the input box
# 
- [x] **Remove date**
Given that an analyst has entered a due by date
When they click on the field
Then they can delete/remove the date entered
#
- [x] **Action: Save**
Given the fields are empty
And I added valid information in the fields
When I click on Save
Then the values are created in the database
And the Save button turns into a spinner and then turns to "Saved"
> reuse the spinner used in the File Upload Save button component
#
- [x] **Change Saved button to Save**
Given the button displays "Saved"
when they edit any information
then the Save button changes back to "Save"
#
- [x] **Assigned analyst is static if list of analysts changes**
Given that the eligibility assessment has been assigned to someone
when their name is removed from the list of analysts
then their name will remain as a response to "assigned to"
#
- [x] **Upload file**
Given that an analyst is on the screening assessment page
when they upload a file
then the button will change to say, "Add file"
and the analyst can upload multiple files
#
- [x] **Delete file**
Given that an analyst is on the screening assessment page
and a file has been uploaded
then a red x will appear beside the filename
and when they press the x
then the filename will be removed from the screen
<s>and when 30 days has passed
then the file will be hard deleted from the S3 bucket.</s>
#
- [ ] **Download file** (Depends on #757)
Given that an analyst is on the screening assessment page
and a file has been uploaded
when they click on the filename
then the file will be begin downloading on their computer
#
~~- [ ] **Scenario: Warning when decision not set**
Given that a user has added file
but decision was not set
when they press save
then a warning will appear  beside the decision field, ”Please select an assessment decision”
[aria-describedby attribute applied to all `<input>` elements](https://russmaxdesign.github.io/accessible-error-fieldset/)~~
#
~~- [ ] **Scenario: Warning when file not uploaded**
Given that a user has set the decision as Eligible, Ineligible, or Incomplete
and did _not_ upload a file
when they press save
then a warning will appear within the file upload "Please upload the completed template"~~
#
- [ ] <s>**Status changes when outcome is eligible**
Given that decision is _Eligible_
and a file uploaded
when an analyst presses save
then the status will change to _Assessment_</s>
#
- [ ] <s>**Applicant does not see the status change** #669
Given that the status is changed from _Received_ to anything else
when an **applicant** logs in
then they will still see the status as _Received_</s>
#
- [x] **Action logged**
Given that an analyst is on the screening assessment page
when they press save
then the values will be created (not updated)
and their username will be tracked (createdby)
and _eventually_ this will be visible in the History
#
- [ ] **Log Actions**
- .
- .
- .

## Not included
- **Note:** no validations are included in the MVP version
#

- [ ] <s> **Status changes after assigned**
Given the application status = "received" 
And that `assigned to` and `target date` are filled
When the user presses Save
Then the status will change to "Screening"</s>
#
- [ ] <s>**Action: Add the Date Assigned**
Given the `Assigned to` field is filled
And I changed the value
When I click on  Save
Then the `Date Assigned` value is updated to `Current Date`</s>
#
- <s>**Validate if Target Date is bigger than Current Date**
Given `Current Date` is the 2022-10-30
And the informed `Target Date` is 2022-10-28
When I click on  Save
Then an error message shows
And the Save action is cancelled</s>
#

## Wireframe
**[Wireframe](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=7437%3A35548)**
![Screening Wireframe HiFi.jpg](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/aed5c105-c160-4879-8b8b-e5b2cf47fd12)

**Comment by eazeredo** [comment]
@elliottSlee and @MarsRomer , why not add the "Decision" field with its options to the story?

**Comment by elliottSlee** [comment]
@eazeredo thats a great question. Let's ask devs what they prefer

**Comment by elliottSlee** [comment]
@VB-at-Bis, @matthieu-foucault, @marcellmueller, @AntBush 
Is hard deleting necessary to mention in this issue if it's part of #492 - Hard Deletes from S3 buckets?

**Comment by zoeyli-46** [comment]
@elliottSlee For the action: Save AC I added this: And the Save button turns to "Saved"

Thinking about it more, if the save button redirects them to the dashboard it feels like a bug, because the button says "save" and not "submit" the expectation isn't that they will be brought to a new page.

**Comment by AntBush** [comment]
5 points left

**Comment by MarsRomer2** [comment]
@marcellmueller can you please remind me which ticket will fix the upload issue?

**Comment by AntBush** [comment]
Did an attachment fail?  Uploads should be working in this ticket

**Comment by marcellmueller** [comment]
I just tried the uploads for the screening assessment and RFI and they were working in test now. Can you let us know if you run into any issues? Thanks!

**Comment by MarsRomer2** [comment]
@AntBush can we please change the uploads to allow multiple files please?  for both types
 CC:
@elliottSlee @zoeyli-46

**Comment by AntBush** [comment]
Sure, I can make that change now

**Comment by elliottSlee** [comment]
@AntBush The horizontal line between Target date and Next step is missing

**Comment by elliottSlee** [comment]
@AntBush & @MarsRomer2 we agreed to change "Next Step" to progress for the other assessments. That change should be reflected here.
