### ISSUE TITLE
Remove 'Login' button in header

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/CONN-CCBC-portal#805]
## Description

The `login` button in the header takes the user to the keycloak page, asking to select an identity provider. This may be confusing for users, now that there is an IDIR option.

Includes e2e testing

## Technical Analysis
- What is the front-end complexity?
- Do it require creating or updating a component?
- Any work on the back-end?
- Integration?
- Any changes in database structure?
- What types of tests that we need to create and run?
- Impacts on DevOps?
- Other risks and potential side effects?
- Which documentation needs to be updated?

**Comment by eazeredo** [comment]
Merged to #806
