### ISSUE TITLE
Remove email uniqueness constraint

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#819]
## Description

If a user logs in with two different identity providers, the user creation will fail on the second login, leading to missing created_by/updated_by foreign keys.

Impact:
 - missing data: created_by/updated_by FKs are not set
 - after log in, the user gets redirected to `applicantportal` instead of `applicantportal/dashboard`

## Acceptance criteria

- [x] Users can log in with two different IdPs, with the same email address configured, and no error will be thrown on the backend

**Comment by MarsRomer** [comment]
Database is not recording the ID for the business bceid

**Comment by MarsRomer** [comment]
Is the best way for me to test this by creating two applications in prod?  each using a unique basic bceid that is tied to the same email?

**Comment by matthieu-foucault** [comment]
> creating two applications in prod

You mean in "test", right?

Just logging in should be enough to see the fix. You should be able to see multiple users with the same email in the `ccbc_user` table

**Comment by MarsRomer** [comment]
yes

**Comment by MarsRomer** [comment]
metabase wont load the Form Data table in Test just now

**Comment by MarsRomer** [comment]
looks like something is broken as Test Metabase is still not loading any data

**Comment by MarsRomer** [comment]
I don't see my applications that all belong to the same email in my dashboard as expected
![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/45f513fd-5cc6-467f-9fef-393640bf95fc)
![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/f6744147-5655-48bc-a205-7477e4518c9a)

**Comment by matthieu-foucault** [comment]
> as expected

Was seeing application for both accounts expected? 

BCeID identifies user with a User Id, not email.

Our applications do not belong to an email, but to a BCeID account, if you're expecting a different behaviour, then that's a different issue.

**Comment by MarsRomer** [comment]
I must have misunderstood how to test this then.  I am to check in metabase then to see if the bug is fixed? I thought I was told to check the dashboard

**Comment by matthieu-foucault** [comment]
As mentioned above

> Just logging in should be enough to see the fix. You should be able to see multiple users with the same email in the ccbc_user table

Looking at the test data, I can indeed see multiple users with your email
