### ISSUE TITLE
View & change status

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#823]
### User Story
As an analyst
I want to view & change the status of an application
so that I can track its progress through the process.
### Acceptance Criteria
- [ ] **Scenario: visible status on application pages**
Given that an analyst is on any page of an application (application, assessments, history)
when they look at the top right
then they will see a pill with the current status of the application
#
- [ ] **Scenario: change status**
Given that an analyst is on a page where they see the status
when they click on the status
then a dropdown will appear with all statuses
when the analyst selects a status
then a modal appears asking for reason for change
when they enter a reason and press save 
then the changes will be saved
and the new status will appear on the dashboard.
#
- [ ] **Scenario: visible only to analysts**
Given that an analyst is on an application page
when they change the status
then it will remain as “received” to the applicant

T-shirt size estimate: Medium-y

**Comment by zoeyli-46** [comment]
What's the difference between this and  #669? Are we planning to have this as the main "status" card and then have different cards for each status? 

Conditionally approved as one ticket, in-flight as another ticket, etc.

**Comment by zoeyli-46** [comment]
Will all statuses need a reason for change? It feels unnecessary as some of them are self explanatory for why one went from conditionally approved to in-flight, how about the reason for change is just required for 
- cancelled 
- closed
- withdrawn 
- on hold

**Comment by elliottSlee** [comment]
Merged with #699
