### ISSUE TITLE
Assign Application to Package

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#824]
### User Story
As an analyst
I want to add a package to an application
so that I can prioritize applications.
#
### Acceptance Criteria
- [x] **Scenario: Add to package**
Given that an analyst is logged in
when they are on any application page (application, assessments, history)
then they will see the package on the right of the application header
and when they click on the package field,
a dropdown appears with options: `<empty>`, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
when they make a selection,
then the package # will be saved
- [x] Empty is selectable
#
- [x] **Scenario: Package value is visible in dashboard**
Given that an analyst has successfully logged in
and is on the dashboard
then they will see a column for “Package”
and the saved package #s will be visible for each application that has been assigned to a package
and when an application does not have a package
then the cell will be empty
# 
- [x] **<mark>Scenario: Track user updates to show them on the history page</mark>**
Given that an analyst is on an application page (application, assessment, history)
when a package # is selected
then the date it was selected is recorded
and the user is recorded
#
### Design
[**In header**](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=8328%3A42424&t=s4cWFIdgcq4mH089-4)
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/7cfddf7a-c06a-4275-888b-d8d7d714e6e2)
#
**Dashboard**
![Dashboard_package.jpg](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/88919bbb-78d3-47eb-82c8-c002bfe9b9fc)
[Dimensions](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=7039%3A31260)

**Comment by AntBush** [comment]
Question: Are the packages always 1-5 going to be 1-5 per intake or on the next intake will it be 6-10

**Comment by elliottSlee** [comment]
@zoeyli-46 & I have the same question. We hypothesize that they'll just continue adding packages. The process is:
1. Identify top applications and assign them to package 1
2. Identify next top applications & assign them to package 2
...process continues for as many applications as needed...
New intake opens
...
3. Identify top applications and assign them to next package, e.g., package 3. Applications from different intakes could part of the same package.

**Comment by AntBush** [comment]
> a dropdown appears with options: <empty>, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10

Instead of empty do we want one option of "unassign"

**Comment by MarsRomer** [comment]
moving this to post MVP, hoping to use Lead column and internal process to flag applications

**Comment by carreenu** [comment]
Functionality is working, though note that instead of "unassigned" or "no package" as discussed in the notes above it just gives a blank option.

**Comment by marcellmueller** [comment]
@carreenu looks like that that was just discussion from before the ticket was completed. The acceptance criteria states it should be `<empty>`.
