### ISSUE TITLE
Remove summary_view 

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/CONN-CCBC-portal#828]
`summary_view`  was added as a part of  the ticket [#771](https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/771)

However, view did not work as expected due to Postgresql rule that `Access to tables referenced in the view is determined by permissions of the view owner.` View is created under `ccbc` user. Changing the owner of the view or changing permissions of the `ccbc` user to bypass RLS would mean opening security hole and effectively disabling row-level security.

Thus, alternative approach was implemented (using Metabase Model) and thus, code that adds `summary_view` in Postgres DB should be removed.

**Comment by MarsRomer** [comment]
I can still see them in metabase: ![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/352353f4-df57-4a4a-8ac0-20e305d67681)

**Comment by VB-at-Bis** [comment]
Ok those views are no longer listed in Metabase
