### ISSUE TITLE
Application form - Project Information, Project Area, & Existing network coverage

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#83]
### User Story

As an applicant, 
I want to submit my "project information", "project area", and "existing network coverage"
so that I can apply to the program.

### Research & Design
**Wireframes**
Project Information
https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=1829%3A6908
Project Area
https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=1890%3A6937
Existing network coverage
https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=1059%3A6852

### Acceptance Criteria
**Project info page**
- Project title
     - [x] required
     - [x] maxLength="200"
#
- Geographic area description
     - [x] required
     - [x] maxLength="150"
#
- Description of the project
     - [x] required
     - [x] maxLength="3500"
#
**Project area page**
- Zones
     - [x] required
#
- Span multiple provs
     - [x] required
#
- If yes, province or territory location (check all that apply):
     - [x] conditionally appears if previous question == Yes
     - [x] required if previous question == Yes
#
**Existing network coverage**
- [x] All 4 questions are required
#
**Source of Truth for Questions**
Full information for input fields such as max length for text fields and the contents of drop-downs can be found in the Research channel Files/[DataMapping.xlsx](https://bcgov.sharepoint.com/:x:/r/teams/04708/Shared%20Documents/Research/DataMapping.xlsx?d=w5224cb99a79b48008b9105279418b6e3&csf=1&web=1&e=k1VR5C)
#
![Project info.jpg](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/94561571-6833-4eec-91d1-36dafd1f16cb)

![Project area.jpg](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/f3b7a758-9fdd-40a9-a9ee-565b4ced671c)

![image.png](https://images.zenhubusercontent.com/606c9d37b7ff542cfdb25c53/f023b0a0-8f75-4c53-95e5-dcb33d7a85ba)

**Comment by marcellmueller** [comment]
@MarsRomer @elliottSlee @zoeyli-46 

Hey everyone! Can we please get a review on the first three pages of the form in the dev environment. Looking for a review from the design team and product owner with a goal of pushing to test once approved or once I've made any requested tweaks. Thanks!

https://ccbc-dev.apps.silver.devops.gov.bc.ca/

**Comment by MarsRomer** [comment]
@marcellmueller  looks good to me!

**Comment by elliottSlee** [comment]
@marcellmueller
The padding at the top is large on my screen. Can it be reduced to 40px?
 ![Screen Shot 2022-06-13 at 3.24.00 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/a18658f3-589b-4da4-b6be-d23406a6695f)

**Comment by marcellmueller** [comment]
@elliottSlee Yeah for sure!
