### ISSUE TITLE
Table of Assessments

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/CONN-CCBC-portal#848]
## User story
As an analyst, 
I want to see a table of the assessments,
So that I can get an overview of the progress of the assessment

## Acceptance Criteria
- [x] Clicking on the 'Assessment' link in the left frame will now show the table of assessments
##
- [x] The **order**  of the "list of assessments type" is as is displayed in the wireframe if the screens exists.
Screening
GIS
Technical
Project Management
Financial Risk
Permitting

![image.png](https://images.zenhubusercontent.com/638e5e789d9295d36fe268e9/1552dd29-1f82-49c2-add4-3625cba87b48)

#
- [x] Clicking on a row in the Assessment Table takes the user to the corresponding assessment tab
#
- [x] If an assessment **has no values** filled, (i.e. the default, empty state) then in the table:
 `Progress` = `Not started`
 `Analyst` = `Not assigned`
 `Target date` = `<empty>`
 `Decision` = `<empty>`
#
- [ ] If an assessment has an assignee in the dropdown AND does not have a radio button selected in the 'Progress' group
`Progress` = `Assigned`
`Analyst` = `<analyst name>`
`Target date` = `<empty>` (assuming it's not filled out)
`Decision` = `<empty>` (assuming none are selected)
#
- [x] If an assessment has a decision AND assessment progress = "Assessment complete" then:
 `Progress` = `Complete`
 `Decision` = `<decision>`
#
- [x] If "Progress" = "RFI" or "Needs 2nd review" then in the table
 `Progress` = `<progress> `
 `Analyst` = `<analyst name>`
 `Target date` = `<target date>`
`Decision` = `<decision>` 
#
- [x] display  Target date with the format [Mon, Jan 9]
#

### Colors
- Pill colors
https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=8545%3A41032&t=hErmLZEzmRwCJ0fl-4

## Wireframes
**Figma** 
https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=7039%3A32767

**Progress pills**
![image.png](https://images.zenhubusercontent.com/61e8875b1de5eff8f072cd04/f4bd1422-b7ed-427c-b2ec-dae2aadf398f)

**Outcome pills**
![image.png](https://images.zenhubusercontent.com/61e8875b1de5eff8f072cd04/c76222bc-924c-40b7-91b9-f153c25c877c)

Frontend Complexity:

- Needs some extra work for the different pills based on different Assessment Type 

Require creating or updating a component:

- Yes

Back-end Work:

- Will require function or computed column to return every kind of assessment

Changes in DB Structure:

- No

Tests:

- DB Test and Integration test

Impacts on DevOps:

- None

Risks and Side effects:

- None that I can think of

Documentation Update:

- Also none that I can think of

## Ultra Refinement :
- [ ] #1061

#
- DB: 
  - Create a query to list all `assessment` form data in the DB for a specific application
- Frontend:
  - Reuse: statusColors.ts for pill colours
  - New: Make the table for Assessments
  - Rows will have onClick to assessment - check figma for hover and cursor (should be the same as other dashboards)
  - Map existing assessments to expected set on the table
    - Assume there will be only one assessment record per type of assessments
    - Implement logic for pill and decision mapping
- Tests:
  - pgTap tests for new tables and computed columns
  - e2e testing with happo screenshots
  - Unit tests for Table and assessments/index.tsx page (landing assessments page)
  - Design review on PR
- Documentation:
  - For the new DB table we will need to update miro board

**Comment by zoeyli-46** [comment]
@elliottSlee @eazeredo  want to review the AC?

**Comment by elliottSlee** [comment]
I'll add the tag needs refinement and get to it closer to the sprint 19

**Comment by elliottSlee** [comment]
I'll add the tag needs refinement and get to it closer to the sprint 19

**Comment by eazeredo** [comment]
Acceptances Criteria updated.

**Comment by MarsRomer2** [comment]
Looks good! 
This acceptance criteria doesn't behave as expected: If an assessment has an assignee in the dropdown AND does not have a radio button selected in the 'Progress' group
Progress = Assigned --> SHOWS AS 'Not Started'
Analyst = <analyst name>
Target date = <empty> (assuming it's not filled out)
Decision = <empty> (assuming none are selected)
