### ISSUE TITLE
Application form - Tech solution, benefits, & planning

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#85]
### User Story

As an applicant, 
I want to input responses about the Technological solution, Benefits, & Project planning and management
so that I can apply to the program.

### Research & Design
Tech solutions
https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=1059%3A6913
Benefits
https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=1059%3A7026
Project plan 
https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=1059%3A6967

Date picker suggestion: https://reactdatepicker.com/#example-year-select-dropdown

**Source of Truth for Questions**
Full information for input fields such as max length for text fields and the contents of drop-downs can be found in the Research channel Files/[DataMapping.xlsx](https://bcgov.sharepoint.com/:x:/r/teams/04708/Shared%20Documents/Research/DataMapping.xlsx?d=w5224cb99a79b48008b9105279418b6e3&csf=1&web=1&e=k1VR5C)

---

Development checklist:
- Tech solutions:
  - [ ] 2 - TextareaWidgets
  - [ ] 2 - CheckboxesWidgets
- Benefits:
  - [ ] 1 - TextareaWidget
  - [ ] 1 - TextInputWidget - type: number
- Project plan:
  - [ ] 2 - DatepickerWidgets
  - [ ] 4 - TextareaWidgets

![Tech solution.jpg](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/07839808-a14f-44ec-943b-a38fb2e6bfef)
![Benefits.jpg](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/384acce9-8fdf-47e0-90dc-742b89fde5ec)
![Proj plan & manage.jpg](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/759f48fd-d6a9-464f-b08a-c70ba1cfb0d6)

**Comment by elliottSlee** [comment]
@BryanGK & @marcellmueller Could you add the development checklist to this page?

**Comment by MarsRomer** [comment]
@marcellmueller  is this in Test?  I am not seeing it, I turned on Tech solutions page, and benefits page in Growthbooks for test env and I still don't see those two pages.  I also don't see the planning page in growthbooks

**Comment by MarsRomer** [comment]
@marcellmueller  is this in Test?  I am not seeing it, I turned on Tech solutions page, and benefits page in Growthbooks for test env and I still don't see those two pages.  I also don't see the planning page in growthbooks

**Comment by marcellmueller** [comment]
@MarsRomer nothing in PO review should be in test until you approve it. Even then there is a backlog that is merged to main so it would be a bunch of new stuff and waiting for a general approval before we push to test.

We can discuss it when you’re back but should always be checking dev for review.
