### ISSUE TITLE
Enter 'Technical' Assessment

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/CONN-CCBC-portal#854]
As an analyst 
I want to complete the technical assessment 
So that I can manage it and record the outcomes.

## Acceptance Criteria:

- [x] Tech assessment tab looks like the design
![image.png](https://images.zenhubusercontent.com/638e5e789d9295d36fe268e9/598acf0b-7461-4551-b8ac-19a3c6046e51)

- [x] components behave the same as in 'Screening' tab
 - [ ] multifile uploads

- [x] Decisions are pass and fail
![image.png](https://images.zenhubusercontent.com/638e5e789d9295d36fe268e9/95bcc37d-aca0-4149-a635-ae27e3c4fc45)

**Comment by zoeyli-46** [comment]
@eazeredo @elliottSlee is it fair to say that for each of the assessment tickets AC, we will just list out the "options", since otherwise they are all the same as #874?

**Comment by elliottSlee** [comment]
Even thought AC are the same across tickets, they still need to be written out. We aren't creating features, we're creating user experiences. If interested, look up differences between test driven development, behaviour driven development, and other models. Our user stories needs to explain everything the user is doing.

**Comment by elliottSlee** [comment]
@MarsRomer the screenshot has been updated.

**Comment by MarsRomer2** [comment]
Looks great, just one minor thing needs changing is the 'Other files' should be a multi-file upload.  I will put this in the done column and we can create a bug ticket for it
