### ISSUE TITLE
Enter 'PM' Assessment

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/CONN-CCBC-portal#855]
As an analyst 
I want to complete the PM assessment 
so that I can manage it and record the outcomes.

## Acceptance Criteria:
- [x] Project Management tab looks like design
![image.png](https://images.zenhubusercontent.com/638e5e789d9295d36fe268e9/33faf072-ad05-47d6-bfcf-b682248080ee)

- [ ] Multifile uploads

- [x] Components behave the same as the 'Screening' tab

**Comment by elliottSlee** [comment]
@MarsRomer screenshot's updated

**Comment by MarsRomer2** [comment]
Looks good, only one thing needs changing - the other files needs to be a multi file upload.  But I am going to put this in 'Done' for now and we can create a bug ticket for fixing that as it's not urgent
