### ISSUE TITLE
Enter 'Financial' Assessment

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/CONN-CCBC-portal#856]
As an Analyst 
I want to complete the Financial assessment 
So that I can manage it and record the outcomes.

## Acceptance Criteria:
- [ ] The PM assessment page will be designed as below:

![Untitled.jpg](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/11fbc866-dc7e-450e-9e09-743824ae25e9)

##
- [ ] The uploads will be multiple file uploads

- [ ] Behaviour of the dropdown, date field, radio buttons, uploads, and save will be the same as other assessment screens.

## Not included:
-
-

## Ultra refinement
- DB:
- [ ] .
- Frontend:
- [ ] . 
- Integration/API:
- [ ] .
- Tests:
- [ ] .
- Documentation:
- [ ] .

## Wireframes
https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=7963%3A39193&t=SZrAF09FkM4Z05Sl-4

**Comment by elliottSlee** [comment]
@MarsRomer screenshot's updated
