### ISSUE TITLE
Application form - BC Questions

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#86]
_**These have not been decided yet.
A first iteration of questions is expected ~~Monday, May 2nd EOD~~ week of May 9th.**_

### User Story

As an applicant, 
I want to input responses to the BC specific questions
so that I can apply to the program.

### Research & Design
https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=26%3A359

### Acceptance Criteria
Given 
when
then

- [ ] ? pages implemented
- [ ] tbd

**Source of Truth for Questions**
Full information for input fields such as max length for text fields and the contents of drop-downs can be found in the Research channel Files/[DataMapping.xlsx](https://bcgov.sharepoint.com/:x:/r/teams/04708/Shared%20Documents/Research/DataMapping.xlsx?d=w5224cb99a79b48008b9105279418b6e3&csf=1&web=1&e=k1VR5C)

**Comment by MarsRomer** [comment]
@elliottSlee @zoeyli-46 just flagging this ticket so we can chat about this ticket at some point.  I am wondering if this is the work that Justin is doing and currently calling Template 9, 10

**Comment by zoeyli-46** [comment]
@MarsRomer It is, the BC required information is being collected through spreadsheets, specifically Template 9 and 10. However, there are some BC specific questions that are sprinkled throughout the form questions itself.

**Comment by MarsRomer** [comment]
This is captured in other tickets.
