### ISSUE TITLE
Applicant withdraw 'Submitted', 'Received', & 'Conditionally Approved' applications

### ISSUE THREAD

**Issue by MarsRomer-zz** [bcgov/CONN-CCBC-portal#866]
As an applicant
I need the ability to withdraw and application that has been received by CCBC
so that I can submit another application for the same area but with changes that may be more likely to be approved

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBczFaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f83f3f1fd672a7930323ebc931894ab2492d6f90/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBajFiIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--74a9083b94a8e9991bafe486d1f7268eb7ee8318/image.png)

## Acceptance Criteria:
- [x] Applicant can withdraw applications regardless of whether intake is open or closed
- [x] Application can only be withdrawn if the External status is Submitted, Received, Conditionally Approved
- [x] Both the internal and external status changes to 'Withdrawn'
- [x] When Applicant clicks 'Withdraw' they get a modal to confirm changes
- [x] When an applicant clicks View on a withdrawn application, they can view the form but all fields are disabled and an alert banner shows at the top saying, "Withdrawn applications cannot be edited."
- Is status a sufficient indicator to analysts to not continue reviewing the application?

## Wireframes
![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/e0f09d0f-2464-4c6e-a0a5-b88a0034104d)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdUZFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--238d34f19e54660764c16d97b27c844cbd776f4d/image.png)
Below screen design are suggestions, keep the current design for how withdrawn applications are displayed:
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/939fdbe7-5e3d-4542-ba60-5c5ec2fd6828)

**Comment by MarsRomer** [comment]
Needs Refinement:  What are the different internal and external status' that the applicant can withdraw at - TBD
