### ISSUE TITLE
Application form - Template uploads

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#87]
### User Story

As an applicant, 
I want to upload the UBF templates
so that I can apply to the program.

As a project analyst
I want the attachments to be linked to project number
so that I know which application the attachments are associated with.

### Research & Design
https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=1059%3A7749

### Acceptance Criteria
- [x] Just HTML
#
- **Scenario: Enable one-file upload**
- [ ] Template 1
- [ ] Template 2
- [ ] Template 3
- [ ] Template 4
- [ ] Template 5
- [ ] Template 6
- [ ] Template 7
- [ ] Template 8
- [ ] Template 9
- [ ] Template 10
---
### Not included

- **Scenario: Validate required fields**
- [ ] Template 1
- [ ] Template 2
- [ ] Template 3
- [ ] Template 4
- [ ] Template 5
- [ ] Template 6
- [ ] Template 9
- [ ] Template 10
#
- [ ] **Scenario: link file to application**
Given that a user attaches a mapping file
When they upload it
Then it is linked with their application.
#
- [ ] Given that an analyst is reviewing applications
When they download a mapping file
Then they know which project the mapping file is association with.
#
- [ ] **Scenario: file name & upload in progress**
Given that a user clicks on upload file
When they press upload
Then they will see their file name below the relevant section
And a loader gif (https://loading.io/asset/572481) beside the filename
#
- [ ] **Scenario: Loader gif replaced by delete button**
Given that a file is currently being uploaded
When the file is successfully uploaded
Then the loader gif will disappear
And a red x will appear beside the filename 
#
- [ ] **Scenario: Delete upload**
Given that user is on the mapping upload page and has uploaded a file
When they click the red x beside the file name
Then their upload will be deleted
And the filename will be removed from the ui.
#
- [ ] **Scenario: Max file size (as defined by ISED)**
Given that a user is trying to upload a file
When they try to upload a file larger than 100mb
Then they see an error message that says, "Files must be less than 100mb. If you must submit a file larger than this, please contact connectingcommunitiesbc@gov.bc.ca"
#
- [ ] **Scenario: upload button changes to replace**
Given that an applicant is on the template upload page
When a file has already been uploaded
Then the upload button will state "replace" instead of upload
#
- [ ] **Scenario: first file is replaced by 2nd**
Given that an applicant is on the template upload page and a file has been uploaded
When they click on replace and upload a new file
the original file will be deleted
And the filename will be removed from below the upload area
And the new file will be uploaded
#
- [ ] **Scenario: upload failed**
Given that an applicant is trying to upload a file
When the file fails to upload
Then an error message will appear that says, "The file did not upload, please try again. If the problem persists please contact connectingcommunitiesbc@gov.bc.ca."
#

![Template Uploads.jpg](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/26a05e0a-3792-4956-a531-8423286a93a8)

**Source of Truth for Questions**
Full information for input fields such as max length for text fields and the contents of drop-downs can be found in the Research channel Files/[DataMapping.xlsx](https://bcgov.sharepoint.com/:x:/r/teams/04708/Shared%20Documents/Research/DataMapping.xlsx?d=w5224cb99a79b48008b9105279418b6e3&csf=1&web=1&e=k1VR5C)

**Comment by MarsRomer** [comment]
Blocked by needing AWS approval.

**Comment by MarsRomer** [comment]
@marcellmueller I am not seeing this page....

**Comment by zoeyli-46** [comment]
@marcellmueller @elliottSlee template 8 should be multi-file upload based on what Rachel mentioned yesterday

**Comment by zoeyli-46** [comment]
@marcellmueller cc: @elliottSlee from today's demo, the single file upload button label did not change text to "replace" is this something we still intend to create?

**Comment by marcellmueller** [comment]
@zoeyli-46 the requirements was just to have the basic html/styling this sprint but that would be easy to add in when we implement the file upload.

**Comment by elliottSlee** [comment]
@zoeyli-46 I think template 8 should remain single file upload and I added a new upload field to the supporting documents page to handle the evidence that Rachel mentioned

**Comment by zoeyli-46** [comment]
@elliottSlee My bad! You mentioned that already, I just blanked
