### ISSUE TITLE
Application form - Supporting documents uploads

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#88]
### User Story

As an applicant, 
I want to upload supporting documents
so that I can apply to the program.

As a project analyst
I want the attachments to be linked to project number
so that I know which application the attachments are associated with.

### Research & Design
https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=1059%3A7602

### Acceptance Criteria
- [ ] Just the HTML

### Not included
- [ ] **Scenario: Max file size (as defined by ISED)**
Given that a user is trying to upload a file
When they try to upload a file larger than 100mb
Then they see an error message that says, "Files must be less than 100mb. If you must submit a file larger than this, please contact connectingcommunitiesbc@gov.bc.ca"
#
- [ ] **Scenario: upload button changes to replace**
Given that a field a single file upload
when a file has been uploaded
then the "Upload" button will change to say "Replace"
#
- [ ] **Scenario: first file is replaced by 2nd**
Given that an applicant has uploaded a file to a single file upload
when they click on replace and upload a new file
the original file will be deleted
and the filename will be removed from below the upload area
and the new file will be uploaded
#
- [ ] **Scenario: file name & upload in progress**
Given that a user clicks on upload file
when they press upload
then they will see their file name below the relevant section
and a loader gif (https://loading.io/asset/572481) beside the filename
#
- [ ] **Scenario: Loader gif replaced by delete button**
Given that a file is currently being uploaded
when the file is successfully uploaded
then the loader gif will disappear
and a red x will appear beside the filename 
#
- [ ] **Scenario: Delete upload**
Given that user is on a file upload page and has uploaded a file
when they click the red x beside the file name
then their upload will be deleted
and the filename will be removed from the ui.
#
- [ ] **Scenario: link file to application**
Given that a user attaches a mapping file
When they upload it
Then it is linked with their application.

Given that an analyst is reviewing applications
When they download a mapping file
Then they know which project the mapping file is associated with.
#
- [ ] **Scenario: upload failed**
Given that an applicant is trying to upload a file
When the file fails to upload
Then an error message will appear that says, "The file did not upload, please try again. If the problem persists please contact connectingcommunitiesbc@gov.bc.ca."
#

- **Scenario: Enable one-file upload**
- [ ] Logical network diagram
- [ ] Project schedule
#
- **Scenario: Enable multiple files upload**
- [ ] Copies of registration and other relevant documents
- [ ] Independently prepared financial statements for the last three (3) years
- [ ] Community and Rural Development Benefits supporting documents
#
- **Scenario: Validate required fields**
- [ ] Copies of registration and other relevant documents
- [ ] Independently prepared financial statements for the last three (3) years
- [ ] Logical network diagram
- [ ] Project schedule
#

![Supporting doc upload.jpg](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/4cf8f6c2-5748-474d-b2eb-8ba84ca713a2)

**Source of Truth for Questions**
Full information for input fields such as max length for text fields and the contents of drop-downs can be found in the Research channel Files/[DataMapping.xlsx](https://bcgov.sharepoint.com/:x:/r/teams/04708/Shared%20Documents/Research/DataMapping.xlsx?d=w5224cb99a79b48008b9105279418b6e3&csf=1&web=1&e=k1VR5C)

**Comment by MarsRomer** [comment]
@elliottSlee @zoeyli-46 would it make sense to have notes on this page to let the applicant know that the file limitations for each category?

**Comment by zoeyli-46** [comment]
@MarsRomer Yes, based on the call we had with Rogers today they wouldn't like to be surprised with this limitation on the submission date. We can put in the description "Please note, if a file size is over 100MB, you will need to contact connectingcommunities@gov.bc.ca" 
Error message can be "This file size exceeds 100MB. Please contact [connectingcommunitiesbc@gov.bc.ca](mailto:connectingcommunitiesbc@gov.bc.ca)"

**Comment by MarsRomer** [comment]
Blocked by needing to get AWS use approval
