### ISSUE TITLE
Analyst - Create RFI

### ISSUE THREAD

**Issue by eazeredo** [bcgov/CONN-CCBC-portal#881]
## User Story
As an Analyst
I want to create an RFI 
So that the applicant will be able to upload the requested files.

## Acceptance Criteria:
- [x] **RFI in the sidebar**
	Given an analyst is on an application page where they can see the sidebar
	when they click on the RFI tab
	then they will see the RFI page
icon is [envelope from font-awesome](https://fontawesome.com/icons/envelope?s=regular&f=classic)
#
- [x] **Show 'New RFI' button**
	Given that I'm on the RFI page
	When I click on "New RFI"
	Then I will be directed to the RFI form
#
- [x] **RFI Number generated**
Given that an analyst is a person who exists in the world and has watched Lion King 16 times
when they click save
Then an RFI# will be autogenerated
and the format will be RFI-CCBC-XXXXYY-Z
RFI-`CCBC ID`-`#`
For CCBC-010023's first RFI, the # would be: RFI-CCBC-010023-1
For CCBC-010102's fifth RFI, the # would be: RFI-CCBC-010102-5
#
- [x] **RFI type** checkboxes
- [x] **Due by date** date-picker
- [x] **Email correspondence** file upload, no file type restrictions, multiple files allowed
- [x] **Checkboxes for requesting files**
#
- [ ] **Action: Save**
	Given that an analyst is on the RFI page
	When they click on Save
	Then the values are created in the database
	And I'm redirected to the page "List RFIs"
	And a success toast with the text "RFI saved"
#
- [x] **Cancel**
Given that an analyst is on the RFI form
when they press cancel
then any information is abandoned
and the RFI number can be used for the next RFI submitted for this application
#

## Technical Analysis
- [ ] On creation of an RFI, a new schema is stored in the ccbc_public.form table with type `rfi`
- [ ] Should create a new computed column to easily get `rfi` for an application
- [ ] .

## Wireframes
[Wireframes](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=7581%3A36769&t=Et08WUiZAvcXQQVj-4)

### New RFI
![RFI_create button.jpg](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/94b30350-70b0-43d6-9f58-adda9fc0353b)

### New RFI - Empty state
![RFI_create.jpg](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/9931ecef-5dbe-4c66-afc6-0cd613c2dfc3)

### New RFI - Open and filled
![RFI_filled.jpg](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/93f62604-2f05-4b0d-aa8b-48cc664e18d0)

#
## Not included:
-  ** Scenario: Validate if RFI type is not empty**
	Given the fields have valid information 
	And the `RFI type` field has no option selected
	When I click on Save
	Then a Error message appears
	And the operation is cancelled

#

### Deprioritized
~~- [ ] **Open and close accordions**
	Given I'm entering a new RFI
	When I click the `+` icon
	Then the section will open
	When I click the `-` icon
	Then the section will close~~
#
~~- [ ] **Show checkbox beside each uploaded file in the application**
	Given I'm entering a new RFI
	And an applicant has uploaded a file as part of their application
	When I open a section
	Then a checkbox will be visible beside each filename uploaded~~

**Comment by MarsRomer** [comment]
@elliottSlee for post MVP I think we will need to design how they will create new 2nd and subsequent RFIs.  I noticed that 'New RFI' button disappears in the screens above.  Also do you think we need to reword the button to 'Create RFI'.... more of an action word?

**Comment by MarsRomer2** [comment]
Looks good, just one thing; the file upload is throwing an error
![image.png](https://images.zenhubusercontent.com/638e5e789d9295d36fe268e9/28a82837-f113-4c74-b4a7-42bc21ffe526)

**Comment by marcellmueller** [comment]
@MarsRomer2 sorry I mentioned on Teams that the permissions for analyst uploads were coming in another ticket that is in review.

**Comment by MarsRomer2** [comment]
Right! I will put it back in PO review column and review this ticket when that one is done

**Comment by MarsRomer2** [comment]
IT works!!! only one thing, it doesn't allow multiple file uploads.  Can you please make that change?
