### ISSUE TITLE
View updated files by RFI in the Application

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#883]
### User Story
As an analyst & an applicant
I want to view the files that an applicant has uploaded after an RFI (#533)
so that I can evaluate an application

#
- [ ] **View in application form**
Given that I am an applicant and I have uploaded new files in an RFI form
When I submit the RFI form
Then my application form is updated with the new attachments
Given that an applicant has uploaded new files in an RFI form
when the analyst views the application
then the files will be visible in the application
and a line below the new filename will say "Received from RFI-CCBC-######-#"
#
- [ ] **Download file**
Given that new file(s) are visible in the application
when the filename is clicked on
then the file will begin downloading
#

## Wireframes
![Screen Shot 2022-11-15 at 4.37.24 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/d5b37d54-9e58-4248-8017-b9512e1c5d2b)
[**Wireframe**](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=6978%3A58877&t=Et08WUiZAvcXQQVj-4)

**Comment by matthieu-foucault** [comment]
This not a must-have for handling of RFIs, as #883 and #37 should allow submitting and viewing of RFIs. 
Updating the applications so that they show the latest attachments is definitely valuable though, so still a fairly high priority

**Comment by MarsRomer** [comment]
I'm considering removing this from mvp

**Comment by MarsRomer** [comment]
Consider this for post MVP based on user feedback of seeing the new files from RFI on the RFI screen in the analyst portal
