### ISSUE TITLE
CCBC app uses horizontal pod autoscaler

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/CONN-CCBC-portal#889]
- [ ] Adjust requests and limits based on load testing results
- [ ] Add horizontal pod autoscaler
- [ ] Run load tests again to make sure it is working correctly (likely we will have to notify platform services again)
- [ ] Depending on how load test goes adjust cpu and memory requests/limits

If needed we may have to request more resources from platform services. We have quite a bit of memory available so likely just increased cpu depending on how this goes.

## Technical Analysis
- What is the front-end complexity?
- Do it require creating or updating a component?
- Any work on the back-end?
- Integration?
- Any changes in database structure?
- What types of tests that we need to create and run?
- Impacts on DevOps?
- Other risks and potential side effects?
- Which documentation needs to be updated?

**Comment by pdoc1111** [comment]
8
