### ISSUE TITLE
Analyst - Edit RFI

### ISSUE THREAD

**Issue by eazeredo** [bcgov/CONN-CCBC-portal#895]
As an analyst
I want to edit an existing RFI
so that I can change an RFI to alter a deadline or fix an error I made.

## Acceptance Criteria:

- [x] **Edit RFI**
Given that an analyst can see an existing RFI
when they click on the edit pencil beside the RFI
then they are taken to the RFI form
and they see the information for the RFI
and they can change it.
Icon: font-awesome [edit](https://fontawesome.com/v5/icons/edit?s=solid&f=classic)
colour: 1A5A96

#
- [ ] **Saved confirmation**
Given that an analyst has changed anything in the RFI form
when they press the save button
then they will be directed to the list RFI page
and they will see the changes they made there
and a success toast will ease-in over 100ms
and when 3 seconds has passed
then the saved indicator will ease-out over 100ms

background-color: 2F8440
Icon: font-awesome [circle-check](https://fontawesome.com/icons/circle-check?s=regular&f=classic)

#

- [x] **History Tracked**
Given that an analyst has edited an RFI form
When they press the save button
Then the previous version of the RFI is preserved
And the latest RFI edited is the one displayed

Complexities: since RFIs are tracked by creating new RFI forms, there needs to be a way to distinguish between a previously made RFI and a brand-new RFI

## Not included:
-
-

## Technical Analysis
- What is the front-end complexity?
- Do it require creating or updating a component?
- Any work on the back-end?
- Integration?
- Any changes in database structure?
- What types of tests that we need to create and run?
- Impacts on DevOps?
- Other risks and potential side effects?
- Which documentation needs to be updated?

## Wireframes
![RFI_editbutton.png](https://images.zenhubusercontent.com/61e8875b1de5eff8f072cd04/dd88e6f8-31db-4b07-8f97-d48d5947f1b6)

![RFI_edit.jpg](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/b44fca5a-e8a7-43f4-8d0c-80afed9f3796)

**Comment by elliottSlee** [comment]
@MarsRomer Should edit RFI be part of the MVP? 
Implications of not having edit:
1. Extending deadline or requesting other files could be done by opening another RFI
2. Can't fix a mistake or unrequest files
Maybe instead of editing, we just have a delete RFI for the short-term?

**Comment by AntBush** [comment]
So if I'm understanding this right, we want an "autosave" but only for changing the due date and uploading a file?

**Comment by elliottSlee** [comment]
@AntBush Sorry, the "finished action" was changed to "pressed save"

**Comment by AntBush** [comment]
Thanks!

**Comment by MarsRomer** [comment]
Zoey feel free to change the screen designs in this ticket
