### ISSUE TITLE
Analyst - RFI - add emails

### ISSUE THREAD

**Issue by eazeredo** [bcgov/CONN-CCBC-portal#896]
## User Story
As an analyst
I want to add emails to existing RFIs
so that I can track the correspondence for the RFI that I took place after first submitting it.

## Acceptance Criteria:
- [ ] **Scenario: upload files**
Given that an analyst is on the RFI page 
and has saved an RFI
when they press the button "Add emails"
then a file picker will appear
and the analyst can upload multiple files
#
- [ ] **Success toast after upload**
Given an analyst has uploaded an additional file in the emails section
when the email successfully uploads
then the file name will appear above
and an x will appear beside that
and a success toast will ease-in for 100ms at the bottom-left of the page (padding-left:55px, vertical alignment: bottom edge in line with the bottom edge of newly listed info)
	And when 3 seconds have passed
	Then the saved indicator will ease-out for 100ms

	Colour: 2F8440
	Icon: font-awesome [circle-check](https://fontawesome.com/icons/circle-check?s=regular&f=classic)
#
- [ ] **Delete file**
Given that analyst has successfully uploaded a file
when the x beside the filename is pressed
then the filename will be removed from the screen

## Not included:
-
-

## Technical Analysis
- [ ] .
- [ ] . 
- [ ] .

## Wireframes
![RFI_upload emaisl.jpg](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/3b9e8c70-ab68-4b54-af4b-0f584604cc1d)

![RFI_email toast.jpg](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/2935bf0a-710c-42b3-9410-e1621fd2f148)

**Comment by MarsRomer** [comment]
De-prioritize to post MVP possibly as the edit button will allow user to add email files.
