### ISSUE TITLE
Analyst - RFI - Delete Files

### ISSUE THREAD

**Issue by eazeredo** [bcgov/CONN-CCBC-portal#897]
As a 
I want 
so that 

## Acceptance Criteria:

- [ ] **Delete file**
Given that an analyst is on the RFI page
and a file has been uploaded
then a red x will appear beside the filename
and when they press the x
then the filename will be removed from the screen
#
# New Card

## Not included:
-
-

## Technical Analysis
- [ ] .
- [ ] . 
- [ ] .

**Comment by elliottSlee** [comment]
Why is this it's own card? It's already a function of the upload widget.

**Comment by eazeredo** [comment]
The existing file upload component (frontend, backend, AWS) is working exclusively for the upload of applicant files. 
It may/might need adjustments in the code to the RFI.

@AntBush , @VB-at-Bis , @marcellmueller , Do we need this card?

**Comment by MarsRomer** [comment]
can someone remind me what the use case is for an analyst to delete an RFI file?  are we just talking about the emails that the analyst is uploading or the attachments that the applicant uploads?  I don't think the analyst will be deleting the uploaded files from the applicant, and it's a bit dicey to give them that ability as mistakes can happen
