### ISSUE TITLE
Application Form - Declarations pages

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#90]
### User Story

As an applicant, 
I want to make the required declarations
so that I can apply to the program.

### Research & Design
https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=1630%3A5945

### Acceptance Criteria

- **Scenario: Validate required fields**
- [x] Completed for [Applicant Legal Name]
- [x] Completed by
- [x] Title
- [x] Completed on [MM/DD/YYYY]

![Declarations1.jpg](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/e0dcc997-880b-4afc-8a9c-6f51899c2d2e)

![image.png](https://images.zenhubusercontent.com/61e8875b1de5eff8f072cd04/db8a8bc3-c003-4b42-a869-5630712a4b97)

**Source of Truth for Questions**
Full information for input fields such as max length for text fields and the contents of drop-downs can be found in the Research channel Files/[DataMapping.xlsx](https://bcgov.sharepoint.com/:x:/r/teams/04708/Shared%20Documents/Research/DataMapping.xlsx?d=w5224cb99a79b48008b9105279418b6e3&csf=1&web=1&e=k1VR5C)

## Not included
Mark as complete is a separate story #92

**Comment by MarsRomer** [comment]
@marcellmueller also not seeing this in test

**Comment by marcellmueller** [comment]
@MarsRomer we made a team agreement not to push to test without PO approval. We can only push to dev.
