### ISSUE TITLE
Add considerations/notes to an application

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/CONN-CCBC-portal#901]
### User Story
As an analyst
I want to read and write notes for an application,
So that all the analysts can take them into consideration when doing their assessment

### Acceptance Criteria
- [ ] By default on the application page there is a large text area input field and a save button
- [ ] When there are 1+ notes, they are displayed in a list in order of creation date (earliest to latest), and there is an "add note" button
- [ ] When the user clicks "add note" button, then a large text area and a save button will appear in place of it 
- [ ] Note shows the name of the person and the date/time.  
- [ ] note can be deleted by any admin :  Clicking delete shows modal that says 'Are you sure you want to delete this note?  This can't be undone'  Delete or cancel.
- [ ] No history of notes - hard deletes.  Don't keep it in the database anywhere.
- [ ] no edit button
- [ ] Notes show at the top of the Application page
- [ ]  If analyst can't delete- they don't get a delete button
- [ ]  Character limit of notes - 1000 each
- [ ] No limit on the number of notes that can be added

## Ultra refinement
- ACL - Access Control List
- [ ] Does this introduce ACL 
- DB:
- [ ] .
- Frontend:
- [ ] . 
- Integration/API:
- [ ] .
- Tests:
- [ ] .
- Documentation:
- [ ] .

**Comment by MarsRomer2** [comment]
De-prioritizing this to the backlog as it is not necessary with all the notes in the assessment templates, and state change reasons.
