### ISSUE TITLE
Uploads erroneously show as missing

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#903]
I uploaded a series of documents to this application but when I went to the review page it showed them all as missing in the Template Uploads, Supporting Documents, and Coverage pages

![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/4355d7a9-a053-47a9-8e31-e571c3b167f3)

![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/158c0dab-3ebe-4d1a-bbed-bafdd05ac148)

**Comment by MarsRomer** [comment]
@marcellmueller @VB-at-Bis @AntBush please assess this bug for it's impact and probability

**Comment by elliottSlee** [comment]
Bug replicated on Mac using Chrome.
