### ISSUE TITLE
Autosave

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#91]
### User Story
As an applicant, 
I want my responses to save automatically while I am on a page
so that I don't lose progress while working on something.

### Research & Design
https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=1059%3A10444 

Loader GIF
https://loading.io/asset/572481  

https://github.com/bcgov/cas-cif/pull/164
https://github.com/bcgov/cas-ciip-portal/pull/933

### Acceptance Criteria
- [x] Given that a user is on any page with inputs
when they make a change to an input
then their responses are automatically saved 250ms after pausing typing
- [x] While the user is typing, the autosave message is "Saving" with loader gif 
- [x] After the user has paused typing, the autosave message is "Last saved: 1:50PM"
- [x] If the user is returning to the form on another day, the autosave message is "Last saved: [MM/DD]
- [x] If there was a problem saving the user response, the error message is "There was an error saving your response <br> Please refresh the page"
**Design**
- [ ] <s>Given that a user is scrolling on the page,
then the position of the autosave message is sticky,
so that even if the page is long, the user can still see the saved status</s>
- [x] The autosave message should be bottom aligned with the page title

<img width="862" alt="image" src="https://user-images.githubusercontent.com/77090142/183508238-6facaad8-890c-4fa2-998f-e954f3b29cf7.png">

**Comment by eazeredo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/91?planning-poker) with ZenHub @AntBush @marcellmueller @wenzowski

**Comment by MarsRomer** [comment]
@marcellmueller can you please estimate this ticket today?

**Comment by eazeredo** [comment]
For reference: https://ant.design/components/notification/

**Comment by eazeredo** [comment]
@zoeyli-46 
1) are we keeping the autosave messages sticky, or 
2) will it be fixed together with the rest of the text?

**Comment by MarsRomer** [comment]
@elliottSlee would you mind explaining (for not-a-dev) what does 'sticky' means please :)

**Comment by zoeyli-46** [comment]
sticky means that it follows the same position on the page wherever you scroll. I.e. autosave message is always in the top right corner of your screen no matter how far down the page you scroll. 

We have decided that it will not be "sticky" and it will be fixed. So the autosave message is in the top right corner of the page and if you scroll down you won't be able to see the message anymore.

**Comment by matthieu-foucault** [comment]
The date/time display do not seem to comply with the [BC Gov IM/IT standards](https://www2.gov.bc.ca/assets/gov/government/services-for-government-and-broader-public-sector/information-technology-services/standards-files/date_and_time_standard.pdf). We should probably use a 24h clock and a 3-character month abbreviation.

**Comment by MarsRomer** [comment]
hmm I'm not seeing the autosave messages in the top right
![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/1e87641d-58fb-40fc-8ba2-69e61659696b)

**Comment by MarsRomer** [comment]
Works now!
