### ISSUE TITLE
Allow analysts to see withdrawn applications

### ISSUE THREAD

**Issue by MarsRomer-zz** [bcgov/CONN-CCBC-portal#926]
As a NWBC Analyst 
I need to see the withdrawn applications (once the intake is closed) and their details
so that I have greater situational awareness of the applications

Currently the list of applications in the analyst portal does not have the withdrawn applications, this ticket is to enable listing and viewing 'withdrawn' status applications regardless of when they were withdrawn.

## Acceptance Criteria:
- [x] Applications with 'Withdrawn' status shows up in the list of applications for the analysts regardless if the application was withdrawn before or after the intake was closed.
- [x]  When clicking on the 'Withdrawn' application in the list, the analyst can see the application data just like for 'Received' applications after that intake has closed
- [x] Withdrawn application form data cannot be edited by the analyst, they do not see the edit pencil
~- [ ] Withdrawn applications cannot have any assessment functionality~
<S>- [ ] Withdrawn applications cannot have any status change functionality,</s>
<S>- [ ] When exporting the attachments, the attachments for withdrawn applications are included in a separate folder (needs discussion, doesn't make sense because zip file is created when intake is closed but attachments can be downloaded long after that)</S>

## Wireframes
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdkJVIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--de93894e1dd1c56d13494dc2588986af9e31bbf9/Withdraw%202.PNG)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc2xoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b7474d3782d2913e821a3ea708b3c7b9fa9a015b/Withdrawn%202.PNG)

**Comment by elliottSlee** [comment]
Will this make a distinction between Withdrawn before received and Withdrawn after received?
