### ISSUE TITLE
Change Lia's last name

### ISSUE THREAD

**Issue by MarsRomer-zz** [bcgov/CONN-CCBC-portal#937]
**`Lia Wilson`** should be changed to **`Lia Pittappillil`** in the list of analysts

**Comment by MarsRomer** [comment]
Lia Wilson should be changed to Lia Pittappillil in the list of analysts

**Comment by MarsRomer2** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/937?planning-poker) with Zenhub @AntBush @marcellmueller @VB-at-Bis @pdoc1111
