### ISSUE TITLE
Virus Scan - Run on existing files

### ISSUE THREAD

**Issue by MarsRomer-zz** [bcgov/CONN-CCBC-portal#938]
As an analyst 
I want to be sure that all the files uploaded prior to the virus scanner being implemented have been scanned
so that I can download them in confidence that I am not putting government systems at risk

Description:  The Virus scanner currently only runs on files when they are uploaded, however there are files that were uploaded prior to the implementation of the virus scanner. This ticket is to scan those objects.

## Acceptance Criteria:
- [x] Virus scanner has been run on the existing files in the s3 bucket

## Technical Analysis
- What is the front-end complexity?
- Do it require creating or updating a component?
- Any work on the back-end?
- Integration?
- Any changes in database structure?
- What types of tests that we need to create and run?
- Impacts on DevOps?
- Other risks and potential side effects?
- Which documentation needs to be updated?

**Comment by AntBush** [comment]
https://docs.aws.amazon.com/AmazonS3/latest/userguide/tagging-and-policies.html - Docs for adding policy that will only allow if tagged with clean

We get error when calling from s3Client, If there's an error then we add error message
