### ISSUE TITLE
Virus - handle single file download 

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/CONN-CCBC-portal#954]
As an analyst or applicant
I want the single file downloads not to allow viruses' to download to my computer
to keep my system safe

## Acceptance Criteria:
- [ ] As an analyst or applicant
Given that I have an infected file
When I click on it to download
Then a modal displaying an error will appear and the download will not happen

## Technical details:
- Back-end: Update S3 download route to fetch tag and error (500) if it is tagged 
- Front-end: Use the Toolkit modal
- Tests: Mock return of error on frontend for modal, mock s3 tag to test route in backend

## [Wireframe](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=9184%3A43533&t=ZuS50PheSOShTqzq-4)
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/74af90d1-5e52-46f6-a21a-a92ff4efe5c7)

**Comment by elliottSlee** [comment]
Related to #962

**Comment by MarsRomer2** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/954?planning-poker) with Zenhub @AntBush @marcellmueller @pdoc1111 @VB-at-Bis

**Comment by MarsRomer2** [comment]
@MarsRomer2  update wording for prefix file name

**Comment by MarsRomer2** [comment]
@elliottSlee @zoeyli-46 can you please add mockups for the modal here?
