### ISSUE TITLE
Uploads getting 504 error

### ISSUE THREAD

**Issue by AntBush** [bcgov/CONN-CCBC-portal#960]
**Describe the bug**

**To Reproduce**
1. Go to any page that has an upload page
2. Click on file upload
3. Upload a file >1MB
4. See error - 504 timeout 

**Expected behaviour**

**Screenshots**

**Logs/tracebacks**
[Kibana link
](https://kibana-openshift-logging.apps.silver.devops.gov.bc.ca/app/kibana#/discover/60404250-7662-11ed-8dcc-b1e5fc84cfeb?_g=(refreshInterval:(pause:!t,value:0),time:(from:'2022-12-07T18:49:13.911Z',mode:absolute,to:'2022-12-07T18:55:38.426Z'))&_a=(columns:!(kubernetes.container_name,message),filters:!(),index:'596db670-226f-11ed-9133-4913a27418aa',interval:auto,query:(language:lucene,query:'kubernetes.pod_name:%22ccbc-7d6777544b-d4t7j%22%20AND%20kubernetes.namespace_name:%22ff61fb-test%22%20AND%20kubernetes.container_name.raw:%22ccbc%22'),sort:!('@timestamp',desc))) with logs showing an upload that failed. The same file was uploaded twice, with the first upload seen a successful one uploading 18MB while the second stops at ~10MB without showing an error
**Additional context**

**Comment by elliottSlee** [comment]
[test.connectingcommunitiesbc.ca-1670606489654.log](https://github.com/bcgov/CONN-CCBC-portal/files/10196763/test.connectingcommunitiesbc.ca-1670606489654.log)
[test.connectingcommunitiesbc.ca-1670606508829.log](https://github.com/bcgov/CONN-CCBC-portal/files/10196764/test.connectingcommunitiesbc.ca-1670606508829.log)
[test.connectingcommunitiesbc.ca-1670606514734.log](https://github.com/bcgov/CONN-CCBC-portal/files/10196768/test.connectingcommunitiesbc.ca-1670606514734.log)
[test.connectingcommunitiesbc.ca-1670606519575.log](https://github.com/bcgov/CONN-CCBC-portal/files/10196769/test.connectingcommunitiesbc.ca-1670606519575.log)
[test.connectingcommunitiesbc.ca-1670606525007.log](https://github.com/bcgov/CONN-CCBC-portal/files/10196770/test.connectingcommunitiesbc.ca-1670606525007.log)
