### ISSUE TITLE
Check if uploaded files are affected

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#962]
- [x] Create a script to check each file uploaded by users to detect if they’re affected 
- [x] Run the script and share results with the team

**Comment by elliottSlee** [comment]
@VB-at-Bis Does there need to be more to this ticket?

**Comment by VB-at-Bis** [comment]
[https://app.zenhub.com/files/476885245/39a42016-f05a-4b73-b75d-4c8b6f52f87f/download](https://app.zenhub.com/files/476885245/39a42016-f05a-4b73-b75d-4c8b6f52f87f/download)

**Comment by VB-at-Bis** [comment]
Steps taken:
- ran `SELECT  "ccbc_public"."attachment"."file" AS "file", "ccbc_public"."attachment"."file_name" AS "file_name", "ccbc_public"."attachment"."file_type" AS "file_type", "ccbc_public"."attachment"."file_size" AS "file_size", 
"ccbc_public"."attachment"."application_id" AS "application_id"
FROM "ccbc_public"."attachment"  LIMIT 1048575` in production metabase and saved results in a JSON file;
- created script (attached) that loads the list of files and iterates the list , sending requests to AWS S3 to check if the file exists and what is the size of the file
- ran the script and detected only one record (file "7d35a3e3-b5d3-4d63-8c21-241c9a7a17a2", uploaded on October 20, 2022, 12:07 PM as part of application 1. Details of the application and the user can be retrieved from Metabase. Results attached.
