### ISSUE TITLE
Move s3Archiver and Downloads to use s3Client v3

### ISSUE THREAD

**Issue by AntBush** [bcgov/CONN-CCBC-portal#981]
To resolve the error with file uploads, a move to the v3 of the AWS S3 SDK was made. This ticket is being made to track our eventual move of the s3Archiver and Downloads to v3

Acceptance Criteria:
- [x] s3Archive.ts uses v3
- [x] s3download.ts uses v3

**Comment by MarsRomer** [comment]
downloads work!
