### ISSUE TITLE
Upgrade to newest version of NextJS

### ISSUE THREAD

**Issue by AntBush** [bcgov/CONN-CCBC-portal#994]
We are behind on our version of NextJS, this brings about a need to verify if Relay will work along with Next

Thomas from CAS made a document on their upgrade here:
https://docs.google.com/document/d/1RiLHdwIs9POaQH5Nj2igzdPasGnKjK1L35ljQqRr_0c/edit#

**Comment by MarsRomer** [comment]
Nothing for PO to review so moving to sprint done
