### ISSUE TITLE
Metabase query in prod not working

### ISSUE THREAD

**Issue by MarsRomer2** [bcgov/CONN-CCBC-portal#999]
The base query for all application data works with test data but switching it to prod does not work currently.  

This ticket is to allow the query to work with prod data as well as test data.

**Comment by VB-at-Bis** [comment]
Permissions changed in Prod. Now Base Query works in Prod (no data in response because there are no submitted applications yet). https://ccbc-metabase.apps.silver.devops.gov.bc.ca/question/36-all-application-data
